#!/bin/csh

cat /proc/cpuinfo

zcat HBformat/Pothen/barth5.psa.gz		| readhb | yifan - barth5.kp
zcat HBformat/GHS_psdef/ford2.psa.gz		| readhb | yifan - ford2.kp
zcat HBformat/GHS_psdef/copter1.psa.gz		| readhb | yifan - copter1.kp
zcat HBformat/Pothen/onera_dual.psa.gz		| readhb | yifan - onera_dual.kp
zcat HBformat/GHS_psdef/copter2.psa.gz		| readhb | yifan - copter2.kp
zcat HBformat/GHS_psdef/pds10.psa.gz		| readhb | yifan - pds10.kp
zcat HBformat/GHS_psdef/finance256.psa.gz	| readhb | yifan - finance256.kp
zcat HBformat/Pothen/tandem_dual.psa.gz		| readhb | yifan - tandem_dual.kp
zcat HBformat/GHS_psdef/ford1.psa.gz		| readhb | yifan - ford1.kp

zcat HBformat/Pothen/tandem_vtx.psa.gz		| readhb | yifan - tandem_vtx.kp
zcat HBformat/Gupta/gupta1.psa.gz		| readhb | yifan - gupta1.PSA
zcat HBformat/Gupta/gupta2.psa.gz		| readhb | yifan - gupta2.PSA
zcat HBformat/Gupta/gupta3.psa.gz		| readhb | yifan - gupta3.PSA

zcat HBformat/Chen/pkustk04.psa.gz		| readhb | yifan - pkustk04.PSA
zcat HBformat/Chen/pkustk08.psa.gz		| readhb | yifan - pkustk08.PSA
zcat HBformat/Chen/pkustk12.psa.gz		| readhb | yifan - pkustk12.PSA

zcat HBformat/Chen/pkustk01.psa.gz		| readhb | yifan - pkustk01.PSA
zcat HBformat/Chen/pkustk05.psa.gz		| readhb | yifan - pkustk05.PSA
zcat HBformat/Chen/pkustk09.psa.gz		| readhb | yifan - pkustk09.PSA

zcat HBformat/Chen/pkustk13.psa.gz		| readhb | yifan - pkustk13.PSA
zcat HBformat/Chen/pkustk02.psa.gz		| readhb | yifan - pkustk02.PSA
zcat HBformat/Chen/pkustk06.psa.gz		| readhb | yifan - pkustk06.PSA

zcat HBformat/Chen/pkustk10.psa.gz		| readhb | yifan - pkustk10.PSA
zcat HBformat/Chen/pkustk14.psa.gz		| readhb | yifan - pkustk14.PSA
zcat HBformat/Chen/pkustk03.psa.gz		| readhb | yifan - pkustk03.PSA

zcat HBformat/Chen/pkustk07.psa.gz		| readhb | yifan - pkustk07.PSA
zcat HBformat/Chen/pkustk11.psa.gz		| readhb | yifan - pkustk11.PSA

zcat HBformat/Pothen/bodyy4.rsa.gz		| readhb | yifan - bodyy4.RSA
zcat HBformat/Pothen/bodyy5.rsa.gz		| readhb | yifan - bodyy5.RSA
zcat HBformat/Pothen/bodyy6.rsa.gz		| readhb | yifan - bodyy6.RSA

zcat HBformat/HB/bcsstk29.psa.gz		| readhb | yifan - bcsstk29.PSA
zcat HBformat/GHS_psdef/obstclae.rsa.gz		| readhb | yifan - OBSTCLAE.rsa
zcat HBformat/GHS_psdef/torsion1.rsa.gz		| readhb | yifan - TORSION1.rsa
zcat HBformat/GHS_psdef/jnlbrng1.rsa.gz		| readhb | yifan - JNLBRNG1.rsa
zcat HBformat/GHS_psdef/minsurfo.rsa.gz		| readhb | yifan - MINSURFO.rsa
zcat HBformat/GHS_psdef/gridgena.rsa.gz		| readhb | yifan - GRIDGENA.rsa
zcat HBformat/GHS_psdef/cvxbqp1.rsa.gz		| readhb | yifan - CVXBQP1.rsa
zcat HBformat/GHS_psdef/wathen100.rsa.gz	| readhb | yifan - wathen100.mat
zcat HBformat/GHS_psdef/wathen120.rsa.gz	| readhb | yifan - wathen120.mat
zcat HBformat/GHS_psdef/s3dkt3m2.rsa.gz		| readhb | yifan - s3dkt3m2.rsa
zcat HBformat/GHS_psdef/s3dkq4m2.rsa.gz		| readhb | yifan - s3dkq4m2.rsa

zcat HBformat/GHS_psdef/bmwcra_1.rsa.gz		| readhb | yifan - bmwcra_1.rsa
zcat HBformat/DNVS/trdheim.pse.gz		| reade  | yifan - trdheim.PSE
zcat HBformat/GHS_psdef/opt1.pse.gz		| reade  | yifan - opt1.PSE
zcat HBformat/DNVS/tsyl201.pse.gz		| reade  | yifan - tsyl201.PSE
zcat HBformat/DNVS/crplat2.pse.gz		| reade  | yifan - crplat2.PSE
zcat HBformat/Pothen/shuttle_eddy.psa.gz	| readhb | yifan - shuttle_eddy.PSA
zcat HBformat/Pothen/skirt.psa.gz		| readhb | yifan - skirt.PSA

# zcat HBformat/GHS_psdef/ramage02.pse.gz	    | reade  | yifan
echo 'ramage02:' ; zcat Triplet/ramage02.tri.gz | yifan - ramage02.PSE

zcat HBformat/GHS_psdef/srb1.pse.gz		| reade  | yifan - Srb1.PSE
zcat HBformat/GHS_psdef/pwt.rsa.gz		| readhb | yifan - pwt.RSA
zcat HBformat/HB/bcsstk30.psa.gz		| readhb | yifan - bcsstk30.PSA
zcat HBformat/HB/bcsstk31.psa.gz		| readhb | yifan - bcsstk31.PSA
zcat HBformat/Rothberg/struct3.psa.gz		| readhb | yifan - struct3.PSA
zcat HBformat/HB/bcsstk32.psa.gz		| readhb | yifan - bcsstk32.PSA
zcat HBformat/HB/bcsstk25.rsa.gz		| readhb | yifan - bcsstk25.RSA
zcat HBformat/Boeing/ct20stif.rsa.gz		| readhb | yifan - ct20stif.PSA
zcat HBformat/DNVS/fcondp2.pse.gz		| reade  | yifan - Fcondp2.PSE
zcat HBformat/Rothberg/3dtube.psa.gz		| readhb | yifan - 3dtube.PSA
zcat HBformat/DNVS/troll.pse.gz			| reade  | yifan - Troll.PSE
zcat HBformat/Mulvey/finan512.rsa.gz		| readhb | yifan - finan512.RSA
zcat HBformat/Rothberg/gearbox.psa.gz		| readhb | yifan - gearbox.PSA
zcat HBformat/Boeing/bcsstk36.rsa.gz		| readhb | yifan - bcsstk36.RSA
zcat HBformat/Boeing/msc23052.rsa.gz		| readhb | yifan - msc23052.RSA
zcat HBformat/Boeing/msc10848.rsa.gz		| readhb | yifan - msc10848.RSA
zcat HBformat/GHS_psdef/oilpan.rsa.gz		| readhb | yifan - OILPAN.rsa
zcat HBformat/Rothberg/cfd1.rsa.gz		| readhb | yifan - cfd1.RSA
zcat HBformat/Nasa/nasasrb.rsa.gz		| readhb | yifan - nasasrb.RSA
zcat HBformat/Rothberg/cfd2.rsa.gz		| readhb | yifan - cfd2.RSA
zcat HBformat/GHS_psdef/vanbody.rsa.gz		| readhb | yifan - vanbody.rsa
zcat HBformat/DNVS/shipsec8.rsa.gz		| readhb | yifan - SHIPSEC8.rsa
zcat HBformat/DNVS/shipsec1.rsa.gz		| readhb | yifan - SHIPSEC1.rsa
zcat HBformat/DNVS/ship_003.rsa.gz		| readhb | yifan - SHIP_003.rsa
zcat HBformat/DNVS/shipsec5.rsa.gz		| readhb | yifan - SHIPSEC5.rsa
zcat HBformat/DNVS/thread.rsa.gz		| readhb | yifan - THREAD.rsa
zcat HBformat/GHS_psdef/crankseg_1.rsa.gz	| readhb | yifan - crankseg_1.rsa
zcat HBformat/GHS_psdef/bmw7st_1.rsa.gz		| readhb | yifan - bmw7st_1.rsa
zcat HBformat/DNVS/x104.rsa.gz			| readhb | yifan - X104.rsa
zcat HBformat/GHS_psdef/crankseg_2.rsa.gz	| readhb | yifan - crankseg_2.rsa
zcat HBformat/Boeing/pwtk.rsa.gz		| readhb | yifan - pwtk.RSA
zcat HBformat/GHS_psdef/hood.rsa.gz		| readhb | yifan - hood.rsa
zcat HBformat/DNVS/m_t1.rsa.gz			| readhb | yifan - M_T1.rsa
zcat HBformat/GHS_psdef/inline_1.rsa.gz		| readhb | yifan - inline_1.rsa
zcat HBformat/GHS_psdef/ldoor.rsa.gz		| readhb | yifan - ldoor.rsa
zcat HBformat/DNVS/fullb.pse.gz			| reade  | yifan - Fullb.PSE
zcat HBformat/DNVS/halfb.pse.gz			| reade  | yifan - Halfb.PSE

# too big
zcat HBformat/GHS_psdef/audikw_1.rsa.gz		| readhb | yifan - audikw_1.rsa

# first residual is OK, iterative refinement is very bad:
# zcat HBformat/DNVS/ship_001.rse.gz	    | reade  | yifan
echo 'ship_001:' ; zcat Triplet/ship_001.tri.gz | yifan - SHIP_001.rse
