Matrix: aggregate.c File Reference
aggregate.c File Reference
#include "Mdefines.h"
#include "M5.h"
#include "idz.h"
Macros
#define TEMPLATE(c)
Functions
SEXP sparse_aggregate (SEXP from, const char *class)
SEXP R_sparse_aggregate (SEXP s_from)
Macro Definition Documentation
TEMPLATE
#define TEMPLATE (c)
Referenced by sparse_aggregate().
Function Documentation
R_sparse_aggregate()
SEXP R_sparse_aggregate (SEXP s_from)
Definition at line 86 of file aggregate.c.
References Matrix_class(), sparse_aggregate(), and valid_sparse.
sparse_aggregate()
SEXP sparse_aggregate (SEXP from, const char * class)
Definition at line 5 of file aggregate.c.
References _, COPY_SLOT, DIAG, DIM, DIMNAMES, GET_SLOT, Matrix_Calloc, Matrix_factorsSym, Matrix_Free, Matrix_iSym, Matrix_jSym, SET_DIAG, SET_DIM, SET_DIMNAMES, SET_TRANS, SET_UPLO, SWITCH5, TEMPLATE, TRANS, and UPLO.
Referenced by R_sparse_aggregate(), scanArgs(), sparse_as_kind(), sparse_dropzero(), sparse_prod(), sparse_sum(), and Tsparse_colsum().