Matrix: attrib.c File Reference
attrib.c File Reference
#include "Mdefines.h"
#include "attrib.h"
Functions
int DimNames_is_trivial (SEXP dn)
int DimNames_is_symmetric (SEXP dn)
SEXP R_DimNames_is_symmetric (SEXP dn)
void symDN (SEXP dest, SEXP src, int J)
void revDN (SEXP dest, SEXP src)
SEXP R_symDN (SEXP dn)
SEXP R_revDN (SEXP dn)
SEXP get_symmetrized_DimNames (SEXP obj, int J)
SEXP get_reversed_DimNames (SEXP obj)
void set_symmetrized_DimNames (SEXP obj, SEXP dn, int J)
void set_reversed_DimNames (SEXP obj, SEXP dn)
static int strmatch (const char *x, SEXP valid)
static SEXP append_to_named_list (SEXP x, const char *nm, SEXP val)
SEXP get_factor (SEXP obj, const char *nm)
void set_factor (SEXP obj, const char *nm, SEXP val)
SEXP R_set_factor (SEXP obj, SEXP nm, SEXP val, SEXP warn)
Function Documentation
append_to_named_list()
static SEXP append_to_named_list (SEXP x, const char * nm, SEXP val) static
Definition at line 166 of file attrib.c.
Referenced by set_factor().
DimNames_is_symmetric()
int DimNames_is_symmetric (SEXP dn)
Definition at line 14 of file attrib.c.
References equal_character_vectors().
Referenced by dense_is_symmetric(), R_DimNames_is_symmetric(), and sparse_is_symmetric().
DimNames_is_trivial()
int DimNames_is_trivial (SEXP dn)
Definition at line 6 of file attrib.c.
Referenced by get_reversed_DimNames(), get_symmetrized_DimNames(), R_Matrix_as_matrix(), R_revDN(), R_symDN(), set_reversed_DimNames(), and set_symmetrized_DimNames().
get_factor()
SEXP get_factor (SEXP obj, const char * nm)
Definition at line 189 of file attrib.c.
References GET_SLOT, Matrix_factorsSym, strmatch(), and valid.
Referenced by dgCMatrix_orf(), dgCMatrix_trf(), dgeMatrix_trf(), dpCMatrix_trf(), dpoMatrix_trf(), dppMatrix_trf(), dspMatrix_trf(), and dsyMatrix_trf().
get_reversed_DimNames()
SEXP get_reversed_DimNames (SEXP obj)
Definition at line 120 of file attrib.c.
References DimNames_is_trivial(), GET_SLOT, Matrix_DimNamesSym, and revDN().
get_symmetrized_DimNames()
SEXP get_symmetrized_DimNames (SEXP obj, int J)
Definition at line 108 of file attrib.c.
References DimNames_is_trivial(), GET_SLOT, Matrix_DimNamesSym, and symDN().
Referenced by dense_marginsum(), dgCMatrix_dgeMatrix_matmult(), dspMatrix_matmult(), dsyMatrix_matmult(), and sparse_marginsum().
R_DimNames_is_symmetric()
SEXP R_DimNames_is_symmetric (SEXP dn)
Definition at line 32 of file attrib.c.
References DimNames_is_symmetric().
R_revDN()
SEXP R_revDN (SEXP dn)
Definition at line 98 of file attrib.c.
References DimNames_is_trivial(), and revDN().
R_set_factor()
SEXP R_set_factor (SEXP obj, SEXP nm, SEXP val, SEXP warn)
Definition at line 225 of file attrib.c.
References _, Matrix_factorsSym, and set_factor().
R_symDN()
SEXP R_symDN (SEXP dn)
Definition at line 88 of file attrib.c.
References DimNames_is_trivial(), and symDN().
revDN()
void revDN (SEXP dest, SEXP src)
Definition at line 68 of file attrib.c.
Referenced by get_reversed_DimNames(), R_revDN(), and set_reversed_DimNames().
set_factor()
void set_factor (SEXP obj, const char * nm, SEXP val)
Definition at line 203 of file attrib.c.
References append_to_named_list(), GET_SLOT, Matrix_factorsSym, SET_SLOT, strmatch(), and valid.
Referenced by dgCMatrix_orf(), dgCMatrix_trf(), dgeMatrix_trf(), dpCMatrix_trf(), dpoMatrix_trf(), dppMatrix_trf(), dspMatrix_trf(), dsyMatrix_trf(), and R_set_factor().
set_reversed_DimNames()
void set_reversed_DimNames (SEXP obj, SEXP dn)
Definition at line 142 of file attrib.c.
References DimNames_is_trivial(), Matrix_DimNamesSym, revDN(), and SET_SLOT.
Referenced by dense_transpose(), and sparse_transpose().
set_symmetrized_DimNames()
void set_symmetrized_DimNames (SEXP obj, SEXP dn, int J)
Definition at line 132 of file attrib.c.
References DimNames_is_trivial(), Matrix_DimNamesSym, SET_SLOT, and symDN().
Referenced by dense_as_general(), dense_band(), dense_force_symmetric(), dense_skewpart(), dense_symmpart(), diagonal_as_dense(), diagonal_as_sparse(), dpCMatrix_trf(), dpoMatrix_trf_(), dppMatrix_trf_(), dspMatrix_trf_(), dsyMatrix_trf_(), matrix_as_dense(), sparse_as_general(), sparse_band(), sparse_force_symmetric(), sparse_skewpart(), sparse_symmpart(), vector_as_dense(), and vector_as_sparse().
strmatch()
static int strmatch (const char * x, SEXP valid) static
Definition at line 156 of file attrib.c.
References valid.
Referenced by get_factor(), and set_factor().
symDN()
void symDN (SEXP dest, SEXP src, int J)
Definition at line 37 of file attrib.c.
Referenced by dgCMatrix_dgCMatrix_matmult(), dgeMatrix_matmult(), get_symmetrized_DimNames(), R_symDN(), and set_symmetrized_DimNames().