Matrix: attrib.h File Reference
attrib.h File Reference
#include <Rinternals.h>
Functions
SEXP R_DimNames_is_symmetric (SEXP)
SEXP R_symDN (SEXP)
SEXP R_revDN (SEXP)
SEXP R_set_factor (SEXP, SEXP, SEXP, SEXP)
Function Documentation
R_DimNames_is_symmetric()
SEXP R_DimNames_is_symmetric (SEXP dn)
Definition at line 32 of file attrib.c.
References DimNames_is_symmetric().
R_revDN()
SEXP R_revDN (SEXP dn)
Definition at line 98 of file attrib.c.
References DimNames_is_trivial(), and revDN().
R_set_factor()
SEXP R_set_factor (SEXP obj, SEXP nm, SEXP val, SEXP warn)
Definition at line 225 of file attrib.c.
References _, Matrix_factorsSym, and set_factor().
R_symDN()
SEXP R_symDN (SEXP dn)
Definition at line 88 of file attrib.c.
References DimNames_is_trivial(), and symDN().