Matrix: band.c File Reference
band.c File Reference
#include "Mdefines.h"
#include "M5.h"
#include "idz.h"
Macros
#define TEMPLATE(c)
#define TEMPLATE(c)
#define TEMPLATE(c)
Functions
SEXP dense_band (SEXP from, const char *class, int a, int b)
SEXP sparse_band (SEXP from, const char *class, int a, int b)
SEXP R_dense_band (SEXP s_from, SEXP s_a, SEXP s_b)
SEXP R_sparse_band (SEXP s_from, SEXP s_a, SEXP s_b)
Macro Definition Documentation
TEMPLATE [1/3]
#define TEMPLATE (c)
Value:
    do { \
        c##TYPE *px0 = c##PTR(x0), *px1 = c##PTR(x1); \
        if (ge && class[1] != 'g') { \
        if (!packed) \
            c##NAME(force2)(px1, px0, n_, ul0, ct0, nu0); \
        else \
            c##NAME( pack1)(px1, px0, n_, ul0, ct0, nu0); \
        px0 = NULL; \
        packed = 0; \
        } else if (tr && class[1] == 's' && ul0 != ul1) { \
        if (!packed) \
            c##NAME(trans2)(px1, px0, m_, n_ , ct0); \
        else \
            c##NAME(trans1)(px1, px0, n_, ul0, ct0); \
        px0 = NULL; \
        ul0 = ul1; \
        } \
        if (!packed) \
            c##NAME( band2)(px1, px0, m_, n_ , a_, b_); \
        else \
            c##NAME( band1)(px1, px0, n_, ul0, a_, b_); \
    } while (0)
Referenced by dense_band(), and sparse_band().
TEMPLATE [2/3]
#define TEMPLATE (c)
TEMPLATE [3/3]
#define TEMPLATE (c)
Function Documentation
dense_band()
SEXP dense_band (SEXP from, const char * class, int a, int b)
Definition at line 7 of file band.c.
References cl, DIAG, DIM, DIMNAMES, GET_SLOT, Matrix_xSym, newObject(), PACKED_LENGTH, SET_DIAG, SET_DIM, SET_DIMNAMES, SET_SLOT, SET_TRANS, SET_UPLO, SWITCH4, TEMPLATE, TRANS, TYPEOF, and UPLO.
Referenced by R_dense_band().
R_dense_band()
SEXP R_dense_band (SEXP s_from, SEXP s_a, SEXP s_b)
Definition at line 350 of file band.c.
References _, dense_band(), DIM, matrix_as_dense(), Matrix_class(), TYPEOF, and valid_dense.
R_sparse_band()
SEXP R_sparse_band (SEXP s_from, SEXP s_a, SEXP s_b)
Definition at line 380 of file band.c.
References _, DIM, Matrix_class(), sparse_band(), and valid_sparse.
sparse_band()
SEXP sparse_band (SEXP from, const char * class, int a, int b)
Definition at line 95 of file band.c.
References cl, DIAG, DIM, DIMNAMES, GET_SLOT, Matrix_Calloc, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_xSym, newObject(), SET_DIAG, SET_DIM, SET_DIMNAMES, SET_SLOT, SET_TRANS, SET_UPLO, SWAP, SWITCH5, TEMPLATE, TRANS, and UPLO.
Referenced by R_sparse_band(), and sparse_diag_N2U().