Matrix: bind.c File Reference
bind.c File Reference
#include "Mdefines.h"
#include "M5.h"
#include "coerce.h"
Macros
#define TEMPLATE(c)
#define TEMPLATE(c)
#define TEMPLATE(c)
#define TEMPLATE(c)
Functions
static void scanArgs (SEXP args, SEXP exprs, int margin, int level, int *rdim, int *rdimnames, char *kind, char *repr)
static void coerceArgs (SEXP args, int margin, int *rdim, char kind, char repr)
static void bindArgs (SEXP args, int margin, SEXP ans, int *rdim, char kind, char repr)
static SEXP bind (SEXP args, SEXP exprs, int margin, int level)
SEXP R_bind (SEXP args)
Variables
static SEXP tagWasVector = NULL
Macro Definition Documentation
TEMPLATE [1/4]
#define TEMPLATE (c)
Referenced by bindArgs().
TEMPLATE [2/4]
#define TEMPLATE (c)
TEMPLATE [3/4]
#define TEMPLATE (c)
TEMPLATE [4/4]
#define TEMPLATE (c)
Function Documentation
bind()
static SEXP bind (SEXP args, SEXP exprs, int margin, int level) static
Definition at line 839 of file bind.c.
References _, bindArgs(), coerceArgs(), GET_SLOT, Matrix_class(), Matrix_DimNamesSym, Matrix_DimSym, newObject(), scanArgs(), tagWasVector, TYPEOF, and valid_matrix.
Referenced by R_bind().
bindArgs()
static void bindArgs (SEXP args, int margin, SEXP ans, int * rdim, char kind, char repr) static
Definition at line 483 of file bind.c.
References _, GET_SLOT, Matrix_Calloc, Matrix_Free, Matrix_iSym, Matrix_jSym, Matrix_permSym, Matrix_pSym, SET_MARGIN, SET_SLOT, SWITCH5, and TEMPLATE.
Referenced by bind().
coerceArgs()
static void coerceArgs (SEXP args, int margin, int * rdim, char kind, char repr) static
Definition at line 350 of file bind.c.
References dense_as_general(), dense_as_kind(), dense_as_sparse(), diagonal_as_dense(), diagonal_as_sparse(), index_as_dense(), index_as_sparse(), kindToType(), matrix_as_sparse(), Matrix_class(), sparse_as_Csparse(), sparse_as_dense(), sparse_as_general(), sparse_as_kind(), sparse_as_Rsparse(), sparse_as_Tsparse(), tagWasVector, TYPEOF, and valid_matrix.
Referenced by bind().
R_bind()
SEXP R_bind (SEXP args)
Definition at line 946 of file bind.c.
References bind().
scanArgs()
static void scanArgs (SEXP args, SEXP exprs, int margin, int level, int * rdim, int * rdimnames, char * kind, char * repr) static
Definition at line 10 of file bind.c.
References _, DIAG, ERROR_INVALID_TYPE, GET_SLOT, MARGIN, Matrix_class(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_permSym, Matrix_pSym, sparse_aggregate(), TYPEOF, UPLO, and valid_matrix.
Referenced by bind().
Variable Documentation
tagWasVector
SEXP tagWasVector = NULL static
Definition at line 7 of file bind.c.
Referenced by bind(), and coerceArgs().