Matrix: BunchKaufman.c File Reference
BunchKaufman.c File Reference
#include "Lapack-etc.h"
#include "Mdefines.h"
Functions
SEXP dense_as_kind (SEXP, const char *, char, int)
SEXP dense_force_canonical (SEXP, const char *, int)
SEXP dense_bunchkaufman (SEXP obj, const char *class, int warn, char ul, char ct)
SEXP R_dense_bunchkaufman (SEXP s_obj, SEXP s_warn, SEXP s_uplo, SEXP s_trans)
Function Documentation
dense_as_kind()
SEXP dense_as_kind (SEXP from, const char * class, char kind, int new)
Definition at line 2000 of file coerce.c.
References cl, DIAG, DIM, DIMNAMES, duplicateVector(), GET_SLOT, kindToType(), Matrix_xSym, naToUnit(), newObject(), SET_DIAG, SET_DIM, SET_DIMNAMES, SET_SLOT, SET_UPLO, TYPEOF, and UPLO.
Referenced by coerceArgs(), dense_bunchkaufman(), R_dense_diag_set(), and R_sparse_matmult().
dense_bunchkaufman()
SEXP dense_bunchkaufman (SEXP obj, const char * class, int warn, char ul, char ct)
Definition at line 10 of file BunchKaufman.c.
References _, cl, dense_as_kind(), dense_force_canonical(), DIAG, DIM, DIMNAMES, ERROR_LAPACK_2, FCONE, GET_SLOT, Matrix_class(), Matrix_permSym, Matrix_xSym, newObject(), SET_DIM, SET_DIMNAMES, SET_SLOT, SET_TRANS, SET_UPLO, TRANS, TYPEOF, UPLO, and valid_dense.
Referenced by R_dense_bunchkaufman().
dense_force_canonical()
SEXP dense_force_canonical (SEXP from, const char * class, int check)
Definition at line 7 of file forceCanonical.c.
References COPY_SLOT, DIAG, DIM, DIMNAMES, GET_SLOT, Matrix_factorsSym, Matrix_sdSym, Matrix_xSym, newObject(), SET_DIM, SET_DIMNAMES, SET_SLOT, SET_TRANS, SET_UPLO, SWITCH4, SWITCH5, TEMPLATE, TRANS, TYPEOF, and UPLO.
Referenced by dense_bunchkaufman().
R_dense_bunchkaufman()
SEXP R_dense_bunchkaufman (SEXP s_obj, SEXP s_warn, SEXP s_uplo, SEXP s_trans)
Definition at line 95 of file BunchKaufman.c.
References dense_bunchkaufman(), get_factor(), Matrix_class(), set_factor(), valid_dense, VALID_TRANS, and VALID_UPLO.