Matrix: chm_common.h File Reference
chm_common.h File Reference
#include "SuiteSparse_config/SuiteSparse_config.h"
#include "CHOLMOD/Include/cholmod.h"
#include "Mutils.h"
Macros
#define AS_CHM_DN(x) as_cholmod_dense ((CHM_DN)alloca(sizeof(cholmod_dense)), x)
#define AS_CHM_FR(x) AS_CHM_FR2(x, TRUE)
#define AS_CHM_FR2(x, chk) as_cholmod_factor3((CHM_FR)alloca(sizeof(cholmod_factor)), x, chk)
#define AS_CHM_FR__(x) AS_CHM_FR2(x, FALSE)
#define AS_CHM_SP(x) as_cholmod_sparse ((CHM_SP)alloca(sizeof(cholmod_sparse)), x, TRUE, FALSE)
#define AS_CHM_SP2(x, chk) as_cholmod_sparse ((CHM_SP)alloca(sizeof(cholmod_sparse)), x, chk, FALSE)
#define AS_CHM_SP__(x) as_cholmod_sparse ((CHM_SP)alloca(sizeof(cholmod_sparse)), x, FALSE, FALSE)
#define AS_CHM_TR(x) as_cholmod_triplet((CHM_TR)alloca(sizeof(cholmod_triplet)),x, TRUE)
#define AS_CHM_TR__(x) as_cholmod_triplet((CHM_TR)alloca(sizeof(cholmod_triplet)), x, FALSE)
#define AS_CHM_xDN(x) as_cholmod_x_dense ((CHM_DN)alloca(sizeof(cholmod_dense)), x)
#define N_AS_CHM_DN(x, nr, nc) M_numeric_as_chm_dense((CHM_DN)alloca(sizeof(cholmod_dense)), x , nr, nc)
Typedefs
typedef cholmod_common * CHM_CM
typedef cholmod_dense * CHM_DN
typedef cholmod_factor * CHM_FR
typedef cholmod_sparse * CHM_SP
typedef cholmod_triplet * CHM_TR
typedef const cholmod_dense * const_CHM_DN
typedef const cholmod_factor * const_CHM_FR
typedef const cholmod_sparse * const_CHM_SP
typedef const cholmod_triplet * const_CHM_TR
Functions
CHM_DN as_cholmod_dense (CHM_DN ans, SEXP x)
Populate ans with the pointers from x and modify its scalar elements accordingly.
CHM_FR as_cholmod_factor (CHM_FR ans, SEXP x)
Populate ans with the pointers from x and modify its scalar elements accordingly.
CHM_FR as_cholmod_factor3 (CHM_FR ans, SEXP x, Rboolean do_check)
Populate ans with the pointers from x and modify its scalar elements accordingly.
CHM_SP as_cholmod_sparse (CHM_SP ans, SEXP x, Rboolean check_Udiag, Rboolean sort_in_place)
Populate ans with the pointers from x and modify its scalar elements accordingly.
CHM_TR as_cholmod_triplet (CHM_TR ans, SEXP x, Rboolean check_Udiag)
Populate ans with the pointers from x and modify its scalar elements accordingly.
CHM_DN as_cholmod_x_dense (CHM_DN ans, SEXP x)
Rboolean check_sorted_chm (CHM_SP A)
SEXP chm_dense_to_matrix (CHM_DN a, int dofree, SEXP dn)
Copy the contents of a to a matrix object and, optionally, free a or free both a and its pointer to its contents.
SEXP chm_dense_to_SEXP (CHM_DN a, int dofree, int Rkind, SEXP dn, Rboolean transp)
Copy the contents of a to an appropriate denseMatrix object and, optionally, free a or free both a and its pointer to its contents.
SEXP chm_dense_to_vector (CHM_DN a, int dofree)
Copy the contents of a to a numeric R object and, optionally, free a or free both a and its pointer to its contents.
void chm_diagN2U (CHM_SP chx, int uploT, Rboolean do_realloc)
Drop the (unit) diagonal entries from a cholmod_sparse matrix.
static R_INLINE Rboolean chm_factor_ok (CHM_FR f)
SEXP chm_factor_to_SEXP (CHM_FR f, int dofree)
Copy the contents of f to an appropriate CHMfactor object and, optionally, free f or free both f and its pointer to its contents.
Rboolean chm_MOD_xtype (int to_xtype, cholmod_sparse *A, CHM_CM Common)
Change the "type" of a cholmod_sparse matrix, i.e.
void CHM_restore_common ()
SEXP CHM_set_common_env (SEXP rho)
SEXP chm_sparse_to_SEXP (CHM_SP a, int dofree, int uploT, int Rkind, const char *diag, SEXP dn)
Copy the contents of a to an appropriate CsparseMatrix object and, optionally, free a or free both a and its the pointers to its contents.
void CHM_store_common ()
void chm_transpose_dense (CHM_DN ans, CHM_DN x)
Transpose a cholmod_dense matrix ("too trivial to be in CHOLMOD?")
SEXP chm_triplet_to_SEXP (CHM_TR a, int dofree, int uploT, int Rkind, const char *diag, SEXP dn)
Copy the contents of a to an appropriate TsparseMatrix object and, optionally, free a or free both a and its the pointers to its contents.
SEXP CHMfactor_validate (SEXP obj)
SEXP CHMsimpl_validate (SEXP obj)
SEXP CHMsuper_validate (SEXP obj)
SEXP get_SuiteSparse_version ()
CHM_DN numeric_as_chm_dense (CHM_DN ans, double *v, int nr, int nc)
void R_cholmod_error (int status, const char *file, int line, const char *message)
int R_cholmod_l_start (CHM_CM Common)
int R_cholmod_start (CHM_CM Common)
Initialize the CHOLMOD library and replace the print and error functions by R-specific versions.
Variables
cholmod_common c
cholmod_common cl
Macro Definition Documentation
AS_CHM_DN
#define AS_CHM_DN (x) as_cholmod_dense ((CHM_DN)alloca(sizeof(cholmod_dense)), x)
Definition at line 44 of file chm_common.h.
AS_CHM_FR
#define AS_CHM_FR (x) AS_CHM_FR2(x, TRUE)
Definition at line 47 of file chm_common.h.
AS_CHM_FR2
#define AS_CHM_FR2 (x, chk) as_cholmod_factor3((CHM_FR)alloca(sizeof(cholmod_factor)), x, chk)
Definition at line 46 of file chm_common.h.
AS_CHM_FR__
#define AS_CHM_FR__ (x) AS_CHM_FR2(x, FALSE)
Definition at line 49 of file chm_common.h.
AS_CHM_SP
#define AS_CHM_SP (x) as_cholmod_sparse ((CHM_SP)alloca(sizeof(cholmod_sparse)), x, TRUE, FALSE)
Definition at line 50 of file chm_common.h.
AS_CHM_SP2
#define AS_CHM_SP2 (x, chk) as_cholmod_sparse ((CHM_SP)alloca(sizeof(cholmod_sparse)), x, chk, FALSE)
Definition at line 56 of file chm_common.h.
AS_CHM_SP__
#define AS_CHM_SP__ (x) as_cholmod_sparse ((CHM_SP)alloca(sizeof(cholmod_sparse)), x, FALSE, FALSE)
Definition at line 53 of file chm_common.h.
AS_CHM_TR
#define AS_CHM_TR (x) as_cholmod_triplet((CHM_TR)alloca(sizeof(cholmod_triplet)),x, TRUE)
Definition at line 51 of file chm_common.h.
AS_CHM_TR__
#define AS_CHM_TR__ (x) as_cholmod_triplet((CHM_TR)alloca(sizeof(cholmod_triplet)), x, FALSE)
Definition at line 54 of file chm_common.h.
AS_CHM_xDN
#define AS_CHM_xDN (x) as_cholmod_x_dense ((CHM_DN)alloca(sizeof(cholmod_dense)), x)
Definition at line 45 of file chm_common.h.
N_AS_CHM_DN
#define N_AS_CHM_DN (x, nr, nc) M_numeric_as_chm_dense((CHM_DN)alloca(sizeof(cholmod_dense)), x , nr, nc)
Definition at line 59 of file chm_common.h.
Typedef Documentation
CHM_CM
typedef cholmod_common* CHM_CM
Definition at line 20 of file chm_common.h.
CHM_DN
typedef cholmod_dense* CHM_DN
Definition at line 21 of file chm_common.h.
CHM_FR
typedef cholmod_factor* CHM_FR
Definition at line 23 of file chm_common.h.
CHM_SP
typedef cholmod_sparse* CHM_SP
Definition at line 25 of file chm_common.h.
CHM_TR
typedef cholmod_triplet* CHM_TR
Definition at line 27 of file chm_common.h.
const_CHM_DN
typedef const cholmod_dense* const_CHM_DN
Definition at line 22 of file chm_common.h.
const_CHM_FR
typedef const cholmod_factor* const_CHM_FR
Definition at line 24 of file chm_common.h.
const_CHM_SP
typedef const cholmod_sparse* const_CHM_SP
Definition at line 26 of file chm_common.h.
const_CHM_TR
typedef const cholmod_triplet* const_CHM_TR
Definition at line 28 of file chm_common.h.
Function Documentation
as_cholmod_dense()
CHM_DN as_cholmod_dense (CHM_DN ans, SEXP x)
Populate ans with the pointers from x and modify its scalar elements accordingly.
Note that later changes to the contents of ans will change the contents of the SEXP.
In most cases this function is called through the macro AS_CHM_DN. It is unusual to call it directly.
Parameters
ans a CHM_DN pointer.
x pointer to an object that inherits from (denseMatrix ^ generalMatrix)
Returns
ans containing pointers to the slots of x.
Definition at line 685 of file chm_common.c.
References _AS_cholmod_dense_1, _AS_cholmod_dense_2, Matrix_xSym, and RallocedREAL().
Referenced by R_init_Matrix().
as_cholmod_factor()
CHM_FR as_cholmod_factor (CHM_FR ans, SEXP x)
Populate ans with the pointers from x and modify its scalar elements accordingly.
Note that later changes to the contents of ans will change the contents of the SEXP.
In most cases this function is called through the macro AS_CHM_FR. It is unusual to call it directly.
Parameters
ans an CHM_FR object
x pointer to an object that inherits from CHMfactor
Returns
ans containing pointers to the slots of x.
Definition at line 1124 of file chm_common.c.
References as_cholmod_factor3().
Referenced by R_init_Matrix().
as_cholmod_factor3()
CHM_FR as_cholmod_factor3 (CHM_FR ans, SEXP x, Rboolean do_check)
Populate ans with the pointers from x and modify its scalar elements accordingly.
Note that later changes to the contents of ans will change the contents of the SEXP.
Parameters
ans an CHM_FR object
x pointer to an object that inherits from CHMfactor
do_check logical indicating if check for correctness should happen
Returns
ans containing pointers to the slots of x.
Definition at line 1045 of file chm_common.c.
References _, c, Matrix_iSym, Matrix_permSym, Matrix_pSym, MATRIX_VALID_CHMfactor, and Matrix_xSym.
Referenced by as_cholmod_factor(), and R_init_Matrix().
as_cholmod_sparse()
CHM_SP as_cholmod_sparse (CHM_SP ans, SEXP x, Rboolean check_Udiag, Rboolean sort_in_place)
Populate ans with the pointers from x and modify its scalar elements accordingly.
Note that later changes to the contents of ans will change the contents of the SEXP.
In most cases this function is called through the macros AS_CHM_SP() or AS_CHM_SP__(). It is unusual to call it directly.
Parameters
ans a CHM_SP pointer
x pointer to an object that inherits from CsparseMatrix
check_Udiag boolean - should a check for (and consequent expansion of) a unit diagonal be performed.
sort_in_place boolean - if the i and x slots are to be sorted should they be sorted in place? If the i and x slots are pointers to an input SEXP they should not be modified.
Returns
ans containing pointers to the slots of x, unless check_Udiag and x is unitriangular.
Definition at line 251 of file chm_common.c.
References _, c, check_sorted_chm(), chm2Ralloc(), diag_P, isValid_Csparse(), Matrix_DimSym, Matrix_iSym, Matrix_pSym, MATRIX_VALID_Csparse, stype(), xpt(), and xtype().
Referenced by CSPARSE_VAL_FN_NAME(), and R_init_Matrix().
as_cholmod_triplet()
CHM_TR as_cholmod_triplet (CHM_TR ans, SEXP x, Rboolean check_Udiag)
Populate ans with the pointers from x and modify its scalar elements accordingly.
Note that later changes to the contents of ans will change the contents of the SEXP.
In most cases this function is called through the macros AS_CHM_TR() or AS_CHM_TR__(). It is unusual to call it directly.
Parameters
ans a CHM_TR pointer
x pointer to an object that inherits from TsparseMatrix
check_Udiag boolean - should a check for (and consequent expansion of) a unit diagonal be performed.
Returns
ans containing pointers to the slots of x, unless check_Udiag and x is unitriangular.
Definition at line 493 of file chm_common.c.
References _, c, chTr2Ralloc(), cl, diag_P, Matrix_DimSym, Matrix_iSym, Matrix_jSym, MATRIX_VALID_Tsparse, stype(), xpt(), and xtype().
Referenced by R_init_Matrix().
as_cholmod_x_dense()
CHM_DN as_cholmod_x_dense (CHM_DN ans, SEXP x)
Definition at line 744 of file chm_common.c.
References _AS_cholmod_dense_1, _AS_cholmod_dense_2, Matrix_xSym, and RallocedREAL().
check_sorted_chm()
Rboolean check_sorted_chm (CHM_SP A)
Definition at line 175 of file chm_common.c.
Referenced by as_cholmod_sparse().
chm_dense_to_matrix()
SEXP chm_dense_to_matrix (CHM_DN a, int dofree, SEXP dn)
Copy the contents of a to a matrix object and, optionally, free a or free both a and its pointer to its contents.
Parameters
a cholmod_dense structure to be converted {already REAL for original l..CMatrix}
dofree 0 - don't free a; > 0 cholmod_free a; < 0 Free a
dn either R_NilValue or an SEXP suitable for the Dimnames slot.
Returns
SEXP containing a copy of a as a matrix object
Definition at line 958 of file chm_common.c.
References CHM_DENSE_COPY_DATA, CHM_DENSE_TYPE, and DOFREE_de_MAYBE.
Referenced by Csparse_to_matrix().
chm_dense_to_SEXP()
SEXP chm_dense_to_SEXP (CHM_DN a, int dofree, int Rkind, SEXP dn, Rboolean transp)
Copy the contents of a to an appropriate denseMatrix object and, optionally, free a or free both a and its pointer to its contents.
Parameters
a matrix to be converted
dofree 0 - don't free a; > 0 cholmod_free a; < 0 Free a
Rkind type of R matrix to be generated (special to this function)
dn – dimnames [list(.,.) or NULL; already transposed when transp is TRUE ]
transp Rboolean, if TRUE, the result must be a copy of t(a), i.e., "a transposed"
Returns
SEXP containing a copy of a
Definition at line 851 of file chm_common.c.
References _, ALLOC_SLOT(), cl, DOFREE_de_MAYBE, Matrix_DimNamesSym, Matrix_DimSym, Matrix_xSym, and NEW_OBJECT_OF_CLASS().
Referenced by CHMfactor_solve(), Csparse_to_dense(), and dsCMatrix_matrix_solve().
chm_dense_to_vector()
SEXP chm_dense_to_vector (CHM_DN a, int dofree)
Copy the contents of a to a numeric R object and, optionally, free a or free both a and its pointer to its contents.
Parameters
a cholmod_dense structure to be converted
dofree 0 - don't free a; > 0 cholmod_free a; < 0 Free a
Returns
SEXP containing a copy of a in the sense of as.vector(a)
Definition at line 1012 of file chm_common.c.
References CHM_DENSE_COPY_DATA, CHM_DENSE_TYPE, and DOFREE_de_MAYBE.
Referenced by Csparse_to_vector().
chm_diagN2U()
void chm_diagN2U (CHM_SP chx, int uploT, Rboolean do_realloc)
Drop the (unit) diagonal entries from a cholmod_sparse matrix.
Parameters
chx cholmod_sparse matrix. Note that the matrix "slots" are modified in place
uploT integer code (= +/- 1) indicating if chx is upper (+1) or lower (-1) triangular
do_realloc Rboolean indicating, if a cholmod_sprealloc() should finalize the procedure; not needed, e.g. when the result is converted to a SEXP immediately afterwards.
Definition at line 1223 of file chm_common.c.
References _, _i, _p, _x, c, and nnz.
Referenced by Csparse_Csparse_crossprod(), and Csparse_Csparse_prod().
chm_factor_ok()
static R_INLINE Rboolean chm_factor_ok (CHM_FR f) static
Definition at line 61 of file chm_common.h.
Referenced by chm_factor_to_SEXP(), dsCMatrix_Csparse_solve(), dsCMatrix_matrix_solve(), and internal_chm_factor().
chm_factor_to_SEXP()
SEXP chm_factor_to_SEXP (CHM_FR f, int dofree)
Copy the contents of f to an appropriate CHMfactor object and, optionally, free f or free both f and its pointer to its contents.
Parameters
f cholmod_factor object to be converted
dofree 0 - don't free a; > 0 cholmod_free a; < 0 Free a
Returns
SEXP containing a copy of a
Definition at line 1138 of file chm_common.c.
References _, ALLOC_SLOT(), chm_factor_ok(), DOFREE_MAYBE, Matrix_iSym, Matrix_pSym, Matrix_xSym, and xtype().
Referenced by CHMfactor_update(), CHMfactor_updown(), dgCMatrix_cholsol(), dsCMatrix_Cholesky(), internal_chm_factor(), and R_init_Matrix().
chm_MOD_xtype()
Rboolean chm_MOD_xtype (int to_xtype, cholmod_sparse * A, CHM_CM Common)
Change the "type" of a cholmod_sparse matrix, i.e.
modify it "in place"
Parameters
to_xtype requested xtype (pattern, real, complex, zomplex)
A sparse matrix to change
Common cholmod's common
Returns
TRUE/FALSE , TRUE iff success
Definition at line 451 of file chm_common.c.
CHM_restore_common()
void CHM_restore_common ()
Definition at line 50 of file chm_common.c.
References c, chm_common_env, dboundSym, final_asisSym, final_llSym, final_monotonicSym, final_packSym, final_resymbolSym, final_superSym, grow0Sym, grow1Sym, grow2Sym, m0_ordSym, maxrankSym, nmethodsSym, postorderSym, prefer_upperSym, prefer_zomplexSym, quick_return_if_not_posdefSym, SET_AS_FROM_FRAME, supernodal_switchSym, and supernodalSym.
Referenced by internal_chm_factor(), and R_cholmod_error().
CHM_set_common_env()
SEXP CHM_set_common_env (SEXP rho)
Definition at line 80 of file chm_common.c.
References _, chm_common_env, CHM_store_common(), dboundSym, final_asisSym, final_llSym, final_monotonicSym, final_packSym, final_resymbolSym, final_superSym, grow0Sym, grow1Sym, grow2Sym, m0_ordSym, maxrankSym, nmethodsSym, postorderSym, prefer_upperSym, prefer_zomplexSym, quick_return_if_not_posdefSym, supernodal_switchSym, and supernodalSym.
chm_sparse_to_SEXP()
SEXP chm_sparse_to_SEXP (CHM_SP a, int dofree, int uploT, int Rkind, const char * diag, SEXP dn)
Copy the contents of a to an appropriate CsparseMatrix object and, optionally, free a or free both a and its the pointers to its contents.
Parameters
a (cholmod_sparse) matrix to be converted
dofree 0 - don't free a; > 0 cholmod_free a; < 0 Free a
uploT 0 - not triangular; > 0 upper triangular; < 0 lower
Rkind - vector type to store for a->xtype == CHOLMOD_REAL, 0 - REAL; 1 - LOGICAL [unused for other a->xtype]
diag character string suitable for the diag slot of a triangular matrix (not accessed if uploT == 0).
dn either R_NilValue or an SEXP suitable for the Dimnames slot.
Returns
SEXP containing a copy of a
Definition at line 341 of file chm_common.c.
References _, ALLOC_SLOT(), c, cl, DOFREE_MAYBE, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), and nnz.
Referenced by CHMfactor_spsolve(), CHMfactor_to_sparse(), Csparse2nz(), Csparse_Csparse_crossprod(), Csparse_Csparse_prod(), Csparse_general_to_symmetric(), Csparse_symmetric_to_general(), Csparse_to_tCsparse(), Csparse_transpose(), dense_to_Csparse(), dsCMatrix_chol(), dsCMatrix_Csparse_solve(), R_init_Matrix(), Tsparse_to_Csparse(), and Tsparse_to_tCsparse().
CHM_store_common()
void CHM_store_common ()
Definition at line 25 of file chm_common.c.
References c, chm_common_env, dboundSym, final_asisSym, final_llSym, final_monotonicSym, final_packSym, final_resymbolSym, final_superSym, grow0Sym, grow1Sym, grow2Sym, m0_ordSym, maxrankSym, nmethodsSym, postorderSym, prefer_upperSym, prefer_zomplexSym, quick_return_if_not_posdefSym, supernodal_switchSym, and supernodalSym.
Referenced by CHM_set_common_env(), and internal_chm_factor().
chm_transpose_dense()
void chm_transpose_dense (CHM_DN ans, CHM_DN x)
Transpose a cholmod_dense matrix ("too trivial to be in CHOLMOD?")
Parameters
ans (pointer to) already allocated result of correct dimension
x (pointer to) cholmod_dense matrix to be transposed
Definition at line 767 of file chm_common.c.
References _.
chm_triplet_to_SEXP()
SEXP chm_triplet_to_SEXP (CHM_TR a, int dofree, int uploT, int Rkind, const char * diag, SEXP dn)
Copy the contents of a to an appropriate TsparseMatrix object and, optionally, free a or free both a and its the pointers to its contents.
Parameters
a matrix to be converted
dofree 0 - don't free a; > 0 cholmod_free a; < 0 Free a
uploT 0 - not triangular; > 0 upper triangular; < 0 lower
Rkind - vector type to store for a->xtype == CHOLMOD_REAL, 0 - REAL; 1 - LOGICAL
diag character string suitable for the diag slot of a triangular matrix (not accessed if uploT == 0).
dn either R_NilValue or an SEXP suitable for the Dimnames slot.
Returns
SEXP containing a copy of a
Definition at line 586 of file chm_common.c.
References _, ALLOC_SLOT(), cl, DOFREE_MAYBE, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_uploSym, Matrix_xSym, and NEW_OBJECT_OF_CLASS().
Referenced by Csparse_to_Tsparse(), Csparse_to_tTsparse(), dsCMatrix_to_dgTMatrix(), and R_init_Matrix().
CHMfactor_validate()
SEXP CHMfactor_validate (SEXP obj)
Definition at line 1291 of file chm_common.c.
CHMsimpl_validate()
SEXP CHMsimpl_validate (SEXP obj)
Definition at line 1296 of file chm_common.c.
CHMsuper_validate()
SEXP CHMsuper_validate (SEXP obj)
Definition at line 1301 of file chm_common.c.
get_SuiteSparse_version()
SEXP get_SuiteSparse_version ()
Definition at line 8 of file chm_common.c.
numeric_as_chm_dense()
CHM_DN numeric_as_chm_dense (CHM_DN ans, double * v, int nr, int nc)
Definition at line 1023 of file chm_common.c.
Referenced by R_init_Matrix().
R_cholmod_error()
void R_cholmod_error (int status, const char * file, int line, const char * message)
Definition at line 782 of file chm_common.c.
References _, and CHM_restore_common().
Referenced by R_cholmod_start().
R_cholmod_l_start()
int R_cholmod_l_start (CHM_CM Common)
R_cholmod_start()
int R_cholmod_start (CHM_CM c)
Initialize the CHOLMOD library and replace the print and error functions by R-specific versions.
Parameters
c pointer to a cholmod_common structure to be initialized
Returns
TRUE if successful
Definition at line 823 of file chm_common.c.
References _, c, R_cholmod_error(), and R_cholmod_printf().
Referenced by R_init_Matrix().
Variable Documentation
c
cholmod_common c extern
Definition at line 15 of file chm_common.c.
Referenced by as_cholmod_factor3(), as_cholmod_sparse(), as_cholmod_triplet(), chm2Ralloc(), chm_diagN2U(), chm_factor_update(), CHM_restore_common(), chm_sparse_to_SEXP(), CHM_store_common(), CHMfactor_ldetL2up(), CHMfactor_solve(), CHMfactor_spsolve(), CHMfactor_to_sparse(), CHMfactor_update(), CHMfactor_updown(), cs_chol(), cs_cumsum(), cs_schol(), Csparse2nz(), Csparse_Csparse_crossprod(), Csparse_Csparse_prod(), Csparse_general_to_symmetric(), Csparse_symmetric_to_general(), Csparse_to_dense(), Csparse_to_matrix(), Csparse_to_Tsparse(), Csparse_to_tTsparse(), Csparse_to_vector(), Csparse_transpose(), dense_to_Csparse(), dgCMatrix_cholsol(), dsCMatrix_chol(), dsCMatrix_Csparse_solve(), dsCMatrix_LDL_D(), dsCMatrix_matrix_solve(), dsCMatrix_to_dgTMatrix(), gCMatrix_colSums(), internal_chm_factor(), Matrix_RLE_(), R_cholmod_start(), R_init_Matrix(), R_unload_Matrix(), Tsparse_to_Csparse(), and Tsparse_to_tCsparse().
cl
cholmod_common cl extern
Definition at line 16 of file chm_common.c.
Referenced by as_cholmod_triplet(), chm_dense_to_SEXP(), chm_sparse_to_SEXP(), chm_triplet_to_SEXP(), dense_band(), dense_to_Csparse(), dense_to_symmetric(), dtCMatrix_matrix_solve(), and Matrix_cs_to_SEXP().