Matrix: CHMfactor.h File Reference
CHMfactor.h File Reference
#include "Mutils.h"
#include "chm_common.h"
Functions
double chm_factor_ldetL2 (CHM_FR f)
Evaluate the logarithm of the square of the determinant of L.
CHM_FR chm_factor_update (CHM_FR f, CHM_SP A, double fac)
Update the numerical values in the factor f as A + mult * I, if A is symmetric, otherwise AA' + mult * I.
SEXP CHMfactor_ldetL2 (SEXP x)
SEXP CHMfactor_ldetL2up (SEXP x, SEXP parent, SEXP mult)
SEXP CHMfactor_solve (SEXP a, SEXP b, SEXP type)
SEXP CHMfactor_spsolve (SEXP a, SEXP b, SEXP type)
SEXP CHMfactor_to_sparse (SEXP x)
SEXP CHMfactor_update (SEXP object, SEXP parent, SEXP mult)
SEXP CHMfactor_updown (SEXP update, SEXP C, SEXP L)
SEXP destructive_CHM_update (SEXP object, SEXP parent, SEXP mult)
Function Documentation
chm_factor_ldetL2()
double chm_factor_ldetL2 (CHM_FR f)
Evaluate the logarithm of the square of the determinant of L.
Parameters
f pointer to a CHMfactor object
Returns
log(det(L)^2)
Definition at line 81 of file CHMfactor.c.
References _.
Referenced by CHMfactor_ldetL2(), CHMfactor_ldetL2up(), and R_init_Matrix().
chm_factor_update()
CHM_FR chm_factor_update (CHM_FR f, CHM_SP A, double mult)
Update the numerical values in the factor f as A + mult * I, if A is symmetric, otherwise AA' + mult * I.
Parameters
f pointer to a CHM_FR object. f is updated upon return.
A pointer to a CHM_SP object, possibly symmetric
mult multiple of the identity to be added to A or AA' before decomposing.
Note
: A and f must be compatible. There is no check on this here. Incompatibility of A and f will cause the CHOLMOD functions to take an error exit.
Definition at line 134 of file CHMfactor.c.
References _, and c.
Referenced by CHMfactor_ldetL2up(), CHMfactor_update(), destructive_CHM_update(), and R_init_Matrix().
CHMfactor_ldetL2()
SEXP CHMfactor_ldetL2 (SEXP x)
Definition at line 113 of file CHMfactor.c.
References AS_CHM_FR, and chm_factor_ldetL2().
CHMfactor_ldetL2up()
SEXP CHMfactor_ldetL2up (SEXP x, SEXP parent, SEXP mult)
Definition at line 174 of file CHMfactor.c.
References AS_CHM_FR, AS_CHM_SP__, c, chm_factor_ldetL2(), and chm_factor_update().
CHMfactor_solve()
SEXP CHMfactor_solve (SEXP a, SEXP b, SEXP type)
Definition at line 20 of file CHMfactor.c.
References _, AS_CHM_DN, AS_CHM_FR, c, chm_dense_to_SEXP(), dup_mMatrix_as_dgeMatrix(), and Matrix_DimNamesSym.
CHMfactor_spsolve()
SEXP CHMfactor_spsolve (SEXP a, SEXP b, SEXP type)
Definition at line 52 of file CHMfactor.c.
References _, AS_CHM_FR, AS_CHM_SP__, c, chm_sparse_to_SEXP(), and Matrix_DimNamesSym.
CHMfactor_to_sparse()
SEXP CHMfactor_to_sparse (SEXP x)
Definition at line 4 of file CHMfactor.c.
References _, AS_CHM_FR, c, and chm_sparse_to_SEXP().
CHMfactor_update()
SEXP CHMfactor_update (SEXP object, SEXP parent, SEXP mult)
Definition at line 152 of file CHMfactor.c.
References AS_CHM_FR, AS_CHM_SP__, c, chm_factor_to_SEXP(), and chm_factor_update().
CHMfactor_updown()
SEXP CHMfactor_updown (SEXP update, SEXP C, SEXP L)
Definition at line 39 of file CHMfactor.c.
References _, AS_CHM_FR, AS_CHM_SP__, c, and chm_factor_to_SEXP().
destructive_CHM_update()
SEXP destructive_CHM_update (SEXP object, SEXP parent, SEXP mult)
Definition at line 163 of file CHMfactor.c.
References AS_CHM_FR, AS_CHM_SP__, and chm_factor_update().