Matrix: Cholesky.c File Reference
Cholesky.c File Reference
#include "Lapack-etc.h"
#include "cholmod-etc.h"
#include "Mdefines.h"
Functions
SEXP dense_as_kind (SEXP, const char *, char, int)
SEXP sparse_as_kind (SEXP, const char *, char)
SEXP sparse_as_general (SEXP, const char *)
SEXP sparse_as_Csparse (SEXP, const char *)
SEXP dense_force_canonical (SEXP, const char *, int)
SEXP sparse_force_symmetric (SEXP, const char *, char, char)
SEXP sparse_transpose (SEXP, const char *, char, int)
SEXP dense_cholesky (SEXP obj, const char *class, int warn, int pivot, double tol, char ul)
SEXP sparse_cholesky (SEXP obj, const char *class, int warn, int order, int *ll, int *super, Rcomplex beta, int force, char ul, SEXP trf)
SEXP R_dense_cholesky (SEXP s_obj, SEXP s_warn, SEXP s_pivot, SEXP s_tol, SEXP s_uplo)
SEXP R_sparse_cholesky (SEXP s_obj, SEXP s_warn, SEXP s_order, SEXP s_ll, SEXP s_super, SEXP s_beta, SEXP s_force, SEXP s_uplo)
Function Documentation
dense_as_kind()
SEXP dense_as_kind (SEXP from, const char * class, char kind, int new)
Definition at line 2000 of file coerce.c.
Referenced by dense_cholesky().
dense_cholesky()
SEXP dense_cholesky (SEXP obj, const char * class, int warn, int pivot, double tol, char ul)
Definition at line 20 of file Cholesky.c.
References _, cl, dense_as_kind(), dense_force_canonical(), DIAG, DIM, DIMNAMES, ERROR_LAPACK_3, ERROR_LAPACK_4, FCONE, GET_SLOT, Matrix_class(), Matrix_permSym, Matrix_xSym, newObject(), SET_DIM, SET_DIMNAMES, SET_SLOT, SET_UPLO, TYPEOF, UPLO, and valid_dense.
Referenced by R_dense_cholesky().
dense_force_canonical()
SEXP dense_force_canonical (SEXP from, const char * class, int check)
Definition at line 7 of file forceCanonical.c.
Referenced by dense_cholesky(), and R_dense_force_canonical().
R_dense_cholesky()
SEXP R_dense_cholesky (SEXP s_obj, SEXP s_warn, SEXP s_pivot, SEXP s_tol, SEXP s_uplo)
Definition at line 197 of file Cholesky.c.
References _, dense_cholesky(), get_factor(), Matrix_class(), set_factor(), TRANS, valid_dense, and VALID_UPLO.
R_sparse_cholesky()
SEXP R_sparse_cholesky (SEXP s_obj, SEXP s_warn, SEXP s_order, SEXP s_ll, SEXP s_super, SEXP s_beta, SEXP s_force, SEXP s_uplo)
Definition at line 230 of file Cholesky.c.
References _, c, CHF2M(), DIMNAMES, get_factor(), M2CHF(), Matrix_class(), SET_DIMNAMES, set_factor(), sparse_cholesky(), TRANS, TYPEOF, valid_sparse, and VALID_UPLO.
sparse_as_Csparse()
SEXP sparse_as_Csparse (SEXP from, const char * class)
Definition at line 2731 of file coerce.c.
References _, cl, COPY_SLOT, DIAG, DIM, DIMNAMES, GET_SLOT, Matrix_Calloc, Matrix_factorsSym, Matrix_Free, Matrix_iSym, Matrix_jSym, Matrix_pSym, newObject(), SET_DIAG, SET_DIM, SET_DIMNAMES, SET_SLOT, SET_TRANS, SET_UPLO, SWITCH5, TEMPLATE, TRANS, and UPLO.
Referenced by coerceArgs(), sparse_cholesky(), sparse_is_symmetric(), sparse_subscript_1ary(), sparse_subscript_1ary_2col(), and sparse_subscript_2ary().
sparse_as_general()
SEXP sparse_as_general (SEXP from, const char * class)
Definition at line 2298 of file coerce.c.
References _, cl, COPY_SLOT, DIAG, DIM, DIMNAMES, GET_SLOT, Matrix_factorsSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_xSym, newObject(), SET_DIM, SET_DIMNAMES, SET_SLOT, SWITCH5, TEMPLATE, TRANS, and UPLO.
Referenced by coerceArgs(), Csparse_writeMM(), R_sparse_diag_set(), R_sparse_matmult(), sparse_cholesky(), and sparse_subscript_2ary().
sparse_as_kind()
SEXP sparse_as_kind (SEXP from, const char * class, char kind)
Definition at line 2076 of file coerce.c.
References allocUnit(), cl, DIAG, DIM, DIMNAMES, GET_SLOT, kindToType(), Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_xSym, newObject(), SET_DIAG, SET_DIM, SET_DIMNAMES, SET_SLOT, SET_UPLO, sparse_aggregate(), and UPLO.
Referenced by coerceArgs(), Csparse_writeMM(), R_diagonal_matmult(), R_sparse_diag_set(), and sparse_cholesky().
sparse_cholesky()
SEXP sparse_cholesky (SEXP obj, const char * class, int warn, int order, int * ll, int * super, Rcomplex beta, int force, char ul, SEXP trf)
Definition at line 118 of file Cholesky.c.
References c, CHF2M(), DIMNAMES, M2CHF(), M2CHS(), Matrix_class(), SET_DIMNAMES, sparse_as_Csparse(), sparse_as_general(), sparse_as_kind(), sparse_force_symmetric(), sparse_transpose(), symDN(), TRANS, TYPEOF, UPLO, and valid_sparse.
Referenced by R_sparse_cholesky().
sparse_force_symmetric()
SEXP sparse_force_symmetric (SEXP from, const char * class, char op_ul, char op_ct)
Definition at line 83 of file forceSymmetric.c.
References _, cl, DIAG, DIM, DIMNAMES, GET_SLOT, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_xSym, newObject(), SET_DIM, SET_DIMNAMES, SET_SLOT, SET_TRANS, SET_UPLO, SWITCH5, TEMPLATE, TRANS, UPLO, zASSIGN_CONJ, zASSIGN_IDEN, and zASSIGN_PROJ_REAL.
Referenced by R_sparse_force_symmetric(), sparse_cholesky(), and sparse_subscript_2ary().
sparse_transpose()
SEXP sparse_transpose (SEXP from, const char * class, char op_ct, int lazy)
Definition at line 52 of file t.c.
References cl, DIAG, DIM, DIMNAMES, GET_SLOT, Matrix_Calloc, Matrix_Free, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_xSym, newObject(), SET_DIAG, SET_DIM, SET_DIMNAMES, SET_SLOT, SET_TRANS, SET_UPLO, SWAP, SWITCH5, TEMPLATE, TRANS, UPLO, and zvconj().
Referenced by sparse_cholesky().