Matrix: cholmod-etc.h File Reference
cholmod-etc.h File Reference
#include "SuiteSparse/CHOLMOD/Include/cholmod.h"
#include <Rinternals.h>
Functions
int Matrix_cholmod_start (cholmod_common *)
int Matrix_cholmod_finish (cholmod_common *)
cholmod_factor * M2CHF (SEXP, int)
cholmod_sparse * M2CHS (SEXP, int)
cholmod_dense * M2CHD (SEXP, char)
SEXP CHF2M (cholmod_factor *, int)
SEXP CHS2M (cholmod_sparse *, int, char)
SEXP CHD2M (cholmod_dense *, char, char)
Variables
cholmod_common c
cholmod_common cl
Function Documentation
CHD2M()
SEXP CHD2M (cholmod_dense * A, char trans, char shape)
Definition at line 375 of file cholmod-etc.c.
References _, dtrans2(), errorChar, GET_SLOT, Matrix_DimSym, Matrix_xSym, newObject(), SET_SLOT, and ztrans2().
Referenced by sparseCholesky_solve().
CHF2M()
SEXP CHF2M (cholmod_factor * L, int values)
Definition at line 222 of file cholmod-etc.c.
References _, errorChar, GET_SLOT, Matrix_colcountSym, Matrix_DimSym, Matrix_isllSym, Matrix_ismtSym, Matrix_iSym, Matrix_maxcsizeSym, Matrix_maxesizeSym, Matrix_minorSym, Matrix_nextSym, Matrix_nzSym, Matrix_orderingSym, Matrix_permSym, Matrix_piSym, Matrix_prevSym, Matrix_pSym, Matrix_pxSym, Matrix_sSym, Matrix_superSym, Matrix_xSym, newObject(), and SET_SLOT.
Referenced by dgCMatrix_cholsol(), R_sparse_cholesky(), and sparse_cholesky().
CHS2M()
SEXP CHS2M (cholmod_sparse * A, int values, char shape)
Definition at line 328 of file cholmod-etc.c.
References _, c, errorChar, GET_SLOT, Matrix_DimSym, Matrix_iSym, Matrix_pSym, Matrix_xSym, newObject(), and SET_SLOT.
Referenced by gCgCMatrix_matmult(), and sparseCholesky_solve().
M2CHD()
cholmod_dense * M2CHD (SEXP obj, char trans)
Definition at line 176 of file cholmod-etc.c.
References dtrans2(), GET_SLOT, Matrix_class(), Matrix_DimSym, Matrix_xSym, and ztrans2().
Referenced by gCgeMatrix_matmult(), and sparseCholesky_solve().
M2CHF()
cholmod_factor * M2CHF (SEXP obj, int values)
Definition at line 39 of file cholmod-etc.c.
References GET_SLOT, Matrix_class(), Matrix_colcountSym, Matrix_DimSym, Matrix_isllSym, Matrix_ismtSym, Matrix_iSym, Matrix_maxcsizeSym, Matrix_maxesizeSym, Matrix_minorSym, Matrix_nextSym, Matrix_nzSym, Matrix_orderingSym, Matrix_permSym, Matrix_piSym, Matrix_prevSym, Matrix_pSym, Matrix_pxSym, Matrix_sSym, Matrix_superSym, and Matrix_xSym.
Referenced by R_sparse_cholesky(), sparse_cholesky(), sparseCholesky_determinant(), sparseCholesky_diag_get(), sparseCholesky_solve(), sparseCholesky_update(), and sparseCholesky_updown().
M2CHS()
cholmod_sparse * M2CHS (SEXP obj, int values)
Definition at line 132 of file cholmod-etc.c.
References GET_SLOT, Matrix_class(), Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, and valid_sparse_compressed.
Referenced by Csparse_writeMM(), CsparseMatrix_validate_maybe_sorting(), dgCMatrix_cholsol(), gCgCMatrix_matmult(), gCgeMatrix_matmult(), sparse_cholesky(), sparseCholesky_solve(), sparseCholesky_update(), and sparseCholesky_updown().
Matrix_cholmod_finish()
int Matrix_cholmod_finish (cholmod_common * Common)
Definition at line 31 of file cholmod-etc.c.
References _.
Referenced by R_unload_Matrix().
Matrix_cholmod_start()
int Matrix_cholmod_start (cholmod_common * Common)
Definition at line 22 of file cholmod-etc.c.
References _, and Matrix_cholmod_error_handler().
Referenced by R_init_Matrix().
Variable Documentation
c
cholmod_common c extern
Definition at line 5 of file cholmod-etc.c.
Referenced by cholmod_factor_update(), cholmod_sparse_as_sexp(), CHS2M(), Csparse_writeMM(), CsparseMatrix_validate_maybe_sorting(), denseBunchKaufman_determinant(), dgCMatrix_cholsol(), gCgCMatrix_matmult(), gCgeMatrix_matmult(), Matrix_cholmod_error_handler(), Matrix_RLE_(), R_init_Matrix(), R_sparse_cholesky(), R_unload_Matrix(), sexp_as_cholmod_sparse(), sparse_cholesky(), sparseCholesky_solve(), sparseCholesky_update(), and sparseCholesky_updown().
cl
cholmod_common cl extern
Definition at line 6 of file cholmod-etc.c.
Referenced by dense_as_general(), dense_as_kind(), dense_as_packed(), dense_as_sparse(), dense_as_unpacked(), dense_band(), dense_bunchkaufman(), dense_cholesky(), dense_expm(), dense_force_symmetric(), dense_lu(), dense_schur(), dense_skewpart(), dense_subscript_2ary(), dense_symmpart(), denseBunchKaufman_expand(), diagonal_as_dense(), diagonal_as_kind(), diagonal_as_sparse(), diagonal_as_Vector(), diagonal_subscript_2ary(), index_as_dense(), index_as_sparse(), matrix_as_dense(), matrix_as_sparse(), sparse_as_Csparse(), sparse_as_dense(), sparse_as_general(), sparse_as_kind(), sparse_as_Rsparse(), sparse_as_Tsparse(), sparse_as_Vector(), sparse_band(), sparse_force_symmetric(), sparse_is_symmetric(), sparse_lu(), sparse_marginsum(), sparse_qr(), sparse_skewpart(), sparse_subscript_2ary(), sparse_symmpart(), sparse_transpose(), validObject(), vector_as_dense(), Vector_as_sparse(), and vector_as_Vector().