Matrix: coerce.h File Reference
coerce.h File Reference
#include <Rinternals.h>
Functions
SEXP vector_as_dense (SEXP, const char *, char, char, int, int, int, SEXP)
SEXP R_vector_as_dense (SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP matrix_as_dense (SEXP, const char *, char, char, int, int)
SEXP R_matrix_as_dense (SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP sparse_as_dense (SEXP, const char *, int)
SEXP R_sparse_as_dense (SEXP, SEXP)
SEXP diagonal_as_dense (SEXP, const char *, char, char, int, char)
SEXP R_diagonal_as_dense (SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP index_as_dense (SEXP, const char *, char)
SEXP R_index_as_dense (SEXP, SEXP)
SEXP vector_as_sparse (SEXP, const char *, char, char, int, int, int, SEXP)
SEXP R_vector_as_sparse (SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP matrix_as_sparse (SEXP, const char *, char, char, int)
SEXP R_matrix_as_sparse (SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP dense_as_sparse (SEXP, const char *, char)
SEXP R_dense_as_sparse (SEXP, SEXP)
SEXP diagonal_as_sparse (SEXP, const char *, char, char, char, char)
SEXP R_diagonal_as_sparse (SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP index_as_sparse (SEXP, const char *, char, char)
SEXP R_index_as_sparse (SEXP, SEXP, SEXP)
SEXP dense_as_kind (SEXP, const char *, char, int)
SEXP R_dense_as_kind (SEXP, SEXP)
SEXP sparse_as_kind (SEXP, const char *, char)
SEXP R_sparse_as_kind (SEXP, SEXP)
SEXP diagonal_as_kind (SEXP, const char *, char)
SEXP R_diagonal_as_kind (SEXP, SEXP)
SEXP index_as_kind (SEXP, const char *, char)
SEXP R_index_as_kind (SEXP, SEXP)
SEXP dense_as_general (SEXP, const char *, int)
SEXP R_dense_as_general (SEXP)
SEXP sparse_as_general (SEXP, const char *)
SEXP R_sparse_as_general (SEXP)
SEXP dense_as_unpacked (SEXP, const char *)
SEXP R_dense_as_unpacked (SEXP)
SEXP dense_as_packed (SEXP, const char *, char, char)
SEXP R_dense_as_packed (SEXP, SEXP, SEXP)
SEXP sparse_as_Csparse (SEXP, const char *)
SEXP R_sparse_as_Csparse (SEXP)
SEXP sparse_as_Rsparse (SEXP, const char *)
SEXP R_sparse_as_Rsparse (SEXP)
SEXP sparse_as_Tsparse (SEXP, const char *)
SEXP R_sparse_as_Tsparse (SEXP)
SEXP R_Matrix_as_vector (SEXP)
SEXP R_Matrix_as_matrix (SEXP)
SEXP R_Matrix_as_unpacked (SEXP)
SEXP R_Matrix_as_packed (SEXP)
SEXP R_Matrix_as_Csparse (SEXP)
SEXP R_Matrix_as_Rsparse (SEXP)
SEXP R_Matrix_as_Tsparse (SEXP)
SEXP R_Matrix_as_kind (SEXP, SEXP, SEXP)
SEXP R_Matrix_as_general (SEXP, SEXP)
Function Documentation
dense_as_general()
SEXP dense_as_general (SEXP from, const char * class, int new)
Definition at line 2734 of file coerce.c.
References _, cl, DAG_SUBCASES, GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, and set_symmetrized_DimNames().
Referenced by coerceArgs(), dense_band(), R_dense_as_general(), R_dense_matmult(), R_diagonal_matmult(), R_Matrix_as_general(), R_Matrix_as_matrix(), R_Matrix_as_vector(), and R_sparse_matmult().
dense_as_kind()
SEXP dense_as_kind (SEXP from, const char * class, char kind, int new)
Definition at line 2409 of file coerce.c.
References cl, GET_SLOT, kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, naToOne(), newObject(), and SET_SLOT.
Referenced by coerceArgs(), dense_skewpart(), dense_symmpart(), R_dense_as_kind(), R_dense_diag_set(), R_dense_matmult(), R_diagonal_matmult(), R_Matrix_as_general(), R_Matrix_as_kind(), and R_sparse_matmult().
dense_as_packed()
SEXP dense_as_packed (SEXP from, const char * class, char ul, char di)
Definition at line 3224 of file coerce.c.
References _, cl, GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_sdSym, Matrix_uploSym, Matrix_xSym, newObject(), PACK, PACKED_LENGTH, and SET_SLOT.
Referenced by R_dense_as_packed(), and R_Matrix_as_packed().
dense_as_sparse()
SEXP dense_as_sparse (SEXP from, const char * class, char repr)
Definition at line 1647 of file coerce.c.
References cl, DAS_CASES, DAS_SUBCASES, GET_SLOT, HIDE, ISNZ_LOGICAL, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, and SHOW.
Referenced by coerceArgs(), matrix_as_sparse(), R_dense_as_sparse(), R_Matrix_as_Csparse(), R_Matrix_as_kind(), R_Matrix_as_Rsparse(), R_Matrix_as_Tsparse(), and R_sparse_matmult().
dense_as_unpacked()
SEXP dense_as_unpacked (SEXP from, const char * class)
Definition at line 3119 of file coerce.c.
References _, cl, GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_sdSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, and UNPACK.
Referenced by R_dense_as_unpacked(), and R_Matrix_as_unpacked().
diagonal_as_dense()
SEXP diagonal_as_dense (SEXP from, const char * class, char kind, char shape, int packed, char ul)
Definition at line 798 of file coerce.c.
References _, cl, DAD_SUBCASES, GET_SLOT, kindToSize(), kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, naToOne(), newObject(), SET_SLOT, and set_symmetrized_DimNames().
Referenced by coerceArgs(), R_diagonal_as_dense(), R_Matrix_as_kind(), R_Matrix_as_matrix(), R_Matrix_as_packed(), R_Matrix_as_unpacked(), and R_Matrix_as_vector().
diagonal_as_kind()
SEXP diagonal_as_kind (SEXP from, const char * class, char kind)
Definition at line 2634 of file coerce.c.
References cl, GET_SLOT, kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_xSym, naToOne(), newObject(), and SET_SLOT.
Referenced by R_diagonal_as_kind(), R_diagonal_matmult(), and R_Matrix_as_kind().
diagonal_as_sparse()
SEXP diagonal_as_sparse (SEXP from, const char * class, char kind, char shape, char repr, char ul)
Definition at line 2066 of file coerce.c.
References cl, DAS_CASES, DAS_LOOP, GET_SLOT, HIDE, ISNZ_LOGICAL, kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_memset(), Matrix_pSym, Matrix_uploSym, Matrix_xSym, naToOne(), newObject(), SET_SLOT, set_symmetrized_DimNames(), and SHOW.
Referenced by coerceArgs(), R_diagonal_as_sparse(), R_Matrix_as_Csparse(), R_Matrix_as_general(), R_Matrix_as_kind(), R_Matrix_as_Rsparse(), and R_Matrix_as_Tsparse().
index_as_dense()
SEXP index_as_dense (SEXP from, const char * class, char kind)
Definition at line 931 of file coerce.c.
References _, cl, GET_SLOT, IAD_SUBCASES, kindToSize(), kindToType(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_marginSym, Matrix_permSym, Matrix_xSym, Matrix_zone, newObject(), and SET_SLOT.
Referenced by coerceArgs(), R_index_as_dense(), R_Matrix_as_kind(), R_Matrix_as_matrix(), R_Matrix_as_unpacked(), and R_Matrix_as_vector().
index_as_kind()
SEXP index_as_kind (SEXP from, const char * class, char kind)
Definition at line 2712 of file coerce.c.
References index_as_sparse().
Referenced by R_index_as_kind().
index_as_sparse()
SEXP index_as_sparse (SEXP from, const char * class, char kind, char repr)
Definition at line 2281 of file coerce.c.
References cl, GET_SLOT, IAS_SUBCASES, kindToType(), Matrix_Calloc, Matrix_DimNamesSym, Matrix_DimSym, Matrix_Free, Matrix_iSym, Matrix_jSym, Matrix_marginSym, Matrix_memcpy(), Matrix_memset(), Matrix_permSym, Matrix_pSym, Matrix_xSym, Matrix_zone, newObject(), and SET_SLOT.
Referenced by coerceArgs(), index_as_kind(), R_index_as_sparse(), R_Matrix_as_Csparse(), R_Matrix_as_general(), R_Matrix_as_kind(), R_Matrix_as_Rsparse(), and R_Matrix_as_Tsparse().
matrix_as_dense()
SEXP matrix_as_dense (SEXP from, const char * zzz, char ul, char di, int trans, int new)
Definition at line 297 of file coerce.c.
References _, cl, GET_SLOT, kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_memcpy(), Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, set_symmetrized_DimNames(), trans(), and typeToKind().
Referenced by matrix_as_sparse(), R_dense_band(), R_dense_is_diagonal(), R_dense_is_symmetric(), R_dense_is_triangular(), R_dense_matmult(), R_diagonal_matmult(), R_matrix_as_dense(), and R_sparse_matmult().
matrix_as_sparse()
SEXP matrix_as_sparse (SEXP from, const char * zzz, char ul, char di, int trans)
Definition at line 1580 of file coerce.c.
References cl, dense_as_sparse(), matrix_as_dense(), sparse_as_kind(), trans(), and typeToKind().
Referenced by coerceArgs(), R_matrix_as_sparse(), and R_sparse_matmult().
R_dense_as_general()
SEXP R_dense_as_general (SEXP from)
Definition at line 2821 of file coerce.c.
References dense_as_general(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_as_kind()
SEXP R_dense_as_kind (SEXP from, SEXP kind)
Definition at line 2483 of file coerce.c.
References _, dense_as_kind(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_as_packed()
SEXP R_dense_as_packed (SEXP from, SEXP uplo, SEXP diag)
Definition at line 3330 of file coerce.c.
References _, dense_as_packed(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_as_sparse()
SEXP R_dense_as_sparse (SEXP from, SEXP repr)
Definition at line 2050 of file coerce.c.
References _, dense_as_sparse(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_as_unpacked()
SEXP R_dense_as_unpacked (SEXP from)
Definition at line 3212 of file coerce.c.
References dense_as_unpacked(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_diagonal_as_dense()
SEXP R_diagonal_as_dense (SEXP from, SEXP kind, SEXP shape, SEXP packed, SEXP uplo)
Definition at line 893 of file coerce.c.
References _, diagonal_as_dense(), ERROR_INVALID_CLASS, valid, and VALID_DIAGONAL.
R_diagonal_as_kind()
SEXP R_diagonal_as_kind (SEXP from, SEXP kind)
Definition at line 2696 of file coerce.c.
References _, diagonal_as_kind(), ERROR_INVALID_CLASS, valid, and VALID_DIAGONAL.
R_diagonal_as_sparse()
SEXP R_diagonal_as_sparse (SEXP from, SEXP kind, SEXP shape, SEXP repr, SEXP uplo)
Definition at line 2244 of file coerce.c.
References _, diagonal_as_sparse(), ERROR_INVALID_CLASS, valid, and VALID_DIAGONAL.
R_index_as_dense()
SEXP R_index_as_dense (SEXP from, SEXP kind)
Definition at line 1004 of file coerce.c.
References _, ERROR_INVALID_CLASS, index_as_dense(), and valid.
R_index_as_kind()
SEXP R_index_as_kind (SEXP from, SEXP kind)
Definition at line 2718 of file coerce.c.
References _, ERROR_INVALID_CLASS, index_as_kind(), and valid.
R_index_as_sparse()
SEXP R_index_as_sparse (SEXP from, SEXP kind, SEXP repr)
Definition at line 2386 of file coerce.c.
References _, ERROR_INVALID_CLASS, index_as_sparse(), and valid.
R_Matrix_as_Csparse()
SEXP R_Matrix_as_Csparse (SEXP from)
Definition at line 4231 of file coerce.c.
References cl, dense_as_sparse(), diagonal_as_sparse(), ERROR_INVALID_CLASS, index_as_sparse(), sparse_as_Csparse(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_matrix_as_dense()
SEXP R_matrix_as_dense (SEXP from, SEXP zzz, SEXP uplo, SEXP diag, SEXP trans)
Definition at line 454 of file coerce.c.
References _, ERROR_INVALID_TYPE, matrix_as_dense(), and trans().
R_Matrix_as_general()
SEXP R_Matrix_as_general (SEXP from, SEXP kind)
Definition at line 4384 of file coerce.c.
References _, cl, dense_as_general(), dense_as_kind(), diagonal_as_sparse(), ERROR_INVALID_CLASS, index_as_sparse(), sparse_as_general(), sparse_as_kind(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_Matrix_as_kind()
SEXP R_Matrix_as_kind (SEXP from, SEXP kind, SEXP sparse)
Definition at line 4315 of file coerce.c.
References _, cl, dense_as_kind(), dense_as_sparse(), diagonal_as_dense(), diagonal_as_kind(), diagonal_as_sparse(), ERROR_INVALID_CLASS, index_as_dense(), index_as_sparse(), sparse_as_dense(), sparse_as_kind(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_Matrix_as_matrix()
SEXP R_Matrix_as_matrix (SEXP from)
Definition at line 4102 of file coerce.c.
References cl, dense_as_general(), diagonal_as_dense(), DimNames_is_trivial(), ERROR_INVALID_CLASS, GET_SLOT, index_as_dense(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_xSym, naToOne(), sparse_as_dense(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_Matrix_as_packed()
SEXP R_Matrix_as_packed (SEXP from)
Definition at line 4202 of file coerce.c.
References _, cl, dense_as_packed(), diagonal_as_dense(), ERROR_INVALID_CLASS, sparse_as_dense(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_Matrix_as_Rsparse()
SEXP R_Matrix_as_Rsparse (SEXP from)
Definition at line 4259 of file coerce.c.
References cl, dense_as_sparse(), diagonal_as_sparse(), ERROR_INVALID_CLASS, index_as_sparse(), sparse_as_Rsparse(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_matrix_as_sparse()
SEXP R_matrix_as_sparse (SEXP from, SEXP zzz, SEXP uplo, SEXP diag, SEXP trans)
Definition at line 1602 of file coerce.c.
References _, ERROR_INVALID_TYPE, matrix_as_sparse(), and trans().
R_Matrix_as_Tsparse()
SEXP R_Matrix_as_Tsparse (SEXP from)
Definition at line 4287 of file coerce.c.
References cl, dense_as_sparse(), diagonal_as_sparse(), ERROR_INVALID_CLASS, index_as_sparse(), sparse_as_Tsparse(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_Matrix_as_unpacked()
SEXP R_Matrix_as_unpacked (SEXP from)
Definition at line 4173 of file coerce.c.
References cl, dense_as_unpacked(), diagonal_as_dense(), ERROR_INVALID_CLASS, index_as_dense(), sparse_as_dense(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_Matrix_as_vector()
SEXP R_Matrix_as_vector (SEXP from)
Definition at line 4029 of file coerce.c.
References cl, dense_as_general(), diagonal_as_dense(), ERROR_INVALID_CLASS, GET_SLOT, index_as_dense(), Matrix_xSym, naToOne(), sparse_as_dense(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_sparse_as_Csparse()
SEXP R_sparse_as_Csparse (SEXP from)
Definition at line 3809 of file coerce.c.
References ERROR_INVALID_CLASS, sparse_as_Csparse(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_as_dense()
SEXP R_sparse_as_dense (SEXP from, SEXP packed)
Definition at line 782 of file coerce.c.
References _, ERROR_INVALID_CLASS, sparse_as_dense(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_as_general()
SEXP R_sparse_as_general (SEXP from)
Definition at line 3108 of file coerce.c.
References ERROR_INVALID_CLASS, sparse_as_general(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_as_kind()
SEXP R_sparse_as_kind (SEXP from, SEXP kind)
Definition at line 2617 of file coerce.c.
References _, ERROR_INVALID_CLASS, sparse_as_kind(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_as_Rsparse()
SEXP R_sparse_as_Rsparse (SEXP from)
Definition at line 3908 of file coerce.c.
References ERROR_INVALID_CLASS, sparse_as_Rsparse(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_as_Tsparse()
SEXP R_sparse_as_Tsparse (SEXP from)
Definition at line 4017 of file coerce.c.
References ERROR_INVALID_CLASS, sparse_as_Tsparse(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_vector_as_dense()
SEXP R_vector_as_dense (SEXP from, SEXP zzz, SEXP uplo, SEXP diag, SEXP m, SEXP n, SEXP byrow, SEXP dimnames)
Definition at line 164 of file coerce.c.
References _, ERROR_INVALID_TYPE, and vector_as_dense().
R_vector_as_sparse()
SEXP R_vector_as_sparse (SEXP from, SEXP zzz, SEXP uplo, SEXP diag, SEXP m, SEXP n, SEXP byrow, SEXP dimnames)
Definition at line 1453 of file coerce.c.
References _, ERROR_INVALID_CLASS, GET_SLOT, Matrix_lengthSym, valid, VALID_NONVIRTUAL_VECTOR, and vector_as_sparse().
sparse_as_Csparse()
SEXP sparse_as_Csparse (SEXP from, const char * class)
Definition at line 3721 of file coerce.c.
References cl, GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, trans(), and tsort().
Referenced by coerceArgs(), R_Matrix_as_Csparse(), R_sparse_as_Csparse(), R_sparse_matmult(), R_subscript_1ary(), R_subscript_1ary_mat(), R_subscript_2ary(), sparse_is_symmetric(), and vector_as_sparse().
sparse_as_dense()
SEXP sparse_as_dense (SEXP from, const char * class, int packed)
Definition at line 501 of file coerce.c.
References _, cl, GET_SLOT, HIDE, INCREMENT_PATTERN, kindToSize(), kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), SAD_CASES, SAD_SUBCASES, SECONDOF, and SET_SLOT.
Referenced by coerceArgs(), R_Matrix_as_kind(), R_Matrix_as_matrix(), R_Matrix_as_packed(), R_Matrix_as_unpacked(), R_Matrix_as_vector(), and R_sparse_as_dense().
sparse_as_general()
SEXP sparse_as_general (SEXP from, const char * class)
Definition at line 2831 of file coerce.c.
References _, ASSIGN_REAL, cl, GET_SLOT, HIDE, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_iSym, Matrix_jSym, Matrix_memset(), Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), SAG_CASES, SAG_SUBCASES, SET_SLOT, and set_symmetrized_DimNames().
Referenced by coerceArgs(), CR2spV(), Csparse_MatrixMarket(), CsparseMatrix_subscript_2ary(), R_diagonal_matmult(), R_Matrix_as_general(), R_sparse_as_general(), R_sparse_matmult(), and RsparseMatrix_subscript_2ary().
sparse_as_kind()
SEXP sparse_as_kind (SEXP from, const char * class, char kind)
Definition at line 2499 of file coerce.c.
References cl, GET_SLOT, kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, Matrix_zone, newObject(), SET_SLOT, and Tsparse_aggregate().
Referenced by coerceArgs(), Csparse_MatrixMarket(), matrix_as_sparse(), R_diagonal_matmult(), R_Matrix_as_general(), R_Matrix_as_kind(), R_sparse_as_kind(), R_sparse_diag_set(), R_sparse_matmult(), sparse_skewpart(), and sparse_symmpart().
sparse_as_Rsparse()
SEXP sparse_as_Rsparse (SEXP from, const char * class)
Definition at line 3820 of file coerce.c.
References cl, GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, trans(), and tsort().
Referenced by coerceArgs(), R_Matrix_as_Rsparse(), R_sparse_as_Rsparse(), and vector_as_sparse().
sparse_as_Tsparse()
SEXP sparse_as_Tsparse (SEXP from, const char * class)
Definition at line 3919 of file coerce.c.
References cl, GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_iSym, Matrix_jSym, Matrix_memcpy(), Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), and SET_SLOT.
Referenced by coerceArgs(), R_Matrix_as_Tsparse(), R_sparse_as_Tsparse(), R_subscript_2ary(), and vector_as_sparse().
vector_as_dense()
SEXP vector_as_dense (SEXP from, const char * zzz, char ul, char di, int m, int n, int byrow, SEXP dimnames)
Definition at line 6 of file coerce.c.
References _, cl, GET_SLOT, kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, Matrix_zna, newObject(), SET_SLOT, set_symmetrized_DimNames(), typeToKind(), and VAD_SUBCASES.
Referenced by R_vector_as_dense().
vector_as_sparse()
SEXP vector_as_sparse (SEXP from, const char * zzz, char ul, char di, int m, int n, int byrow, SEXP dimnames)
Definition at line 1020 of file coerce.c.
References _, cl, FIRSTOF, GET_SLOT, HIDE, kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_lengthSym, Matrix_memset(), Matrix_pSym, Matrix_uploSym, Matrix_xSym, Matrix_zna, Matrix_zone, newObject(), SECONDOF, SET_SLOT, set_symmetrized_DimNames(), SHOW, sparse_as_Csparse(), sparse_as_Rsparse(), sparse_as_Tsparse(), typeToKind(), and VAS_SUBCASES.
Referenced by R_vector_as_sparse().