Matrix: coerce.c File Reference
coerce.c File Reference
#include <math.h>
#include "Mdefines.h"
#include "idz.h"
#include "coerce.h"
Macros
#define VAD_SUBCASES(_PREFIX_, _CTYPE_, _PTR_, _NA_)
#define SAD_CASES
#define SAD_SUBCASES(_CTYPE_, _PTR_, _MASK_, _REPLACE_, _INCREMENT_, _ONE_)
#define SAD_SUBSUBCASES(_LOOP_C_, _LOOP_R_, _LOOP_T_, _MASK_, _REPLACE_, _INCREMENT_)
#define SAD_LOOP_C2NP(_MASK_, _REPLACE_, _INCREMENT_)
#define SAD_LOOP_C2UP(_MASK_, _REPLACE_, _INCREMENT_)
#define SAD_LOOP_C2LP(_MASK_, _REPLACE_, _INCREMENT_)
#define SAD_LOOP_R2NP(_MASK_, _REPLACE_, _INCREMENT_)
#define SAD_LOOP_R2UP(_MASK_, _REPLACE_, _INCREMENT_)
#define SAD_LOOP_R2LP(_MASK_, _REPLACE_, _INCREMENT_)
#define SAD_LOOP_T2NP(_MASK_, _REPLACE_, _INCREMENT_)
#define SAD_LOOP_T2UP(_MASK_, _REPLACE_, _INCREMENT_)
#define SAD_LOOP_T2LP(_MASK_, _REPLACE_, _INCREMENT_)
#define DAD_SUBCASES(_PREFIX_, _CTYPE_, _PTR_)
#define IAD_SUBCASES(_CTYPE_, _PTR_, _ONE_)
#define VAS_SUBCASES(...)
#define VAS_SUBSUBCASES()
#define VAS_SUBSUBCASES(_MASK0_, _MASK1_, _REPLACE_, _CTYPE_, _PTR_, _ONE_, _NA_)
#define DAS_CASES(_MASK_)
#define DAS_SUBCASES(_CTYPE_, _PTR_, _MASK_, _ISNZ_)
#define DAS_SUBSUBCASES(_LOOP_C_, _LOOP_R_, _LOOP_T_, _MASK_, _ISNZ_)
#define DAS_LOOP_GEN2C(_ISNZ_, _DO_INNER_, _DO_OUTER_)
#define DAS_LOOP_GEN2R(_ISNZ_, _DO_INNER_, _DO_OUTER_)
#define DAS_LOOP_TRN2C(_ISNZ_, _DO_INNER_, _DO_OUTER_)
#define DAS_LOOP_TRN2R(_ISNZ_, _DO_INNER_, _DO_OUTER_)
#define DAS_LOOP_TRU2C(_ISNZ_, _DO_INNER_, _DO_OUTER_)
#define DAS_LOOP_TRU2R(_ISNZ_, _DO_INNER_, _DO_OUTER_)
#define DAS_LOOP_TPN2C(_ISNZ_, _DO_INNER_, _DO_OUTER_)
#define DAS_LOOP_TPN2R(_ISNZ_, _DO_INNER_, _DO_OUTER_)
#define DAS_LOOP_TPU2C(_ISNZ_, _DO_INNER_, _DO_OUTER_)
#define DAS_LOOP_TPU2R(_ISNZ_, _DO_INNER_, _DO_OUTER_)
#define DAS_VALID2T
#define DAS_VALID2C do { DAS_VALID2T; else *(pp++) = (int) nnz; } while (0)
#define DAS_VALID2R DAS_VALID2C
#define DAS_SUBSUBCASES(_LOOP_C_, _LOOP_R_, _LOOP_T_, _MASK_, _ISNZ_)
#define DAS_CASES(_MASK_)
#define DAS_LOOP(_CTYPE_, _PTR_, _MASK_, _ISNZ_, _ONE_)
#define DAS_LOOP(_CTYPE_, _PTR_, _MASK_, _ISNZ_, _ONE_)
#define DAS_LOOP(_CTYPE_, _PTR_, _MASK_, _ISNZ_, _ONE_)
#define IAS_SUBCASES(_CTYPE_, _PTR_, _ONE_)
#define DAG_SUBCASES(_PREFIX_, _CTYPE_, _PTR_)
#define ASSIGN_COMPLEX_JJ(_X_, _Y_) do { _X_.r = _Y_.r; _X_.i = 0.0; } while (0)
#define ASSIGN_COMPLEX_JI(_X_, _Y_) do { _X_.r = _Y_.r; _X_.i = -_Y_.i; } while (0)
#define SAG_CASES
#define SAG_SUBCASES(_CTYPE_, _PTR_, _MASK_, _ONE_, _ASSIGN_JJ_, _ASSIGN_JI_)
#define SAG_SUBCASES(_CTYPE_, _PTR_, _MASK_, _ONE_, _ASSIGN_JJ_, _ASSIGN_JI_)
#define UNPACK(_PREFIX_, _CTYPE_, _PTR_)
#define PACK(_PREFIX_, _CTYPE_, _PTR_)
#define TRANS_LOOP(_CTYPE_, _PTR_, _MASK_)
#define TSORT_LOOP(_CTYPE_, _PTR_, _MASK_, _INCREMENT_)
#define TAGGR_LOOP(_CTYPE_, _PTR_, _MASK_, _INCREMENT_)
Functions
SEXP vector_as_dense (SEXP from, const char *zzz, char ul, char di, int m, int n, int byrow, SEXP dimnames)
SEXP R_vector_as_dense (SEXP from, SEXP zzz, SEXP uplo, SEXP diag, SEXP m, SEXP n, SEXP byrow, SEXP dimnames)
SEXP matrix_as_dense (SEXP from, const char *zzz, char ul, char di, int trans, int new)
SEXP R_matrix_as_dense (SEXP from, SEXP zzz, SEXP uplo, SEXP diag, SEXP trans)
SEXP sparse_as_dense (SEXP from, const char *class, int packed)
SEXP R_sparse_as_dense (SEXP from, SEXP packed)
SEXP diagonal_as_dense (SEXP from, const char *class, char kind, char shape, int packed, char ul)
SEXP R_diagonal_as_dense (SEXP from, SEXP kind, SEXP shape, SEXP packed, SEXP uplo)
SEXP index_as_dense (SEXP from, const char *class, char kind)
SEXP R_index_as_dense (SEXP from, SEXP kind)
SEXP vector_as_sparse (SEXP from, const char *zzz, char ul, char di, int m, int n, int byrow, SEXP dimnames)
SEXP R_vector_as_sparse (SEXP from, SEXP zzz, SEXP uplo, SEXP diag, SEXP m, SEXP n, SEXP byrow, SEXP dimnames)
SEXP matrix_as_sparse (SEXP from, const char *zzz, char ul, char di, int trans)
SEXP R_matrix_as_sparse (SEXP from, SEXP zzz, SEXP uplo, SEXP diag, SEXP trans)
SEXP dense_as_sparse (SEXP from, const char *class, char repr)
SEXP R_dense_as_sparse (SEXP from, SEXP repr)
SEXP diagonal_as_sparse (SEXP from, const char *class, char kind, char shape, char repr, char ul)
SEXP R_diagonal_as_sparse (SEXP from, SEXP kind, SEXP shape, SEXP repr, SEXP uplo)
SEXP index_as_sparse (SEXP from, const char *class, char kind, char repr)
SEXP R_index_as_sparse (SEXP from, SEXP kind, SEXP repr)
SEXP dense_as_kind (SEXP from, const char *class, char kind, int new)
SEXP R_dense_as_kind (SEXP from, SEXP kind)
SEXP sparse_as_kind (SEXP from, const char *class, char kind)
SEXP R_sparse_as_kind (SEXP from, SEXP kind)
SEXP diagonal_as_kind (SEXP from, const char *class, char kind)
SEXP R_diagonal_as_kind (SEXP from, SEXP kind)
SEXP index_as_kind (SEXP from, const char *class, char kind)
SEXP R_index_as_kind (SEXP from, SEXP kind)
SEXP dense_as_general (SEXP from, const char *class, int new)
SEXP R_dense_as_general (SEXP from)
SEXP sparse_as_general (SEXP from, const char *class)
SEXP R_sparse_as_general (SEXP from)
SEXP dense_as_unpacked (SEXP from, const char *class)
SEXP R_dense_as_unpacked (SEXP from)
SEXP dense_as_packed (SEXP from, const char *class, char ul, char di)
SEXP R_dense_as_packed (SEXP from, SEXP uplo, SEXP diag)
void trans (SEXP p0, SEXP i0, SEXP x0, SEXP p1, SEXP i1, SEXP x1, int m, int n)
void tsort (SEXP i0, SEXP j0, SEXP x0, SEXP *p1, SEXP *i1, SEXP *x1, int m, int n)
void taggr (SEXP i0, SEXP j0, SEXP x0, SEXP *i1, SEXP *j1, SEXP *x1, int m, int n)
SEXP sparse_as_Csparse (SEXP from, const char *class)
SEXP R_sparse_as_Csparse (SEXP from)
SEXP sparse_as_Rsparse (SEXP from, const char *class)
SEXP R_sparse_as_Rsparse (SEXP from)
SEXP sparse_as_Tsparse (SEXP from, const char *class)
SEXP R_sparse_as_Tsparse (SEXP from)
SEXP R_Matrix_as_vector (SEXP from)
SEXP R_Matrix_as_matrix (SEXP from)
SEXP R_Matrix_as_unpacked (SEXP from)
SEXP R_Matrix_as_packed (SEXP from)
SEXP R_Matrix_as_Csparse (SEXP from)
SEXP R_Matrix_as_Rsparse (SEXP from)
SEXP R_Matrix_as_Tsparse (SEXP from)
SEXP R_Matrix_as_kind (SEXP from, SEXP kind, SEXP sparse)
SEXP R_Matrix_as_general (SEXP from, SEXP kind)
Macro Definition Documentation
ASSIGN_COMPLEX_JI
#define ASSIGN_COMPLEX_JI (_X_, _Y_) do { _X_.r = _Y_.r; _X_.i = -_Y_.i; } while (0)
ASSIGN_COMPLEX_JJ
#define ASSIGN_COMPLEX_JJ (_X_, _Y_) do { _X_.r = _Y_.r; _X_.i = 0.0; } while (0)
DAD_SUBCASES
#define DAD_SUBCASES (_PREFIX_, _CTYPE_, _PTR_)
Value:
    do { \
        _CTYPE_ *px0 = _PTR_(x0), *px1 = _PTR_(x1); \
        Matrix_memset(px1, 0, (R_xlen_t) len, sizeof(_CTYPE_)); \
        if (di == 'N' || cl[1] != 't') { \
            if (cl[2] != 'p') \
                _PREFIX_ ## dcpy2(px1, px0, n, n,     ul, di); \
            else \
                _PREFIX_ ## dcpy1(px1, px0, n, n, ul, ul, di); \
        } \
    } while (0)
DAG_SUBCASES
#define DAG_SUBCASES (_PREFIX_, _CTYPE_, _PTR_)
Value:
    do { \
        _CTYPE_ *px0 = _PTR_(x0), *px1 = _PTR_(x1); \
        if (class[2] == 'p') \
            _PREFIX_ ## unpack1(px1, px0, n, ul, di); \
        else if (new) \
            Matrix_memcpy(px1, px0, (R_xlen_t) n * n, sizeof(_CTYPE_)); \
        if (class[1] == 's') \
            _PREFIX_ ## syforce2(px1, n, ul); \
        else \
            _PREFIX_ ## trforce2(px1, n, n, ul, di); \
    } while (0)
DAS_CASES [1/2]
#define DAS_CASES (_MASK_)
Value:
    do { \
        switch (class[0]) { \
        case 'l': \
            DAS_SUBCASES(int, LOGICAL, _MASK_, ISNZ_LOGICAL); \
            break; \
        case 'i': \
            DAS_SUBCASES(int, INTEGER, _MASK_, ISNZ_INTEGER); \
            break; \
        case 'd': \
            DAS_SUBCASES(double, REAL, _MASK_, ISNZ_REAL); \
            break; \
        case 'z': \
            DAS_SUBCASES(Rcomplex, COMPLEX, _MASK_, ISNZ_COMPLEX); \
            break; \
        default: \
            break; \
        } \
    } while (0)
DAS_CASES [2/2]
#define DAS_CASES (_MASK_)
Value:
    do { \
        switch (cl[0]) { \
        case 'l': \
            DAS_LOOP(int, LOGICAL, _MASK_, ISNZ_LOGICAL, 1); \
            break; \
        case 'i': \
            DAS_LOOP(int, INTEGER, _MASK_, ISNZ_INTEGER, 1); \
            break; \
        case 'd': \
            DAS_LOOP(double, REAL, _MASK_, ISNZ_REAL, 1.0); \
            break; \
        case 'z': \
            DAS_LOOP(Rcomplex, COMPLEX, _MASK_, ISNZ_COMPLEX, Matrix_zone); \
            break; \
        default: \
            break; \
        } \
    } while (0)
DAS_LOOP [1/3]
#define DAS_LOOP (_CTYPE_, _PTR_, _MASK_, _ISNZ_, _ONE_)
Value:
            do { \
                _CTYPE_ *px0 = _PTR_(x0); \
                for (d = 0; d < n; ++d) { \
                    if (_ISNZ_(*px0)) \
                        ++nnz; \
                    *(pp++) = nnz; \
                    ++px0; \
                } \
            } while (0)
DAS_LOOP [2/3]
#define DAS_LOOP (_CTYPE_, _PTR_, _MASK_, _ISNZ_, _ONE_)
Value:
            do { \
                _CTYPE_ *px0 = _PTR_(x0); \
                for (d = 0; d < n; ++d) { \
                    if (_ISNZ_(*px0)) \
                        ++nnz; \
                    ++px0; \
                } \
            } while (0)
DAS_LOOP [3/3]
#define DAS_LOOP (_CTYPE_, _PTR_, _MASK_, _ISNZ_, _ONE_)
Value:
    do { \
        _MASK_(_CTYPE_ *px1 = _PTR_(x1)); \
        if (di == 'N') { \
            _CTYPE_ *px0 = _PTR_(x0); \
            for (d = 0; d < n; ++d) { \
                if (_ISNZ_(*px0)) { \
                    *(pi1++) = d; \
                    _MASK_(*(px1++) = *px0); \
                } \
                ++px0; \
            } \
        } else { \
            for (d = 0; d < n; ++d) { \
                *(pi1++) = d; \
                _MASK_(*(px1++) = _ONE_); \
            } \
        } \
    } while (0)
DAS_LOOP_GEN2C
#define DAS_LOOP_GEN2C (_ISNZ_, _DO_INNER_, _DO_OUTER_)
Value:
    do { \
        for (j = 0; j < n; ++j) { \
            for (i = 0; i < m; ++i, ++px0) \
                if (_ISNZ_(*px0)) _DO_INNER_; \
            _DO_OUTER_; \
        } \
    } while (0)
DAS_LOOP_GEN2R
#define DAS_LOOP_GEN2R (_ISNZ_, _DO_INNER_, _DO_OUTER_)
Value:
    do { \
        R_xlen_t mn1s = (R_xlen_t) m * n - 1; \
        for (i = 0; i < m; ++i, px0 -= mn1s) { \
            for (j = 0; j < n; ++j, px0 += m) \
                if (_ISNZ_(*px0)) _DO_INNER_; \
            _DO_OUTER_; \
        } \
    } while (0)
DAS_LOOP_TPN2C
#define DAS_LOOP_TPN2C (_ISNZ_, _DO_INNER_, _DO_OUTER_)
Value:
    do { \
        if (ul == 'U') { \
            for (j = 0; j < n; ++j) { \
                for (i = 0; i <= j; ++i, ++px0) \
                    if (_ISNZ_(*px0)) _DO_INNER_; \
                _DO_OUTER_; \
            } \
        } else { \
            for (j = 0; j < n; ++j) { \
                for (i = j; i < n; ++i, ++px0) \
                    if (_ISNZ_(*px0)) _DO_INNER_; \
                _DO_OUTER_; \
            } \
        } \
    } while (0)
DAS_LOOP_TPN2R
#define DAS_LOOP_TPN2R (_ISNZ_, _DO_INNER_, _DO_OUTER_)
Value:
    do { \
        R_xlen_t d; \
        if (ul == 'U') { \
            d = PACKED_LENGTH(n) - 1; \
            for (i = 0; i < n; px0 -= (d -= (++i))) { \
                for (j = i; j < n; px0 += (++j)) \
                    if (_ISNZ_(*px0)) _DO_INNER_; \
                _DO_OUTER_; \
            } \
        } else { \
            d = -1; \
            for (i = 0; i < n; px0 -= (d += n - (++i))) { \
                for (j = 0; j <= i; px0 += n - (++j)) \
                    if (_ISNZ_(*px0)) _DO_INNER_; \
                _DO_OUTER_; \
            } \
        } \
    } while (0)
DAS_LOOP_TPU2C
#define DAS_LOOP_TPU2C (_ISNZ_, _DO_INNER_, _DO_OUTER_)
Value:
    do { \
        if (ul == 'U') { \
            for (j = 1; j < n; ++j) { \
                ++px0; \
                for (i = 0; i < j; ++i, ++px0) \
                    if (_ISNZ_(*px0)) _DO_INNER_; \
                _DO_OUTER_; \
            } \
        } else { \
            for (j = 0; j < n; ++j) { \
                ++px0; \
                for (i = j + 1; i < n; ++i, ++px0) \
                    if (_ISNZ_(*px0)) _DO_INNER_; \
                _DO_OUTER_; \
            } \
        } \
    } while (0)
DAS_LOOP_TPU2R
#define DAS_LOOP_TPU2R (_ISNZ_, _DO_INNER_, _DO_OUTER_)
Value:
    do { \
        R_xlen_t d; \
        if (ul == 'U') { \
            d = PACKED_LENGTH(n - 1) - 1; \
            for (i = 0; i < n; ++i) { \
                for (j = i + 1; j < n; ++j) { \
                    px0 += j; \
                    if (_ISNZ_(*px0)) _DO_INNER_; \
                } \
                _DO_OUTER_; \
                px0 -= (d -= i + 1); \
            } \
        } else { \
            ++px0; \
            d = -1; \
            for (i = 1; i < n; ++i) { \
                for (j = 0; j < i; ++j) { \
                    if (_ISNZ_(*px0)) _DO_INNER_; \
                    px0 += n - j - 1; \
                } \
                _DO_OUTER_; \
                px0 -= (d += n - i); \
            } \
        } \
    } while (0)
DAS_LOOP_TRN2C
#define DAS_LOOP_TRN2C (_ISNZ_, _DO_INNER_, _DO_OUTER_)
Value:
    do { \
        if (ul == 'U') { \
            for (j = 0; j < n; px0 += n - (++j)) { \
                for (i = 0; i <= j; ++i, ++px0) \
                    if (_ISNZ_(*px0)) _DO_INNER_; \
                _DO_OUTER_; \
            } \
        } else { \
            for (j = 0; j < n; px0 += (++j)) { \
                for (i = j; i < n; ++i, ++px0) \
                    if (_ISNZ_(*px0)) _DO_INNER_; \
                _DO_OUTER_; \
            } \
        } \
    } while (0)
DAS_LOOP_TRN2R
#define DAS_LOOP_TRN2R (_ISNZ_, _DO_INNER_, _DO_OUTER_)
Value:
    do { \
        R_xlen_t d; \
        if (ul == 'U') { \
            d = (R_xlen_t) n * n - 1; \
            for (i = 0; i < n; ++i, px0 -= (d -= n)) { \
                for (j = i; j < n; ++j, px0 += n) \
                    if (_ISNZ_(*px0)) _DO_INNER_; \
                _DO_OUTER_; \
            } \
        } else { \
            d = -1; \
            for (i = 0; i < n; ++i, px0 -= (d += n)) { \
                for (j = 0; j <= i; ++j, px0 += n) \
                    if (_ISNZ_(*px0)) _DO_INNER_; \
                _DO_OUTER_; \
            } \
        } \
    } while (0)
DAS_LOOP_TRU2C
#define DAS_LOOP_TRU2C (_ISNZ_, _DO_INNER_, _DO_OUTER_)
Value:
    do { \
        if (ul == 'U') { \
            px0 += n; \
            for (j = 1; j < n; ++j) { \
                for (i = 0; i < j; ++i, ++px0) \
                    if (_ISNZ_(*px0)) _DO_INNER_; \
                _DO_OUTER_; \
                px0 += n - j; \
            } \
        } else { \
            for (j = 0; j < n; ++j) { \
                px0 += j + 1; \
                for (i = j + 1; i < n; ++i, ++px0) \
                    if (_ISNZ_(*px0)) _DO_INNER_; \
                _DO_OUTER_; \
            } \
        } \
    } while (0)
DAS_LOOP_TRU2R
#define DAS_LOOP_TRU2R (_ISNZ_, _DO_INNER_, _DO_OUTER_)
Value:
    do { \
        R_xlen_t d; \
        if (ul == 'U') { \
            d = (R_xlen_t) n * (n - 1) - 1; \
            for (i = 0; i < n; ++i) { \
                for (j = i + 1; j < n; ++j) { \
                    px0 += n; \
                    if (_ISNZ_(*px0)) _DO_INNER_; \
                } \
                _DO_OUTER_; \
                px0 -= (d -= n); \
            } \
        } else { \
            ++px0; \
            d = -1; \
            for (i = 1; i < n; ++i) { \
                for (j = 0; j < i; ++j) { \
                    if (_ISNZ_(*px0)) _DO_INNER_; \
                    px0 += n; \
                } \
                _DO_OUTER_; \
                px0 -= (d += n); \
            } \
        } \
    } while (0)
DAS_SUBCASES
#define DAS_SUBCASES (_CTYPE_, _PTR_, _MASK_, _ISNZ_)
Value:
    do { \
               _CTYPE_ *px0 = _PTR_(x0) ; \
        _MASK_(_CTYPE_ *px1 = _PTR_(x1)); \
        if (class[1] == 'g') \
            /* .geMatrix */ \
            DAS_SUBSUBCASES(DAS_LOOP_GEN2C, DAS_LOOP_GEN2R, DAS_LOOP_GEN2C, \
                            _MASK_, _ISNZ_);     \
        else if (class[2] != 'p' && di == 'N') \
            /* .syMatrix, non-unit diagonal .trMatrix */ \
            DAS_SUBSUBCASES(DAS_LOOP_TRN2C, DAS_LOOP_TRN2R, DAS_LOOP_TRN2C, \
                            _MASK_, _ISNZ_); \
        else if (class[2] != 'p') \
            /* unit diagonal .trMatrix */ \
            DAS_SUBSUBCASES(DAS_LOOP_TRU2C, DAS_LOOP_TRU2R, DAS_LOOP_TRU2C, \
                            _MASK_, _ISNZ_); \
        else if (di == 'N') \
            /* .spMatrix, non-unit diagonal .tpMatrix */ \
            DAS_SUBSUBCASES(DAS_LOOP_TPN2C, DAS_LOOP_TPN2R, DAS_LOOP_TPN2C, \
                            _MASK_, _ISNZ_); \
        else \
            /* unit diagonal .tpMatrix */ \
            DAS_SUBSUBCASES(DAS_LOOP_TPU2C, DAS_LOOP_TPU2R, DAS_LOOP_TPU2C, \
                            _MASK_, _ISNZ_); \
    } while (0)
DAS_SUBSUBCASES [1/2]
#define DAS_SUBSUBCASES (_LOOP_C_, _LOOP_R_, _LOOP_T_, _MASK_, _ISNZ_)
Value:
    do { \
        switch (cl[2]) { \
        case 'C': \
            _LOOP_C_(_ISNZ_, ++nnz, DAS_VALID2C); \
            break; \
        case 'R': \
            _LOOP_R_(_ISNZ_, ++nnz, DAS_VALID2R); \
            break; \
        case 'T': \
            _LOOP_T_(_ISNZ_, ++nnz, DAS_VALID2T); \
            break; \
        default: \
            break; \
        } \
    } while (0)
DAS_SUBSUBCASES [2/2]
#define DAS_SUBSUBCASES (_LOOP_C_, _LOOP_R_, _LOOP_T_, _MASK_, _ISNZ_)
Value:
    do { \
        switch (repr) { \
        case 'C': \
            _LOOP_C_(_ISNZ_, \
                     do { \
                         *(pi++) = i; \
                         _MASK_(*(px1++) = *px0); \
                     } while (0), ); \
            break; \
        case 'R': \
            _LOOP_R_(_ISNZ_, \
                     do { \
                         *(pj++) = j; \
                         _MASK_(*(px1++) = *px0); \
                     } while (0), ); \
            break; \
        case 'T': \
            _LOOP_T_(_ISNZ_, \
                     do { \
                         *(pi++) = i; \
                         *(pj++) = j; \
                         _MASK_(*(px1++) = *px0); \
                     } while (0), ); \
            break; \
        default: \
            break; \
        } \
    } while (0)
DAS_VALID2C
#define DAS_VALID2C do { DAS_VALID2T; else *(pp++) = (int) nnz; } while (0)
DAS_VALID2R
#define DAS_VALID2R DAS_VALID2C
DAS_VALID2T
#define DAS_VALID2T
Value:
    if (nnz > INT_MAX) \
        error(_("attempt to construct %s with more than %s nonzero entries"), \
              "sparseMatrix", "2^31-1")
IAD_SUBCASES
#define IAD_SUBCASES (_CTYPE_, _PTR_, _ONE_)
Value:
    do { \
        _CTYPE_ *px = _PTR_(x); \
        Matrix_memset(px, 0, (R_xlen_t) len, sizeof(_CTYPE_)); \
        if (mg == 0) { \
            R_xlen_t m1 = (R_xlen_t) m; \
            for (int i = 0; i < m; ++i) \
                px[i + m1 * (*(pperm++) - 1)] = _ONE_; \
        } else { \
            for (int j = 0; j < n; ++j, px += m) \
                px[          *(pperm++) - 1 ] = _ONE_; \
        } \
    } while (0)
IAS_SUBCASES
#define IAS_SUBCASES (_CTYPE_, _PTR_, _ONE_)
Value:
        do { \
            _CTYPE_ *px = _PTR_(x); \
            for (int k = 0; k < r; ++k) \
                *(px++) = _ONE_; \
        } while (0)
PACK
#define PACK (_PREFIX_, _CTYPE_, _PTR_)
Value:
    do { \
        _CTYPE_ *px0 = _PTR_(x0), *px1 = _PTR_(x1); \
        _PREFIX_ ## pack2(px1, px0, n, ul, 'N'); \
    } while (0)
SAD_CASES
#define SAD_CASES
Value:
    do { \
        switch (class[0]) { \
        case 'l': \
            SAD_SUBCASES(int, LOGICAL, SHOW, FIRSTOF, INCREMENT_LOGICAL, 1); \
            break; \
        case 'i': \
            SAD_SUBCASES(int, INTEGER, SHOW, FIRSTOF, INCREMENT_INTEGER, 1); \
            break; \
        case 'd': \
            SAD_SUBCASES(double, REAL, SHOW, FIRSTOF, INCREMENT_REAL, 1.0); \
            break; \
        case 'z': \
            SAD_SUBCASES(Rcomplex, COMPLEX, SHOW, FIRSTOF, INCREMENT_COMPLEX, Matrix_zone); \
            break; \
        default: \
            break; \
        } \
    } while (0)
SAD_LOOP_C2LP
#define SAD_LOOP_C2LP (_MASK_, _REPLACE_, _INCREMENT_)
Value:
    do { \
        for (j = 0, k = 0; j < n; px1 += n - (j++)) { \
            kend = pp[j]; \
            while (k < kend) { \
                px1[*pi - j] = _REPLACE_(*px0, 1); \
                ++k; ++pi; _MASK_(++px0); \
            } \
        } \
    } while (0)
SAD_LOOP_C2NP
#define SAD_LOOP_C2NP (_MASK_, _REPLACE_, _INCREMENT_)
Value:
    do { \
        for (j = 0, k = 0; j < n; ++j, px1 += m) { \
            kend = pp[j]; \
            while (k < kend) { \
                px1[*pi] = _REPLACE_(*px0, 1); \
                ++k; ++pi; _MASK_(++px0); \
            } \
        } \
    } while (0)
SAD_LOOP_C2UP
#define SAD_LOOP_C2UP (_MASK_, _REPLACE_, _INCREMENT_)
Value:
    do { \
        for (j = 0, k = 0; j < n; px1 += (++j)) { \
            kend = pp[j]; \
            while (k < kend) { \
                px1[*pi] = _REPLACE_(*px0, 1); \
                ++k; ++pi; _MASK_(++px0); \
            } \
        } \
    } while (0)
SAD_LOOP_R2LP
#define SAD_LOOP_R2LP (_MASK_, _REPLACE_, _INCREMENT_)
Value:
    do { \
        R_xlen_t n2 = (R_xlen_t) n * 2; \
        for (i = 0, k = 0; i < n; ++i) { \
            kend = pp[i]; \
            while (k < kend) { \
                px1[PACKED_AR21_LO(i, *pj, n2)] = _REPLACE_(*px0, 1); \
                ++k; ++pj; _MASK_(++px0); \
            } \
        } \
    } while (0)
SAD_LOOP_R2NP
#define SAD_LOOP_R2NP (_MASK_, _REPLACE_, _INCREMENT_)
Value:
    do { \
        R_xlen_t m1 = (R_xlen_t) m; \
        for (i = 0, k = 0; i < m; ++i, ++px1) { \
            kend = pp[i]; \
            while (k < kend) { \
                px1[m1 * *pj] = _REPLACE_(*px0, 1); \
                ++k; ++pj; _MASK_(++px0); \
            } \
        } \
    } while (0)
SAD_LOOP_R2UP
#define SAD_LOOP_R2UP (_MASK_, _REPLACE_, _INCREMENT_)
Value:
    do { \
        for (i = 0, k = 0; i < n; ++i) { \
            kend = pp[i]; \
            while (k < kend) { \
                px1[PACKED_AR21_UP(i, *pj)] = _REPLACE_(*px0, 1); \
                ++k; ++pj; _MASK_(++px0); \
            } \
        } \
    } while (0)
SAD_LOOP_T2LP
#define SAD_LOOP_T2LP (_MASK_, _REPLACE_, _INCREMENT_)
Value:
    do { \
        R_xlen_t n2 = (R_xlen_t) n * 2; \
        for (k = 0; k < nnz; ++k) { \
            index = PACKED_AR21_LO(*pi, *pj, n2); \
            _INCREMENT_(px1[index], (*px0)); \
            ++pi; ++pj; _MASK_(++px0); \
        } \
    } while (0)
SAD_LOOP_T2NP
#define SAD_LOOP_T2NP (_MASK_, _REPLACE_, _INCREMENT_)
Value:
    do { \
        R_xlen_t m1 = (R_xlen_t) m; \
        for (k = 0; k < nnz; ++k) { \
            index = m1 * *pj + *pi; \
            _INCREMENT_(px1[index], (*px0)); \
            ++pi; ++pj; _MASK_(++px0); \
        } \
    } while (0)
SAD_LOOP_T2UP
#define SAD_LOOP_T2UP (_MASK_, _REPLACE_, _INCREMENT_)
Value:
    do { \
        for (k = 0; k < nnz; ++k) { \
            index = PACKED_AR21_UP(*pi, *pj); \
            _INCREMENT_(px1[index], (*px0)); \
            ++pi; ++pj; _MASK_(++px0); \
        } \
    } while (0)
SAD_SUBCASES
#define SAD_SUBCASES (_CTYPE_, _PTR_, _MASK_, _REPLACE_, _INCREMENT_, _ONE_)
SAD_SUBSUBCASES
#define SAD_SUBSUBCASES (_LOOP_C_, _LOOP_R_, _LOOP_T_, _MASK_, _REPLACE_, _INCREMENT_)
Value:
    do { \
        switch (class[2]) { \
        case 'C': \
        { \
            int j, k, kend; \
            _LOOP_C_(_MASK_, _REPLACE_, _INCREMENT_); \
            break; \
        } \
        case 'R': \
        { \
            int i, k, kend; \
            _LOOP_R_(_MASK_, _REPLACE_, _INCREMENT_); \
            break; \
        } \
        case 'T': \
        { \
            R_xlen_t index, k, nnz = XLENGTH(i0); \
            _LOOP_T_(_MASK_, _REPLACE_, _INCREMENT_); \
            break; \
        } \
        default: \
            break; \
        } \
    } while (0)
SAG_CASES
#define SAG_CASES
Value:
    do { \
        switch (class[0]) { \
        case 'l': \
            SAG_SUBCASES(int, LOGICAL, SHOW, 1, \
                         ASSIGN_REAL, ASSIGN_REAL); \
            break; \
        case 'i': \
            SAG_SUBCASES(int, INTEGER, SHOW, 1, \
                         ASSIGN_REAL, ASSIGN_REAL); \
            break; \
        case 'd': \
            SAG_SUBCASES(double, REAL, SHOW, 1.0, \
                         ASSIGN_REAL, ASSIGN_REAL); \
            break; \
        case 'z': \
            SAG_SUBCASES(Rcomplex, COMPLEX, SHOW, Matrix_zone, \
                         ASSIGN_COMPLEX_JJ, ASSIGN_COMPLEX_JI); \
            break; \
        default: \
            break; \
        } \
    } while (0)
SAG_SUBCASES [1/2]
#define SAG_SUBCASES (_CTYPE_, _PTR_, _MASK_, _ONE_, _ASSIGN_JJ_, _ASSIGN_JI_)
SAG_SUBCASES [2/2]
#define SAG_SUBCASES (_CTYPE_, _PTR_, _MASK_, _ONE_, _ASSIGN_JJ_, _ASSIGN_JI_)
TAGGR_LOOP
#define TAGGR_LOOP (_CTYPE_, _PTR_, _MASK_, _INCREMENT_)
TRANS_LOOP
#define TRANS_LOOP (_CTYPE_, _PTR_, _MASK_)
Value:
    do { \
        _MASK_(_CTYPE_ *px0 = _PTR_(x0), *px1 = _PTR_(x1)); \
        for (j = 0, k = 0; j < n; ++j) { \
            kend = pp0[j]; \
            while (k < kend) { \
                i = pi0[k]; \
                pi1[pp1_[i]] = j; \
                _MASK_(px1[pp1_[i]] = px0[k]); \
                ++pp1_[i]; \
                ++k; \
            } \
        } \
    } while (0)
TSORT_LOOP
#define TSORT_LOOP (_CTYPE_, _PTR_, _MASK_, _INCREMENT_)
UNPACK
#define UNPACK (_PREFIX_, _CTYPE_, _PTR_)
Value:
    do { \
        _CTYPE_ *px0 = _PTR_(x0), *px1 = _PTR_(x1); \
        Matrix_memset(px1, 0, (R_xlen_t) n * n, sizeof(_CTYPE_)); \
        _PREFIX_ ## unpack1(px1, px0, n, ul, 'N'); \
    } while (0)
VAD_SUBCASES
#define VAD_SUBCASES (_PREFIX_, _CTYPE_, _PTR_, _NA_)
VAS_SUBCASES
#define VAS_SUBCASES (...)
Value:
    do { \
        switch (TYPEOF(i0)) { \
        case INTSXP: \
        { \
            int *pi0 = INTEGER(i0); \
            VAS_SUBSUBCASES(__VA_ARGS__); \
            break; \
        } \
        case REALSXP: \
        { \
            double *pi0 = REAL(i0); \
            VAS_SUBSUBCASES(__VA_ARGS__); \
            break; \
        } \
        default: \
            break; \
        } \
    } while (0)
VAS_SUBSUBCASES [1/2]
#define VAS_SUBSUBCASES ()
VAS_SUBSUBCASES [2/2]
#define VAS_SUBSUBCASES (_MASK0_, _MASK1_, _REPLACE_, _CTYPE_, _PTR_, _ONE_, _NA_)
Function Documentation
dense_as_general()
SEXP dense_as_general (SEXP from, const char * class, int new)
Definition at line 2734 of file coerce.c.
References _, cl, DAG_SUBCASES, GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, and set_symmetrized_DimNames().
Referenced by coerceArgs(), dense_band(), R_dense_as_general(), R_dense_matmult(), R_diagonal_matmult(), R_Matrix_as_general(), R_Matrix_as_matrix(), R_Matrix_as_vector(), and R_sparse_matmult().
dense_as_kind()
SEXP dense_as_kind (SEXP from, const char * class, char kind, int new)
Definition at line 2409 of file coerce.c.
References cl, GET_SLOT, kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, naToOne(), newObject(), and SET_SLOT.
Referenced by coerceArgs(), dense_skewpart(), dense_symmpart(), R_dense_as_kind(), R_dense_diag_set(), R_dense_matmult(), R_diagonal_matmult(), R_Matrix_as_general(), R_Matrix_as_kind(), and R_sparse_matmult().
dense_as_packed()
SEXP dense_as_packed (SEXP from, const char * class, char ul, char di)
Definition at line 3224 of file coerce.c.
References _, cl, GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_sdSym, Matrix_uploSym, Matrix_xSym, newObject(), PACK, PACKED_LENGTH, and SET_SLOT.
Referenced by R_dense_as_packed(), and R_Matrix_as_packed().
dense_as_sparse()
SEXP dense_as_sparse (SEXP from, const char * class, char repr)
Definition at line 1647 of file coerce.c.
References cl, DAS_CASES, DAS_SUBCASES, GET_SLOT, HIDE, ISNZ_LOGICAL, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, and SHOW.
Referenced by coerceArgs(), matrix_as_sparse(), R_dense_as_sparse(), R_Matrix_as_Csparse(), R_Matrix_as_kind(), R_Matrix_as_Rsparse(), R_Matrix_as_Tsparse(), and R_sparse_matmult().
dense_as_unpacked()
SEXP dense_as_unpacked (SEXP from, const char * class)
Definition at line 3119 of file coerce.c.
References _, cl, GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_sdSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, and UNPACK.
Referenced by R_dense_as_unpacked(), and R_Matrix_as_unpacked().
diagonal_as_dense()
SEXP diagonal_as_dense (SEXP from, const char * class, char kind, char shape, int packed, char ul)
Definition at line 798 of file coerce.c.
References _, cl, DAD_SUBCASES, GET_SLOT, kindToSize(), kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, naToOne(), newObject(), SET_SLOT, and set_symmetrized_DimNames().
Referenced by coerceArgs(), R_diagonal_as_dense(), R_Matrix_as_kind(), R_Matrix_as_matrix(), R_Matrix_as_packed(), R_Matrix_as_unpacked(), and R_Matrix_as_vector().
diagonal_as_kind()
SEXP diagonal_as_kind (SEXP from, const char * class, char kind)
Definition at line 2634 of file coerce.c.
References cl, GET_SLOT, kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_xSym, naToOne(), newObject(), and SET_SLOT.
Referenced by R_diagonal_as_kind(), R_diagonal_matmult(), and R_Matrix_as_kind().
diagonal_as_sparse()
SEXP diagonal_as_sparse (SEXP from, const char * class, char kind, char shape, char repr, char ul)
Definition at line 2066 of file coerce.c.
References cl, DAS_CASES, DAS_LOOP, GET_SLOT, HIDE, ISNZ_LOGICAL, kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_memset(), Matrix_pSym, Matrix_uploSym, Matrix_xSym, naToOne(), newObject(), SET_SLOT, set_symmetrized_DimNames(), and SHOW.
Referenced by coerceArgs(), R_diagonal_as_sparse(), R_Matrix_as_Csparse(), R_Matrix_as_general(), R_Matrix_as_kind(), R_Matrix_as_Rsparse(), and R_Matrix_as_Tsparse().
index_as_dense()
SEXP index_as_dense (SEXP from, const char * class, char kind)
Definition at line 931 of file coerce.c.
References _, cl, GET_SLOT, IAD_SUBCASES, kindToSize(), kindToType(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_marginSym, Matrix_permSym, Matrix_xSym, Matrix_zone, newObject(), and SET_SLOT.
Referenced by coerceArgs(), R_index_as_dense(), R_Matrix_as_kind(), R_Matrix_as_matrix(), R_Matrix_as_unpacked(), and R_Matrix_as_vector().
index_as_kind()
SEXP index_as_kind (SEXP from, const char * class, char kind)
Definition at line 2712 of file coerce.c.
References index_as_sparse().
Referenced by R_index_as_kind().
index_as_sparse()
SEXP index_as_sparse (SEXP from, const char * class, char kind, char repr)
Definition at line 2281 of file coerce.c.
References cl, GET_SLOT, IAS_SUBCASES, kindToType(), Matrix_Calloc, Matrix_DimNamesSym, Matrix_DimSym, Matrix_Free, Matrix_iSym, Matrix_jSym, Matrix_marginSym, Matrix_memcpy(), Matrix_memset(), Matrix_permSym, Matrix_pSym, Matrix_xSym, Matrix_zone, newObject(), and SET_SLOT.
Referenced by coerceArgs(), index_as_kind(), R_index_as_sparse(), R_Matrix_as_Csparse(), R_Matrix_as_general(), R_Matrix_as_kind(), R_Matrix_as_Rsparse(), and R_Matrix_as_Tsparse().
matrix_as_dense()
SEXP matrix_as_dense (SEXP from, const char * zzz, char ul, char di, int trans, int new)
Definition at line 297 of file coerce.c.
References _, cl, GET_SLOT, kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_memcpy(), Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, set_symmetrized_DimNames(), trans(), and typeToKind().
Referenced by matrix_as_sparse(), R_dense_band(), R_dense_is_diagonal(), R_dense_is_symmetric(), R_dense_is_triangular(), R_dense_matmult(), R_diagonal_matmult(), R_matrix_as_dense(), and R_sparse_matmult().
matrix_as_sparse()
SEXP matrix_as_sparse (SEXP from, const char * zzz, char ul, char di, int trans)
Definition at line 1580 of file coerce.c.
References cl, dense_as_sparse(), matrix_as_dense(), sparse_as_kind(), trans(), and typeToKind().
Referenced by coerceArgs(), R_matrix_as_sparse(), and R_sparse_matmult().
R_dense_as_general()
SEXP R_dense_as_general (SEXP from)
Definition at line 2821 of file coerce.c.
References dense_as_general(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_as_kind()
SEXP R_dense_as_kind (SEXP from, SEXP kind)
Definition at line 2483 of file coerce.c.
References _, dense_as_kind(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_as_packed()
SEXP R_dense_as_packed (SEXP from, SEXP uplo, SEXP diag)
Definition at line 3330 of file coerce.c.
References _, dense_as_packed(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_as_sparse()
SEXP R_dense_as_sparse (SEXP from, SEXP repr)
Definition at line 2050 of file coerce.c.
References _, dense_as_sparse(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_as_unpacked()
SEXP R_dense_as_unpacked (SEXP from)
Definition at line 3212 of file coerce.c.
References dense_as_unpacked(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_diagonal_as_dense()
SEXP R_diagonal_as_dense (SEXP from, SEXP kind, SEXP shape, SEXP packed, SEXP uplo)
Definition at line 893 of file coerce.c.
References _, diagonal_as_dense(), ERROR_INVALID_CLASS, valid, and VALID_DIAGONAL.
R_diagonal_as_kind()
SEXP R_diagonal_as_kind (SEXP from, SEXP kind)
Definition at line 2696 of file coerce.c.
References _, diagonal_as_kind(), ERROR_INVALID_CLASS, valid, and VALID_DIAGONAL.
R_diagonal_as_sparse()
SEXP R_diagonal_as_sparse (SEXP from, SEXP kind, SEXP shape, SEXP repr, SEXP uplo)
Definition at line 2244 of file coerce.c.
References _, diagonal_as_sparse(), ERROR_INVALID_CLASS, valid, and VALID_DIAGONAL.
R_index_as_dense()
SEXP R_index_as_dense (SEXP from, SEXP kind)
Definition at line 1004 of file coerce.c.
References _, ERROR_INVALID_CLASS, index_as_dense(), and valid.
R_index_as_kind()
SEXP R_index_as_kind (SEXP from, SEXP kind)
Definition at line 2718 of file coerce.c.
References _, ERROR_INVALID_CLASS, index_as_kind(), and valid.
R_index_as_sparse()
SEXP R_index_as_sparse (SEXP from, SEXP kind, SEXP repr)
Definition at line 2386 of file coerce.c.
References _, ERROR_INVALID_CLASS, index_as_sparse(), and valid.
R_Matrix_as_Csparse()
SEXP R_Matrix_as_Csparse (SEXP from)
Definition at line 4231 of file coerce.c.
References cl, dense_as_sparse(), diagonal_as_sparse(), ERROR_INVALID_CLASS, index_as_sparse(), sparse_as_Csparse(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_matrix_as_dense()
SEXP R_matrix_as_dense (SEXP from, SEXP zzz, SEXP uplo, SEXP diag, SEXP trans)
Definition at line 454 of file coerce.c.
References _, ERROR_INVALID_TYPE, matrix_as_dense(), and trans().
R_Matrix_as_general()
SEXP R_Matrix_as_general (SEXP from, SEXP kind)
Definition at line 4384 of file coerce.c.
References _, cl, dense_as_general(), dense_as_kind(), diagonal_as_sparse(), ERROR_INVALID_CLASS, index_as_sparse(), sparse_as_general(), sparse_as_kind(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_Matrix_as_kind()
SEXP R_Matrix_as_kind (SEXP from, SEXP kind, SEXP sparse)
Definition at line 4315 of file coerce.c.
References _, cl, dense_as_kind(), dense_as_sparse(), diagonal_as_dense(), diagonal_as_kind(), diagonal_as_sparse(), ERROR_INVALID_CLASS, index_as_dense(), index_as_sparse(), sparse_as_dense(), sparse_as_kind(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_Matrix_as_matrix()
SEXP R_Matrix_as_matrix (SEXP from)
Definition at line 4102 of file coerce.c.
References cl, dense_as_general(), diagonal_as_dense(), DimNames_is_trivial(), ERROR_INVALID_CLASS, GET_SLOT, index_as_dense(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_xSym, naToOne(), sparse_as_dense(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_Matrix_as_packed()
SEXP R_Matrix_as_packed (SEXP from)
Definition at line 4202 of file coerce.c.
References _, cl, dense_as_packed(), diagonal_as_dense(), ERROR_INVALID_CLASS, sparse_as_dense(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_Matrix_as_Rsparse()
SEXP R_Matrix_as_Rsparse (SEXP from)
Definition at line 4259 of file coerce.c.
References cl, dense_as_sparse(), diagonal_as_sparse(), ERROR_INVALID_CLASS, index_as_sparse(), sparse_as_Rsparse(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_matrix_as_sparse()
SEXP R_matrix_as_sparse (SEXP from, SEXP zzz, SEXP uplo, SEXP diag, SEXP trans)
Definition at line 1602 of file coerce.c.
References _, ERROR_INVALID_TYPE, matrix_as_sparse(), and trans().
R_Matrix_as_Tsparse()
SEXP R_Matrix_as_Tsparse (SEXP from)
Definition at line 4287 of file coerce.c.
References cl, dense_as_sparse(), diagonal_as_sparse(), ERROR_INVALID_CLASS, index_as_sparse(), sparse_as_Tsparse(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_Matrix_as_unpacked()
SEXP R_Matrix_as_unpacked (SEXP from)
Definition at line 4173 of file coerce.c.
References cl, dense_as_unpacked(), diagonal_as_dense(), ERROR_INVALID_CLASS, index_as_dense(), sparse_as_dense(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_Matrix_as_vector()
SEXP R_Matrix_as_vector (SEXP from)
Definition at line 4029 of file coerce.c.
References cl, dense_as_general(), diagonal_as_dense(), ERROR_INVALID_CLASS, GET_SLOT, index_as_dense(), Matrix_xSym, naToOne(), sparse_as_dense(), valid, VALID_NONVIRTUAL_MATRIX, and VALID_NONVIRTUAL_SHIFT.
R_sparse_as_Csparse()
SEXP R_sparse_as_Csparse (SEXP from)
Definition at line 3809 of file coerce.c.
References ERROR_INVALID_CLASS, sparse_as_Csparse(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_as_dense()
SEXP R_sparse_as_dense (SEXP from, SEXP packed)
Definition at line 782 of file coerce.c.
References _, ERROR_INVALID_CLASS, sparse_as_dense(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_as_general()
SEXP R_sparse_as_general (SEXP from)
Definition at line 3108 of file coerce.c.
References ERROR_INVALID_CLASS, sparse_as_general(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_as_kind()
SEXP R_sparse_as_kind (SEXP from, SEXP kind)
Definition at line 2617 of file coerce.c.
References _, ERROR_INVALID_CLASS, sparse_as_kind(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_as_Rsparse()
SEXP R_sparse_as_Rsparse (SEXP from)
Definition at line 3908 of file coerce.c.
References ERROR_INVALID_CLASS, sparse_as_Rsparse(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_as_Tsparse()
SEXP R_sparse_as_Tsparse (SEXP from)
Definition at line 4017 of file coerce.c.
References ERROR_INVALID_CLASS, sparse_as_Tsparse(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_vector_as_dense()
SEXP R_vector_as_dense (SEXP from, SEXP zzz, SEXP uplo, SEXP diag, SEXP m, SEXP n, SEXP byrow, SEXP dimnames)
Definition at line 164 of file coerce.c.
References _, ERROR_INVALID_TYPE, and vector_as_dense().
R_vector_as_sparse()
SEXP R_vector_as_sparse (SEXP from, SEXP zzz, SEXP uplo, SEXP diag, SEXP m, SEXP n, SEXP byrow, SEXP dimnames)
Definition at line 1453 of file coerce.c.
References _, ERROR_INVALID_CLASS, GET_SLOT, Matrix_lengthSym, valid, VALID_NONVIRTUAL_VECTOR, and vector_as_sparse().
sparse_as_Csparse()
SEXP sparse_as_Csparse (SEXP from, const char * class)
Definition at line 3721 of file coerce.c.
References cl, GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, trans(), and tsort().
Referenced by coerceArgs(), R_Matrix_as_Csparse(), R_sparse_as_Csparse(), R_sparse_matmult(), R_subscript_1ary(), R_subscript_1ary_mat(), R_subscript_2ary(), sparse_is_symmetric(), and vector_as_sparse().
sparse_as_dense()
SEXP sparse_as_dense (SEXP from, const char * class, int packed)
Definition at line 501 of file coerce.c.
References _, cl, GET_SLOT, HIDE, INCREMENT_PATTERN, kindToSize(), kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), SAD_CASES, SAD_SUBCASES, SECONDOF, and SET_SLOT.
Referenced by coerceArgs(), R_Matrix_as_kind(), R_Matrix_as_matrix(), R_Matrix_as_packed(), R_Matrix_as_unpacked(), R_Matrix_as_vector(), and R_sparse_as_dense().
sparse_as_general()
SEXP sparse_as_general (SEXP from, const char * class)
Definition at line 2831 of file coerce.c.
References _, ASSIGN_REAL, cl, GET_SLOT, HIDE, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_iSym, Matrix_jSym, Matrix_memset(), Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), SAG_CASES, SAG_SUBCASES, SET_SLOT, and set_symmetrized_DimNames().
Referenced by coerceArgs(), CR2spV(), Csparse_MatrixMarket(), CsparseMatrix_subscript_2ary(), R_diagonal_matmult(), R_Matrix_as_general(), R_sparse_as_general(), R_sparse_matmult(), and RsparseMatrix_subscript_2ary().
sparse_as_kind()
SEXP sparse_as_kind (SEXP from, const char * class, char kind)
Definition at line 2499 of file coerce.c.
References cl, GET_SLOT, kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, Matrix_zone, newObject(), SET_SLOT, and Tsparse_aggregate().
Referenced by coerceArgs(), Csparse_MatrixMarket(), matrix_as_sparse(), R_diagonal_matmult(), R_Matrix_as_general(), R_Matrix_as_kind(), R_sparse_as_kind(), R_sparse_diag_set(), R_sparse_matmult(), sparse_skewpart(), and sparse_symmpart().
sparse_as_Rsparse()
SEXP sparse_as_Rsparse (SEXP from, const char * class)
Definition at line 3820 of file coerce.c.
References cl, GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, trans(), and tsort().
Referenced by coerceArgs(), R_Matrix_as_Rsparse(), R_sparse_as_Rsparse(), and vector_as_sparse().
sparse_as_Tsparse()
SEXP sparse_as_Tsparse (SEXP from, const char * class)
Definition at line 3919 of file coerce.c.
References cl, GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_iSym, Matrix_jSym, Matrix_memcpy(), Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), and SET_SLOT.
Referenced by coerceArgs(), R_Matrix_as_Tsparse(), R_sparse_as_Tsparse(), R_subscript_2ary(), and vector_as_sparse().
taggr()
void taggr (SEXP i0, SEXP j0, SEXP x0, SEXP * i1, SEXP * j1, SEXP * x1, int m, int n)
Definition at line 3585 of file coerce.c.
References _, HIDE, INCREMENT_COMPLEX, INCREMENT_INTEGER, INCREMENT_LOGICAL, INCREMENT_REAL, Matrix_Calloc, Matrix_Free, SHOW, and TAGGR_LOOP.
Referenced by Tsparse_aggregate().
trans()
void trans (SEXP p0, SEXP i0, SEXP x0, SEXP p1, SEXP i1, SEXP x1, int m, int n)
Definition at line 3356 of file coerce.c.
References HIDE, Matrix_Calloc, Matrix_Free, Matrix_memcpy(), Matrix_memset(), SHOW, and TRANS_LOOP.
Referenced by CHD2M(), M2CHD(), matrix_as_dense(), matrix_as_sparse(), R_matrix_as_dense(), R_matrix_as_sparse(), sparse_as_Csparse(), sparse_as_Rsparse(), and sparse_transpose().
tsort()
void tsort (SEXP i0, SEXP j0, SEXP x0, SEXP * p1, SEXP * i1, SEXP * x1, int m, int n)
Definition at line 3415 of file coerce.c.
References _, HIDE, INCREMENT_COMPLEX, INCREMENT_INTEGER, INCREMENT_LOGICAL, INCREMENT_PATTERN, INCREMENT_REAL, Matrix_Calloc, Matrix_Free, SHOW, and TSORT_LOOP.
Referenced by sparse_as_Csparse(), and sparse_as_Rsparse().
vector_as_dense()
SEXP vector_as_dense (SEXP from, const char * zzz, char ul, char di, int m, int n, int byrow, SEXP dimnames)
Definition at line 6 of file coerce.c.
References _, cl, GET_SLOT, kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, Matrix_zna, newObject(), SET_SLOT, set_symmetrized_DimNames(), typeToKind(), and VAD_SUBCASES.
Referenced by R_vector_as_dense().
vector_as_sparse()
SEXP vector_as_sparse (SEXP from, const char * zzz, char ul, char di, int m, int n, int byrow, SEXP dimnames)
Definition at line 1020 of file coerce.c.
References _, cl, FIRSTOF, GET_SLOT, HIDE, kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_lengthSym, Matrix_memset(), Matrix_pSym, Matrix_uploSym, Matrix_xSym, Matrix_zna, Matrix_zone, newObject(), SECONDOF, SET_SLOT, set_symmetrized_DimNames(), SHOW, sparse_as_Csparse(), sparse_as_Rsparse(), sparse_as_Tsparse(), typeToKind(), and VAS_SUBCASES.
Referenced by R_vector_as_sparse().