Matrix: cs-etc.h File Reference
cs-etc.h File Reference
#include "SuiteSparse/CXSparse/Include/cs.h"
#include <Rinternals.h>
Data Structures
struct Matrix_cs_sparse
struct Matrix_cs_symbolic
struct Matrix_cs_numeric
struct Matrix_cs_dmperm_results
Macros
#define CXSPARSE_PATTERN 0
#define CXSPARSE_REAL 1
#define CXSPARSE_COMPLEX 2
#define CXSPARSE_XTYPE_GET()
#define CXSPARSE_XTYPE_SET(_VALUE_)
Typedefs
typedef struct Matrix_cs_sparse Matrix_cs
typedef struct Matrix_cs_symbolic Matrix_css
typedef struct Matrix_cs_numeric Matrix_csn
typedef struct Matrix_cs_dmperm_results Matrix_csd
Functions
Matrix_cs * M2CXS (SEXP, int)
SEXP CXS2M (Matrix_cs *, int, char)
Matrix_csd * Matrix_cs_dfree (Matrix_csd *)
Matrix_csd * Matrix_cs_dmperm (const Matrix_cs *, int)
int Matrix_cs_dropzeros (Matrix_cs *)
void * Matrix_cs_free (void *)
int Matrix_cs_happly (const Matrix_cs *, int, double, void *)
int Matrix_cs_ipvec (const int *, const void *, void *, int)
int Matrix_cs_lsolve (const Matrix_cs *, void *)
Matrix_csn * Matrix_cs_lu (const Matrix_cs *, const Matrix_css *, double)
int Matrix_cs_lusol (int, const Matrix_cs *, void *, double)
Matrix_csn * Matrix_cs_nfree (Matrix_csn *)
Matrix_cs * Matrix_cs_permute (const Matrix_cs *, const int *, const int *, int)
int * Matrix_cs_pinv (const int *, int)
int Matrix_cs_pvec (const int *, const void *, void *, int)
Matrix_csn * Matrix_cs_qr (const Matrix_cs *, const Matrix_css *)
int Matrix_cs_qrsol (int, const Matrix_cs *, void *)
Matrix_css * Matrix_cs_sfree (Matrix_css *)
Matrix_cs * Matrix_cs_spalloc (int, int, int, int, int)
Matrix_cs * Matrix_cs_speye (int, int, int, int)
Matrix_cs * Matrix_cs_spfree (Matrix_cs *)
int Matrix_cs_sprealloc (Matrix_cs *, int)
int Matrix_cs_spsolve (Matrix_cs *, const Matrix_cs *, int, int *, void *, const int *, int)
Matrix_css * Matrix_cs_sqr (int, const Matrix_cs *, int)
Matrix_cs * Matrix_cs_transpose (const Matrix_cs *, int)
int Matrix_cs_usolve (const Matrix_cs *, void *)
Variables
int Matrix_cs_xtype
Macro Definition Documentation
CXSPARSE_COMPLEX
#define CXSPARSE_COMPLEX 2
Definition at line 9 of file cs-etc.h.
Referenced by CXS2M(), M2CXS(), Matrix_cs_dfree(), Matrix_cs_dmperm(), Matrix_cs_dropzeros(), Matrix_cs_free(), Matrix_cs_happly(), Matrix_cs_ipvec(), Matrix_cs_lsolve(), Matrix_cs_lu(), Matrix_cs_lusol(), Matrix_cs_nfree(), Matrix_cs_permute(), Matrix_cs_pinv(), Matrix_cs_pvec(), Matrix_cs_qr(), Matrix_cs_qrsol(), Matrix_cs_sfree(), Matrix_cs_spalloc(), Matrix_cs_speye(), Matrix_cs_spfree(), Matrix_cs_sprealloc(), Matrix_cs_spsolve(), Matrix_cs_sqr(), Matrix_cs_transpose(), Matrix_cs_usolve(), sparse_lu(), sparse_qr(), sparseLU_solve(), sparseQR_matmult(), and tCMatrix_solve().
CXSPARSE_PATTERN
#define CXSPARSE_PATTERN 0
Definition at line 7 of file cs-etc.h.
Referenced by M2CXS().
CXSPARSE_REAL
#define CXSPARSE_REAL 1
Definition at line 8 of file cs-etc.h.
Referenced by CXS2M(), dgCMatrix_lusol(), dgCMatrix_qrsol(), and M2CXS().
CXSPARSE_XTYPE_GET
#define CXSPARSE_XTYPE_GET ()
Value:
Matrix_cs_xtype
Definition at line 11 of file cs-etc.h.
Referenced by Matrix_cs_dfree(), Matrix_cs_dmperm(), Matrix_cs_dropzeros(), Matrix_cs_free(), Matrix_cs_happly(), Matrix_cs_ipvec(), Matrix_cs_lsolve(), Matrix_cs_lu(), Matrix_cs_lusol(), Matrix_cs_nfree(), Matrix_cs_permute(), Matrix_cs_pinv(), Matrix_cs_pvec(), Matrix_cs_qr(), Matrix_cs_qrsol(), Matrix_cs_sfree(), Matrix_cs_spalloc(), Matrix_cs_speye(), Matrix_cs_spfree(), Matrix_cs_sprealloc(), Matrix_cs_spsolve(), Matrix_cs_sqr(), Matrix_cs_transpose(), and Matrix_cs_usolve().
CXSPARSE_XTYPE_SET
#define CXSPARSE_XTYPE_SET (_VALUE_)
Value:
Matrix_cs_xtype = _VALUE_
Definition at line 12 of file cs-etc.h.
Referenced by Csparse_dmperm(), dgCMatrix_lusol(), dgCMatrix_qrsol(), sparse_lu(), sparse_qr(), sparseLU_solve(), sparseQR_matmult(), and tCMatrix_solve().
Typedef Documentation
Matrix_cs
typedef struct Matrix_cs_sparse Matrix_cs
Matrix_csd
typedef struct Matrix_cs_dmperm_results Matrix_csd
Matrix_csn
typedef struct Matrix_cs_numeric Matrix_csn
Matrix_css
typedef struct Matrix_cs_symbolic Matrix_css
Function Documentation
CXS2M()
SEXP CXS2M (Matrix_cs * A, int values, char shape)
Definition at line 42 of file cs-etc.c.
References CXSPARSE_COMPLEX, CXSPARSE_REAL, GET_SLOT, Matrix_cs_sparse::i, Matrix_cs_sparse::m, Matrix_DimSym, Matrix_iSym, Matrix_pSym, Matrix_xSym, Matrix_cs_sparse::n, newObject(), Matrix_cs_sparse::p, SET_SLOT, Matrix_cs_sparse::x, and Matrix_cs_sparse::xtype.
Referenced by sparse_lu(), sparse_qr(), sparseLU_solve(), and tCMatrix_solve().
M2CXS()
Matrix_cs * M2CXS (SEXP obj, int values)
Definition at line 6 of file cs-etc.c.
References CXSPARSE_COMPLEX, CXSPARSE_PATTERN, CXSPARSE_REAL, GET_SLOT, Matrix_cs_sparse::i, Matrix_cs_sparse::m, Matrix_class(), Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_xSym, Matrix_cs_sparse::n, Matrix_cs_sparse::nz, Matrix_cs_sparse::nzmax, Matrix_cs_sparse::p, valid_sparse_compressed, Matrix_cs_sparse::x, and Matrix_cs_sparse::xtype.
Referenced by Csparse_dmperm(), dgCMatrix_lusol(), dgCMatrix_qrsol(), sparse_lu(), sparse_qr(), sparseLU_solve(), sparseQR_matmult(), and tCMatrix_solve().
Matrix_cs_dfree()
Matrix_csd * Matrix_cs_dfree (Matrix_csd * D)
Definition at line 77 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by Csparse_dmperm().
Matrix_cs_dmperm()
Matrix_csd * Matrix_cs_dmperm (const Matrix_cs * A, int seed)
Definition at line 89 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by Csparse_dmperm().
Matrix_cs_dropzeros()
int Matrix_cs_dropzeros (Matrix_cs * A)
Definition at line 101 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by sparseLU_solve(), and tCMatrix_solve().
Matrix_cs_free()
void * Matrix_cs_free (void * p)
Definition at line 113 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by sparseLU_solve().
Matrix_cs_happly()
int Matrix_cs_happly (const Matrix_cs * V, int i, double beta, void * x)
Definition at line 125 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Matrix_cs_ipvec()
int Matrix_cs_ipvec (const int * p, const void * b, void * x, int n)
Definition at line 137 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Matrix_cs_lsolve()
int Matrix_cs_lsolve (const Matrix_cs * L, void * x)
Definition at line 149 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Matrix_cs_lu()
Matrix_csn * Matrix_cs_lu (const Matrix_cs * A, const Matrix_css * S, double tol)
Definition at line 161 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by sparse_lu().
Matrix_cs_lusol()
int Matrix_cs_lusol (int order, const Matrix_cs * A, void * b, double tol)
Definition at line 173 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by dgCMatrix_lusol().
Matrix_cs_nfree()
Matrix_csn * Matrix_cs_nfree (Matrix_csn * N)
Definition at line 185 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Matrix_cs_permute()
Matrix_cs * Matrix_cs_permute (const Matrix_cs * A, const int * pinv, const int * q, int values)
Definition at line 197 of file cs-etc.c.
References CXSPARSE_COMPLEX, CXSPARSE_XTYPE_GET, and Matrix_cs_sparse::xtype.
Referenced by sparseLU_solve().
Matrix_cs_pinv()
int * Matrix_cs_pinv (const int * p, int n)
Definition at line 222 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by sparse_lu(), sparse_qr(), and sparseLU_solve().
Matrix_cs_pvec()
int Matrix_cs_pvec (const int * p, const void * b, void * x, int n)
Definition at line 234 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Matrix_cs_qr()
Matrix_csn * Matrix_cs_qr (const Matrix_cs * A, const Matrix_css * S)
Definition at line 246 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by sparse_qr().
Matrix_cs_qrsol()
int Matrix_cs_qrsol (int order, const Matrix_cs * A, void * b)
Definition at line 258 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by dgCMatrix_qrsol().
Matrix_cs_sfree()
Matrix_css * Matrix_cs_sfree (Matrix_css * S)
Definition at line 270 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Matrix_cs_spalloc()
Matrix_cs * Matrix_cs_spalloc (int m, int n, int nzmax, int values, int triplet)
Definition at line 282 of file cs-etc.c.
References CXSPARSE_COMPLEX, CXSPARSE_XTYPE_GET, and Matrix_cs_sparse::xtype.
Referenced by Matrix_cs_speye().
Matrix_cs_speye()
Matrix_cs * Matrix_cs_speye (int m, int n, int values, int triplet)
Definition at line 307 of file cs-etc.c.
References CXSPARSE_COMPLEX, CXSPARSE_XTYPE_GET, Matrix_cs_sparse::i, Matrix_cs_spalloc(), Matrix_cs_sparse::p, and Matrix_cs_sparse::x.
Referenced by sparseLU_solve(), and tCMatrix_solve().
Matrix_cs_spfree()
Matrix_cs * Matrix_cs_spfree (Matrix_cs * A)
Definition at line 337 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by sparseLU_solve(), and tCMatrix_solve().
Matrix_cs_sprealloc()
int Matrix_cs_sprealloc (Matrix_cs * A, int nzmax)
Definition at line 349 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Matrix_cs_spsolve()
int Matrix_cs_spsolve (Matrix_cs * L, const Matrix_cs * B, int k, int * xi, void * x, const int * pinv, int lo)
Definition at line 361 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Matrix_cs_sqr()
Matrix_css * Matrix_cs_sqr (int order, const Matrix_cs * A, int qr)
Definition at line 373 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by sparse_lu(), and sparse_qr().
Matrix_cs_transpose()
Matrix_cs * Matrix_cs_transpose (const Matrix_cs * A, int values)
Definition at line 385 of file cs-etc.c.
References CXSPARSE_COMPLEX, CXSPARSE_XTYPE_GET, and Matrix_cs_sparse::xtype.
Referenced by sparseLU_solve(), and tCMatrix_solve().
Matrix_cs_usolve()
int Matrix_cs_usolve (const Matrix_cs * U, void * x)
Definition at line 410 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Variable Documentation
Matrix_cs_xtype
int Matrix_cs_xtype extern
Definition at line 4 of file cs-etc.c.