Matrix: cs-etc.c File Reference
cs-etc.c File Reference
#include "Mdefines.h"
#include "cs-etc.h"
Functions
Matrix_cs * M2CXS (SEXP obj, int values)
SEXP CXS2M (Matrix_cs *A, int values, char shape)
Matrix_csd * Matrix_cs_dfree (Matrix_csd *D)
Matrix_csd * Matrix_cs_dmperm (const Matrix_cs *A, int seed)
int Matrix_cs_dropzeros (Matrix_cs *A)
void * Matrix_cs_free (void *p)
int Matrix_cs_happly (const Matrix_cs *V, int i, double beta, void *x)
int Matrix_cs_ipvec (const int *p, const void *b, void *x, int n)
int Matrix_cs_lsolve (const Matrix_cs *L, void *x)
Matrix_csn * Matrix_cs_lu (const Matrix_cs *A, const Matrix_css *S, double tol)
int Matrix_cs_lusol (int order, const Matrix_cs *A, void *b, double tol)
Matrix_csn * Matrix_cs_nfree (Matrix_csn *N)
Matrix_cs * Matrix_cs_permute (const Matrix_cs *A, const int *pinv, const int *q, int values)
int * Matrix_cs_pinv (const int *p, int n)
int Matrix_cs_pvec (const int *p, const void *b, void *x, int n)
Matrix_csn * Matrix_cs_qr (const Matrix_cs *A, const Matrix_css *S)
int Matrix_cs_qrsol (int order, const Matrix_cs *A, void *b)
Matrix_css * Matrix_cs_sfree (Matrix_css *S)
Matrix_cs * Matrix_cs_spalloc (int m, int n, int nzmax, int values, int triplet)
Matrix_cs * Matrix_cs_speye (int m, int n, int values, int triplet)
Matrix_cs * Matrix_cs_spfree (Matrix_cs *A)
int Matrix_cs_sprealloc (Matrix_cs *A, int nzmax)
int Matrix_cs_spsolve (Matrix_cs *L, const Matrix_cs *B, int k, int *xi, void *x, const int *pinv, int lo)
Matrix_css * Matrix_cs_sqr (int order, const Matrix_cs *A, int qr)
Matrix_cs * Matrix_cs_transpose (const Matrix_cs *A, int values)
int Matrix_cs_usolve (const Matrix_cs *U, void *x)
Variables
int Matrix_cs_xtype
Function Documentation
CXS2M()
SEXP CXS2M (Matrix_cs * A, int values, char shape)
Definition at line 42 of file cs-etc.c.
References CXSPARSE_COMPLEX, CXSPARSE_REAL, GET_SLOT, Matrix_cs_sparse::i, Matrix_cs_sparse::m, Matrix_DimSym, Matrix_iSym, Matrix_pSym, Matrix_xSym, Matrix_cs_sparse::n, newObject(), Matrix_cs_sparse::p, SET_SLOT, Matrix_cs_sparse::x, and Matrix_cs_sparse::xtype.
Referenced by sparse_lu(), sparse_qr(), sparseLU_solve(), and tCMatrix_solve().
M2CXS()
Matrix_cs * M2CXS (SEXP obj, int values)
Definition at line 6 of file cs-etc.c.
References CXSPARSE_COMPLEX, CXSPARSE_PATTERN, CXSPARSE_REAL, GET_SLOT, Matrix_cs_sparse::i, Matrix_cs_sparse::m, Matrix_class(), Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_xSym, Matrix_cs_sparse::n, Matrix_cs_sparse::nz, Matrix_cs_sparse::nzmax, Matrix_cs_sparse::p, valid_sparse_compressed, Matrix_cs_sparse::x, and Matrix_cs_sparse::xtype.
Referenced by Csparse_dmperm(), dgCMatrix_lusol(), dgCMatrix_qrsol(), sparse_lu(), sparse_qr(), sparseLU_solve(), sparseQR_matmult(), and tCMatrix_solve().
Matrix_cs_dfree()
Matrix_csd * Matrix_cs_dfree (Matrix_csd * D)
Definition at line 77 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by Csparse_dmperm().
Matrix_cs_dmperm()
Matrix_csd * Matrix_cs_dmperm (const Matrix_cs * A, int seed)
Definition at line 89 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by Csparse_dmperm().
Matrix_cs_dropzeros()
int Matrix_cs_dropzeros (Matrix_cs * A)
Definition at line 101 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by sparseLU_solve(), and tCMatrix_solve().
Matrix_cs_free()
void * Matrix_cs_free (void * p)
Definition at line 113 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by sparseLU_solve().
Matrix_cs_happly()
int Matrix_cs_happly (const Matrix_cs * V, int i, double beta, void * x)
Definition at line 125 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Matrix_cs_ipvec()
int Matrix_cs_ipvec (const int * p, const void * b, void * x, int n)
Definition at line 137 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Matrix_cs_lsolve()
int Matrix_cs_lsolve (const Matrix_cs * L, void * x)
Definition at line 149 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Matrix_cs_lu()
Matrix_csn * Matrix_cs_lu (const Matrix_cs * A, const Matrix_css * S, double tol)
Definition at line 161 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by sparse_lu().
Matrix_cs_lusol()
int Matrix_cs_lusol (int order, const Matrix_cs * A, void * b, double tol)
Definition at line 173 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by dgCMatrix_lusol().
Matrix_cs_nfree()
Matrix_csn * Matrix_cs_nfree (Matrix_csn * N)
Definition at line 185 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Matrix_cs_permute()
Matrix_cs * Matrix_cs_permute (const Matrix_cs * A, const int * pinv, const int * q, int values)
Definition at line 197 of file cs-etc.c.
References CXSPARSE_COMPLEX, CXSPARSE_XTYPE_GET, and Matrix_cs_sparse::xtype.
Referenced by sparseLU_solve().
Matrix_cs_pinv()
int * Matrix_cs_pinv (const int * p, int n)
Definition at line 222 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by sparse_lu(), sparse_qr(), and sparseLU_solve().
Matrix_cs_pvec()
int Matrix_cs_pvec (const int * p, const void * b, void * x, int n)
Definition at line 234 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Matrix_cs_qr()
Matrix_csn * Matrix_cs_qr (const Matrix_cs * A, const Matrix_css * S)
Definition at line 246 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by sparse_qr().
Matrix_cs_qrsol()
int Matrix_cs_qrsol (int order, const Matrix_cs * A, void * b)
Definition at line 258 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by dgCMatrix_qrsol().
Matrix_cs_sfree()
Matrix_css * Matrix_cs_sfree (Matrix_css * S)
Definition at line 270 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Matrix_cs_spalloc()
Matrix_cs * Matrix_cs_spalloc (int m, int n, int nzmax, int values, int triplet)
Definition at line 282 of file cs-etc.c.
References CXSPARSE_COMPLEX, CXSPARSE_XTYPE_GET, and Matrix_cs_sparse::xtype.
Referenced by Matrix_cs_speye().
Matrix_cs_speye()
Matrix_cs * Matrix_cs_speye (int m, int n, int values, int triplet)
Definition at line 307 of file cs-etc.c.
References CXSPARSE_COMPLEX, CXSPARSE_XTYPE_GET, Matrix_cs_sparse::i, Matrix_cs_spalloc(), Matrix_cs_sparse::p, and Matrix_cs_sparse::x.
Referenced by sparseLU_solve(), and tCMatrix_solve().
Matrix_cs_spfree()
Matrix_cs * Matrix_cs_spfree (Matrix_cs * A)
Definition at line 337 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by sparseLU_solve(), and tCMatrix_solve().
Matrix_cs_sprealloc()
int Matrix_cs_sprealloc (Matrix_cs * A, int nzmax)
Definition at line 349 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Matrix_cs_spsolve()
int Matrix_cs_spsolve (Matrix_cs * L, const Matrix_cs * B, int k, int * xi, void * x, const int * pinv, int lo)
Definition at line 361 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Matrix_cs_sqr()
Matrix_css * Matrix_cs_sqr (int order, const Matrix_cs * A, int qr)
Definition at line 373 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Referenced by sparse_lu(), and sparse_qr().
Matrix_cs_transpose()
Matrix_cs * Matrix_cs_transpose (const Matrix_cs * A, int values)
Definition at line 385 of file cs-etc.c.
References CXSPARSE_COMPLEX, CXSPARSE_XTYPE_GET, and Matrix_cs_sparse::xtype.
Referenced by sparseLU_solve(), and tCMatrix_solve().
Matrix_cs_usolve()
int Matrix_cs_usolve (const Matrix_cs * U, void * x)
Definition at line 410 of file cs-etc.c.
References CXSPARSE_COMPLEX, and CXSPARSE_XTYPE_GET.
Variable Documentation
Matrix_cs_xtype
int Matrix_cs_xtype
Definition at line 4 of file cs-etc.c.