Matrix: cs.c File Reference
cs.c File Reference
#include "cs.h"
Macros
#define HEAD(k, j) (ata ? head [k] : j)
#define NEXT(J) (ata ? next [J] : -1)
#define csi_MAX INT_MAX
Functions
cs * cs_add (const cs *A, const cs *B, double alpha, double beta)
static csi cs_wclear (csi mark, csi lemax, csi *w, csi n)
static csi cs_diag (csi i, csi j, double aij, void *other)
csi * cs_amd (csi order, const cs *A)
csn * cs_chol (const cs *A, const css *S)
csi cs_cholsol (csi order, const cs *A, double *b)
cs * cs_compress (const cs *T)
static void init_ata (cs *AT, const csi *post, csi *w, csi **head, csi **next)
csi * cs_counts (const cs *A, const csi *parent, const csi *post, csi ata)
double cs_cumsum (csi *p, csi *c, csi n)
csi cs_dfs (csi j, cs *G, csi top, csi *xi, csi *pstack, const csi *pinv)
static csi cs_bfs (const cs *A, csi n, csi *wi, csi *wj, csi *queue, const csi *imatch, const csi *jmatch, csi mark)
static void cs_matched (csi n, const csi *wj, const csi *imatch, csi *p, csi *q, csi *cc, csi *rr, csi set, csi mark)
static void cs_unmatched (csi m, const csi *wi, csi *p, csi *rr, csi set)
static csi cs_rprune (csi i, csi j, double aij, void *other)
csd * cs_dmperm (const cs *A, csi seed)
static csi cs_tol (csi i, csi j, double aij, void *tol)
csi cs_droptol (cs *A, double tol)
static csi cs_nonzero (csi i, csi j, double aij, void *other)
csi cs_dropzeros (cs *A)
csi cs_dupl (cs *A)
csi cs_entry (cs *T, csi i, csi j, double x)
csi cs_ereach (const cs *A, csi k, const csi *parent, csi *s, csi *w)
csi * cs_etree (const cs *A, csi ata)
csi cs_fkeep (cs *A, csi(*fkeep)(csi, csi, double, void *), void *other)
csi cs_gaxpy (const cs *A, const double *x, double *y)
csi cs_happly (const cs *V, csi i, double beta, double *x)
double cs_house (double *x, double *beta, csi n)
csi cs_ipvec (const csi *p, const double *b, double *x, csi n)
csi cs_leaf (csi i, csi j, const csi *first, csi *maxfirst, csi *prevleaf, csi *ancestor, csi *jleaf)
cs * cs_load (FILE *f)
csi cs_lsolve (const cs *L, double *x)
csi cs_ltsolve (const cs *L, double *x)
csn * cs_lu (const cs *A, const css *S, double tol)
csi cs_lusol (csi order, const cs *A, double *b, double tol)
void * cs_malloc (csi n, size_t size)
void * cs_calloc (csi n, size_t size)
void * cs_free (void *p)
void * cs_realloc (void *p, csi n, size_t size, csi *ok)
static void cs_augment (csi k, const cs *A, csi *jmatch, csi *cheap, csi *w, csi *js, csi *is, csi *ps)
csi * cs_maxtrans (const cs *A, csi seed)
cs * cs_multiply (const cs *A, const cs *B)
double cs_norm (const cs *A)
cs * cs_permute (const cs *A, const csi *pinv, const csi *q, csi values)
csi * cs_pinv (csi const *p, csi n)
csi * cs_post (const csi *parent, csi n)
csi cs_print (const cs *A, csi brief)
csi cs_pvec (const csi *p, const double *b, double *x, csi n)
csn * cs_qr (const cs *A, const css *S)
csi cs_qrsol (csi order, const cs *A, double *b)
csi * cs_randperm (csi n, csi seed)
csi cs_reach (cs *G, const cs *B, csi k, csi *xi, const csi *pinv)
csi cs_scatter (const cs *A, csi j, double beta, csi *w, double *x, csi mark, cs *C, csi nz)
csd * cs_scc (cs *A)
css * cs_schol (csi order, const cs *A)
csi cs_spsolve (cs *G, const cs *B, csi k, csi *xi, double *x, const csi *pinv, csi lo)
static csi cs_vcount (const cs *A, css *S)
css * cs_sqr (csi order, const cs *A, csi qr)
cs * cs_symperm (const cs *A, const csi *pinv, csi values)
csi cs_tdfs (csi j, csi k, csi *head, const csi *next, csi *post, csi *stack)
cs * cs_transpose (const cs *A, csi values)
csi cs_updown (cs *L, csi sigma, const cs *C, const csi *parent)
csi cs_usolve (const cs *U, double *x)
cs * cs_spalloc (csi m, csi n, csi nzmax, csi values, csi triplet)
csi cs_sprealloc (cs *A, csi nzmax)
cs * cs_spfree (cs *A)
csn * cs_nfree (csn *N)
css * cs_sfree (css *S)
csd * cs_dalloc (csi m, csi n)
csd * cs_dfree (csd *D)
cs * cs_done (cs *C, void *w, void *x, csi ok)
csi * cs_idone (csi *p, cs *C, void *w, csi ok)
csn * cs_ndone (csn *N, cs *C, void *w, void *x, csi ok)
csd * cs_ddone (csd *D, cs *C, void *w, csi ok)
csi cs_utsolve (const cs *U, double *x)
Macro Definition Documentation
csi_MAX
#define csi_MAX INT_MAX
Definition at line 1256 of file cs.c.
HEAD
#define HEAD (k, j) (ata ? head [k] : j)
Definition at line 496 of file cs.c.
NEXT
#define NEXT (J) (ata ? next [J] : -1)
Definition at line 497 of file cs.c.
Function Documentation
cs_add()
cs * cs_add (const cs * A, const cs * B, double alpha, double beta)
Definition at line 3 of file cs.c.
References cs_calloc(), CS_CSC, cs_done(), cs_malloc(), cs_scatter(), cs_spalloc(), cs_sprealloc(), csi, cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_amd().
cs_amd()
csi * cs_amd (csi order, const cs * A)
Definition at line 45 of file cs.c.
References cs_add(), CS_CSC, cs_diag(), cs_fkeep(), CS_FLIP, cs_idone(), cs_malloc(), CS_MAX, CS_MIN, cs_multiply(), cs_spfree(), cs_sprealloc(), cs_tdfs(), cs_transpose(), cs_wclear(), csi, cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::nzmax, and cs_sparse::p.
Referenced by cs_schol(), and cs_sqr().
cs_augment()
static void cs_augment (csi k, const cs * A, csi * jmatch, csi * cheap, csi * w, csi * js, csi * is, csi * ps) static
Definition at line 1164 of file cs.c.
References csi, cs_sparse::i, and cs_sparse::p.
Referenced by cs_maxtrans().
cs_bfs()
static csi cs_bfs (const cs * A, csi n, csi * wi, csi * wj, csi * queue, const csi * imatch, const csi * jmatch, csi mark) static
Definition at line 607 of file cs.c.
References cs_spfree(), cs_transpose(), csi, cs_sparse::i, and cs_sparse::p.
Referenced by cs_dmperm().
cs_calloc()
void * cs_calloc (csi n, size_t size)
Definition at line 1143 of file cs.c.
References CS_MAX.
Referenced by cs_add(), cs_chol(), cs_compress(), cs_dalloc(), cs_lu(), cs_maxtrans(), cs_multiply(), cs_qr(), cs_qrsol(), cs_schol(), cs_spalloc(), cs_sqr(), cs_symperm(), cs_transpose(), Matrix_cs_permute(), Matrix_cs_spalloc(), and Matrix_cs_transpose().
cs_chol()
csn * cs_chol (const cs * A, const css * S)
Definition at line 393 of file cs.c.
References c, cs_symbolic::cp, cs_calloc(), CS_CSC, cs_ereach(), cs_malloc(), cs_ndone(), cs_spalloc(), cs_symperm(), csi, cs_sparse::i, cs_numeric::L, cs_sparse::n, cs_sparse::p, cs_symbolic::parent, cs_symbolic::pinv, and cs_sparse::x.
Referenced by cs_cholsol().
cs_cholsol()
csi cs_cholsol (csi order, const cs * A, double * b)
Definition at line 450 of file cs.c.
References cs_chol(), CS_CSC, cs_free(), cs_ipvec(), cs_lsolve(), cs_ltsolve(), cs_malloc(), cs_nfree(), cs_pvec(), cs_schol(), cs_sfree(), csi, cs_numeric::L, cs_sparse::n, and cs_symbolic::pinv.
cs_compress()
cs * cs_compress (const cs * T)
Definition at line 475 of file cs.c.
References cs_calloc(), cs_cumsum(), cs_done(), cs_spalloc(), CS_TRIPLET, csi, cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::nz, cs_sparse::p, and cs_sparse::x.
cs_counts()
csi * cs_counts (const cs * A, const csi * parent, const csi * post, csi ata)
Definition at line 510 of file cs.c.
References CS_CSC, cs_idone(), cs_leaf(), cs_malloc(), cs_transpose(), csi, HEAD, cs_sparse::i, init_ata(), cs_sparse::m, cs_sparse::n, NEXT, and cs_sparse::p.
Referenced by cs_schol(), and cs_sqr().
cs_cumsum()
double cs_cumsum (csi * p, csi * c, csi n)
Definition at line 556 of file cs.c.
References c, and csi.
Referenced by cs_compress(), cs_schol(), cs_symperm(), and cs_transpose().
cs_dalloc()
csd * cs_dalloc (csi m, csi n)
Definition at line 1985 of file cs.c.
References cs_calloc(), cs_dfree(), cs_malloc(), csi, cs_dmperm_results::p, cs_dmperm_results::q, cs_dmperm_results::r, and cs_dmperm_results::s.
Referenced by cs_dmperm(), and cs_scc().
cs_ddone()
csd * cs_ddone (csd * D, cs * C, void * w, csi ok)
Definition at line 2034 of file cs.c.
References cs_dfree(), cs_free(), and cs_spfree().
Referenced by cs_dmperm(), and cs_scc().
cs_dfree()
csd * cs_dfree (csd * D)
Definition at line 1998 of file cs.c.
References cs_free(), cs_dmperm_results::p, cs_dmperm_results::q, cs_dmperm_results::r, and cs_dmperm_results::s.
Referenced by cs_dalloc(), cs_ddone(), cs_dmperm(), and Matrix_cs_dfree().
cs_dfs()
csi cs_dfs (csi j, cs * G, csi top, csi * xi, csi * pstack, const csi * pinv)
Definition at line 572 of file cs.c.
References CS_CSC, CS_MARK, CS_MARKED, CS_UNFLIP, csi, cs_sparse::i, and cs_sparse::p.
Referenced by cs_reach(), and cs_scc().
cs_diag()
static csi cs_diag (csi i, csi j, double aij, void * other) static
Definition at line 42 of file cs.c.
Referenced by cs_amd().
cs_dmperm()
csd * cs_dmperm (const cs * A, csi seed)
Definition at line 672 of file cs.c.
References cs_dmperm_results::cc, cs_bfs(), CS_CSC, cs_dalloc(), cs_ddone(), cs_dfree(), cs_fkeep(), cs_free(), cs_matched(), cs_maxtrans(), cs_permute(), cs_pinv(), cs_rprune(), cs_scc(), cs_unmatched(), csi, cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_dmperm_results::nb, cs_sparse::p, cs_dmperm_results::p, cs_dmperm_results::q, cs_dmperm_results::r, cs_dmperm_results::rr, and cs_dmperm_results::s.
Referenced by Matrix_cs_dmperm().
cs_done()
cs * cs_done (cs * C, void * w, void * x, csi ok)
Definition at line 2009 of file cs.c.
References cs_free(), and cs_spfree().
Referenced by cs_add(), cs_compress(), cs_multiply(), cs_permute(), cs_symperm(), and cs_transpose().
cs_droptol()
csi cs_droptol (cs * A, double tol)
Definition at line 753 of file cs.c.
References cs_fkeep(), and cs_tol().
cs_dropzeros()
csi cs_dropzeros (cs * A)
Definition at line 761 of file cs.c.
References cs_fkeep(), and cs_nonzero().
Referenced by Matrix_cs_dropzeros().
cs_dupl()
csi cs_dupl (cs * A)
Definition at line 766 of file cs.c.
References CS_CSC, cs_free(), cs_malloc(), cs_sprealloc(), csi, cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
cs_entry()
csi cs_entry (cs * T, csi i, csi j, double x)
Definition at line 799 of file cs.c.
References CS_MAX, cs_sprealloc(), CS_TRIPLET, cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::nz, cs_sparse::nzmax, cs_sparse::p, and cs_sparse::x.
Referenced by cs_load().
cs_ereach()
csi cs_ereach (const cs * A, csi k, const csi * parent, csi * s, csi * w)
Definition at line 811 of file cs.c.
References CS_CSC, CS_MARK, CS_MARKED, csi, cs_sparse::i, cs_sparse::n, and cs_sparse::p.
Referenced by cs_chol().
cs_etree()
csi * cs_etree (const cs * A, csi ata)
Definition at line 833 of file cs.c.
References CS_CSC, cs_idone(), cs_malloc(), csi, cs_sparse::i, cs_sparse::m, cs_sparse::n, and cs_sparse::p.
Referenced by cs_schol(), and cs_sqr().
cs_fkeep()
csi cs_fkeep (cs * A, csi(*)(csi, csi, double, void *) fkeep, void * other)
Definition at line 862 of file cs.c.
References CS_CSC, cs_sprealloc(), csi, cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_amd(), cs_dmperm(), cs_droptol(), and cs_dropzeros().
cs_free()
void * cs_free (void * p)
Definition at line 1149 of file cs.c.
Referenced by cs_cholsol(), cs_ddone(), cs_dfree(), cs_dmperm(), cs_done(), cs_dupl(), cs_idone(), cs_lusol(), cs_maxtrans(), cs_ndone(), cs_nfree(), cs_qrsol(), cs_schol(), cs_sfree(), cs_spfree(), cs_sqr(), cs_updown(), cs_vcount(), Matrix_cs_free(), Matrix_cs_permute(), Matrix_cs_spalloc(), and Matrix_cs_transpose().
cs_gaxpy()
csi cs_gaxpy (const cs * A, const double * x, double * y)
Definition at line 886 of file cs.c.
References CS_CSC, csi, cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
cs_happly()
csi cs_happly (const cs * V, csi i, double beta, double * x)
Definition at line 902 of file cs.c.
References CS_CSC, csi, cs_sparse::i, cs_sparse::p, and cs_sparse::x.
Referenced by cs_qr(), cs_qrsol(), and Matrix_cs_happly().
cs_house()
double cs_house (double * x, double * beta, csi n)
Definition at line 921 of file cs.c.
References csi.
Referenced by cs_qr().
cs_idone()
csi * cs_idone (csi * p, cs * C, void * w, csi ok)
Definition at line 2017 of file cs.c.
References cs_free(), cs_spfree(), and csi.
Referenced by cs_amd(), cs_counts(), cs_etree(), cs_maxtrans(), and cs_post().
cs_ipvec()
csi cs_ipvec (const csi * p, const double * b, double * x, csi n)
Definition at line 942 of file cs.c.
References csi.
Referenced by cs_cholsol(), cs_lusol(), cs_qrsol(), and Matrix_cs_ipvec().
cs_leaf()
csi cs_leaf (csi i, csi j, const csi * first, csi * maxfirst, csi * prevleaf, csi * ancestor, csi * jleaf)
Definition at line 950 of file cs.c.
References csi.
Referenced by cs_counts().
cs_load()
cs * cs_load (FILE * f)
Definition at line 971 of file cs.c.
References cs_entry(), cs_spalloc(), cs_spfree(), and csi.
cs_lsolve()
csi cs_lsolve (const cs * L, double * x)
Definition at line 985 of file cs.c.
References CS_CSC, csi, cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_cholsol(), cs_lusol(), and Matrix_cs_lsolve().
cs_ltsolve()
csi cs_ltsolve (const cs * L, double * x)
Definition at line 1002 of file cs.c.
References CS_CSC, csi, cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_cholsol().
cs_lu()
csn * cs_lu (const cs * A, const css * S, double tol)
Definition at line 1019 of file cs.c.
References cs_calloc(), CS_CSC, cs_malloc(), cs_ndone(), cs_spalloc(), cs_sprealloc(), cs_spsolve(), csi, cs_sparse::i, cs_numeric::L, cs_symbolic::lnz, cs_sparse::n, cs_sparse::nzmax, cs_sparse::p, cs_numeric::pinv, cs_symbolic::q, cs_numeric::U, cs_symbolic::unz, and cs_sparse::x.
Referenced by cs_lusol(), and Matrix_cs_lu().
cs_lusol()
csi cs_lusol (csi order, const cs * A, double * b, double tol)
Definition at line 1105 of file cs.c.
References CS_CSC, cs_free(), cs_ipvec(), cs_lsolve(), cs_lu(), cs_malloc(), cs_nfree(), cs_sfree(), cs_sqr(), cs_usolve(), csi, cs_numeric::L, cs_sparse::n, cs_numeric::pinv, cs_symbolic::q, and cs_numeric::U.
Referenced by Matrix_cs_lusol().
cs_malloc()
void * cs_malloc (csi n, size_t size)
Definition at line 1137 of file cs.c.
References CS_MAX.
Referenced by cs_add(), cs_amd(), cs_chol(), cs_cholsol(), cs_counts(), cs_dalloc(), cs_dupl(), cs_etree(), cs_lu(), cs_lusol(), cs_maxtrans(), cs_multiply(), cs_pinv(), cs_post(), cs_qr(), cs_randperm(), cs_scc(), cs_schol(), cs_spalloc(), cs_updown(), and cs_vcount().
cs_matched()
static void cs_matched (csi n, const csi * wj, const csi * imatch, csi * p, csi * q, csi * cc, csi * rr, csi set, csi mark) static
Definition at line 641 of file cs.c.
References csi.
Referenced by cs_dmperm().
cs_maxtrans()
csi * cs_maxtrans (const cs * A, csi seed)
Definition at line 1205 of file cs.c.
References cs_augment(), cs_calloc(), CS_CSC, cs_free(), cs_idone(), cs_malloc(), CS_MIN, cs_randperm(), cs_transpose(), csi, cs_sparse::i, cs_sparse::m, cs_sparse::n, and cs_sparse::p.
Referenced by cs_dmperm().
cs_multiply()
cs * cs_multiply (const cs * A, const cs * B)
Definition at line 1262 of file cs.c.
References cs_calloc(), CS_CSC, cs_done(), cs_malloc(), cs_scatter(), cs_spalloc(), cs_sprealloc(), csi, csi_MAX, cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::nzmax, cs_sparse::p, and cs_sparse::x.
Referenced by cs_amd().
cs_ndone()
csn * cs_ndone (csn * N, cs * C, void * w, void * x, csi ok)
Definition at line 2025 of file cs.c.
References cs_free(), cs_nfree(), and cs_spfree().
Referenced by cs_chol(), cs_lu(), and cs_qr().
cs_nfree()
csn * cs_nfree (csn * N)
Definition at line 1962 of file cs.c.
References cs_numeric::B, cs_free(), cs_spfree(), cs_numeric::L, cs_numeric::pinv, and cs_numeric::U.
Referenced by cs_cholsol(), cs_lusol(), cs_ndone(), cs_qrsol(), and Matrix_cs_nfree().
cs_nonzero()
static csi cs_nonzero (csi i, csi j, double aij, void * other) static
Definition at line 757 of file cs.c.
Referenced by cs_dropzeros().
cs_norm()
double cs_norm (const cs * A)
Definition at line 1298 of file cs.c.
References CS_CSC, CS_MAX, csi, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_print().
cs_permute()
cs * cs_permute (const cs * A, const csi * pinv, const csi * q, csi values)
Definition at line 1312 of file cs.c.
References CS_CSC, cs_done(), cs_spalloc(), csi, cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_dmperm(), cs_sqr(), and Matrix_cs_permute().
cs_pinv()
csi * cs_pinv (csi const * p, csi n)
Definition at line 1336 of file cs.c.
References cs_malloc(), and csi.
Referenced by cs_dmperm(), cs_schol(), and Matrix_cs_pinv().
cs_post()
csi * cs_post (const csi * parent, csi n)
Definition at line 1346 of file cs.c.
References cs_idone(), cs_malloc(), cs_tdfs(), and csi.
Referenced by cs_schol(), and cs_sqr().
cs_print()
csi cs_print (const cs * A, csi brief)
Definition at line 1369 of file cs.c.
References CS_COPYRIGHT, CS_DATE, cs_norm(), CS_SUBSUB, CS_SUBVER, CS_VER, csi, cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::nz, cs_sparse::nzmax, cs_sparse::p, printf, and cs_sparse::x.
cs_pvec()
csi cs_pvec (const csi * p, const double * b, double * x, csi n)
Definition at line 1407 of file cs.c.
References csi.
Referenced by cs_cholsol(), cs_qrsol(), and Matrix_cs_pvec().
cs_qr()
csn * cs_qr (const cs * A, const css * S)
Definition at line 1415 of file cs.c.
References cs_numeric::B, cs_calloc(), CS_CSC, cs_happly(), cs_house(), cs_malloc(), cs_ndone(), cs_scatter(), cs_spalloc(), csi, cs_sparse::i, cs_numeric::L, cs_symbolic::leftmost, cs_symbolic::lnz, cs_symbolic::m2, cs_sparse::n, cs_sparse::p, cs_symbolic::parent, cs_symbolic::pinv, cs_symbolic::q, cs_numeric::U, cs_symbolic::unz, and cs_sparse::x.
Referenced by cs_qrsol(), and Matrix_cs_qr().
cs_qrsol()
csi cs_qrsol (csi order, const cs * A, double * b)
Definition at line 1487 of file cs.c.
References cs_numeric::B, cs_calloc(), CS_CSC, cs_free(), cs_happly(), cs_ipvec(), cs_nfree(), cs_pvec(), cs_qr(), cs_sfree(), cs_spfree(), cs_sqr(), cs_transpose(), cs_usolve(), cs_utsolve(), csi, cs_numeric::L, cs_sparse::m, cs_symbolic::m2, cs_sparse::n, cs_symbolic::pinv, cs_symbolic::q, and cs_numeric::U.
Referenced by Matrix_cs_qrsol().
cs_randperm()
csi * cs_randperm (csi n, csi seed)
Definition at line 1546 of file cs.c.
References cs_malloc(), and csi.
Referenced by cs_maxtrans().
cs_reach()
csi cs_reach (cs * G, const cs * B, csi k, csi * xi, const csi * pinv)
Definition at line 1568 of file cs.c.
References CS_CSC, cs_dfs(), CS_MARK, CS_MARKED, csi, cs_sparse::i, cs_sparse::n, and cs_sparse::p.
Referenced by cs_spsolve().
cs_realloc()
void * cs_realloc (void * p, csi n, size_t size, csi * ok)
Definition at line 1156 of file cs.c.
References CS_MAX.
Referenced by cs_sprealloc().
cs_rprune()
static csi cs_rprune (csi i, csi j, double aij, void * other) static
Definition at line 665 of file cs.c.
References csi.
Referenced by cs_dmperm().
cs_scatter()
csi cs_scatter (const cs * A, csi j, double beta, csi * w, double * x, csi mark, cs * C, csi nz)
Definition at line 1585 of file cs.c.
References CS_CSC, csi, cs_sparse::i, cs_sparse::p, and cs_sparse::x.
Referenced by cs_add(), cs_multiply(), and cs_qr().
cs_scc()
csd * cs_scc (cs * A)
Definition at line 1606 of file cs.c.
References CS_CSC, cs_dalloc(), cs_ddone(), cs_dfs(), cs_malloc(), CS_MARK, CS_MARKED, cs_transpose(), csi, cs_sparse::n, cs_dmperm_results::nb, cs_sparse::p, cs_dmperm_results::p, and cs_dmperm_results::r.
Referenced by cs_dmperm().
cs_schol()
css * cs_schol (csi order, const cs * A)
Definition at line 1646 of file cs.c.
References c, cs_symbolic::cp, cs_amd(), cs_calloc(), cs_counts(), CS_CSC, cs_cumsum(), cs_etree(), cs_free(), cs_malloc(), cs_pinv(), cs_post(), cs_sfree(), cs_spfree(), cs_symperm(), csi, cs_symbolic::lnz, cs_sparse::n, cs_symbolic::parent, cs_symbolic::pinv, and cs_symbolic::unz.
Referenced by cs_cholsol().
cs_sfree()
css * cs_sfree (css * S)
Definition at line 1973 of file cs.c.
References cs_symbolic::cp, cs_free(), cs_symbolic::leftmost, cs_symbolic::parent, cs_symbolic::pinv, and cs_symbolic::q.
Referenced by cs_cholsol(), cs_lusol(), cs_qrsol(), cs_schol(), cs_sqr(), and Matrix_cs_sfree().
cs_spalloc()
cs * cs_spalloc (csi m, csi n, csi nzmax, csi values, csi triplet)
Definition at line 1922 of file cs.c.
References cs_calloc(), cs_malloc(), CS_MAX, cs_spfree(), csi, cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::nz, cs_sparse::nzmax, cs_sparse::p, and cs_sparse::x.
Referenced by cs_add(), cs_chol(), cs_compress(), cs_load(), cs_lu(), cs_multiply(), cs_permute(), cs_qr(), cs_symperm(), cs_transpose(), and Matrix_cs_spalloc().
cs_spfree()
cs * cs_spfree (cs * A)
Definition at line 1952 of file cs.c.
References cs_free(), cs_sparse::i, cs_sparse::p, and cs_sparse::x.
Referenced by cs_amd(), cs_bfs(), cs_ddone(), cs_done(), cs_idone(), cs_load(), cs_ndone(), cs_nfree(), cs_qrsol(), cs_schol(), cs_spalloc(), cs_sqr(), and Matrix_cs_spfree().
cs_sprealloc()
csi cs_sprealloc (cs * A, csi nzmax)
Definition at line 1937 of file cs.c.
References CS_CSC, CS_MAX, cs_realloc(), CS_TRIPLET, csi, cs_sparse::i, cs_sparse::n, cs_sparse::nz, cs_sparse::nzmax, cs_sparse::p, and cs_sparse::x.
Referenced by cs_add(), cs_amd(), cs_dupl(), cs_entry(), cs_fkeep(), cs_lu(), cs_multiply(), and Matrix_cs_sprealloc().
cs_spsolve()
csi cs_spsolve (cs * G, const cs * B, csi k, csi * xi, double * x, const csi * pinv, csi lo)
Definition at line 1671 of file cs.c.
References CS_CSC, cs_reach(), csi, cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_lu(), and Matrix_cs_spsolve().
cs_sqr()
css * cs_sqr (csi order, const cs * A, csi qr)
Definition at line 1755 of file cs.c.
References cs_symbolic::cp, cs_amd(), cs_calloc(), cs_counts(), CS_CSC, cs_etree(), cs_free(), cs_permute(), cs_post(), cs_sfree(), cs_spfree(), cs_vcount(), csi, cs_symbolic::lnz, cs_sparse::n, cs_sparse::p, cs_symbolic::parent, cs_symbolic::q, and cs_symbolic::unz.
Referenced by cs_lusol(), cs_qrsol(), and Matrix_cs_sqr().
cs_symperm()
cs * cs_symperm (const cs * A, const csi * pinv, csi values)
Definition at line 1784 of file cs.c.
References cs_calloc(), CS_CSC, cs_cumsum(), cs_done(), CS_MAX, CS_MIN, cs_spalloc(), csi, cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_chol(), and cs_schol().
cs_tdfs()
csi cs_tdfs (csi j, csi k, csi * head, const csi * next, csi * post, csi * stack)
Definition at line 1822 of file cs.c.
References csi.
Referenced by cs_amd(), and cs_post().
cs_tol()
static csi cs_tol (csi i, csi j, double aij, void * tol) static
Definition at line 749 of file cs.c.
Referenced by cs_droptol().
cs_transpose()
cs * cs_transpose (const cs * A, csi values)
Definition at line 1845 of file cs.c.
References cs_calloc(), CS_CSC, cs_cumsum(), cs_done(), cs_spalloc(), csi, cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_amd(), cs_bfs(), cs_counts(), cs_maxtrans(), cs_qrsol(), cs_scc(), and Matrix_cs_transpose().
cs_unmatched()
static void cs_unmatched (csi m, const csi * wi, csi * p, csi * rr, csi set) static
Definition at line 657 of file cs.c.
References csi.
Referenced by cs_dmperm().
cs_updown()
csi cs_updown (cs * L, csi sigma, const cs * C, const csi * parent)
Definition at line 1869 of file cs.c.
References CS_CSC, cs_free(), cs_malloc(), CS_MIN, csi, cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
cs_usolve()
csi cs_usolve (const cs * U, double * x)
Definition at line 1905 of file cs.c.
References CS_CSC, csi, cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_lusol(), cs_qrsol(), and Matrix_cs_usolve().
cs_utsolve()
csi cs_utsolve (const cs * U, double * x)
Definition at line 2041 of file cs.c.
References CS_CSC, csi, cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_qrsol().
cs_vcount()
static csi cs_vcount (const cs * A, css * S) static
Definition at line 1698 of file cs.c.
References cs_free(), cs_malloc(), csi, cs_sparse::i, cs_symbolic::leftmost, cs_symbolic::lnz, cs_sparse::m, cs_symbolic::m2, cs_sparse::n, cs_sparse::p, cs_symbolic::parent, and cs_symbolic::pinv.
Referenced by cs_sqr().
cs_wclear()
static csi cs_wclear (csi mark, csi lemax, csi * w, csi n) static
Definition at line 30 of file cs.c.
References csi.
Referenced by cs_amd().
init_ata()
static void init_ata (cs * AT, const csi * post, csi * w, csi ** head, csi ** next) static
Definition at line 498 of file cs.c.
References CS_MIN, csi, cs_sparse::i, cs_sparse::m, cs_sparse::n, and cs_sparse::p.
Referenced by cs_counts().