Matrix: dense.h File Reference
dense.h File Reference
#include <Rinternals.h>
Functions
SEXP dense_band (SEXP, const char *, int, int)
SEXP R_dense_band (SEXP, SEXP, SEXP)
SEXP dense_diag_get (SEXP, const char *, int)
SEXP R_dense_diag_get (SEXP, SEXP)
SEXP dense_diag_set (SEXP, const char *, SEXP, int)
SEXP R_dense_diag_set (SEXP, SEXP)
SEXP dense_transpose (SEXP, const char *)
SEXP R_dense_transpose (SEXP)
SEXP dense_force_symmetric (SEXP, const char *, char)
SEXP R_dense_force_symmetric (SEXP, SEXP)
SEXP dense_symmpart (SEXP, const char *)
SEXP R_dense_symmpart (SEXP)
SEXP dense_skewpart (SEXP, const char *)
SEXP R_dense_skewpart (SEXP)
int dense_is_symmetric (SEXP, const char *, int)
SEXP R_dense_is_symmetric (SEXP, SEXP)
int dense_is_triangular (SEXP, const char *, int)
SEXP R_dense_is_triangular (SEXP, SEXP)
int dense_is_diagonal (SEXP, const char *)
SEXP R_dense_is_diagonal (SEXP)
SEXP dense_marginsum (SEXP, const char *, int, int, int)
SEXP R_dense_marginsum (SEXP, SEXP, SEXP, SEXP)
SEXP dense_sum (SEXP, const char *, int)
SEXP R_dense_sum (SEXP, SEXP)
SEXP dense_prod (SEXP, const char *, int)
SEXP R_dense_prod (SEXP, SEXP)
Function Documentation
dense_band()
SEXP dense_band (SEXP from, const char * class, int a, int b)
Definition at line 5 of file dense.c.
References BAND1, BAND2, BAND_CASES, cl, DCPY1, DCPY2, dense_as_general(), dense_transpose(), GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, and set_symmetrized_DimNames().
Referenced by R_dense_band().
dense_diag_get()
SEXP dense_diag_get (SEXP obj, const char * class, int names)
Definition at line 226 of file dense.c.
References DG_LOOP, equal_character_vectors(), GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, and Matrix_zone.
Referenced by R_dense_diag_get().
dense_diag_set()
SEXP dense_diag_set (SEXP from, const char * class, SEXP value, int new)
Definition at line 327 of file dense.c.
References DS_LOOP, GET_SLOT, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, newObject(), and SET_SLOT.
Referenced by R_dense_diag_set().
dense_force_symmetric()
SEXP dense_force_symmetric (SEXP from, const char * class, char ul)
Definition at line 585 of file dense.c.
References _, cl, conjugate(), DCPY, dense_transpose(), GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, and set_symmetrized_DimNames().
Referenced by R_dense_force_symmetric().
dense_is_diagonal()
int dense_is_diagonal (SEXP obj, const char * class)
Definition at line 1256 of file dense.c.
References GET_SLOT, ID_LOOP, ISNZ_COMPLEX, ISNZ_INTEGER, ISNZ_LOGICAL, ISNZ_PATTERN, ISNZ_REAL, Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
Referenced by dense_is_symmetric(), dense_is_triangular(), and R_dense_is_diagonal().
dense_is_symmetric()
int dense_is_symmetric (SEXP obj, const char * class, int checkDN)
Definition at line 1026 of file dense.c.
References dense_is_diagonal(), DimNames_is_symmetric(), GET_SLOT, IS_LOOP, Matrix_DimNamesSym, Matrix_DimSym, Matrix_xSym, NOTCONJ_COMPLEX, NOTCONJ_INTEGER, NOTCONJ_LOGICAL, NOTCONJ_PATTERN, NOTCONJ_REAL, NOTREAL_COMPLEX, NOTREAL_INTEGER, NOTREAL_LOGICAL, NOTREAL_PATTERN, and NOTREAL_REAL.
Referenced by R_dense_is_symmetric().
dense_is_triangular()
int dense_is_triangular (SEXP obj, const char * class, int upper)
Definition at line 1114 of file dense.c.
References dense_is_diagonal(), GET_SLOT, ISNZ_COMPLEX, ISNZ_INTEGER, ISNZ_LOGICAL, ISNZ_PATTERN, ISNZ_REAL, IT_LOOP, Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
Referenced by R_dense_is_triangular().
dense_marginsum()
SEXP dense_marginsum (SEXP obj, const char * class, int margin, int narm, int mean)
Definition at line 1627 of file dense.c.
References dense_colsum(), dense_rowsum(), GET_SLOT, get_symmetrized_DimNames(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, and SUM_TYPEOF.
Referenced by R_dense_marginsum().
dense_prod()
SEXP dense_prod (SEXP obj, const char * class, int narm)
Definition at line 1939 of file dense.c.
References GET_SLOT, LONGDOUBLE_AS_DOUBLE, Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, and PROD_LOOP.
Referenced by R_dense_prod().
dense_skewpart()
SEXP dense_skewpart (SEXP from, const char * class)
Definition at line 859 of file dense.c.
References _, ASSIGN_COMPLEX, ASSIGN_REAL, cl, dense_as_kind(), GET_SLOT, INCREMENT_COMPLEX, INCREMENT_REAL, Matrix_DimNamesSym, Matrix_DimSym, Matrix_memset(), Matrix_pSym, Matrix_uploSym, Matrix_xSym, Matrix_zzero, newObject(), SET_SLOT, set_symmetrized_DimNames(), SP_LOOP, and zeroRe().
Referenced by R_dense_skewpart().
dense_sum()
SEXP dense_sum (SEXP obj, const char * class, int narm)
Definition at line 1713 of file dense.c.
References GET_SLOT, LONGDOUBLE_AS_DOUBLE, Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, SUM_LOOP, and TRY_INCREMENT.
Referenced by R_dense_sum().
dense_symmpart()
SEXP dense_symmpart (SEXP from, const char * class)
Definition at line 707 of file dense.c.
References _, cl, dense_as_kind(), GET_SLOT, INCREMENT_COMPLEX, INCREMENT_REAL, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, Matrix_zone, newObject(), SCALE1_COMPLEX, SCALE1_REAL, SET_SLOT, set_symmetrized_DimNames(), SP_LOOP, and zeroIm().
Referenced by R_dense_symmpart().
dense_transpose()
SEXP dense_transpose (SEXP from, const char * class)
Definition at line 466 of file dense.c.
References GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_sdSym, Matrix_uploSym, Matrix_xSym, newObject(), set_reversed_DimNames(), SET_SLOT, and TRANS_LOOP.
Referenced by dense_band(), dense_force_symmetric(), R_dense_transpose(), and R_diagonal_matmult().
R_dense_band()
SEXP R_dense_band (SEXP from, SEXP k1, SEXP k2)
Definition at line 189 of file dense.c.
References _, dense_band(), ERROR_INVALID_CLASS, GET_SLOT, matrix_as_dense(), Matrix_DimSym, valid, and VALID_DENSE.
R_dense_diag_get()
SEXP R_dense_diag_get (SEXP obj, SEXP names)
Definition at line 312 of file dense.c.
References _, dense_diag_get(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_diag_set()
SEXP R_dense_diag_set (SEXP from, SEXP value)
Definition at line 411 of file dense.c.
References _, dense_as_kind(), dense_diag_set(), ERROR_INVALID_CLASS, GET_SLOT, kindToType(), Matrix_DimSym, typeToKind(), valid, and VALID_DENSE.
R_dense_force_symmetric()
SEXP R_dense_force_symmetric (SEXP from, SEXP uplo)
Definition at line 689 of file dense.c.
References _, dense_force_symmetric(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_is_diagonal()
SEXP R_dense_is_diagonal (SEXP obj)
Definition at line 1360 of file dense.c.
References dense_is_diagonal(), ERROR_INVALID_CLASS, matrix_as_dense(), valid, and VALID_DENSE.
R_dense_is_symmetric()
SEXP R_dense_is_symmetric (SEXP obj, SEXP checkDN)
Definition at line 1091 of file dense.c.
References _, dense_is_symmetric(), ERROR_INVALID_CLASS, matrix_as_dense(), valid, and VALID_DENSE.
R_dense_is_triangular()
SEXP R_dense_is_triangular (SEXP obj, SEXP upper)
Definition at line 1223 of file dense.c.
References _, dense_is_triangular(), ERROR_INVALID_CLASS, matrix_as_dense(), valid, and VALID_DENSE.
R_dense_marginsum()
SEXP R_dense_marginsum (SEXP obj, SEXP margin, SEXP narm, SEXP mean)
Definition at line 1667 of file dense.c.
References _, dense_marginsum(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_prod()
SEXP R_dense_prod (SEXP obj, SEXP narm)
Definition at line 2119 of file dense.c.
References _, dense_prod(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_skewpart()
SEXP R_dense_skewpart (SEXP from)
Definition at line 1016 of file dense.c.
References dense_skewpart(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_sum()
SEXP R_dense_sum (SEXP obj, SEXP narm)
Definition at line 1924 of file dense.c.
References _, dense_sum(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_symmpart()
SEXP R_dense_symmpart (SEXP from)
Definition at line 849 of file dense.c.
References dense_symmpart(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_transpose()
SEXP R_dense_transpose (SEXP from)
Definition at line 573 of file dense.c.
References dense_transpose(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.