Matrix: dense.c File Reference
dense.c File Reference
#include "Mdefines.h"
#include "idz.h"
#include "dense.h"
Macros
#define BAND_CASES(_DO_)
#define BAND2(_PREFIX_, _CTYPE_, _PTR_) _PREFIX_ ## band2(_PTR_(x1), m, n, a, b, di)
#define BAND1(_PREFIX_, _CTYPE_, _PTR_) _PREFIX_ ## band1(_PTR_(x1), n, a, b, ul1, di)
#define DCPY2(_PREFIX_, _CTYPE_, _PTR_)
#define DCPY1(_PREFIX_, _CTYPE_, _PTR_)
#define DG_LOOP(_CTYPE_, _PTR_, _ONE_)
#define DS_LOOP(_CTYPE_, _PTR_)
#define TRANS_LOOP(_CTYPE_, _PTR_)
#define DCPY(_PREFIX_, _CTYPE_, _PTR_)
#define SP_LOOP(_CTYPE_, _PTR_, _INCREMENT_, _SCALE1_, _ONE_)
#define SP_LOOP(_CTYPE_, _PTR_, _INCREMENT_, _ASSIGN_, _ZERO_)
#define IS_LOOP(_CTYPE_, _PTR_, _NOTREAL_, _NOTCONJ_)
#define IT_LOOP(_CTYPE_, _PTR_, _ISNZ_)
#define ID_LOOP(_CTYPE_, _PTR_, _ISNZ_)
#define CAST_PATTERN(_X_) (_X_ != 0)
#define CAST_LOGICAL(_X_) (_X_ != 0)
#define CAST_INTEGER(_X_) _X_
#define CAST_REAL(_X_) _X_
#define CAST_COMPLEX(_X_) _X_
#define SUM_CASES
#define SUM_TYPEOF(c) (c == 'z') ? CPLXSXP : ((mean || c == 'd' || c == 'i') ? REALSXP : INTSXP)
#define SUM_LOOP(_CTYPE0_, _PTR0_, _CTYPE1_, _PTR1_, _ZERO_, _ONE_, _NA_, _ISNA_, _CAST_, _INCREMENT_, _SCALE2_)
#define SUM_KERNEL(_FOR_, _NA_, _ISNA_, _CAST_, _INCREMENT_, _SCALE2_)
#define SUM_LOOP(_CTYPE0_, _PTR0_, _CTYPE1_, _PTR1_, _ZERO_, _ONE_, _NA_, _ISNA_, _CAST_, _INCREMENT_, _SCALE2_)
#define SUM_KERNEL(_FOR_, _NA_, _ISNA_, _CAST_, _INCREMENT_)
#define TRY_INCREMENT(_LABEL_)
#define LONGDOUBLE_AS_DOUBLE(v) (v > DBL_MAX) ? R_PosInf : ((v < -DBL_MAX) ? R_NegInf : (double) v);
#define SUM_LOOP
#define SUM_KERNEL(_FOR_)
#define SUM_KERNEL(_FOR_)
#define SUM_KERNEL(_FOR_)
#define SUM_KERNEL(_FOR_)
#define SUM_KERNEL(_FOR_)
#define SUM_KERNEL(_FOR_)
#define PROD_LOOP
#define PROD_KERNEL(_FOR_)
#define PROD_KERNEL(_FOR_)
#define PROD_KERNEL(_FOR_)
#define PROD_KERNEL(_FOR_)
Functions
SEXP dense_band (SEXP from, const char *class, int a, int b)
SEXP R_dense_band (SEXP from, SEXP k1, SEXP k2)
SEXP dense_diag_get (SEXP obj, const char *class, int names)
SEXP R_dense_diag_get (SEXP obj, SEXP names)
SEXP dense_diag_set (SEXP from, const char *class, SEXP value, int new)
SEXP R_dense_diag_set (SEXP from, SEXP value)
SEXP dense_transpose (SEXP from, const char *class)
SEXP R_dense_transpose (SEXP from)
SEXP dense_force_symmetric (SEXP from, const char *class, char ul)
SEXP R_dense_force_symmetric (SEXP from, SEXP uplo)
SEXP dense_symmpart (SEXP from, const char *class)
SEXP R_dense_symmpart (SEXP from)
SEXP dense_skewpart (SEXP from, const char *class)
SEXP R_dense_skewpart (SEXP from)
int dense_is_symmetric (SEXP obj, const char *class, int checkDN)
SEXP R_dense_is_symmetric (SEXP obj, SEXP checkDN)
int dense_is_triangular (SEXP obj, const char *class, int upper)
SEXP R_dense_is_triangular (SEXP obj, SEXP upper)
int dense_is_diagonal (SEXP obj, const char *class)
SEXP R_dense_is_diagonal (SEXP obj)
static void dense_colsum (SEXP x, const char *class, int m, int n, char ul, char di, int narm, int mean, SEXP res)
static void dense_rowsum (SEXP x, const char *class, int m, int n, char ul, char di, int narm, int mean, SEXP res)
SEXP dense_marginsum (SEXP obj, const char *class, int margin, int narm, int mean)
SEXP R_dense_marginsum (SEXP obj, SEXP margin, SEXP narm, SEXP mean)
SEXP dense_sum (SEXP obj, const char *class, int narm)
SEXP R_dense_sum (SEXP obj, SEXP narm)
SEXP dense_prod (SEXP obj, const char *class, int narm)
SEXP R_dense_prod (SEXP obj, SEXP narm)
Macro Definition Documentation
BAND1
#define BAND1 (_PREFIX_, _CTYPE_, _PTR_) _PREFIX_ ## band1(_PTR_(x1), n, a, b, ul1, di)
BAND2
#define BAND2 (_PREFIX_, _CTYPE_, _PTR_) _PREFIX_ ## band2(_PTR_(x1), m, n, a, b, di)
BAND_CASES
#define BAND_CASES (_DO_)
Value:
    do { \
        switch (class[0]) { \
        case 'n': \
        case 'l': \
            _DO_(i, int, LOGICAL); \
            break; \
        case 'i': \
            _DO_(i, int, INTEGER); \
            break; \
        case 'd': \
            _DO_(d, double, REAL); \
            break; \
        case 'z': \
            _DO_(z, Rcomplex, COMPLEX); \
            break; \
        default: \
            break; \
        } \
    } while (0)
CAST_COMPLEX
#define CAST_COMPLEX (_X_) _X_
Definition at line 1382 of file dense.c.
CAST_INTEGER
#define CAST_INTEGER (_X_) _X_
Definition at line 1380 of file dense.c.
CAST_LOGICAL
#define CAST_LOGICAL (_X_) (_X_ != 0)
Definition at line 1379 of file dense.c.
CAST_PATTERN
#define CAST_PATTERN (_X_) (_X_ != 0)
Definition at line 1378 of file dense.c.
CAST_REAL
#define CAST_REAL (_X_) _X_
Definition at line 1381 of file dense.c.
DCPY
#define DCPY (_PREFIX_, _CTYPE_, _PTR_)
Value:
        do { \
            _CTYPE_ *px0 = _PTR_(x0), *px1 = _PTR_(x1); \
            Matrix_memset(px1, 0, len, sizeof(_CTYPE_)); \
            if (class[2] != 'p') \
                _PREFIX_ ## dcpy2(px1, px0, n, len,     '\0', di); \
            else \
                _PREFIX_ ## dcpy1(px1, px0, n, len, ul1, ul0, di); \
        } while (0)
DCPY1
#define DCPY1 (_PREFIX_, _CTYPE_, _PTR_)
Value:
    do { \
        _CTYPE_ *px0 = _PTR_(x0), *px1 = _PTR_(x1); \
        Matrix_memset(px1, 0, XLENGTH(x1), sizeof(_CTYPE_)); \
        if (a <= 0 && b >= 0) \
            _PREFIX_ ## dcpy1(px1, px0, n, XLENGTH(x1), ul1, ul0, di); \
    } while (0)
DCPY2
#define DCPY2 (_PREFIX_, _CTYPE_, _PTR_)
Value:
    do { \
        _CTYPE_ *px0 = _PTR_(x0), *px1 = _PTR_(x1); \
        Matrix_memset(px1, 0, XLENGTH(x1), sizeof(_CTYPE_)); \
        if (a <= 0 && b >= 0) \
            _PREFIX_ ## dcpy2(px1, px0, n, XLENGTH(x1),      'U', di); \
    } while (0)
DG_LOOP
#define DG_LOOP (_CTYPE_, _PTR_, _ONE_)
Value:
    do { \
        _CTYPE_ *pres = _PTR_(res), *px = _PTR_(x); \
        if (di == 'U') \
            for (j = 0; j < r; ++j) \
                *(pres++) = _ONE_; \
        else if (class[2] != 'p') { \
            R_xlen_t m1a = (R_xlen_t) m + 1; \
            for (j = 0; j < r; ++j, px += m1a) \
                *(pres++) = *px; \
        } \
        else if (ul == 'U') \
            for (j = 0; j < n; px += (++j) + 1) \
                *(pres++) = *px; \
        else \
            for (j = 0; j < n; px += n - (j++)) \
                *(pres++) = *px; \
    } while (0)
DS_LOOP
#define DS_LOOP (_CTYPE_, _PTR_)
Value:
    do { \
        _CTYPE_ *px = _PTR_(x), *pvalue = _PTR_(value); \
        if (class[2] != 'p') { \
            R_xlen_t m1a = (R_xlen_t) m + 1; \
            if (v) \
                for (j = 0; j < r; ++j, px += m1a) \
                    *px = *(pvalue++); \
            else \
                for (j = 0; j < r; ++j, px += m1a) \
                    *px = *pvalue; \
        } else if (ul == 'U') { \
            if (v) \
                for (j = 0; j < n; px += (++j) + 1) \
                    *px = *(pvalue++); \
            else \
                for (j = 0; j < n; px += (++j) + 1) \
                    *px = *pvalue; \
        } else { \
            if (v) \
                for (j = 0; j < n; px += n - (j++)) \
                    *px = *(pvalue++); \
            else \
                for (j = 0; j < n; px += n - (j++)) \
                    *px = *pvalue; \
        } \
    } while (0)
ID_LOOP
#define ID_LOOP (_CTYPE_, _PTR_, _ISNZ_)
IS_LOOP
#define IS_LOOP (_CTYPE_, _PTR_, _NOTREAL_, _NOTCONJ_)
Value:
    do { \
        _CTYPE_ *px = _PTR_(x), *py = px; \
        for (j = 0; j < n; px = (py += (++j) + 1)) { \
            if (_NOTREAL_((*px))) \
                return 0; \
            for (i = j + 1; i < n; ++i) { \
                px += n; \
                py += 1; \
                if (_NOTCONJ_((*px), (*py))) \
                    return 0; \
            } \
        } \
        return 1; \
    } while (0)
IT_LOOP
#define IT_LOOP (_CTYPE_, _PTR_, _ISNZ_)
LONGDOUBLE_AS_DOUBLE
#define LONGDOUBLE_AS_DOUBLE (v) (v > DBL_MAX) ? R_PosInf : ((v < -DBL_MAX) ? R_NegInf : (double) v);
Definition at line 1710 of file dense.c.
PROD_KERNEL [1/4]
#define PROD_KERNEL (_FOR_)
Value:
            do { \
                _FOR_ { \
                    if (*px == 0) { \
                        REAL(res)[0] = 0.0; \
                        UNPROTECT(1); /* res */ \
                        return res; \
                    } \
                    ++px; \
                } \
            } while (0)
PROD_KERNEL [2/4]
#define PROD_KERNEL (_FOR_)
Value:
        do { \
            _FOR_ { \
                if (!(narm && (ISNAN((*px).r) || ISNAN((*px).i)))) { \
                    zr0 = zr; zi0 = zi; \
                    zr = zr0 * (*px).r - zi0 * (*px).i; \
                    zi = zr0 * (*px).i + zi0 * (*px).r; \
                    if (symmetric && i != j) { \
                    zr0 = zr; zi0 = zi; \
                    zr = zr0 * (*px).r - zi0 * (*px).i; \
                    zi = zr0 * (*px).i + zi0 * (*px).r; \
                    } \
                } \
                ++px; \
            } \
        } while (0)
PROD_KERNEL [3/4]
#define PROD_KERNEL (_FOR_)
Value:
        do { \
            _FOR_ { \
                if (!(narm && ISNAN(*px))) \
                    zr *= (symmetric && i != j) \
                        ? (long double) *px * *px : *px; \
                ++px; \
            } \
        } while (0)
PROD_KERNEL [4/4]
#define PROD_KERNEL (_FOR_)
Value:
        do { \
            _FOR_ { \
                if (*px != NA_INTEGER) \
                    zr *= (symmetric && i != j) \
                        ? (long double) *px * *px : *px; \
                else if (!narm) \
                    zr *= NA_REAL; \
                ++px; \
            } \
        } while (0)
PROD_LOOP
#define PROD_LOOP
SP_LOOP [1/2]
#define SP_LOOP (_CTYPE_, _PTR_, _INCREMENT_, _ASSIGN_, _ZERO_)
SP_LOOP [2/2]
#define SP_LOOP (_CTYPE_, _PTR_, _INCREMENT_, _SCALE1_, _ONE_)
SUM_CASES
#define SUM_CASES
Definition at line 1384 of file dense.c.
SUM_KERNEL [1/8]
#define SUM_KERNEL (_FOR_)
Value:
        do { \
            _FOR_ { \
                if (*px != 0) \
                    s += (symmetric && i != j) ? 2 : 1; \
                ++px; \
            } \
        } while (0)
SUM_KERNEL [2/8]
#define SUM_KERNEL (_FOR_)
Value:
        do { \
            _FOR_ { \
                if (*px == NA_INTEGER) { \
                    res = allocVector(INTSXP, 1); \
                    INTEGER(res)[0] = NA_INTEGER; \
                    return res; \
                } \
                ++px; \
            } \
        } while (0)
SUM_KERNEL [3/8]
#define SUM_KERNEL (_FOR_)
Value:
        do { \
            _FOR_ { \
                if (!(narm && (ISNAN((*px).r) || ISNAN((*px).i)))) { \
                    zr += (symmetric && i != j) \
                        ? 2.0L * (*px).r : (*px).r; \
                    zi += (symmetric && i != j) \
                        ? 2.0L * (*px).i : (*px).i; \
                } \
                ++px; \
            } \
        } while (0)
SUM_KERNEL [4/8]
#define SUM_KERNEL (_FOR_)
Value:
        do { \
            _FOR_ { \
                if (!(narm && ISNAN(*px))) \
                    zr += (symmetric && i != j) \
                        ? 2.0L * *px : *px; \
                ++px; \
            } \
        } while (0)
SUM_KERNEL [5/8]
#define SUM_KERNEL (_FOR_)
Value:
        do { \
            _FOR_ { \
                if (!(narm && *px == NA_INTEGER)) { \
                    int d = (symmetric && i != j) ? 2 : 1; \
                    if (count > UINT_MAX - d) \
                        TRY_INCREMENT(ifover); \
                    t += (d == 2) ? 2LL * *px : *px; \
                    count += d; \
                } \
                ++px; \
            } \
        } while (0)
SUM_KERNEL [6/8]
#define SUM_KERNEL (_FOR_)
Value:
            do { \
                _FOR_ { \
                    if (!(narm && *px == NA_INTEGER)) \
                        zr += (symmetric && i != j) \
                            ? 2.0L * *px : *px; \
                    ++px; \
                } \
            } while (0)
SUM_KERNEL [7/8]
#define SUM_KERNEL (_FOR_, _NA_, _ISNA_, _CAST_, _INCREMENT_)
Value:
    do { \
        _FOR_ { \
            int again = symmetric && i != j; \
            if (_ISNA_(*px0)) { \
                if (!narm) { \
                    px1[i] = _NA_; \
                    if (again) \
                    px1[j] = _NA_; \
                } else if (narm_) { \
                    --count[i]; \
                    if (again) \
                    --count[j]; \
                } \
            } else { \
                tmp = _CAST_(*px0); \
                _INCREMENT_(px1[i], tmp); \
                if (again) \
                _INCREMENT_(px1[j], tmp); \
            } \
            ++px0; \
        } \
    } while (0)
SUM_KERNEL [8/8]
#define SUM_KERNEL (_FOR_, _NA_, _ISNA_, _CAST_, _INCREMENT_, _SCALE2_)
Value:
    do { \
        if (mean) \
            count = m; \
        _FOR_ { \
            if (_ISNA_(*px0)) { \
                if (!narm) \
                    *px1 = _NA_; \
                else if (narm_) \
                    --count; \
            } else { \
                tmp = _CAST_(*px0); \
                _INCREMENT_((*px1), tmp); \
            } \
            ++px0; \
        } \
        if (mean) \
            _SCALE2_((*px1), count); \
    } while (0)
SUM_LOOP [1/3]
#define SUM_LOOP (_CTYPE0_, _PTR0_, _CTYPE1_, _PTR1_, _ZERO_, _ONE_, _NA_, _ISNA_, _CAST_, _INCREMENT_, _SCALE2_)
SUM_LOOP [2/3]
#define SUM_LOOP (_CTYPE0_, _PTR0_, _CTYPE1_, _PTR1_, _ZERO_, _ONE_, _NA_, _ISNA_, _CAST_, _INCREMENT_, _SCALE2_)
SUM_LOOP [3/3]
#define SUM_LOOP
SUM_TYPEOF
#define SUM_TYPEOF (c) (c == 'z') ? CPLXSXP : ((mean || c == 'd' || c == 'i') ? REALSXP : INTSXP)
Definition at line 1427 of file dense.c.
TRANS_LOOP
#define TRANS_LOOP (_CTYPE_, _PTR_)
Value:
    do { \
        _CTYPE_ *px0 = _PTR_(x0), *px1 = _PTR_(x1); \
        if (class[2] != 'p') { \
            R_xlen_t mn1s = XLENGTH(x0) - 1; \
            for (j = 0; j < m; ++j, px0 -= mn1s) \
                for (i = 0; i < n; ++i, px0 += m) \
                    *(px1++) = *px0; \
        } else if (ul == 'U') { \
            for (j = 0; j < n; ++j) \
                for (i = j; i < n; ++i) \
                    *(px1++) = *(px0 + PACKED_AR21_UP(j, i)); \
        } else { \
            R_xlen_t n2 = (R_xlen_t) n * 2; \
            for (j = 0; j < n; ++j) \
                for (i = 0; i <= j; ++i) \
                    *(px1++) = *(px0 + PACKED_AR21_LO(j, i, n2)); \
        } \
    } while (0)
TRY_INCREMENT
#define TRY_INCREMENT (_LABEL_)
Value:
    do { \
        if ((s >= 0) \
            ? ( t <= MATRIX_INT_FAST64_MAX - s) \
            : (-t <= s - MATRIX_INT_FAST64_MIN)) { \
            s += t; \
            t = 0; \
            count = 0; \
        } else { \
            over = 1; \
            goto _LABEL_; \
        } \
    } while (0)
Definition at line 1696 of file dense.c.
Function Documentation
dense_band()
SEXP dense_band (SEXP from, const char * class, int a, int b)
Definition at line 5 of file dense.c.
References BAND1, BAND2, BAND_CASES, cl, DCPY1, DCPY2, dense_as_general(), dense_transpose(), GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, and set_symmetrized_DimNames().
Referenced by R_dense_band().
dense_colsum()
static void dense_colsum (SEXP x, const char * class, int m, int n, char ul, char di, int narm, int mean, SEXP res) static
Definition at line 1430 of file dense.c.
References SUM_CASES.
Referenced by dense_marginsum().
dense_diag_get()
SEXP dense_diag_get (SEXP obj, const char * class, int names)
Definition at line 226 of file dense.c.
References DG_LOOP, equal_character_vectors(), GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, and Matrix_zone.
Referenced by R_dense_diag_get().
dense_diag_set()
SEXP dense_diag_set (SEXP from, const char * class, SEXP value, int new)
Definition at line 327 of file dense.c.
References DS_LOOP, GET_SLOT, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, newObject(), and SET_SLOT.
Referenced by R_dense_diag_set().
dense_force_symmetric()
SEXP dense_force_symmetric (SEXP from, const char * class, char ul)
Definition at line 585 of file dense.c.
References _, cl, conjugate(), DCPY, dense_transpose(), GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, and set_symmetrized_DimNames().
Referenced by R_dense_force_symmetric().
dense_is_diagonal()
int dense_is_diagonal (SEXP obj, const char * class)
Definition at line 1256 of file dense.c.
References GET_SLOT, ID_LOOP, ISNZ_COMPLEX, ISNZ_INTEGER, ISNZ_LOGICAL, ISNZ_PATTERN, ISNZ_REAL, Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
Referenced by dense_is_symmetric(), dense_is_triangular(), and R_dense_is_diagonal().
dense_is_symmetric()
int dense_is_symmetric (SEXP obj, const char * class, int checkDN)
Definition at line 1026 of file dense.c.
References dense_is_diagonal(), DimNames_is_symmetric(), GET_SLOT, IS_LOOP, Matrix_DimNamesSym, Matrix_DimSym, Matrix_xSym, NOTCONJ_COMPLEX, NOTCONJ_INTEGER, NOTCONJ_LOGICAL, NOTCONJ_PATTERN, NOTCONJ_REAL, NOTREAL_COMPLEX, NOTREAL_INTEGER, NOTREAL_LOGICAL, NOTREAL_PATTERN, and NOTREAL_REAL.
Referenced by R_dense_is_symmetric().
dense_is_triangular()
int dense_is_triangular (SEXP obj, const char * class, int upper)
Definition at line 1114 of file dense.c.
References dense_is_diagonal(), GET_SLOT, ISNZ_COMPLEX, ISNZ_INTEGER, ISNZ_LOGICAL, ISNZ_PATTERN, ISNZ_REAL, IT_LOOP, Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
Referenced by R_dense_is_triangular().
dense_marginsum()
SEXP dense_marginsum (SEXP obj, const char * class, int margin, int narm, int mean)
Definition at line 1627 of file dense.c.
References dense_colsum(), dense_rowsum(), GET_SLOT, get_symmetrized_DimNames(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, and SUM_TYPEOF.
Referenced by R_dense_marginsum().
dense_prod()
SEXP dense_prod (SEXP obj, const char * class, int narm)
Definition at line 1939 of file dense.c.
References GET_SLOT, LONGDOUBLE_AS_DOUBLE, Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, and PROD_LOOP.
Referenced by R_dense_prod().
dense_rowsum()
static void dense_rowsum (SEXP x, const char * class, int m, int n, char ul, char di, int narm, int mean, SEXP res) static
Definition at line 1524 of file dense.c.
References Matrix_Calloc, Matrix_Free, and SUM_CASES.
Referenced by dense_marginsum().
dense_skewpart()
SEXP dense_skewpart (SEXP from, const char * class)
Definition at line 859 of file dense.c.
References _, ASSIGN_COMPLEX, ASSIGN_REAL, cl, dense_as_kind(), GET_SLOT, INCREMENT_COMPLEX, INCREMENT_REAL, Matrix_DimNamesSym, Matrix_DimSym, Matrix_memset(), Matrix_pSym, Matrix_uploSym, Matrix_xSym, Matrix_zzero, newObject(), SET_SLOT, set_symmetrized_DimNames(), SP_LOOP, and zeroRe().
Referenced by R_dense_skewpart().
dense_sum()
SEXP dense_sum (SEXP obj, const char * class, int narm)
Definition at line 1713 of file dense.c.
References GET_SLOT, LONGDOUBLE_AS_DOUBLE, Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, SUM_LOOP, and TRY_INCREMENT.
Referenced by R_dense_sum().
dense_symmpart()
SEXP dense_symmpart (SEXP from, const char * class)
Definition at line 707 of file dense.c.
References _, cl, dense_as_kind(), GET_SLOT, INCREMENT_COMPLEX, INCREMENT_REAL, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, Matrix_zone, newObject(), SCALE1_COMPLEX, SCALE1_REAL, SET_SLOT, set_symmetrized_DimNames(), SP_LOOP, and zeroIm().
Referenced by R_dense_symmpart().
dense_transpose()
SEXP dense_transpose (SEXP from, const char * class)
Definition at line 466 of file dense.c.
References GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_sdSym, Matrix_uploSym, Matrix_xSym, newObject(), set_reversed_DimNames(), SET_SLOT, and TRANS_LOOP.
Referenced by dense_band(), dense_force_symmetric(), R_dense_transpose(), and R_diagonal_matmult().
R_dense_band()
SEXP R_dense_band (SEXP from, SEXP k1, SEXP k2)
Definition at line 189 of file dense.c.
References _, dense_band(), ERROR_INVALID_CLASS, GET_SLOT, matrix_as_dense(), Matrix_DimSym, valid, and VALID_DENSE.
R_dense_diag_get()
SEXP R_dense_diag_get (SEXP obj, SEXP names)
Definition at line 312 of file dense.c.
References _, dense_diag_get(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_diag_set()
SEXP R_dense_diag_set (SEXP from, SEXP value)
Definition at line 411 of file dense.c.
References _, dense_as_kind(), dense_diag_set(), ERROR_INVALID_CLASS, GET_SLOT, kindToType(), Matrix_DimSym, typeToKind(), valid, and VALID_DENSE.
R_dense_force_symmetric()
SEXP R_dense_force_symmetric (SEXP from, SEXP uplo)
Definition at line 689 of file dense.c.
References _, dense_force_symmetric(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_is_diagonal()
SEXP R_dense_is_diagonal (SEXP obj)
Definition at line 1360 of file dense.c.
References dense_is_diagonal(), ERROR_INVALID_CLASS, matrix_as_dense(), valid, and VALID_DENSE.
R_dense_is_symmetric()
SEXP R_dense_is_symmetric (SEXP obj, SEXP checkDN)
Definition at line 1091 of file dense.c.
References _, dense_is_symmetric(), ERROR_INVALID_CLASS, matrix_as_dense(), valid, and VALID_DENSE.
R_dense_is_triangular()
SEXP R_dense_is_triangular (SEXP obj, SEXP upper)
Definition at line 1223 of file dense.c.
References _, dense_is_triangular(), ERROR_INVALID_CLASS, matrix_as_dense(), valid, and VALID_DENSE.
R_dense_marginsum()
SEXP R_dense_marginsum (SEXP obj, SEXP margin, SEXP narm, SEXP mean)
Definition at line 1667 of file dense.c.
References _, dense_marginsum(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_prod()
SEXP R_dense_prod (SEXP obj, SEXP narm)
Definition at line 2119 of file dense.c.
References _, dense_prod(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_skewpart()
SEXP R_dense_skewpart (SEXP from)
Definition at line 1016 of file dense.c.
References dense_skewpart(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_sum()
SEXP R_dense_sum (SEXP obj, SEXP narm)
Definition at line 1924 of file dense.c.
References _, dense_sum(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_symmpart()
SEXP R_dense_symmpart (SEXP from)
Definition at line 849 of file dense.c.
References dense_symmpart(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.
R_dense_transpose()
SEXP R_dense_transpose (SEXP from)
Definition at line 573 of file dense.c.
References dense_transpose(), ERROR_INVALID_CLASS, valid, and VALID_DENSE.