Matrix: determinant.c File Reference
determinant.c File Reference
#include "cholmod-etc.h"
#include "Mdefines.h"
#include <Rmath.h>
Macros
#define DETERMINANT_START(_F_)
Functions
static SEXP det (double modulus, int logarithm, int sign)
SEXP denseLU_determinant (SEXP s_trf, SEXP s_logarithm)
SEXP denseBunchKaufman_determinant (SEXP s_trf, SEXP s_logarithm)
SEXP denseCholesky_determinant (SEXP s_trf, SEXP s_logarithm)
SEXP sparseQR_determinant (SEXP orf, SEXP s_logarithm)
SEXP sparseLU_determinant (SEXP s_trf, SEXP s_logarithm)
SEXP sparseCholesky_determinant (SEXP s_trf, SEXP s_logarithm, SEXP s_root)
Macro Definition Documentation
DETERMINANT_START
#define DETERMINANT_START (_F_)
Value:
    int *pdim = DIM(_F_), n = pdim[1]; \
    if (pdim[0] != n) \
        Rf_error(_("matrix is not square")); \
    int givelog = Rf_asLogical(s_logarithm); \
    double modulus = 0.0; /* result for n == 0 */
Referenced by denseBunchKaufman_determinant(), denseCholesky_determinant(), denseLU_determinant(), sparseCholesky_determinant(), sparseLU_determinant(), and sparseQR_determinant().
Function Documentation
denseBunchKaufman_determinant()
SEXP denseBunchKaufman_determinant (SEXP s_trf, SEXP s_logarithm)
Definition at line 76 of file determinant.c.
References c, det(), DETERMINANT_START, GET_SLOT, Matrix_permSym, Matrix_xSym, TRANS, TYPEOF, and UPLO.
denseCholesky_determinant()
SEXP denseCholesky_determinant (SEXP s_trf, SEXP s_logarithm)
Definition at line 196 of file determinant.c.
References det(), DETERMINANT_START, GET_SLOT, Matrix_xSym, TYPEOF, and UPLO.
denseLU_determinant()
SEXP denseLU_determinant (SEXP s_trf, SEXP s_logarithm)
Definition at line 28 of file determinant.c.
References det(), DETERMINANT_START, GET_SLOT, Matrix_permSym, Matrix_xSym, and TYPEOF.
det()
static SEXP det (double modulus, int logarithm, int sign) static
Definition at line 8 of file determinant.c.
References Matrix_logarithmSym.
Referenced by denseBunchKaufman_determinant(), denseCholesky_determinant(), denseLU_determinant(), sparseCholesky_determinant(), sparseLU_determinant(), and sparseQR_determinant().
sparseCholesky_determinant()
SEXP sparseCholesky_determinant (SEXP s_trf, SEXP s_logarithm, SEXP s_root)
Definition at line 359 of file determinant.c.
References det(), DETERMINANT_START, and M2CHF().
sparseLU_determinant()
SEXP sparseLU_determinant (SEXP s_trf, SEXP s_logarithm)
Definition at line 298 of file determinant.c.
References det(), DETERMINANT_START, GET_SLOT, Matrix_iSym, Matrix_pSym, Matrix_qSym, Matrix_USym, Matrix_xSym, signPerm(), and TYPEOF.
sparseQR_determinant()
SEXP sparseQR_determinant (SEXP orf, SEXP s_logarithm)
Definition at line 228 of file determinant.c.
References _, det(), DETERMINANT_START, DIM, GET_SLOT, Matrix_iSym, Matrix_pSym, Matrix_qSym, Matrix_RSym, Matrix_xSym, signPerm(), and TYPEOF.