Matrix: determinant.h File Reference
determinant.h File Reference
#include <Rinternals.h>
Functions
SEXP denseLU_determinant (SEXP, SEXP)
SEXP BunchKaufman_determinant (SEXP, SEXP)
SEXP Cholesky_determinant (SEXP, SEXP)
SEXP sparseLU_determinant (SEXP, SEXP)
SEXP sparseQR_determinant (SEXP, SEXP)
SEXP CHMfactor_determinant (SEXP, SEXP, SEXP)
Function Documentation
BunchKaufman_determinant()
SEXP BunchKaufman_determinant (SEXP obj, SEXP logarithm)
Definition at line 75 of file determinant.c.
References c, DETERMINANT_START, GET_SLOT, Matrix_permSym, Matrix_uploSym, Matrix_xSym, and mkDet().
CHMfactor_determinant()
SEXP CHMfactor_determinant (SEXP obj, SEXP logarithm, SEXP sqrt)
Definition at line 332 of file determinant.c.
References DETERMINANT_START, M2CHF(), and mkDet().
Cholesky_determinant()
SEXP Cholesky_determinant (SEXP obj, SEXP logarithm)
Definition at line 168 of file determinant.c.
References DETERMINANT_START, GET_SLOT, Matrix_uploSym, Matrix_xSym, and mkDet().
denseLU_determinant()
SEXP denseLU_determinant (SEXP obj, SEXP logarithm)
Definition at line 26 of file determinant.c.
References DETERMINANT_START, GET_SLOT, Matrix_permSym, Matrix_xSym, and mkDet().
sparseLU_determinant()
SEXP sparseLU_determinant (SEXP obj, SEXP logarithm)
Definition at line 207 of file determinant.c.
References DETERMINANT_START, GET_SLOT, Matrix_iSym, Matrix_pSym, Matrix_qSym, Matrix_USym, Matrix_xSym, mkDet(), and signPerm().
sparseQR_determinant()
SEXP sparseQR_determinant (SEXP obj, SEXP logarithm)
Definition at line 266 of file determinant.c.
References _, DETERMINANT_START, GET_SLOT, Matrix_DimSym, Matrix_iSym, Matrix_pSym, Matrix_qSym, Matrix_RSym, Matrix_xSym, mkDet(), and signPerm().