Matrix: dgCMatrix.c File Reference
dgCMatrix.c File Reference
#include "dgCMatrix.h"
#include "Csparse.h"
#include "chm_common.h"
#include "t_gCMatrix_colSums.c"
Macros
#define _dgC_
#define _igC_
#define _lgC_
#define _lgC_mn
#define _ngC_
#define _ngC_mn
Functions
SEXP compressed_non_0_ij (SEXP x, SEXP colP)
Return a 2 column matrix '' cbind(i, j) '' of 0-origin index vectors (i,j) which entirely correspond to the (i,j) slots of as(x, "TsparseMatrix") :
SEXP compressed_to_TMatrix (SEXP x, SEXP colP)
SEXP dgCMatrix_cholsol (SEXP x, SEXP y)
SEXP dgCMatrix_LU (SEXP Ap, SEXP orderp, SEXP tolp, SEXP error_on_sing, SEXP keep_dimnames)
SEXP dgCMatrix_matrix_solve (SEXP Ap, SEXP b, SEXP give_sparse)
SEXP dgCMatrix_QR (SEXP Ap, SEXP order, SEXP keep_dimnames)
SEXP dgCMatrix_qrsol (SEXP x, SEXP y, SEXP ord)
void install_lu (SEXP Ap, int order, double tol, Rboolean err_sing, Rboolean keep_dimnms)
SEXP lgCMatrix_colSums (SEXP x, SEXP NArm, SEXP spRes, SEXP trans, SEXP means)
SEXP ngCMatrix_colSums (SEXP x, SEXP NArm, SEXP spRes, SEXP trans, SEXP means)
SEXP R_to_CMatrix (SEXP x)
SEXP xCMatrix_validate (SEXP x)
SEXP xRMatrix_validate (SEXP x)
Macro Definition Documentation
#define _dgC_
Definition at line 593 of file dgCMatrix.c.
#define _igC_
Definition at line 596 of file dgCMatrix.c.
#define _lgC_
Definition at line 599 of file dgCMatrix.c.
#define _lgC_mn
Definition at line 605 of file dgCMatrix.c.
#define _ngC_
Definition at line 602 of file dgCMatrix.c.
#define _ngC_mn
Definition at line 608 of file dgCMatrix.c.
Function Documentation
SEXP compressed_non_0_ij (SEXP x, SEXP colP)
Return a 2 column matrix '' cbind(i, j) '' of 0-origin index vectors (i,j) which entirely correspond to the (i,j) slots of as(x, "TsparseMatrix") :
Definition at line 122 of file dgCMatrix.c.
References expand_cmprPt(), Matrix_DimSym, Matrix_iSym, Matrix_jSym, and Matrix_pSym.
SEXP compressed_to_TMatrix (SEXP x, SEXP colP)
Definition at line 36 of file dgCMatrix.c.
References _, ALLOC_SLOT(), class_P, expand_cmprPt(), Matrix_diagSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, MATRIX_VALID_Csparse, MATRIX_VALID_Rsparse, Matrix_xSym, SET_DimNames(), and slot_dup.
SEXP dgCMatrix_cholsol (SEXP x, SEXP y)
Definition at line 523 of file dgCMatrix.c.
References _, AS_CHM_DN, AS_CHM_SP, c, and chm_factor_to_SEXP().
SEXP dgCMatrix_LU (SEXP Ap, SEXP orderp, SEXP tolp, SEXP error_on_sing, SEXP keep_dimnames)
Definition at line 446 of file dgCMatrix.c.
References _, get_factors(), and install_lu().
SEXP dgCMatrix_matrix_solve (SEXP Ap, SEXP b, SEXP give_sparse)
Definition at line 467 of file dgCMatrix.c.
References _, AS_CSP__, C_or_Alloca_TO, cs_ipvec(), cs_lsolve(), cs_pvec(), cs_usolve(), dup_mMatrix_as_dgeMatrix(), get_factors(), install_lu(), Matrix_DimSym, Matrix_pSym, Matrix_xSym, cs_sparse::n, and SMALL_4_Alloca.
SEXP dgCMatrix_QR (SEXP Ap, SEXP order, SEXP keep_dimnames)
Definition at line 214 of file dgCMatrix.c.
References _, ALLOC_SLOT(), AS_CSP__, cs_numeric::B, cs_dropzeros(), cs_free(), cs_nfree(), cs_pinv(), cs_qr(), cs_sfree(), cs_spfree(), cs_sqr(), cs_transpose(), cs_numeric::L, cs_sparse::m, cs_symbolic::m2, Matrix_betaSym, Matrix_cs_to_SEXP(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_pSym, Matrix_VSym, cs_sparse::n, cs_symbolic::pinv, cs_symbolic::q, and cs_numeric::U.
SEXP dgCMatrix_qrsol (SEXP x, SEXP y, SEXP ord)
Definition at line 169 of file dgCMatrix.c.
References _, AS_CSP, cs_qrsol(), cs_sparse::m, and cs_sparse::n.
void install_lu (SEXP Ap, int order, double tol, Rboolean err_sing, Rboolean keep_dimnms)
Definition at line 354 of file dgCMatrix.c.
References _, ALLOC_SLOT(), AS_CSP__, cs_dropzeros(), cs_free(), cs_lu(), cs_nfree(), cs_pinv(), cs_sfree(), cs_spfree(), cs_sqr(), cs_transpose(), cs_numeric::L, cs_sparse::m, Matrix_cs_to_SEXP(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_pSym, cs_sparse::n, cs_numeric::pinv, cs_symbolic::q, set_factors(), and cs_numeric::U.
Referenced by dgCMatrix_LU(), and dgCMatrix_matrix_solve().
SEXP lgCMatrix_colSums (SEXP x, SEXP NArm, SEXP spRes, SEXP trans, SEXP means)
Definition at line 612 of file dgCMatrix.c.
SEXP ngCMatrix_colSums (SEXP x, SEXP NArm, SEXP spRes, SEXP trans, SEXP means)
Definition at line 620 of file dgCMatrix.c.
SEXP R_to_CMatrix (SEXP x)
Definition at line 76 of file dgCMatrix.c.
References _, ALLOC_SLOT(), class_P, Csparse_transpose(), Matrix_diagSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, MATRIX_VALID_Rsparse, Matrix_xSym, SET_DimNames(), slot_dup, and uplo_P.
SEXP xCMatrix_validate (SEXP x)
Definition at line 11 of file dgCMatrix.c.
References _, Matrix_iSym, and Matrix_xSym.
Referenced by tCMatrix_validate().
SEXP xRMatrix_validate (SEXP x)
Definition at line 23 of file dgCMatrix.c.
References _, Matrix_jSym, and Matrix_xSym.
Referenced by tRMatrix_validate().