Matrix: dgCMatrix.h File Reference
dgCMatrix.h File Reference
#include <R_ext/BLAS.h>
#include "Mutils.h"
#include "cs_utils.h"
Functions
SEXP compressed_non_0_ij (SEXP x, SEXP colP)
Return a 2 column matrix '' cbind(i, j) '' of 0-origin index vectors (i,j) which entirely correspond to the (i,j) slots of as(x, "TsparseMatrix") :
SEXP compressed_to_TMatrix (SEXP x, SEXP colP)
SEXP dgCMatrix_cholsol (SEXP x, SEXP y)
SEXP dgCMatrix_colSums (SEXP x, SEXP NArm, SEXP spRes, SEXP trans, SEXP means)
SEXP dgCMatrix_LU (SEXP Ap, SEXP orderp, SEXP tolp, SEXP error_on_sing, SEXP keep_dimnames)
SEXP dgCMatrix_matrix_solve (SEXP Ap, SEXP bp, SEXP give_sparse)
SEXP dgCMatrix_QR (SEXP Ap, SEXP order, SEXP keep_dimnames)
SEXP dgCMatrix_qrsol (SEXP x, SEXP y, SEXP ord)
SEXP igCMatrix_colSums (SEXP x, SEXP NArm, SEXP spRes, SEXP trans, SEXP means)
SEXP lgCMatrix_colSums (SEXP x, SEXP NArm, SEXP spRes, SEXP trans, SEXP means)
SEXP ngCMatrix_colSums (SEXP x, SEXP NArm, SEXP spRes, SEXP trans, SEXP means)
SEXP R_to_CMatrix (SEXP x)
SEXP xCMatrix_validate (SEXP x)
SEXP xRMatrix_validate (SEXP x)
Function Documentation
compressed_non_0_ij()
SEXP compressed_non_0_ij (SEXP x, SEXP colP)
Return a 2 column matrix '' cbind(i, j) '' of 0-origin index vectors (i,j) which entirely correspond to the (i,j) slots of as(x, "TsparseMatrix") :
Definition at line 129 of file dgCMatrix.c.
References expand_cmprPt(), Matrix_DimSym, Matrix_iSym, Matrix_jSym, and Matrix_pSym.
compressed_to_TMatrix()
SEXP compressed_to_TMatrix (SEXP x, SEXP colP)
Definition at line 43 of file dgCMatrix.c.
References _, ALLOC_SLOT(), class_P, expand_cmprPt(), Matrix_diagSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, MATRIX_VALID_Csparse, MATRIX_VALID_Rsparse, Matrix_xSym, NEW_OBJECT_OF_CLASS(), SET_DimNames(), and slot_dup.
dgCMatrix_cholsol()
SEXP dgCMatrix_cholsol (SEXP x, SEXP y)
Definition at line 532 of file dgCMatrix.c.
References _, AS_CHM_DN, AS_CHM_SP, c, and chm_factor_to_SEXP().
dgCMatrix_colSums()
SEXP dgCMatrix_colSums (SEXP x, SEXP NArm, SEXP spRes, SEXP trans, SEXP means)
dgCMatrix_LU()
SEXP dgCMatrix_LU (SEXP Ap, SEXP orderp, SEXP tolp, SEXP error_on_sing, SEXP keep_dimnames)
Definition at line 454 of file dgCMatrix.c.
References _, get_factors(), and install_lu().
dgCMatrix_matrix_solve()
SEXP dgCMatrix_matrix_solve (SEXP Ap, SEXP bp, SEXP give_sparse)
Definition at line 475 of file dgCMatrix.c.
References _, AS_CSP__, C_or_Alloca_TO, cs_ipvec(), cs_lsolve(), cs_pvec(), cs_usolve(), dup_mMatrix_as_dgeMatrix(), get_factors(), install_lu(), Matrix_DimSym, Matrix_LSym, Matrix_pSym, Matrix_USym, Matrix_xSym, cs_sparse::n, and SMALL_4_Alloca.
dgCMatrix_QR()
SEXP dgCMatrix_QR (SEXP Ap, SEXP order, SEXP keep_dimnames)
Definition at line 221 of file dgCMatrix.c.
References _, ALLOC_SLOT(), AS_CSP__, cs_numeric::B, cs_dropzeros(), cs_free(), cs_nfree(), cs_pinv(), cs_qr(), cs_sfree(), cs_spfree(), cs_sqr(), cs_transpose(), cs_numeric::L, cs_sparse::m, cs_symbolic::m2, Matrix_betaSym, Matrix_cs_to_SEXP(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_pSym, Matrix_RSym, Matrix_VSym, cs_sparse::n, NEW_OBJECT_OF_CLASS(), cs_symbolic::pinv, cs_symbolic::q, and cs_numeric::U.
dgCMatrix_qrsol()
SEXP dgCMatrix_qrsol (SEXP x, SEXP y, SEXP ord)
Definition at line 176 of file dgCMatrix.c.
References _, AS_CSP, cs_qrsol(), cs_sparse::m, and cs_sparse::n.
igCMatrix_colSums()
SEXP igCMatrix_colSums (SEXP x, SEXP NArm, SEXP spRes, SEXP trans, SEXP means)
lgCMatrix_colSums()
SEXP lgCMatrix_colSums (SEXP x, SEXP NArm, SEXP spRes, SEXP trans, SEXP means)
Definition at line 622 of file dgCMatrix.c.
ngCMatrix_colSums()
SEXP ngCMatrix_colSums (SEXP x, SEXP NArm, SEXP spRes, SEXP trans, SEXP means)
Definition at line 630 of file dgCMatrix.c.
R_to_CMatrix()
SEXP R_to_CMatrix (SEXP x)
Definition at line 83 of file dgCMatrix.c.
References _, ALLOC_SLOT(), class_P, Csparse_transpose(), Matrix_diagSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, MATRIX_VALID_Rsparse, Matrix_xSym, NEW_OBJECT_OF_CLASS(), SET_DimNames(), slot_dup, and uplo_P.
xCMatrix_validate()
SEXP xCMatrix_validate (SEXP x)
Definition at line 18 of file dgCMatrix.c.
References _, Matrix_iSym, and Matrix_xSym.
Referenced by tCMatrix_validate().
xRMatrix_validate()
SEXP xRMatrix_validate (SEXP x)
Definition at line 30 of file dgCMatrix.c.
References _, Matrix_jSym, and Matrix_xSym.
Referenced by tRMatrix_validate().