Matrix: dgeMatrix.h File Reference
dgeMatrix.h File Reference
#include <R_ext/Boolean.h>
#include "Lapack-etc.h"
#include "Mutils.h"
Functions
SEXP dgeMatrix_addDiag (SEXP x, SEXP d)
SEXP dgeMatrix_colsums (SEXP x, SEXP naRmP, SEXP cols, SEXP mean)
SEXP dgeMatrix_crossprod (SEXP x, SEXP trans)
SEXP dgeMatrix_determinant (SEXP x, SEXP logarithm)
SEXP dgeMatrix_dgeMatrix_crossprod (SEXP x, SEXP y, SEXP trans)
SEXP dgeMatrix_exp (SEXP x)
Matrix exponential - based on the corrected code for Octave's expm function.
SEXP dgeMatrix_getDiag (SEXP x)
SEXP dgeMatrix_LU (SEXP x, SEXP warn_singularity)
SEXP dgeMatrix_LU_ (SEXP x, Rboolean warn_sing)
SEXP dgeMatrix_matrix_crossprod (SEXP x, SEXP y, SEXP trans)
SEXP dgeMatrix_matrix_mm (SEXP a, SEXP b, SEXP right)
SEXP dgeMatrix_matrix_solve (SEXP a, SEXP b)
SEXP dgeMatrix_norm (SEXP obj, SEXP norm)
SEXP dgeMatrix_rcond (SEXP obj, SEXP type)
SEXP dgeMatrix_Schur (SEXP x, SEXP vectors, SEXP isDGE)
SEXP dgeMatrix_setDiag (SEXP x, SEXP d)
SEXP dgeMatrix_solve (SEXP a)
SEXP dgeMatrix_svd (SEXP x, SEXP nu, SEXP nv)
SEXP dgeMatrix_validate (SEXP obj)
SEXP dMatrix_validate (SEXP obj)
SEXP geMatrix_crossprod (SEXP x, SEXP trans)
SEXP geMatrix_geMatrix_crossprod (SEXP x, SEXP y, SEXP trans)
SEXP geMatrix_matrix_crossprod (SEXP x, SEXP y, SEXP trans)
SEXP geMatrix_matrix_mm (SEXP a, SEXP b, SEXP right)
%*% – generalized from dge to *ge():
SEXP lgeMatrix_getDiag (SEXP x)
SEXP lgeMatrix_setDiag (SEXP x, SEXP d)
Function Documentation
dgeMatrix_addDiag()
SEXP dgeMatrix_addDiag (SEXP x, SEXP d)
Definition at line 450 of file dgeMatrix.c.
References _, Matrix_DimSym, and Matrix_xSym.
dgeMatrix_colsums()
SEXP dgeMatrix_colsums (SEXP x, SEXP naRmP, SEXP cols, SEXP mean)
Definition at line 850 of file dgeMatrix.c.
References C_or_Alloca_TO, Matrix_DimNamesSym, Matrix_DimSym, Matrix_xSym, and SMALL_4_Alloca.
dgeMatrix_crossprod()
SEXP dgeMatrix_crossprod (SEXP x, SEXP trans)
Definition at line 76 of file dgeMatrix.c.
References DGE_CROSS_1, DGE_CROSS_DO, and Matrix_xSym.
dgeMatrix_determinant()
SEXP dgeMatrix_determinant (SEXP x, SEXP logarithm)
Definition at line 506 of file dgeMatrix.c.
References _, as_det_obj(), dgeMatrix_LU_(), Matrix_DimSym, Matrix_permSym, and Matrix_xSym.
dgeMatrix_dgeMatrix_crossprod()
SEXP dgeMatrix_dgeMatrix_crossprod (SEXP x, SEXP y, SEXP trans)
Definition at line 146 of file dgeMatrix.c.
References DGE_DGE_CROSS_1, DGE_DGE_CROSS_DO, and Matrix_xSym.
dgeMatrix_exp()
SEXP dgeMatrix_exp (SEXP x)
Matrix exponential - based on the corrected code for Octave's expm function.
Parameters
x real square matrix to exponentiate
Returns
matrix exponential of x
Definition at line 668 of file dgeMatrix.c.
References _, AZERO, FCONE, Matrix_DimSym, Matrix_xSym, padec, and RE_PERMUTE.
dgeMatrix_getDiag()
SEXP dgeMatrix_getDiag (SEXP x)
Definition at line 375 of file dgeMatrix.c.
References geMatrix_getDiag_1, and geMatrix_getDiag_2.
dgeMatrix_LU()
SEXP dgeMatrix_LU (SEXP x, SEXP warn_singularity)
Definition at line 501 of file dgeMatrix.c.
References dgeMatrix_LU_().
dgeMatrix_LU_()
SEXP dgeMatrix_LU_ (SEXP x, Rboolean warn_sing)
Definition at line 470 of file dgeMatrix.c.
References _, ALLOC_SLOT(), get_factors(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_permSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), set_factors(), and slot_dup.
Referenced by dgeMatrix_determinant(), dgeMatrix_LU(), dgeMatrix_matrix_solve(), dgeMatrix_rcond(), and dgeMatrix_solve().
dgeMatrix_matrix_crossprod()
SEXP dgeMatrix_matrix_crossprod (SEXP x, SEXP y, SEXP trans)
Definition at line 212 of file dgeMatrix.c.
References DGE_MAT_CROSS_1, DGE_MAT_CROSS_DO, and Matrix_xSym.
dgeMatrix_matrix_mm()
SEXP dgeMatrix_matrix_mm (SEXP a, SEXP b, SEXP right)
Definition at line 300 of file dgeMatrix.c.
References DGE_MAT_MM_1, DGE_MAT_MM_DO, Matrix_xSym, and mMatrix_as_dgeMatrix().
dgeMatrix_matrix_solve()
SEXP dgeMatrix_matrix_solve (SEXP a, SEXP b)
Definition at line 587 of file dgeMatrix.c.
References _, dgeMatrix_LU_(), dup_mMatrix_as_dgeMatrix(), FCONE, Matrix_DimSym, Matrix_permSym, and Matrix_xSym.
dgeMatrix_norm()
SEXP dgeMatrix_norm (SEXP obj, SEXP norm)
Definition at line 49 of file dgeMatrix.c.
References get_norm().
dgeMatrix_rcond()
SEXP dgeMatrix_rcond (SEXP obj, SEXP type)
Definition at line 54 of file dgeMatrix.c.
References _, dgeMatrix_LU_(), FCONE, get_norm(), La_rcond_type(), Matrix_DimSym, and Matrix_xSym.
dgeMatrix_Schur()
SEXP dgeMatrix_Schur (SEXP x, SEXP vectors, SEXP isDGE)
Definition at line 801 of file dgeMatrix.c.
References _, C_or_Alloca_TO, FCONE, Matrix_DimSym, Matrix_xSym, and SMALL_4_Alloca.
dgeMatrix_setDiag()
SEXP dgeMatrix_setDiag (SEXP x, SEXP d)
Definition at line 413 of file dgeMatrix.c.
References geMatrix_setDiag_1, and geMatrix_setDiag_2.
dgeMatrix_solve()
SEXP dgeMatrix_solve (SEXP a)
Definition at line 539 of file dgeMatrix.c.
References _, dgeMatrix_LU_(), FCONE, get_norm(), Matrix_DimSym, Matrix_permSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), and slot_dup.
dgeMatrix_svd()
SEXP dgeMatrix_svd (SEXP x, SEXP nu, SEXP nv)
Definition at line 608 of file dgeMatrix.c.
References _, C_or_Alloca_TO, FCONE, Matrix_DimSym, Matrix_xSym, and SMALL_4_Alloca.
dgeMatrix_validate()
SEXP dgeMatrix_validate (SEXP obj)
Definition at line 16 of file dgeMatrix.c.
References _, dense_nonpacked_validate(), dim_validate(), Matrix_DimSym, and Matrix_factorSym.
dMatrix_validate()
SEXP dMatrix_validate (SEXP obj)
Definition at line 4 of file dgeMatrix.c.
References _, dim_validate(), Matrix_DimSym, and Matrix_xSym.
geMatrix_crossprod()
SEXP geMatrix_crossprod (SEXP x, SEXP trans)
Definition at line 138 of file dgeMatrix.c.
References _geMatrix_crossprod(), and dup_mMatrix_as_geMatrix().
geMatrix_geMatrix_crossprod()
SEXP geMatrix_geMatrix_crossprod (SEXP x, SEXP y, SEXP trans)
Definition at line 203 of file dgeMatrix.c.
References _geMatrix__geMatrix_crossprod(), and dup_mMatrix_as_geMatrix().
geMatrix_matrix_crossprod()
SEXP geMatrix_matrix_crossprod (SEXP x, SEXP y, SEXP trans)
Definition at line 292 of file dgeMatrix.c.
References _geMatrix_matrix_crossprod(), and dup_mMatrix_as_geMatrix().
geMatrix_matrix_mm()
SEXP geMatrix_matrix_mm (SEXP a, SEXP b, SEXP right)
%*% – generalized from dge to *ge():
Definition at line 364 of file dgeMatrix.c.
References _geMatrix_matrix_mm(), and dup_mMatrix_as_geMatrix().
lgeMatrix_getDiag()
SEXP lgeMatrix_getDiag (SEXP x)
Definition at line 398 of file dgeMatrix.c.
References geMatrix_getDiag_1, and geMatrix_getDiag_2.
lgeMatrix_setDiag()
SEXP lgeMatrix_setDiag (SEXP x, SEXP d)
Definition at line 439 of file dgeMatrix.c.
References geMatrix_setDiag_1, and geMatrix_setDiag_2.