Matrix: dpoMatrix.c File Reference
dpoMatrix.c File Reference
#include "dpoMatrix.h"
Functions
SEXP dpoMatrix_chol (SEXP x)
SEXP dpoMatrix_dgeMatrix_solve (SEXP a, SEXP b)
SEXP dpoMatrix_matrix_solve (SEXP a, SEXP b)
SEXP dpoMatrix_rcond (SEXP obj, SEXP type)
SEXP dpoMatrix_solve (SEXP x)
SEXP dpoMatrix_validate (SEXP obj)
Function Documentation
dpoMatrix_chol()
SEXP dpoMatrix_chol (SEXP x)
Definition at line 20 of file dpoMatrix.c.
References _, ALLOC_SLOT(), AZERO, FCONE, get_factors(), Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), and set_factors().
Referenced by dpoMatrix_dgeMatrix_solve(), dpoMatrix_matrix_solve(), dpoMatrix_rcond(), dpoMatrix_solve(), and R_init_Matrix().
dpoMatrix_dgeMatrix_solve()
SEXP dpoMatrix_dgeMatrix_solve (SEXP a, SEXP b)
Definition at line 88 of file dpoMatrix.c.
References _, dpoMatrix_chol(), FCONE, Matrix_DimSym, Matrix_factorSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), slot_dup, and uplo_P.
dpoMatrix_matrix_solve()
SEXP dpoMatrix_matrix_solve (SEXP a, SEXP b)
Definition at line 111 of file dpoMatrix.c.
References _, dpoMatrix_chol(), FCONE, Matrix_DimSym, Matrix_xSym, and uplo_P.
dpoMatrix_rcond()
SEXP dpoMatrix_rcond (SEXP obj, SEXP type)
Definition at line 55 of file dpoMatrix.c.
References dpoMatrix_chol(), FCONE, get_norm_sy(), Matrix_DimSym, Matrix_xSym, and uplo_P.
dpoMatrix_solve()
SEXP dpoMatrix_solve (SEXP x)
Definition at line 70 of file dpoMatrix.c.
References dpoMatrix_chol(), FCONE, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), slot_dup, and uplo_P.
dpoMatrix_validate()
SEXP dpoMatrix_validate (SEXP obj)
Definition at line 3 of file dpoMatrix.c.
References _, dense_nonpacked_validate(), Matrix_DimSym, and Matrix_xSym.