Matrix: dpoMatrix.h File Reference
dpoMatrix.h File Reference
#include <R_ext/Lapack.h>
#include "Mutils.h"
Functions
SEXP dpoMatrix_chol (SEXP x)
SEXP dpoMatrix_dgeMatrix_solve (SEXP a, SEXP b)
SEXP dpoMatrix_matrix_solve (SEXP a, SEXP b)
SEXP dpoMatrix_rcond (SEXP obj, SEXP type)
SEXP dpoMatrix_solve (SEXP a)
SEXP dpoMatrix_validate (SEXP obj)
double get_norm_sy (SEXP obj, const char *typstr)
Function Documentation
SEXP dpoMatrix_chol (SEXP x)
Definition at line 16 of file dpoMatrix.c.
References _, ALLOC_SLOT(), AZERO, get_factors(), Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, and set_factors().
Referenced by dpoMatrix_dgeMatrix_solve(), dpoMatrix_matrix_solve(), dpoMatrix_rcond(), dpoMatrix_solve(), and R_init_Matrix().
SEXP dpoMatrix_dgeMatrix_solve (SEXP a, SEXP b)
Definition at line 82 of file dpoMatrix.c.
References _, dpoMatrix_chol(), Matrix_DimSym, Matrix_factorSym, Matrix_xSym, slot_dup, and uplo_P.
SEXP dpoMatrix_matrix_solve (SEXP a, SEXP b)
Definition at line 105 of file dpoMatrix.c.
References _, dpoMatrix_chol(), Matrix_DimSym, Matrix_xSym, and uplo_P.
SEXP dpoMatrix_rcond (SEXP obj, SEXP type)
Definition at line 49 of file dpoMatrix.c.
References dpoMatrix_chol(), get_norm_sy(), Matrix_DimSym, Matrix_xSym, and uplo_P.
SEXP dpoMatrix_solve (SEXP a)
Definition at line 64 of file dpoMatrix.c.
References dpoMatrix_chol(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorSym, Matrix_uploSym, Matrix_xSym, slot_dup, and uplo_P.
SEXP dpoMatrix_validate (SEXP obj)
Definition at line 3 of file dpoMatrix.c.
References _, Matrix_DimSym, and Matrix_xSym.
double get_norm_sy (SEXP obj, const char * typstr)
Definition at line 21 of file dsyMatrix.c.
Referenced by dpoMatrix_rcond(), dsyMatrix_norm(), and dsyMatrix_rcond().