Matrix: dppMatrix.h File Reference
dppMatrix.h File Reference
#include "Lapack-etc.h"
#include "Mutils.h"
#include "dspMatrix.h"
Functions
SEXP dppMatrix_chol (SEXP x)
SEXP dppMatrix_matrix_solve (SEXP a, SEXP b)
SEXP dppMatrix_rcond (SEXP obj, SEXP type)
SEXP dppMatrix_solve (SEXP a)
SEXP dppMatrix_validate (SEXP obj)
double get_norm_sp (SEXP obj, const char *typstr)
Function Documentation
dppMatrix_chol()
SEXP dppMatrix_chol (SEXP x)
Definition at line 15 of file dppMatrix.c.
References _, FCONE, get_factors(), Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), set_factors(), and slot_dup.
Referenced by dppMatrix_matrix_solve(), dppMatrix_rcond(), and dppMatrix_solve().
dppMatrix_matrix_solve()
SEXP dppMatrix_matrix_solve (SEXP a, SEXP b)
Definition at line 71 of file dppMatrix.c.
References _, dppMatrix_chol(), dup_mMatrix_as_dgeMatrix(), FCONE, Matrix_DimSym, Matrix_xSym, and uplo_P.
dppMatrix_rcond()
SEXP dppMatrix_rcond (SEXP obj, SEXP type)
Definition at line 42 of file dppMatrix.c.
References dppMatrix_chol(), FCONE, get_norm_sp(), Matrix_DimSym, Matrix_xSym, and uplo_P.
dppMatrix_solve()
SEXP dppMatrix_solve (SEXP a)
Definition at line 56 of file dppMatrix.c.
References dppMatrix_chol(), FCONE, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), slot_dup, and uplo_P.
dppMatrix_validate()
SEXP dppMatrix_validate (SEXP obj)
Definition at line 3 of file dppMatrix.c.
References dspMatrix_validate().
get_norm_sp()
double get_norm_sp (SEXP obj, const char * typstr)
Definition at line 18 of file dspMatrix.c.
References FCONE, La_norm_type(), Matrix_DimSym, Matrix_xSym, and uplo_P.
Referenced by dppMatrix_rcond().