Matrix: dppMatrix.c File Reference
dppMatrix.c File Reference
#include "dppMatrix.h"
#include <R_ext/Lapack.h>
#include "Mutils.h"
#include "dgeMatrix.h"
Functions
SEXP dppMatrix_chol (SEXP x)
SEXP dppMatrix_matrix_solve (SEXP a, SEXP b)
SEXP dppMatrix_rcond (SEXP obj, SEXP type)
SEXP dppMatrix_solve (SEXP x)
SEXP dppMatrix_validate (SEXP obj)
Function Documentation
SEXP dppMatrix_chol (SEXP x)
Definition at line 15 of file dppMatrix.c.
References _, get_factors(), Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, set_factors(), and slot_dup.
Referenced by dppMatrix_matrix_solve(), dppMatrix_rcond(), and dppMatrix_solve().
SEXP dppMatrix_matrix_solve (SEXP a, SEXP b)
Definition at line 71 of file dppMatrix.c.
References _, dppMatrix_chol(), dup_mMatrix_as_dgeMatrix(), Matrix_DimSym, Matrix_xSym, and uplo_P.
SEXP dppMatrix_rcond (SEXP obj, SEXP type)
Definition at line 42 of file dppMatrix.c.
References dppMatrix_chol(), get_norm_sp(), Matrix_DimSym, Matrix_xSym, and uplo_P.
SEXP dppMatrix_solve (SEXP x)
Definition at line 56 of file dppMatrix.c.
References dppMatrix_chol(), Matrix_DimSym, Matrix_uploSym, Matrix_xSym, slot_dup, and uplo_P.
SEXP dppMatrix_validate (SEXP obj)
Definition at line 3 of file dppMatrix.c.
References dspMatrix_validate().