Matrix: dsCMatrix.h File Reference
dsCMatrix.h File Reference
#include "Mutils.h"
#include "Csparse.h"
#include "chm_common.h"
Functions
SEXP dsCMatrix_chol (SEXP x, SEXP pivot)
SEXP dsCMatrix_Cholesky (SEXP A, SEXP perm, SEXP LDL, SEXP super, SEXP Imult)
SEXP dsCMatrix_Csparse_solve (SEXP a, SEXP b, SEXP LDL)
SEXP dsCMatrix_LDL_D (SEXP Ap, SEXP permP, SEXP resultKind)
Fast version of getting at the diagonal matrix D of the (generalized) simplicial Cholesky LDL' decomposition of a (sparse symmetric) dsCMatrix.
SEXP dsCMatrix_matrix_solve (SEXP a, SEXP b, SEXP LDL)
SEXP dsCMatrix_to_dgTMatrix (SEXP x)
SEXP R_chkName_Cholesky (SEXP nm, SEXP perm, SEXP LDL, SEXP super)
SEXP R_chm_factor_name (SEXP perm, SEXP LDL, SEXP super)
Function Documentation
SEXP dsCMatrix_chol (SEXP x, SEXP pivot)
Definition at line 121 of file dsCMatrix.c.
References c, chm_sparse_to_SEXP(), internal_chm_factor(), and Matrix_DimNamesSym.
SEXP dsCMatrix_Cholesky (SEXP A, SEXP perm, SEXP LDL, SEXP super, SEXP Imult)
Definition at line 149 of file dsCMatrix.c.
References chm_factor_to_SEXP(), and internal_chm_factor().
SEXP dsCMatrix_Csparse_solve (SEXP a, SEXP b, SEXP LDL)
Definition at line 197 of file dsCMatrix.c.
References AS_CHM_SP, c, chm_factor_ok(), chm_sparse_to_SEXP(), and internal_chm_factor().
SEXP dsCMatrix_LDL_D (SEXP Ap, SEXP permP, SEXP resultKind)
Fast version of getting at the diagonal matrix D of the (generalized) simplicial Cholesky LDL' decomposition of a (sparse symmetric) dsCMatrix.
Parameters
Ap symmetric CsparseMatrix
permP logical indicating if permutation is allowed
resultKind an (SEXP) string indicating which kind of result is desired.
Returns
SEXP containing either the vector diagonal entries of D, or just sum_i D[i], prod_i D[i] or sum_i log(D[i]).
Definition at line 178 of file dsCMatrix.c.
References c, diag_tC_ptr(), and internal_chm_factor().
SEXP dsCMatrix_matrix_solve (SEXP a, SEXP b, SEXP LDL)
Definition at line 219 of file dsCMatrix.c.
References AS_CHM_DN, c, chm_dense_to_SEXP(), chm_factor_ok(), internal_chm_factor(), and mMatrix_as_dgeMatrix().
SEXP dsCMatrix_to_dgTMatrix (SEXP x)
Definition at line 242 of file dsCMatrix.c.
References _, AS_CHM_SP__, c, chm_triplet_to_SEXP(), and Matrix_DimNamesSym.
SEXP R_chkName_Cholesky (SEXP nm, SEXP perm, SEXP LDL, SEXP super)
Definition at line 16 of file dsCMatrix.c.
References chk_nm().
SEXP R_chm_factor_name (SEXP perm, SEXP LDL, SEXP super)
Definition at line 35 of file dsCMatrix.c.
References chm_factor_name().