Matrix: dspMatrix.c File Reference
dspMatrix.c File Reference
#include "dspMatrix.h"
Functions
SEXP dspMatrix_as_dsyMatrix (SEXP from)
SEXP dspMatrix_getDiag (SEXP x)
SEXP dspMatrix_matrix_mm (SEXP a, SEXP b)
SEXP dspMatrix_matrix_solve (SEXP a, SEXP b)
SEXP dspMatrix_norm (SEXP obj, SEXP type)
SEXP dspMatrix_rcond (SEXP obj, SEXP type)
SEXP dspMatrix_setDiag (SEXP x, SEXP d)
SEXP dspMatrix_solve (SEXP a)
SEXP dspMatrix_trf (SEXP x)
SEXP dspMatrix_validate (SEXP obj)
double get_norm_sp (SEXP obj, const char *typstr)
SEXP lspMatrix_getDiag (SEXP x)
SEXP lspMatrix_setDiag (SEXP x, SEXP d)
Function Documentation
SEXP dspMatrix_as_dsyMatrix (SEXP from)
Definition at line 121 of file dspMatrix.c.
References ALLOC_SLOT(), LOW, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, and UPP.
SEXP dspMatrix_getDiag (SEXP x)
Definition at line 87 of file dspMatrix.c.
References d_packed_getDiag(), and Matrix_DimSym.
SEXP dspMatrix_matrix_mm (SEXP a, SEXP b)
Definition at line 139 of file dspMatrix.c.
References _, Alloca, dup_mMatrix_as_dgeMatrix(), Matrix_DimSym, Matrix_xSym, and uplo_P.
SEXP dspMatrix_matrix_solve (SEXP a, SEXP b)
Definition at line 69 of file dspMatrix.c.
References _, dspMatrix_trf(), dup_mMatrix_as_dgeMatrix(), Matrix_DimSym, Matrix_permSym, Matrix_xSym, and uplo_P.
SEXP dspMatrix_norm (SEXP obj, SEXP type)
Definition at line 32 of file dspMatrix.c.
References get_norm_sp().
SEXP dspMatrix_rcond (SEXP obj, SEXP type)
Definition at line 37 of file dspMatrix.c.
References dspMatrix_trf(), get_norm_sp(), Matrix_DimSym, Matrix_permSym, Matrix_xSym, and uplo_P.
SEXP dspMatrix_setDiag (SEXP x, SEXP d)
Definition at line 108 of file dspMatrix.c.
References d_packed_setDiag(), and Matrix_DimSym.
SEXP dspMatrix_solve (SEXP a)
Definition at line 52 of file dspMatrix.c.
References dspMatrix_trf(), Matrix_DimSym, Matrix_permSym, Matrix_uploSym, Matrix_xSym, slot_dup, and uplo_P.
SEXP dspMatrix_trf (SEXP x)
Definition at line 163 of file dspMatrix.c.
References _, ALLOC_SLOT(), get_factors(), Matrix_diagSym, Matrix_DimSym, Matrix_permSym, Matrix_uploSym, Matrix_xSym, set_factors(), and slot_dup.
Referenced by dspMatrix_matrix_solve(), dspMatrix_rcond(), and dspMatrix_solve().
SEXP dspMatrix_validate (SEXP obj)
Definition at line 4 of file dspMatrix.c.
References _, Matrix_DimSym, Matrix_xSym, and symmetricMatrix_validate().
Referenced by dppMatrix_validate().
double get_norm_sp (SEXP obj, const char * typstr)
Definition at line 18 of file dspMatrix.c.
References La_norm_type(), Matrix_DimSym, Matrix_xSym, and uplo_P.
Referenced by dppMatrix_rcond(), dspMatrix_norm(), and dspMatrix_rcond().
SEXP lspMatrix_getDiag (SEXP x)
Definition at line 98 of file dspMatrix.c.
References l_packed_getDiag(), and Matrix_DimSym.
SEXP lspMatrix_setDiag (SEXP x, SEXP d)
Definition at line 114 of file dspMatrix.c.
References l_packed_setDiag(), and Matrix_DimSym.