Matrix: dspMatrix.h File Reference
dspMatrix.h File Reference
#include "Lapack-etc.h"
#include "Mutils.h"
Functions
SEXP dspMatrix_as_dsyMatrix (SEXP from)
SEXP dspMatrix_getDiag (SEXP x)
SEXP dspMatrix_matrix_mm (SEXP a, SEXP b)
SEXP dspMatrix_matrix_solve (SEXP a, SEXP b)
SEXP dspMatrix_norm (SEXP obj, SEXP type)
SEXP dspMatrix_rcond (SEXP obj, SEXP type)
SEXP dspMatrix_setDiag (SEXP x, SEXP d)
SEXP dspMatrix_solve (SEXP a)
SEXP dspMatrix_trf (SEXP x)
SEXP dspMatrix_validate (SEXP obj)
double get_norm_sp (SEXP obj, const char *typstr)
SEXP lspMatrix_getDiag (SEXP x)
SEXP lspMatrix_setDiag (SEXP x, SEXP d)
Function Documentation
dspMatrix_as_dsyMatrix()
SEXP dspMatrix_as_dsyMatrix (SEXP from)
Definition at line 121 of file dspMatrix.c.
References ALLOC_SLOT(), LOW, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), and UPP.
dspMatrix_getDiag()
SEXP dspMatrix_getDiag (SEXP x)
Definition at line 87 of file dspMatrix.c.
References d_packed_getDiag(), and Matrix_DimSym.
dspMatrix_matrix_mm()
SEXP dspMatrix_matrix_mm (SEXP a, SEXP b)
Definition at line 139 of file dspMatrix.c.
References _, C_or_Alloca_TO, dup_mMatrix_as_dgeMatrix(), FCONE, Matrix_DimSym, Matrix_xSym, SMALL_4_Alloca, and uplo_P.
dspMatrix_matrix_solve()
SEXP dspMatrix_matrix_solve (SEXP a, SEXP b)
Definition at line 69 of file dspMatrix.c.
References _, dspMatrix_trf(), dup_mMatrix_as_dgeMatrix(), FCONE, Matrix_DimSym, Matrix_permSym, Matrix_xSym, and uplo_P.
dspMatrix_norm()
SEXP dspMatrix_norm (SEXP obj, SEXP type)
Definition at line 32 of file dspMatrix.c.
References get_norm_sp().
dspMatrix_rcond()
SEXP dspMatrix_rcond (SEXP obj, SEXP type)
Definition at line 37 of file dspMatrix.c.
References dspMatrix_trf(), FCONE, get_norm_sp(), Matrix_DimSym, Matrix_permSym, Matrix_xSym, and uplo_P.
dspMatrix_setDiag()
SEXP dspMatrix_setDiag (SEXP x, SEXP d)
Definition at line 108 of file dspMatrix.c.
References d_packed_setDiag(), and Matrix_DimSym.
dspMatrix_solve()
SEXP dspMatrix_solve (SEXP a)
Definition at line 52 of file dspMatrix.c.
References dspMatrix_trf(), FCONE, Matrix_DimSym, Matrix_permSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), slot_dup, and uplo_P.
dspMatrix_trf()
SEXP dspMatrix_trf (SEXP x)
Definition at line 165 of file dspMatrix.c.
References _, ALLOC_SLOT(), FCONE, get_factors(), Matrix_diagSym, Matrix_DimSym, Matrix_permSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), set_factors(), and slot_dup.
Referenced by dspMatrix_matrix_solve(), dspMatrix_rcond(), and dspMatrix_solve().
dspMatrix_validate()
SEXP dspMatrix_validate (SEXP obj)
Definition at line 4 of file dspMatrix.c.
References _, Matrix_DimSym, Matrix_xSym, and symmetricMatrix_validate().
Referenced by dppMatrix_validate().
get_norm_sp()
double get_norm_sp (SEXP obj, const char * typstr)
Definition at line 18 of file dspMatrix.c.
Referenced by dspMatrix_norm(), and dspMatrix_rcond().
lspMatrix_getDiag()
SEXP lspMatrix_getDiag (SEXP x)
Definition at line 98 of file dspMatrix.c.
References l_packed_getDiag(), and Matrix_DimSym.
lspMatrix_setDiag()
SEXP lspMatrix_setDiag (SEXP x, SEXP d)
Definition at line 114 of file dspMatrix.c.
References l_packed_setDiag(), and Matrix_DimSym.