Matrix: dsyMatrix.c File Reference
dsyMatrix.c File Reference
#include "dsyMatrix.h"
Functions
SEXP dsyMatrix_as_dspMatrix (SEXP from)
SEXP dsyMatrix_as_matrix (SEXP from, SEXP keep_dimnames)
SEXP dsyMatrix_matrix_mm (SEXP a, SEXP b, SEXP rtP)
SEXP dsyMatrix_matrix_solve (SEXP a, SEXP b)
SEXP dsyMatrix_norm (SEXP obj, SEXP type)
SEXP dsyMatrix_rcond (SEXP obj, SEXP type)
SEXP dsyMatrix_solve (SEXP a)
SEXP dsyMatrix_trf (SEXP x)
double get_norm_sy (SEXP obj, const char *typstr)
SEXP matrix_trf (SEXP x, SEXP uploP)
BunchKaufmann(<simple matrix>)
SEXP symmetricMatrix_validate (SEXP obj)
Function Documentation
dsyMatrix_as_dspMatrix()
SEXP dsyMatrix_as_dspMatrix (SEXP from)
Definition at line 223 of file dsyMatrix.c.
References ALLOC_SLOT(), LOW, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), NUN, and UPP.
dsyMatrix_as_matrix()
SEXP dsyMatrix_as_matrix (SEXP from, SEXP keep_dimnames)
Definition at line 94 of file dsyMatrix.c.
References make_d_matrix_symmetric(), Matrix_DimSym, Matrix_xSym, and R_symmetric_Dimnames().
dsyMatrix_matrix_mm()
SEXP dsyMatrix_matrix_mm (SEXP a, SEXP b, SEXP rtP)
Definition at line 109 of file dsyMatrix.c.
References _, C_or_Alloca_TO, dup_mMatrix_as_dgeMatrix(), FCONE, Matrix_DimNamesSym, Matrix_DimSym, Matrix_xSym, SMALL_4_Alloca, and uplo_P.
dsyMatrix_matrix_solve()
SEXP dsyMatrix_matrix_solve (SEXP a, SEXP b)
Definition at line 75 of file dsyMatrix.c.
References _, dsyMatrix_trf(), dup_mMatrix_as_dgeMatrix(), FCONE, Matrix_DimSym, Matrix_permSym, Matrix_xSym, and uplo_P.
dsyMatrix_norm()
SEXP dsyMatrix_norm (SEXP obj, SEXP type)
Definition at line 35 of file dsyMatrix.c.
References get_norm_sy().
dsyMatrix_rcond()
SEXP dsyMatrix_rcond (SEXP obj, SEXP type)
Definition at line 41 of file dsyMatrix.c.
References dsyMatrix_trf(), FCONE, get_norm_sy(), Matrix_DimSym, Matrix_permSym, Matrix_xSym, and uplo_P.
dsyMatrix_solve()
SEXP dsyMatrix_solve (SEXP a)
Definition at line 57 of file dsyMatrix.c.
References dsyMatrix_trf(), FCONE, Matrix_DimSym, Matrix_permSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), slot_dup, and uplo_P.
dsyMatrix_trf()
SEXP dsyMatrix_trf (SEXP x)
Definition at line 139 of file dsyMatrix.c.
References _, ALLOC_SLOT(), AZERO, C_or_Alloca_TO, FCONE, get_factors(), Matrix_diagSym, Matrix_DimSym, Matrix_permSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), set_factors(), and SMALL_4_Alloca.
Referenced by dsyMatrix_matrix_solve(), dsyMatrix_rcond(), and dsyMatrix_solve().
get_norm_sy()
double get_norm_sy (SEXP obj, const char * typstr)
Definition at line 20 of file dsyMatrix.c.
References FCONE, La_norm_type(), Matrix_DimSym, Matrix_xSym, and uplo_P.
Referenced by dpoMatrix_rcond(), dsyMatrix_norm(), and dsyMatrix_rcond().
matrix_trf()
SEXP matrix_trf (SEXP x, SEXP uploP)
BunchKaufmann(<simple matrix>)
Definition at line 174 of file dsyMatrix.c.
References _, ALLOC_SLOT(), AZERO, C_or_Alloca_TO, FCONE, Matrix_diagSym, Matrix_DimSym, Matrix_permSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), and SMALL_4_Alloca.
symmetricMatrix_validate()
SEXP symmetricMatrix_validate (SEXP obj)
Definition at line 3 of file dsyMatrix.c.
References _, check_scalar_string(), Matrix_DimSym, and Matrix_uploSym.
Referenced by dspMatrix_validate().