Matrix: dsyMatrix.h File Reference
dsyMatrix.h File Reference
#include "Mutils.h"
#include "R_ext/Lapack.h"
Functions
SEXP dsyMatrix_as_dspMatrix (SEXP from)
SEXP dsyMatrix_as_matrix (SEXP from, SEXP keep_dimnames)
SEXP dsyMatrix_matrix_mm (SEXP a, SEXP b, SEXP rt)
SEXP dsyMatrix_matrix_solve (SEXP a, SEXP b)
SEXP dsyMatrix_norm (SEXP obj, SEXP type)
SEXP dsyMatrix_rcond (SEXP obj, SEXP type)
SEXP dsyMatrix_solve (SEXP a)
SEXP dsyMatrix_trf (SEXP x)
SEXP dsyMatrix_validate (SEXP obj)
double get_norm_sy (SEXP obj, const char *typstr)
Function Documentation
SEXP dsyMatrix_as_dspMatrix (SEXP from)
Definition at line 165 of file dsyMatrix.c.
References ALLOC_SLOT(), LOW, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorSym, Matrix_uploSym, Matrix_xSym, NUN, and UPP.
SEXP dsyMatrix_as_matrix (SEXP from, SEXP keep_dimnames)
Definition at line 97 of file dsyMatrix.c.
References make_d_matrix_symmetric(), Matrix_DimNamesSym, Matrix_DimSym, and Matrix_xSym.
SEXP dsyMatrix_matrix_mm (SEXP a, SEXP b, SEXP rt)
Definition at line 111 of file dsyMatrix.c.
References _, Alloca, dup_mMatrix_as_dgeMatrix(), Matrix_DimSym, Matrix_xSym, and uplo_P.
SEXP dsyMatrix_matrix_solve (SEXP a, SEXP b)
Definition at line 78 of file dsyMatrix.c.
References _, dsyMatrix_trf(), dup_mMatrix_as_dgeMatrix(), Matrix_DimSym, Matrix_permSym, Matrix_xSym, and uplo_P.
SEXP dsyMatrix_norm (SEXP obj, SEXP type)
Definition at line 36 of file dsyMatrix.c.
References get_norm_sy().
SEXP dsyMatrix_rcond (SEXP obj, SEXP type)
Definition at line 42 of file dsyMatrix.c.
References dsyMatrix_trf(), get_norm_sy(), La_rcond_type(), Matrix_DimSym, Matrix_permSym, Matrix_xSym, and uplo_P.
SEXP dsyMatrix_solve (SEXP a)
Definition at line 60 of file dsyMatrix.c.
References dsyMatrix_trf(), Matrix_DimSym, Matrix_permSym, Matrix_uploSym, Matrix_xSym, slot_dup, and uplo_P.
SEXP dsyMatrix_trf (SEXP x)
Definition at line 135 of file dsyMatrix.c.
References _, ALLOC_SLOT(), Alloca, AZERO, get_factors(), Matrix_diagSym, Matrix_DimSym, Matrix_permSym, Matrix_uploSym, Matrix_xSym, and set_factors().
Referenced by dsyMatrix_matrix_solve(), dsyMatrix_rcond(), and dsyMatrix_solve().
SEXP dsyMatrix_validate (SEXP obj)
Definition at line 15 of file dsyMatrix.c.
References dense_nonpacked_validate().
double get_norm_sy (SEXP obj, const char * typstr)
Definition at line 21 of file dsyMatrix.c.
References La_norm_type(), Matrix_DimSym, Matrix_xSym, and uplo_P.