Matrix: dtCMatrix.h File Reference
dtCMatrix.h File Reference
#include "Mutils.h"
#include "dgCMatrix.h"
Functions
SEXP dtCMatrix_matrix_solve (SEXP a, SEXP b, SEXP classed)
SEXP dtCMatrix_solve (SEXP a)
SEXP dtCMatrix_upper_solve (SEXP a)
void parent_inv_ai (int n, int countDiag, const int pr[], int ai[])
Derive the row index array for the inverse of L from the parent array.
int parent_inv_ap (int n, int countDiag, const int pr[], int ap[])
Derive the column pointer vector for the inverse of L from the parent array.
SEXP Parent_inverse (SEXP par, SEXP unitdiag)
SEXP tCMatrix_validate (SEXP x)
SEXP tRMatrix_validate (SEXP x)
Function Documentation
SEXP dtCMatrix_matrix_solve (SEXP a, SEXP b, SEXP classed)
Definition at line 203 of file dtCMatrix.c.
References _, ALLOC_SLOT(), AS_CSP, cs_lsolve(), cs_usolve(), Matrix_DimSym, Matrix_xSym, and uplo_P.
SEXP dtCMatrix_solve (SEXP a)
Definition at line 149 of file dtCMatrix.c.
References ALLOC_SLOT(), Alloca, AS_CSP, cs_spalloc(), cs_spfree(), cs_spsolve(), cs::i, Matrix_diagSym, Matrix_DimSym, Matrix_iSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, cs::n, cs::p, SET_DimNames, slot_dup, uplo_P, and cs::x.
SEXP dtCMatrix_upper_solve (SEXP a)
Definition at line 227 of file dtCMatrix.c.
References _, ALLOC_SLOT(), Alloca, AZERO, diag_P, Matrix_diagSym, Matrix_DimSym, Matrix_iSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, SET_DimNames, slot_dup, and uplo_P.
void parent_inv_ai (int n, int countDiag, const int pr[], int ai[])
Derive the row index array for the inverse of L from the parent array.
Parameters:
n length of parent array
countDiag 0 for a unit triangular matrix with implicit diagonal, otherwise 1
pr parent vector describing the elimination tree
ai row index vector of length ap[n]
Definition at line 113 of file dtCMatrix.c.
int parent_inv_ap (int n, int countDiag, const int pr[], int ap[])
Derive the column pointer vector for the inverse of L from the parent array.
Parameters:
n length of parent array
countDiag 0 for a unit triangular matrix with implicit diagonal, otherwise 1
pr parent vector describing the elimination tree
ap array of length n+1 to be filled with the column pointers
Returns:
the number of non-zero entries (ap[n])
Definition at line 90 of file dtCMatrix.c.
References Alloca.
SEXP Parent_inverse (SEXP par, SEXP unitdiag)
Definition at line 122 of file dtCMatrix.c.
References _, Matrix_diagSym, Matrix_DimSym, Matrix_iSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, parent_inv_ai(), and parent_inv_ap().
SEXP tCMatrix_validate (SEXP x)
Definition at line 8 of file dtCMatrix.c.
References _, expand_cmprPt(), Matrix_iSym, Matrix_pSym, RETURN, uplo_P, and xCMatrix_validate().
SEXP tRMatrix_validate (SEXP x)
Definition at line 43 of file dtCMatrix.c.
References _, expand_cmprPt(), Matrix_jSym, Matrix_pSym, RETURN, uplo_P, and xRMatrix_validate().