Matrix: dtCMatrix.c File Reference
dtCMatrix.c File Reference
#include "dtCMatrix.h"
#include "cs_utils.h"
Macros
#define RETURN(_CH_) UNPROTECT(1); return (_CH_);
Functions
SEXP dtCMatrix_matrix_solve (SEXP a, SEXP b, SEXP classed)
SEXP dtCMatrix_sparse_solve (SEXP a, SEXP b)
SEXP tCMatrix_validate (SEXP x)
SEXP tRMatrix_validate (SEXP x)
Macro Definition Documentation
RETURN
#define RETURN (_CH_) UNPROTECT(1); return (_CH_);
Definition at line 5 of file dtCMatrix.c.
Function Documentation
dtCMatrix_matrix_solve()
SEXP dtCMatrix_matrix_solve (SEXP a, SEXP b, SEXP classed)
Definition at line 77 of file dtCMatrix.c.
References _, ALLOC_SLOT(), AS_CSP, cl, cs_lsolve(), cs_usolve(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), RETURN, and uplo_P.
dtCMatrix_sparse_solve()
SEXP dtCMatrix_sparse_solve (SEXP a, SEXP b)
Definition at line 115 of file dtCMatrix.c.
References _, ALLOC_SLOT(), AS_CSP, cs_spsolve(), cs_sparse::m, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_pSym, Matrix_xSym, cs_sparse::n, NEW_OBJECT_OF_CLASS(), RETURN, slot_dup, and uplo_P.
tCMatrix_validate()
SEXP tCMatrix_validate (SEXP x)
Definition at line 8 of file dtCMatrix.c.
References _, expand_cmprPt(), Matrix_iSym, Matrix_pSym, nnz, RETURN, uplo_P, and xCMatrix_validate().
tRMatrix_validate()
SEXP tRMatrix_validate (SEXP x)
Definition at line 43 of file dtCMatrix.c.
References _, expand_cmprPt(), Matrix_jSym, Matrix_pSym, nnz, RETURN, uplo_P, and xRMatrix_validate().