Matrix: dtpMatrix.h File Reference
dtpMatrix.h File Reference
#include "Lapack-etc.h"
#include "Mutils.h"
Functions
SEXP dgeMatrix_dtpMatrix_mm (SEXP x, SEXP y)
SEXP dtpMatrix_addDiag (SEXP x, SEXP d)
SEXP dtpMatrix_as_dtrMatrix (SEXP from)
SEXP dtpMatrix_getDiag (SEXP x)
SEXP dtpMatrix_matrix_mm (SEXP x, SEXP y, SEXP right, SEXP trans)
SEXP dtpMatrix_matrix_solve (SEXP a, SEXP b)
SEXP dtpMatrix_norm (SEXP obj, SEXP type)
SEXP dtpMatrix_rcond (SEXP obj, SEXP type)
SEXP dtpMatrix_setDiag (SEXP x, SEXP d)
SEXP dtpMatrix_solve (SEXP a)
SEXP dtpMatrix_validate (SEXP obj)
SEXP ltpMatrix_getDiag (SEXP x)
SEXP ltpMatrix_setDiag (SEXP x, SEXP d)
Function Documentation
dgeMatrix_dtpMatrix_mm()
SEXP dgeMatrix_dtpMatrix_mm (SEXP x, SEXP y)
Definition at line 174 of file dtpMatrix.c.
References _, diag_P, FCONE, Matrix_DimSym, Matrix_xSym, and uplo_P.
dtpMatrix_addDiag()
SEXP dtpMatrix_addDiag (SEXP x, SEXP d)
Definition at line 102 of file dtpMatrix.c.
References Matrix_DimSym, and tr_d_packed_addDiag().
dtpMatrix_as_dtrMatrix()
SEXP dtpMatrix_as_dtrMatrix (SEXP from)
Definition at line 194 of file dtpMatrix.c.
References ALLOC_SLOT(), LOW, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), and UPP.
dtpMatrix_getDiag()
SEXP dtpMatrix_getDiag (SEXP x)
Definition at line 69 of file dtpMatrix.c.
References Matrix_DimSym, and tr_d_packed_getDiag().
dtpMatrix_matrix_mm()
SEXP dtpMatrix_matrix_mm (SEXP x, SEXP y, SEXP right, SEXP trans)
Definition at line 109 of file dtpMatrix.c.
References _, diag_P, dup_mMatrix_as_dgeMatrix(), FCONE, Matrix_DimSym, Matrix_xSym, and uplo_P.
dtpMatrix_matrix_solve()
SEXP dtpMatrix_matrix_solve (SEXP a, SEXP b)
Definition at line 144 of file dtpMatrix.c.
References _, diag_P, dup_mMatrix_as_dgeMatrix(), FCONE, Matrix_DimSym, Matrix_xSym, and uplo_P.
dtpMatrix_norm()
SEXP dtpMatrix_norm (SEXP obj, SEXP type)
Definition at line 37 of file dtpMatrix.c.
References get_norm().
dtpMatrix_rcond()
SEXP dtpMatrix_rcond (SEXP obj, SEXP type)
Definition at line 42 of file dtpMatrix.c.
References diag_P, FCONE, La_rcond_type(), Matrix_DimSym, Matrix_xSym, and uplo_P.
dtpMatrix_setDiag()
SEXP dtpMatrix_setDiag (SEXP x, SEXP d)
Definition at line 90 of file dtpMatrix.c.
References Matrix_DimSym, and tr_d_packed_setDiag().
dtpMatrix_solve()
SEXP dtpMatrix_solve (SEXP a)
Definition at line 57 of file dtpMatrix.c.
References diag_P, FCONE, Matrix_DimSym, Matrix_xSym, and uplo_P.
dtpMatrix_validate()
SEXP dtpMatrix_validate (SEXP obj)
Definition at line 7 of file dtpMatrix.c.
References _, Matrix_DimSym, Matrix_xSym, and triangularMatrix_validate().
ltpMatrix_getDiag()
SEXP ltpMatrix_getDiag (SEXP x)
Definition at line 80 of file dtpMatrix.c.
References Matrix_DimSym, and tr_l_packed_getDiag().
ltpMatrix_setDiag()
SEXP ltpMatrix_setDiag (SEXP x, SEXP d)
Definition at line 96 of file dtpMatrix.c.
References Matrix_DimSym, and tr_l_packed_setDiag().