Matrix: dtrMatrix.c File Reference
dtrMatrix.c File Reference
#include "dtrMatrix.h"
Macros
#define GET_trMatrix_Diag(_C_TYPE_, _SEXPTYPE_, _SEXP_, _ONE_)
#define SET_trMatrix_Diag(_C_TYPE_, _SEXP_)
Functions
SEXP dtrMatrix_addDiag (SEXP x, SEXP d)
SEXP dtrMatrix_as_dtpMatrix (SEXP from)
SEXP dtrMatrix_as_matrix (SEXP from, SEXP keep_dimnames)
SEXP dtrMatrix_chol2inv (SEXP a)
SEXP dtrMatrix_dtrMatrix_mm (SEXP a, SEXP b, SEXP right, SEXP trans)
Matrix products of dense triangular Matrices.
SEXP dtrMatrix_getDiag (SEXP x)
SEXP dtrMatrix_matrix_mm (SEXP a, SEXP b, SEXP right, SEXP trans)
Matrix products dense triangular Matrices o <matrix>
SEXP dtrMatrix_matrix_solve (SEXP a, SEXP b)
SEXP dtrMatrix_norm (SEXP obj, SEXP type)
SEXP dtrMatrix_rcond (SEXP obj, SEXP type)
SEXP dtrMatrix_setDiag (SEXP x, SEXP d)
SEXP dtrMatrix_solve (SEXP a)
static double get_norm (SEXP obj, const char *typstr)
SEXP ltrMatrix_getDiag (SEXP x)
SEXP ltrMatrix_setDiag (SEXP x, SEXP d)
SEXP triangularMatrix_validate (SEXP obj)
Macro Definition Documentation
GET_trMatrix_Diag
#define GET_trMatrix_Diag (_C_TYPE_, _SEXPTYPE_, _SEXP_, _ONE_)
Value:
    int i, n = INTEGER(GET_SLOT(x, Matrix_DimSym))[0];                  \
    SEXP x_x = GET_SLOT(x, Matrix_xSym);                                \
                                                                        \
    SEXP ret = PROTECT(allocVector(_SEXPTYPE_, n));                     \
    _C_TYPE_ *rv = _SEXP_(ret),                                         \
             *xv = _SEXP_(x_x);                                         \
                                                                        \
    if ('U' == diag_P(x)[0]) {                                          \
        for (i = 0; i < n; i++) rv[i] = _ONE_;                          \
    } else {                                                            \
        for (i = 0; i < n; i++) rv[i] = xv[i * (n + 1)];                \
    }                                                                   \
    UNPROTECT(1);                                                       \
    return ret
Definition at line 256 of file dtrMatrix.c.
SET_trMatrix_Diag
#define SET_trMatrix_Diag (_C_TYPE_, _SEXP_)
Value:
    if ('U' == diag_P(x)[0])                                            \
        error(_("cannot set diag() as long as 'diag = \"U\"'"));        \
                            /* careful to recycle RHS value: */         \
    int n = INTEGER(GET_SLOT(x, Matrix_DimSym))[0];                     \
    int l_d = LENGTH(d); Rboolean d_full = (l_d == n);                  \
    if (!d_full && l_d != 1)                                            \
        error(_("replacement diagonal has wrong length"));              \
    SEXP ret = PROTECT(duplicate(x)),                                   \
        r_x = GET_SLOT(ret, Matrix_xSym);                               \
    _C_TYPE_ *dv = _SEXP_(d),                                           \
             *rv = _SEXP_(r_x);                                         \
                                                                        \
    if(d_full) for (int i = 0; i < n; i++)                              \
        rv[i * (n + 1)] = dv[i];                                        \
    else for (int i = 0; i < n; i++)                                    \
        rv[i * (n + 1)] = *dv;                                          \
                                                                        \
    UNPROTECT(1);                                                       \
    return ret
Definition at line 281 of file dtrMatrix.c.
Function Documentation
dtrMatrix_addDiag()
SEXP dtrMatrix_addDiag (SEXP x, SEXP d)
Definition at line 310 of file dtrMatrix.c.
References _, diag_P, Matrix_DimSym, and Matrix_xSym.
dtrMatrix_as_dtpMatrix()
SEXP dtrMatrix_as_dtpMatrix (SEXP from)
Definition at line 325 of file dtrMatrix.c.
References ALLOC_SLOT(), LOW, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), NUN, UNT, and UPP.
dtrMatrix_as_matrix()
SEXP dtrMatrix_as_matrix (SEXP from, SEXP keep_dimnames)
Definition at line 242 of file dtrMatrix.c.
References make_d_matrix_triangular(), Matrix_DimNamesSym, Matrix_DimSym, and Matrix_xSym.
dtrMatrix_chol2inv()
SEXP dtrMatrix_chol2inv (SEXP a)
Definition at line 67 of file dtrMatrix.c.
References FCONE, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), slot_dup, and uplo_P.
dtrMatrix_dtrMatrix_mm()
SEXP dtrMatrix_dtrMatrix_mm (SEXP a, SEXP b, SEXP right, SEXP trans)
Matrix products of dense triangular Matrices.
Parameters
a triangular matrix of class "dtrMatrix"
b (ditto)
right logical, if true, compute b %*% a, else a %*% b
trans logical, if true, "transpose a", i.e., use t(a), otherwise a
Returns
the matrix product, one of a %*% b, t(a) %*% b, b %*% a, or b %*% t(a) depending on (right, trans) = (F, F) (F, T) (T, F) (T, T)
Definition at line 164 of file dtrMatrix.c.
References _, ALLOC_SLOT(), dup_mMatrix_as_dgeMatrix(), FCONE, make_d_matrix_triangular(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), and SET_DimNames().
dtrMatrix_getDiag()
SEXP dtrMatrix_getDiag (SEXP x)
Definition at line 273 of file dtrMatrix.c.
References GET_trMatrix_Diag.
dtrMatrix_matrix_mm()
SEXP dtrMatrix_matrix_mm (SEXP a, SEXP b, SEXP right, SEXP trans)
Matrix products dense triangular Matrices o <matrix>
Parameters
a triangular matrix of class "dtrMatrix"
b a <matrix> or <any-denseMatrix>
right logical, if true, compute b %*% a, else a %*% b
trans logical, if true, "transpose a", i.e., use t(a), otherwise a
Returns
the matrix product, one of a %*% b, t(a) %*% b, b %*% a, or b %*% t(a) depending on (right, trans) = (F, F) (F, T) (T, F) (T, T)
Definition at line 113 of file dtrMatrix.c.
References _, diag_P, dup_mMatrix_as_dgeMatrix(), FCONE, Matrix_DimNamesSym, Matrix_DimSym, Matrix_xSym, and uplo_P.
dtrMatrix_matrix_solve()
SEXP dtrMatrix_matrix_solve (SEXP a, SEXP b)
Definition at line 84 of file dtrMatrix.c.
References _, diag_P, dup_mMatrix_as_dgeMatrix(), FCONE, Matrix_DimSym, Matrix_xSym, and uplo_P.
dtrMatrix_norm()
SEXP dtrMatrix_norm (SEXP obj, SEXP type)
Definition at line 37 of file dtrMatrix.c.
References get_norm().
dtrMatrix_rcond()
SEXP dtrMatrix_rcond (SEXP obj, SEXP type)
Definition at line 42 of file dtrMatrix.c.
References diag_P, FCONE, La_rcond_type(), Matrix_DimSym, Matrix_xSym, and uplo_P.
dtrMatrix_setDiag()
SEXP dtrMatrix_setDiag (SEXP x, SEXP d)
Definition at line 302 of file dtrMatrix.c.
References SET_trMatrix_Diag.
dtrMatrix_solve()
SEXP dtrMatrix_solve (SEXP a)
Definition at line 57 of file dtrMatrix.c.
References diag_P, FCONE, Matrix_DimSym, Matrix_xSym, and uplo_P.
get_norm()
static double get_norm (SEXP obj, const char * typstr) static
Definition at line 21 of file dtrMatrix.c.
References diag_P, FCONE, La_norm_type(), Matrix_DimSym, Matrix_xSym, and uplo_P.
Referenced by dtrMatrix_norm().
ltrMatrix_getDiag()
SEXP ltrMatrix_getDiag (SEXP x)
Definition at line 277 of file dtrMatrix.c.
References GET_trMatrix_Diag.
ltrMatrix_setDiag()
SEXP ltrMatrix_setDiag (SEXP x, SEXP d)
Definition at line 306 of file dtrMatrix.c.
References SET_trMatrix_Diag.
triangularMatrix_validate()
SEXP triangularMatrix_validate (SEXP obj)
Definition at line 5 of file dtrMatrix.c.
References _, check_scalar_string(), Matrix_diagSym, Matrix_DimSym, and Matrix_uploSym.
Referenced by dtpMatrix_validate().