Matrix: dtTMatrix.h File Reference
dtTMatrix.h File Reference
#include "Mutils.h"
#include "chm_common.h"
Functions
SEXP dtTMatrix_as_dtrMatrix (SEXP x)
SEXP tTMatrix_validate (SEXP x)
SEXP xTMatrix_validate (SEXP x)
Function Documentation
dtTMatrix_as_dtrMatrix()
SEXP dtTMatrix_as_dtrMatrix (SEXP x)
Definition at line 49 of file TMatrix_as.c.
References Matrix_diagSym, Matrix_T_as_DENSE, Matrix_T_as_DENSE_FINISH, NEW_OBJECT_OF_CLASS(), and slot_dup.
tTMatrix_validate()
SEXP tTMatrix_validate (SEXP x)
Definition at line 6 of file dtTMatrix.c.
References _, Matrix_iSym, Matrix_jSym, nnz, uplo_P, and xTMatrix_validate().
xTMatrix_validate()
SEXP xTMatrix_validate (SEXP x)
Definition at line 9 of file dgTMatrix.c.
References _, Matrix_iSym, and Matrix_xSym.
Referenced by tTMatrix_validate().