Matrix: expm.c File Reference
expm.c File Reference
#include <complex.h>
#include "Lapack-etc.h"
#include "Mdefines.h"
#include "idz.h"
Macros
#define SHOW(x, header)
#define asC(x)
#define asR(x)
Functions
SEXP dense_schur (SEXP, const char *, int, int)
SEXP dense_as_kind (SEXP, const char *, char, int)
SEXP dense_as_general (SEXP, const char *, int)
SEXP dense_as_packed (SEXP, const char *, char, char, char)
SEXP dense_expm (SEXP obj, const char *class)
SEXP R_dense_expm (SEXP s_obj)
Variables
static double thetam [] = { 1.5e-2, 2.5e-1, 9.5e-1, 2.1e+0, 5.4e+0 }
static double padecm [][14]
Macro Definition Documentation
asC
#define asC (x)
Value:
((double _Complex *) &(x))[0]
Referenced by dense_expm().
asR
#define asR (x)
Value:
((Rcomplex *) &(x))[0]
Referenced by dense_expm().
SHOW
#define SHOW (x, header)
Value:
do { \
    Rprintf("%s ...\n", (header)); \
    for (k = 0; k < nn; ++k) \
        Rprintf("    % .8e\n", (x)[k]); \
} while (0)
Definition at line 8 of file expm.c.
Function Documentation
dense_as_general()
SEXP dense_as_general (SEXP from, const char * class, int new)
Definition at line 2237 of file coerce.c.
Referenced by dense_expm().
dense_as_kind()
SEXP dense_as_kind (SEXP from, const char * class, char kind, int new)
Definition at line 2000 of file coerce.c.
Referenced by dense_expm().
dense_as_packed()
SEXP dense_as_packed (SEXP from, const char * class, char ul, char ct, char nu)
Definition at line 2654 of file coerce.c.
References _, cl, COPY_SLOT, DIAG, DIM, DIMNAMES, GET_SLOT, Matrix_factorsSym, Matrix_sdSym, Matrix_xSym, newObject(), PACKED_LENGTH, SET_DIAG, SET_DIM, SET_DIMNAMES, SET_SLOT, SET_TRANS, SET_UPLO, SWITCH4, TEMPLATE, TRANS, TYPEOF, and UPLO.
Referenced by dense_expm(), R_dense_as_packed(), and R_Matrix_as_packed().
dense_expm()
SEXP dense_expm (SEXP obj, const char * class)
Definition at line 36 of file expm.c.
References _, asC, asR, cl, dense_as_general(), dense_as_kind(), dense_as_packed(), dense_schur(), DIM, DIMNAMES, dswap2(), ERROR_LAPACK_1, ERROR_LAPACK_2, FCONE, GET_SLOT, Matrix_class(), Matrix_valuesSym, Matrix_vectorsSym, Matrix_xSym, Matrix_zunit, Matrix_zzero, newObject(), padecm, SET_DIM, SET_DIMNAMES, SET_SLOT, SET_UPLO, thetam, TRANS, TYPEOF, UPLO, valid_dense, and zswap2().
Referenced by R_dense_expm().
dense_schur()
SEXP dense_schur (SEXP obj, const char * class, int warn, int vectors)
Definition at line 8 of file Schur.c.
References _, cl, dense_as_general(), dense_as_kind(), DIM, DIMNAMES, ERROR_LAPACK_5, FCONE, GET_SLOT, Matrix_class(), Matrix_valuesSym, Matrix_vectorsSym, Matrix_xSym, newObject(), SET_DIM, SET_DIMNAMES, SET_SLOT, TRANS, TYPEOF, UPLO, and valid_dense.
Referenced by dense_expm(), and R_dense_schur().
R_dense_expm()
SEXP R_dense_expm (SEXP s_obj)
Definition at line 466 of file expm.c.
References dense_expm(), Matrix_class(), and valid_dense.
Variable Documentation
padecm
double padecm[][14] static
Initial value:
= {
    { 120.0, 60.0, 12.0, 1.0 },
    { 30240.0, 15120.0, 3360.0, 420.0, 30.0, 1.0 },
    { 17297280.0, 8648640.0, 1995840.0, 277200.0, 25200.0,
      1512.0, 56.0, 1.0 },
    { 17643225600.0, 8821612800.0, 2075673600.0, 302702400.0,
      30270240.0, 2162160.0, 110880.0, 3960.0, 90.0, 1.0 },
    { 64764752532480000.0, 32382376266240000.0,
      7771770303897600.0, 1187353796428800.0, 129060195264000.0,
      10559470521600.0, 670442572800.0, 33522128640.0,
      1323241920.0, 40840800.0, 960960.0, 16380.0, 182.0, 1.0 } }
Definition at line 24 of file expm.c.
Referenced by dense_expm().
thetam
double thetam[] = { 1.5e-2, 2.5e-1, 9.5e-1, 2.1e+0, 5.4e+0 } static
Definition at line 23 of file expm.c.
Referenced by dense_expm().