Matrix: factorizations.c File Reference
factorizations.c File Reference
#include "Lapack-etc.h"
#include "cs-etc.h"
#include "cholmod-etc.h"
#include "Mdefines.h"
#include "factorizations.h"
Macros
#define DO_FREE(_A_, _S_, _N_)
#define DO_SORT(_A_)
Functions
SEXP get_factor (SEXP, const char *)
void set_factor (SEXP, const char *, SEXP)
static SEXP dgeMatrix_trf_ (SEXP obj, int warn)
static SEXP dsyMatrix_trf_ (SEXP obj, int warn)
static SEXP dspMatrix_trf_ (SEXP obj, int warn)
static SEXP dpoMatrix_trf_ (SEXP obj, int warn, int pivot, double tol)
static SEXP dppMatrix_trf_ (SEXP obj, int warn)
SEXP dgeMatrix_trf (SEXP obj, SEXP warn)
SEXP dsyMatrix_trf (SEXP obj, SEXP warn)
SEXP dspMatrix_trf (SEXP obj, SEXP warn)
SEXP dpoMatrix_trf (SEXP obj, SEXP warn, SEXP pivot, SEXP tol)
SEXP dppMatrix_trf (SEXP obj, SEXP warn)
static int dgCMatrix_trf_ (const Matrix_cs *A, Matrix_css **S, Matrix_csn **N, int order, double tol)
SEXP dgCMatrix_trf (SEXP obj, SEXP order, SEXP tol, SEXP doError)
static int dgCMatrix_orf_ (const Matrix_cs *A, Matrix_css **S, Matrix_csn **N, int order)
SEXP dgCMatrix_orf (SEXP obj, SEXP order, SEXP doError)
static int dpCMatrix_trf_ (cholmod_sparse *A, cholmod_factor **L, int perm, int ldl, int super, double mult)
SEXP dpCMatrix_trf (SEXP obj, SEXP perm, SEXP ldl, SEXP super, SEXP mult)
SEXP BunchKaufman_expand (SEXP obj, SEXP packed)
SEXP CHMfactor_diag_get (SEXP obj, SEXP square)
SEXP CHMfactor_update (SEXP obj, SEXP parent, SEXP mult)
SEXP CHMfactor_updown (SEXP obj, SEXP parent, SEXP update)
Macro Definition Documentation
DO_FREE
#define DO_FREE (_A_, _S_, _N_)
Value:
do { \
    if (!(_A_)) \
        _A_ = Matrix_cs_spfree(_A_); \
    if (!(_S_)) \
        _S_ = Matrix_cs_sfree (_S_); \
    if (!(_N_)) \
        _N_ = Matrix_cs_nfree (_N_); \
} while (0)
Definition at line 309 of file factorizations.c.
DO_SORT
#define DO_SORT (_A_)
Value:
do { \
    Matrix_cs_dropzeros(_A_); \
    T = Matrix_cs_transpose(_A_, 1); \
    if (!T) { \
        DO_FREE(T, *S, *N); \
        return 0; \
    } \
    _A_ = Matrix_cs_spfree(_A_); \
    _A_ = Matrix_cs_transpose(T, 1); \
    if (!(_A_)) { \
        DO_FREE(T, *S, *N); \
        return 0; \
    } \
    T = Matrix_cs_spfree(T); \
} while (0)
Definition at line 319 of file factorizations.c.
Function Documentation
BunchKaufman_expand()
SEXP BunchKaufman_expand (SEXP obj, SEXP packed)
Definition at line 627 of file factorizations.c.
References GET_SLOT, Matrix_diagSym, Matrix_DimSym, Matrix_iSym, Matrix_permSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), and SET_SLOT.
CHMfactor_diag_get()
SEXP CHMfactor_diag_get (SEXP obj, SEXP square)
Definition at line 801 of file factorizations.c.
References M2CHF().
CHMfactor_update()
SEXP CHMfactor_update (SEXP obj, SEXP parent, SEXP mult)
Definition at line 842 of file factorizations.c.
References _, c, CHF2M(), dpCMatrix_trf_(), GET_SLOT, M2CHF(), M2CHS(), Matrix_DimNamesSym, Matrix_shape(), Matrix_uploSym, and SET_SLOT.
CHMfactor_updown()
SEXP CHMfactor_updown (SEXP obj, SEXP parent, SEXP update)
Definition at line 872 of file factorizations.c.
References c, CHF2M(), GET_SLOT, M2CHF(), M2CHS(), Matrix_DimNamesSym, Matrix_shape(), Matrix_uploSym, and SET_SLOT.
dgCMatrix_orf()
SEXP dgCMatrix_orf (SEXP obj, SEXP order, SEXP doError)
Definition at line 443 of file factorizations.c.
References _, Matrix_cs_numeric::B, CXS2M(), dgCMatrix_orf_(), get_factor(), GET_SLOT, Matrix_cs_numeric::L, Matrix_cs_sparse::m, Matrix_cs_symbolic::m2, M2CXS(), Matrix_betaSym, Matrix_cs_free(), Matrix_cs_nfree(), Matrix_cs_pinv(), Matrix_cs_sfree(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_memcpy(), Matrix_pSym, Matrix_qSym, Matrix_RSym, Matrix_VSym, MCS_XTYPE_SET, Matrix_cs_sparse::n, newObject(), Matrix_cs_symbolic::pinv, Matrix_cs_symbolic::q, set_factor(), SET_SLOT, Matrix_cs_numeric::U, and Matrix_cs_sparse::xtype.
dgCMatrix_orf_()
static int dgCMatrix_orf_ (const Matrix_cs * A, Matrix_css ** S, Matrix_csn ** N, int order) static
Definition at line 429 of file factorizations.c.
References DO_FREE, DO_SORT, Matrix_cs_qr(), and Matrix_cs_sqr().
Referenced by dgCMatrix_orf().
dgCMatrix_trf()
SEXP dgCMatrix_trf (SEXP obj, SEXP order, SEXP tol, SEXP doError)
Definition at line 351 of file factorizations.c.
References _, CXS2M(), dgCMatrix_trf_(), get_factor(), GET_SLOT, Matrix_cs_numeric::L, Matrix_cs_sparse::m, M2CXS(), Matrix_cs_free(), Matrix_cs_nfree(), Matrix_cs_pinv(), Matrix_cs_sfree(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_LSym, Matrix_memcpy(), Matrix_pSym, Matrix_qSym, Matrix_uploSym, Matrix_USym, MCS_XTYPE_SET, Matrix_cs_sparse::n, newObject(), Matrix_cs_numeric::pinv, Matrix_cs_symbolic::q, set_factor(), SET_SLOT, Matrix_cs_numeric::U, and Matrix_cs_sparse::xtype.
dgCMatrix_trf_()
static int dgCMatrix_trf_ (const Matrix_cs * A, Matrix_css ** S, Matrix_csn ** N, int order, double tol) static
Definition at line 337 of file factorizations.c.
References DO_FREE, DO_SORT, Matrix_cs_lu(), and Matrix_cs_sqr().
Referenced by dgCMatrix_trf().
dgeMatrix_trf()
SEXP dgeMatrix_trf (SEXP obj, SEXP warn)
Definition at line 252 of file factorizations.c.
References dgeMatrix_trf_(), get_factor(), and set_factor().
dgeMatrix_trf_()
static SEXP dgeMatrix_trf_ (SEXP obj, int warn) static
Definition at line 12 of file factorizations.c.
References ERROR_LAPACK_2, GET_SLOT, Matrix_DimNamesSym, Matrix_DimSym, Matrix_memcpy(), Matrix_permSym, Matrix_xSym, newObject(), and SET_SLOT.
Referenced by dgeMatrix_trf().
dpCMatrix_trf()
SEXP dpCMatrix_trf (SEXP obj, SEXP perm, SEXP ldl, SEXP super, SEXP mult)
Definition at line 564 of file factorizations.c.
References _, c, CHF2M(), dpCMatrix_trf_(), get_factor(), GET_SLOT, M2CHF(), M2CHS(), Matrix_DimNamesSym, Matrix_uploSym, set_factor(), and set_symmetrized_DimNames().
dpCMatrix_trf_()
static int dpCMatrix_trf_ (cholmod_sparse * A, cholmod_factor ** L, int perm, int ldl, int super, double mult) static
Definition at line 521 of file factorizations.c.
References c, R_cholmod_common_envget(), and R_cholmod_common_envset().
Referenced by CHMfactor_update(), and dpCMatrix_trf().
dpoMatrix_trf()
SEXP dpoMatrix_trf (SEXP obj, SEXP warn, SEXP pivot, SEXP tol)
Definition at line 285 of file factorizations.c.
References dpoMatrix_trf_(), get_factor(), and set_factor().
dpoMatrix_trf_()
static SEXP dpoMatrix_trf_ (SEXP obj, int warn, int pivot, double tol) static
Definition at line 139 of file factorizations.c.
References ERROR_LAPACK_3, ERROR_LAPACK_4, FCONE, GET_SLOT, Matrix_DimNamesSym, Matrix_DimSym, Matrix_memset(), Matrix_permSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, and set_symmetrized_DimNames().
Referenced by dpoMatrix_trf().
dppMatrix_trf()
SEXP dppMatrix_trf (SEXP obj, SEXP warn)
Definition at line 298 of file factorizations.c.
References dppMatrix_trf_(), get_factor(), and set_factor().
dppMatrix_trf_()
static SEXP dppMatrix_trf_ (SEXP obj, int warn) static
Definition at line 215 of file factorizations.c.
References ERROR_LAPACK_3, FCONE, GET_SLOT, Matrix_DimNamesSym, Matrix_DimSym, Matrix_memcpy(), Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, and set_symmetrized_DimNames().
Referenced by dppMatrix_trf().
dspMatrix_trf()
SEXP dspMatrix_trf (SEXP obj, SEXP warn)
Definition at line 274 of file factorizations.c.
References dspMatrix_trf_(), get_factor(), and set_factor().
dspMatrix_trf_()
static SEXP dspMatrix_trf_ (SEXP obj, int warn) static
Definition at line 99 of file factorizations.c.
References ERROR_LAPACK_2, FCONE, GET_SLOT, Matrix_DimNamesSym, Matrix_DimSym, Matrix_memcpy(), Matrix_permSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, and set_symmetrized_DimNames().
Referenced by dspMatrix_trf().
dsyMatrix_trf()
SEXP dsyMatrix_trf (SEXP obj, SEXP warn)
Definition at line 263 of file factorizations.c.
References dsyMatrix_trf_(), get_factor(), and set_factor().
dsyMatrix_trf_()
static SEXP dsyMatrix_trf_ (SEXP obj, int warn) static
Definition at line 49 of file factorizations.c.
References ERROR_LAPACK_2, FCONE, GET_SLOT, Matrix_Calloc, Matrix_DimNamesSym, Matrix_DimSym, Matrix_Free, Matrix_memset(), Matrix_permSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, and set_symmetrized_DimNames().
Referenced by dsyMatrix_trf().
get_factor()
SEXP get_factor (SEXP obj, const char * nm)
Definition at line 189 of file attrib.c.
References GET_SLOT, Matrix_factorsSym, strmatch(), and valid.
Referenced by dgCMatrix_orf(), dgCMatrix_trf(), dgeMatrix_trf(), dpCMatrix_trf(), dpoMatrix_trf(), dppMatrix_trf(), dspMatrix_trf(), and dsyMatrix_trf().
set_factor()
void set_factor (SEXP obj, const char * nm, SEXP val)
Definition at line 203 of file attrib.c.
References append_to_named_list(), GET_SLOT, Matrix_factorsSym, SET_SLOT, strmatch(), and valid.
Referenced by dgCMatrix_orf(), dgCMatrix_trf(), dgeMatrix_trf(), dpCMatrix_trf(), dpoMatrix_trf(), dppMatrix_trf(), dspMatrix_trf(), dsyMatrix_trf(), and R_set_factor().