Matrix: factorizations.h File Reference
factorizations.h File Reference
#include <Rinternals.h>
Functions
SEXP dgeMatrix_trf (SEXP, SEXP)
SEXP dsyMatrix_trf (SEXP, SEXP)
SEXP dspMatrix_trf (SEXP, SEXP)
SEXP dpoMatrix_trf (SEXP, SEXP, SEXP, SEXP)
SEXP dppMatrix_trf (SEXP, SEXP)
SEXP dgCMatrix_trf (SEXP, SEXP, SEXP, SEXP)
SEXP dgCMatrix_orf (SEXP, SEXP, SEXP)
SEXP dpCMatrix_trf (SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP BunchKaufman_expand (SEXP, SEXP)
SEXP CHMfactor_diag_get (SEXP, SEXP)
SEXP CHMfactor_update (SEXP, SEXP, SEXP)
SEXP CHMfactor_updown (SEXP, SEXP, SEXP)
Function Documentation
BunchKaufman_expand()
SEXP BunchKaufman_expand (SEXP obj, SEXP packed)
Definition at line 627 of file factorizations.c.
References GET_SLOT, Matrix_diagSym, Matrix_DimSym, Matrix_iSym, Matrix_permSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), and SET_SLOT.
CHMfactor_diag_get()
SEXP CHMfactor_diag_get (SEXP obj, SEXP square)
Definition at line 801 of file factorizations.c.
References M2CHF().
CHMfactor_update()
SEXP CHMfactor_update (SEXP obj, SEXP parent, SEXP mult)
Definition at line 842 of file factorizations.c.
References _, c, CHF2M(), dpCMatrix_trf_(), GET_SLOT, M2CHF(), M2CHS(), Matrix_DimNamesSym, Matrix_shape(), Matrix_uploSym, and SET_SLOT.
CHMfactor_updown()
SEXP CHMfactor_updown (SEXP obj, SEXP parent, SEXP update)
Definition at line 872 of file factorizations.c.
References c, CHF2M(), GET_SLOT, M2CHF(), M2CHS(), Matrix_DimNamesSym, Matrix_shape(), Matrix_uploSym, and SET_SLOT.
dgCMatrix_orf()
SEXP dgCMatrix_orf (SEXP obj, SEXP order, SEXP doError)
Definition at line 443 of file factorizations.c.
References _, Matrix_cs_numeric::B, CXS2M(), dgCMatrix_orf_(), get_factor(), GET_SLOT, Matrix_cs_numeric::L, Matrix_cs_sparse::m, Matrix_cs_symbolic::m2, M2CXS(), Matrix_betaSym, Matrix_cs_free(), Matrix_cs_nfree(), Matrix_cs_pinv(), Matrix_cs_sfree(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_memcpy(), Matrix_pSym, Matrix_qSym, Matrix_RSym, Matrix_VSym, MCS_XTYPE_SET, Matrix_cs_sparse::n, newObject(), Matrix_cs_symbolic::pinv, Matrix_cs_symbolic::q, set_factor(), SET_SLOT, Matrix_cs_numeric::U, and Matrix_cs_sparse::xtype.
dgCMatrix_trf()
SEXP dgCMatrix_trf (SEXP obj, SEXP order, SEXP tol, SEXP doError)
Definition at line 351 of file factorizations.c.
References _, CXS2M(), dgCMatrix_trf_(), get_factor(), GET_SLOT, Matrix_cs_numeric::L, Matrix_cs_sparse::m, M2CXS(), Matrix_cs_free(), Matrix_cs_nfree(), Matrix_cs_pinv(), Matrix_cs_sfree(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_LSym, Matrix_memcpy(), Matrix_pSym, Matrix_qSym, Matrix_uploSym, Matrix_USym, MCS_XTYPE_SET, Matrix_cs_sparse::n, newObject(), Matrix_cs_numeric::pinv, Matrix_cs_symbolic::q, set_factor(), SET_SLOT, Matrix_cs_numeric::U, and Matrix_cs_sparse::xtype.
dgeMatrix_trf()
SEXP dgeMatrix_trf (SEXP obj, SEXP warn)
Definition at line 252 of file factorizations.c.
References dgeMatrix_trf_(), get_factor(), and set_factor().
dpCMatrix_trf()
SEXP dpCMatrix_trf (SEXP obj, SEXP perm, SEXP ldl, SEXP super, SEXP mult)
Definition at line 564 of file factorizations.c.
References _, c, CHF2M(), dpCMatrix_trf_(), get_factor(), GET_SLOT, M2CHF(), M2CHS(), Matrix_DimNamesSym, Matrix_uploSym, set_factor(), and set_symmetrized_DimNames().
dpoMatrix_trf()
SEXP dpoMatrix_trf (SEXP obj, SEXP warn, SEXP pivot, SEXP tol)
Definition at line 285 of file factorizations.c.
References dpoMatrix_trf_(), get_factor(), and set_factor().
dppMatrix_trf()
SEXP dppMatrix_trf (SEXP obj, SEXP warn)
Definition at line 298 of file factorizations.c.
References dppMatrix_trf_(), get_factor(), and set_factor().
dspMatrix_trf()
SEXP dspMatrix_trf (SEXP obj, SEXP warn)
Definition at line 274 of file factorizations.c.
References dspMatrix_trf_(), get_factor(), and set_factor().
dsyMatrix_trf()
SEXP dsyMatrix_trf (SEXP obj, SEXP warn)
Definition at line 263 of file factorizations.c.
References dsyMatrix_trf_(), get_factor(), and set_factor().