Matrix: idz.c File Reference
idz.c File Reference
#include "Mdefines.h"
#include "M5.h"
#include "idz.h"
Macros
#define TEMPLATE(c)
#define TEMPLATE(c)
Functions
void zvreal (Rcomplex *x, const Rcomplex *y, size_t n)
void zvimag (Rcomplex *x, const Rcomplex *y, size_t n)
void zvconj (Rcomplex *x, const Rcomplex *y, size_t n)
Macro Definition Documentation
TEMPLATE [1/2]
#define TEMPLATE (c)
Definition at line 5 of file idz.c.
TEMPLATE [2/2]
#define TEMPLATE (c)
Definition at line 5 of file idz.c.
Function Documentation
zvconj()
void zvconj (Rcomplex * x, const Rcomplex * y, size_t n)
Definition at line 1300 of file idz.c.
Referenced by sparse_transpose(), spMatrix_matmult(), syMatrix_matmult(), and tpMatrix_matmult().
zvimag()
void zvimag (Rcomplex * x, const Rcomplex * y, size_t n)
Definition at line 1287 of file idz.c.
Referenced by dense_skewpart(), and sparse_skewpart().
zvreal()
void zvreal (Rcomplex * x, const Rcomplex * y, size_t n)
Definition at line 1274 of file idz.c.
Referenced by dense_diag_get(), dense_symmpart(), sparse_diag_get(), and sparse_symmpart().