Matrix: idz.h File Reference
idz.h File Reference
#include <stddef.h>
#include <R_ext/Complex.h>
Functions
void iswap2 (size_t, int *, size_t, int *, size_t)
void dswap2 (size_t, double *, size_t, double *, size_t)
void zswap2 (size_t, Rcomplex *, size_t, Rcomplex *, size_t)
void iswap1 (size_t, int *, size_t, size_t, int, int *, size_t, size_t, int)
void dswap1 (size_t, double *, size_t, size_t, int, double *, size_t, size_t, int)
void zswap1 (size_t, Rcomplex *, size_t, size_t, int, Rcomplex *, size_t, size_t, int)
void icopy2 (size_t, int *, size_t, const int *, size_t)
void dcopy2 (size_t, double *, size_t, const double *, size_t)
void zcopy2 (size_t, Rcomplex *, size_t, const Rcomplex *, size_t)
void icopy1 (size_t, int *, size_t, size_t, int, const int *, size_t, size_t, int)
void dcopy1 (size_t, double *, size_t, size_t, int, const double *, size_t, size_t, int)
void zcopy1 (size_t, Rcomplex *, size_t, size_t, int, const Rcomplex *, size_t, size_t, int)
void irowperm2 (int *, const int *, int, int, const int *, int, int)
void drowperm2 (double *, const double *, int, int, const int *, int, int)
void zrowperm2 (Rcomplex *, const Rcomplex *, int, int, const int *, int, int)
void isymperm2 (int *, const int *, int, char, const int *, int, int)
void dsymperm2 (double *, const double *, int, char, const int *, int, int)
void zsymperm2 (Rcomplex *, const Rcomplex *, int, char, const int *, int, int)
void isymperm1 (int *, const int *, int, char, const int *, int, int)
void dsymperm1 (double *, const double *, int, char, const int *, int, int)
void zsymperm1 (Rcomplex *, const Rcomplex *, int, char, const int *, int, int)
void ipack2 (int *, const int *, size_t, char, char, char)
void dpack2 (double *, const double *, size_t, char, char, char)
void zpack2 (Rcomplex *, const Rcomplex *, size_t, char, char, char)
void ipack1 (int *, const int *, size_t, char, char, char)
void dpack1 (double *, const double *, size_t, char, char, char)
void zpack1 (Rcomplex *, const Rcomplex *, size_t, char, char, char)
void iforce2 (int *, const int *, size_t, char, char, char)
void dforce2 (double *, const double *, size_t, char, char, char)
void zforce2 (Rcomplex *, const Rcomplex *, size_t, char, char, char)
void iforce1 (int *, const int *, size_t, char, char, char)
void dforce1 (double *, const double *, size_t, char, char, char)
void zforce1 (Rcomplex *, const Rcomplex *, size_t, char, char, char)
void itrans2 (int *, const int *, size_t, size_t, char)
void dtrans2 (double *, const double *, size_t, size_t, char)
void ztrans2 (Rcomplex *, const Rcomplex *, size_t, size_t, char)
void itrans1 (int *, const int *, size_t, char, char)
void dtrans1 (double *, const double *, size_t, char, char)
void ztrans1 (Rcomplex *, const Rcomplex *, size_t, char, char)
void iband2 (int *, const int *, size_t, size_t, size_t, size_t)
void dband2 (double *, const double *, size_t, size_t, size_t, size_t)
void zband2 (Rcomplex *, const Rcomplex *, size_t, size_t, size_t, size_t)
void iband1 (int *, const int *, size_t, char, size_t, size_t)
void dband1 (double *, const double *, size_t, char, size_t, size_t)
void zband1 (Rcomplex *, const Rcomplex *, size_t, char, size_t, size_t)
int ntest2 (const int *, size_t, char, char, char)
int ltest2 (const int *, size_t, char, char, char)
int itest2 (const int *, size_t, char, char, char)
int dtest2 (const double *, size_t, char, char, char)
int ztest2 (const Rcomplex *, size_t, char, char, char)
int ntest1 (const int *, size_t, char, char, char)
int ltest1 (const int *, size_t, char, char, char)
int itest1 (const int *, size_t, char, char, char)
int dtest1 (const double *, size_t, char, char, char)
int ztest1 (const Rcomplex *, size_t, char, char, char)
void ntspaggr (int *, int *, int *, const int *, const int *, const int *, int, int, int *, int *, int *)
void ltspaggr (int *, int *, int *, const int *, const int *, const int *, int, int, int *, int *, int *)
void itspaggr (int *, int *, int *, const int *, const int *, const int *, int, int, int *, int *, int *)
void dtspaggr (int *, int *, double *, const int *, const int *, const double *, int, int, int *, int *, double *)
void ztspaggr (int *, int *, Rcomplex *, const int *, const int *, const Rcomplex *, int, int, int *, int *, Rcomplex *)
void ntspsort (int *, int *, int *, const int *, const int *, const int *, int, int, int *, int *, int *)
void ltspsort (int *, int *, int *, const int *, const int *, const int *, int, int, int *, int *, int *)
void itspsort (int *, int *, int *, const int *, const int *, const int *, int, int, int *, int *, int *)
void dtspsort (int *, int *, double *, const int *, const int *, const double *, int, int, int *, int *, double *)
void ztspsort (int *, int *, Rcomplex *, const int *, const int *, const Rcomplex *, int, int, int *, int *, Rcomplex *)
void ncspsort (int *, int *, int *, int, int, int *, int *)
void lcspsort (int *, int *, int *, int, int, int *, int *)
void icspsort (int *, int *, int *, int, int, int *, int *)
void dcspsort (int *, int *, double *, int, int, int *, double *)
void zcspsort (int *, int *, Rcomplex *, int, int, int *, Rcomplex *)
void ncsptrans (int *, int *, int *, const int *, const int *, const int *, int, int, char, int *)
void lcsptrans (int *, int *, int *, const int *, const int *, const int *, int, int, char, int *)
void icsptrans (int *, int *, int *, const int *, const int *, const int *, int, int, char, int *)
void dcsptrans (int *, int *, double *, const int *, const int *, const double *, int, int, char, int *)
void zcsptrans (int *, int *, Rcomplex *, const int *, const int *, const Rcomplex *, int, int, char, int *)
void zvreal (Rcomplex *, const Rcomplex *, size_t)
void zvimag (Rcomplex *, const Rcomplex *, size_t)
void zvconj (Rcomplex *, const Rcomplex *, size_t)
Function Documentation
dband1()
void dband1 (double * , const double * , size_t , char , size_t , size_t)
dband2()
void dband2 (double * , const double * , size_t , size_t , size_t , size_t)
dcopy1()
void dcopy1 (size_t , double * , size_t , size_t , int , const double * , size_t , size_t , int)
dcopy2()
void dcopy2 (size_t , double * , size_t , const double * , size_t)
dcspsort()
void dcspsort (int * , int * , double * , int , int , int * , double *)
dcsptrans()
void dcsptrans (int * , int * , double * , const int * , const int * , const double * , int , int , char , int *)
dforce1()
void dforce1 (double * , const double * , size_t , char , char , char)
dforce2()
void dforce2 (double * , const double * , size_t , char , char , char)
dpack1()
void dpack1 (double * , const double * , size_t , char , char , char)
dpack2()
void dpack2 (double * , const double * , size_t , char , char , char)
drowperm2()
void drowperm2 (double * , const double * , int , int , const int * , int , int)
Referenced by denseCholesky_solve().
dswap1()
void dswap1 (size_t , double * , size_t , size_t , int , double * , size_t , size_t , int)
dswap2()
void dswap2 (size_t , double * , size_t , double * , size_t)
Referenced by dense_expm().
dsymperm1()
void dsymperm1 (double * , const double * , int , char , const int * , int , int)
Referenced by denseCholesky_solve().
dsymperm2()
void dsymperm2 (double * , const double * , int , char , const int * , int , int)
Referenced by denseCholesky_solve().
dtest1()
int dtest1 (const double * , size_t , char , char , char)
dtest2()
int dtest2 (const double * , size_t , char , char , char)
dtrans1()
void dtrans1 (double * , const double * , size_t , char , char)
dtrans2()
void dtrans2 (double * , const double * , size_t , size_t , char)
Referenced by CHD2M(), gCgeMatrix_matmult(), M2CHD(), tpMatrix_matmult(), and trMatrix_matmult().
dtspaggr()
void dtspaggr (int * , int * , double * , const int * , const int * , const double * , int , int , int * , int * , double *)
dtspsort()
void dtspsort (int * , int * , double * , const int * , const int * , const double * , int , int , int * , int * , double *)
iband1()
void iband1 (int * , const int * , size_t , char , size_t , size_t)
iband2()
void iband2 (int * , const int * , size_t , size_t , size_t , size_t)
icopy1()
void icopy1 (size_t , int * , size_t , size_t , int , const int * , size_t , size_t , int)
icopy2()
void icopy2 (size_t , int * , size_t , const int * , size_t)
icspsort()
void icspsort (int * , int * , int * , int , int , int * , int *)
icsptrans()
void icsptrans (int * , int * , int * , const int * , const int * , const int * , int , int , char , int *)
iforce1()
void iforce1 (int * , const int * , size_t , char , char , char)
iforce2()
void iforce2 (int * , const int * , size_t , char , char , char)
ipack1()
void ipack1 (int * , const int * , size_t , char , char , char)
ipack2()
void ipack2 (int * , const int * , size_t , char , char , char)
irowperm2()
void irowperm2 (int * , const int * , int , int , const int * , int , int)
iswap1()
void iswap1 (size_t , int * , size_t , size_t , int , int * , size_t , size_t , int)
iswap2()
void iswap2 (size_t , int * , size_t , int * , size_t)
isymperm1()
void isymperm1 (int * , const int * , int , char , const int * , int , int)
isymperm2()
void isymperm2 (int * , const int * , int , char , const int * , int , int)
itest1()
int itest1 (const int * , size_t , char , char , char)
itest2()
int itest2 (const int * , size_t , char , char , char)
itrans1()
void itrans1 (int * , const int * , size_t , char , char)
itrans2()
void itrans2 (int * , const int * , size_t , size_t , char)
itspaggr()
void itspaggr (int * , int * , int * , const int * , const int * , const int * , int , int , int * , int * , int *)
itspsort()
void itspsort (int * , int * , int * , const int * , const int * , const int * , int , int , int * , int * , int *)
lcspsort()
void lcspsort (int * , int * , int * , int , int , int * , int *)
lcsptrans()
void lcsptrans (int * , int * , int * , const int * , const int * , const int * , int , int , char , int *)
ltest1()
int ltest1 (const int * , size_t , char , char , char)
ltest2()
int ltest2 (const int * , size_t , char , char , char)
ltspaggr()
void ltspaggr (int * , int * , int * , const int * , const int * , const int * , int , int , int * , int * , int *)
ltspsort()
void ltspsort (int * , int * , int * , const int * , const int * , const int * , int , int , int * , int * , int *)
ncspsort()
void ncspsort (int * , int * , int * , int , int , int * , int *)
ncsptrans()
void ncsptrans (int * , int * , int * , const int * , const int * , const int * , int , int , char , int *)
Referenced by sparse_skewpart(), and sparse_symmpart().
ntest1()
int ntest1 (const int * , size_t , char , char , char)
ntest2()
int ntest2 (const int * , size_t , char , char , char)
ntspaggr()
void ntspaggr (int * , int * , int * , const int * , const int * , const int * , int , int , int * , int * , int *)
ntspsort()
void ntspsort (int * , int * , int * , const int * , const int * , const int * , int , int , int * , int * , int *)
zband1()
void zband1 (Rcomplex * , const Rcomplex * , size_t , char , size_t , size_t)
zband2()
void zband2 (Rcomplex * , const Rcomplex * , size_t , size_t , size_t , size_t)
zcopy1()
void zcopy1 (size_t , Rcomplex * , size_t , size_t , int , const Rcomplex * , size_t , size_t , int)
zcopy2()
void zcopy2 (size_t , Rcomplex * , size_t , const Rcomplex * , size_t)
zcspsort()
void zcspsort (int * , int * , Rcomplex * , int , int , int * , Rcomplex *)
zcsptrans()
void zcsptrans (int * , int * , Rcomplex * , const int * , const int * , const Rcomplex * , int , int , char , int *)
zforce1()
void zforce1 (Rcomplex * , const Rcomplex * , size_t , char , char , char)
zforce2()
void zforce2 (Rcomplex * , const Rcomplex * , size_t , char , char , char)
zpack1()
void zpack1 (Rcomplex * , const Rcomplex * , size_t , char , char , char)
zpack2()
void zpack2 (Rcomplex * , const Rcomplex * , size_t , char , char , char)
zrowperm2()
void zrowperm2 (Rcomplex * , const Rcomplex * , int , int , const int * , int , int)
Referenced by denseCholesky_solve().
zswap1()
void zswap1 (size_t , Rcomplex * , size_t , size_t , int , Rcomplex * , size_t , size_t , int)
zswap2()
void zswap2 (size_t , Rcomplex * , size_t , Rcomplex * , size_t)
Referenced by dense_expm().
zsymperm1()
void zsymperm1 (Rcomplex * , const Rcomplex * , int , char , const int * , int , int)
Referenced by denseCholesky_solve().
zsymperm2()
void zsymperm2 (Rcomplex * , const Rcomplex * , int , char , const int * , int , int)
Referenced by denseCholesky_solve().
ztest1()
int ztest1 (const Rcomplex * , size_t , char , char , char)
ztest2()
int ztest2 (const Rcomplex * , size_t , char , char , char)
ztrans1()
void ztrans1 (Rcomplex * , const Rcomplex * , size_t , char , char)
ztrans2()
void ztrans2 (Rcomplex * , const Rcomplex * , size_t , size_t , char)
Referenced by CHD2M(), gCgeMatrix_matmult(), M2CHD(), tpMatrix_matmult(), and trMatrix_matmult().
ztspaggr()
void ztspaggr (int * , int * , Rcomplex * , const int * , const int * , const Rcomplex * , int , int , int * , int * , Rcomplex *)
ztspsort()
void ztspsort (int * , int * , Rcomplex * , const int * , const int * , const Rcomplex * , int , int , int * , int * , Rcomplex *)
zvconj()
void zvconj (Rcomplex * x, const Rcomplex * y, size_t n)
Definition at line 1300 of file idz.c.
Referenced by sparse_transpose(), spMatrix_matmult(), syMatrix_matmult(), and tpMatrix_matmult().
zvimag()
void zvimag (Rcomplex * x, const Rcomplex * y, size_t n)
Definition at line 1287 of file idz.c.
Referenced by dense_skewpart(), and sparse_skewpart().
zvreal()
void zvreal (Rcomplex * x, const Rcomplex * y, size_t n)
Definition at line 1274 of file idz.c.
Referenced by dense_diag_get(), dense_symmpart(), sparse_diag_get(), and sparse_symmpart().