Matrix: init.c File Reference
init.c File Reference
#include "cholmod-api.h"
#include <R_ext/Rdynload.h>
#include <R_ext/Visibility.h>
#include <Rinternals.h>
Macros
#define CALL_METHOD(name, n)
#define EXTERNAL_METHOD(name, n)
#define REGISTER(name)
Functions
SEXP R_dense_bunchkaufman (SEXP, SEXP, SEXP, SEXP)
SEXP R_dense_cholesky (SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP R_sparse_cholesky (SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP CsparseMatrix_validate_maybe_sorting (SEXP)
SEXP dgCMatrix_lusol (SEXP, SEXP)
SEXP dgCMatrix_qrsol (SEXP, SEXP, SEXP)
SEXP dgCMatrix_cholsol (SEXP, SEXP)
SEXP dtCMatrix_diag (SEXP, SEXP)
SEXP Csparse_dmperm (SEXP, SEXP, SEXP)
SEXP Csparse_writeMM (SEXP, SEXP)
SEXP R_dense_schur (SEXP, SEXP, SEXP)
SEXP R_dense_sum (SEXP, SEXP)
SEXP R_sparse_sum (SEXP, SEXP)
SEXP R_dense_prod (SEXP, SEXP)
SEXP R_sparse_prod (SEXP, SEXP)
SEXP R_sparse_aggregate (SEXP)
SEXP R_Dim_prod (SEXP)
SEXP R_DimNames_is_symmetric (SEXP)
SEXP R_symDN (SEXP)
SEXP R_set_factor (SEXP, SEXP, SEXP, SEXP)
SEXP R_dense_band (SEXP, SEXP, SEXP)
SEXP R_sparse_band (SEXP, SEXP, SEXP)
SEXP R_bind (SEXP)
SEXP R_vector_as_dense (SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP R_matrix_as_dense (SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP R_sparse_as_dense (SEXP, SEXP)
SEXP R_diagonal_as_dense (SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP R_index_as_dense (SEXP, SEXP)
SEXP R_Vector_as_sparse (SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP R_matrix_as_sparse (SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP R_dense_as_sparse (SEXP, SEXP)
SEXP R_diagonal_as_sparse (SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP R_index_as_sparse (SEXP, SEXP, SEXP)
SEXP R_dense_as_kind (SEXP, SEXP)
SEXP R_sparse_as_kind (SEXP, SEXP)
SEXP R_diagonal_as_kind (SEXP, SEXP)
SEXP R_index_as_kind (SEXP, SEXP)
SEXP R_dense_as_general (SEXP)
SEXP R_sparse_as_general (SEXP)
SEXP R_dense_as_unpacked (SEXP)
SEXP R_dense_as_packed (SEXP, SEXP, SEXP, SEXP)
SEXP R_sparse_as_Csparse (SEXP)
SEXP R_sparse_as_Rsparse (SEXP)
SEXP R_sparse_as_Tsparse (SEXP)
SEXP R_vector_as_Vector (SEXP, SEXP)
SEXP R_sparse_as_Vector (SEXP)
SEXP R_diagonal_as_Vector (SEXP)
SEXP R_index_as_Vector (SEXP)
SEXP R_Matrix_as_vector (SEXP)
SEXP R_Matrix_as_matrix (SEXP)
SEXP R_Matrix_as_unpacked (SEXP)
SEXP R_Matrix_as_packed (SEXP)
SEXP R_Matrix_as_Csparse (SEXP)
SEXP R_Matrix_as_Rsparse (SEXP)
SEXP R_Matrix_as_Tsparse (SEXP)
SEXP R_Matrix_as_Vector (SEXP)
SEXP R_Matrix_as_kind (SEXP, SEXP, SEXP)
SEXP R_Matrix_as_general (SEXP, SEXP)
SEXP R_dense_marginsum (SEXP, SEXP, SEXP, SEXP)
SEXP R_sparse_marginsum (SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP denseLU_determinant (SEXP, SEXP)
SEXP denseBunchKaufman_determinant (SEXP, SEXP)
SEXP denseCholesky_determinant (SEXP, SEXP)
SEXP sparseQR_determinant (SEXP, SEXP)
SEXP sparseLU_determinant (SEXP, SEXP)
SEXP sparseCholesky_determinant (SEXP, SEXP, SEXP)
SEXP R_dense_diag_get (SEXP, SEXP)
SEXP R_sparse_diag_get (SEXP, SEXP)
SEXP R_dense_diag_set (SEXP, SEXP)
SEXP R_sparse_diag_set (SEXP, SEXP)
SEXP R_sparse_diag_U2N (SEXP)
SEXP R_sparse_diag_N2U (SEXP)
SEXP denseCholesky_diag_get (SEXP, SEXP)
SEXP sparseCholesky_diag_get (SEXP, SEXP)
SEXP R_sparse_dropzero (SEXP, SEXP)
SEXP denseBunchKaufman_expand (SEXP)
SEXP R_dense_expm (SEXP)
SEXP R_dense_force_canonical (SEXP, SEXP)
SEXP R_sparse_force_canonical (SEXP, SEXP)
SEXP R_dense_force_symmetric (SEXP, SEXP, SEXP)
SEXP R_sparse_force_symmetric (SEXP, SEXP, SEXP)
SEXP R_dense_is_canonical (SEXP)
SEXP R_sparse_is_canonical (SEXP)
SEXP R_dense_is_diagonal (SEXP)
SEXP R_sparse_is_diagonal (SEXP)
SEXP R_dense_is_symmetric (SEXP, SEXP, SEXP, SEXP)
SEXP R_sparse_is_symmetric (SEXP, SEXP, SEXP, SEXP)
SEXP R_dense_is_triangular (SEXP, SEXP)
SEXP R_sparse_is_triangular (SEXP, SEXP)
SEXP R_dense_lu (SEXP, SEXP)
SEXP R_sparse_lu (SEXP, SEXP, SEXP, SEXP)
SEXP R_dense_matmult (SEXP, SEXP, SEXP, SEXP)
SEXP R_sparse_matmult (SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP R_diagonal_matmult (SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP geMatrix_norm (SEXP, SEXP)
SEXP syMatrix_norm (SEXP, SEXP)
SEXP spMatrix_norm (SEXP, SEXP)
SEXP trMatrix_norm (SEXP, SEXP)
SEXP tpMatrix_norm (SEXP, SEXP)
SEXP R_Matrix_class (SEXP, SEXP)
SEXP R_Matrix_kind (SEXP)
SEXP R_Matrix_shape (SEXP, SEXP)
SEXP R_Matrix_repr (SEXP)
SEXP R_isPerm (SEXP, SEXP)
SEXP R_signPerm (SEXP, SEXP)
SEXP R_invertPerm (SEXP, SEXP, SEXP)
SEXP R_asPerm (SEXP, SEXP, SEXP, SEXP)
SEXP R_sparse_qr (SEXP, SEXP, SEXP)
SEXP geMatrix_rcond (SEXP, SEXP, SEXP)
SEXP syMatrix_rcond (SEXP, SEXP, SEXP)
SEXP spMatrix_rcond (SEXP, SEXP, SEXP)
SEXP poMatrix_rcond (SEXP, SEXP, SEXP)
SEXP ppMatrix_rcond (SEXP, SEXP, SEXP)
SEXP trMatrix_rcond (SEXP, SEXP)
SEXP tpMatrix_rcond (SEXP, SEXP)
SEXP R_dense_skewpart (SEXP, SEXP)
SEXP R_sparse_skewpart (SEXP, SEXP)
SEXP denseLU_solve (SEXP, SEXP)
SEXP denseBunchKaufman_solve (SEXP, SEXP)
SEXP denseCholesky_solve (SEXP, SEXP)
SEXP trMatrix_solve (SEXP, SEXP)
SEXP sparseLU_solve (SEXP, SEXP, SEXP)
SEXP sparseCholesky_solve (SEXP, SEXP, SEXP, SEXP)
SEXP tCMatrix_solve (SEXP, SEXP, SEXP)
SEXP sparseQR_matmult (SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP nCsparse_subassign (SEXP, SEXP, SEXP, SEXP)
SEXP lCsparse_subassign (SEXP, SEXP, SEXP, SEXP)
SEXP iCsparse_subassign (SEXP, SEXP, SEXP, SEXP)
SEXP dCsparse_subassign (SEXP, SEXP, SEXP, SEXP)
SEXP zCsparse_subassign (SEXP, SEXP, SEXP, SEXP)
SEXP R_subscript_1ary (SEXP, SEXP, SEXP)
SEXP R_subscript_1ary_2col (SEXP, SEXP, SEXP)
SEXP R_subscript_2ary (SEXP, SEXP, SEXP)
SEXP R_dense_symmpart (SEXP, SEXP, SEXP)
SEXP R_sparse_symmpart (SEXP, SEXP, SEXP)
SEXP R_dense_transpose (SEXP, SEXP)
SEXP R_sparse_transpose (SEXP, SEXP, SEXP)
SEXP sparseCholesky_updown (SEXP, SEXP, SEXP)
SEXP sparseCholesky_update (SEXP, SEXP, SEXP)
SEXP R_index_triangle (SEXP, SEXP, SEXP, SEXP)
SEXP R_index_diagonal (SEXP, SEXP, SEXP)
SEXP R_nnz (SEXP, SEXP, SEXP)
SEXP R_all0 (SEXP)
SEXP R_any0 (SEXP)
SEXP Mmatrix (SEXP)
SEXP compressed_non_0_ij (SEXP, SEXP)
Return a 2 column matrix '' cbind(i, j) '' of 0-origin index vectors (i,j) which entirely correspond to the (i,j) slots of as(x, "TsparseMatrix") :
SEXP Matrix_expand_pointers (SEXP)
SEXP m_encodeInd (SEXP, SEXP, SEXP, SEXP)
Encode Matrix index (i,j) |--> i + j * nrow {i,j : 0-origin}.
SEXP m_encodeInd2 (SEXP, SEXP, SEXP, SEXP, SEXP)
Encode Matrix index (i,j) |--> i + j * nrow {i,j : 0-origin}.
SEXP Matrix_rle_d (SEXP, SEXP)
SEXP Matrix_rle_i (SEXP, SEXP)
SEXP R_Dim_validate (SEXP)
SEXP R_DimNames_validate (SEXP, SEXP)
SEXP R_DimNames_fixup (SEXP)
SEXP Matrix_validate (SEXP)
SEXP nMatrix_validate (SEXP)
SEXP lMatrix_validate (SEXP)
SEXP iMatrix_validate (SEXP)
SEXP dMatrix_validate (SEXP)
SEXP zMatrix_validate (SEXP)
SEXP generalMatrix_validate (SEXP)
SEXP symmetricMatrix_validate (SEXP)
SEXP triangularMatrix_validate (SEXP)
SEXP unpackedMatrix_validate (SEXP)
SEXP packedMatrix_validate (SEXP)
SEXP CsparseMatrix_validate (SEXP)
SEXP RsparseMatrix_validate (SEXP)
SEXP TsparseMatrix_validate (SEXP)
SEXP diagonalMatrix_validate (SEXP)
SEXP indMatrix_validate (SEXP)
SEXP pMatrix_validate (SEXP)
SEXP sCMatrix_validate (SEXP)
SEXP tCMatrix_validate (SEXP)
SEXP sRMatrix_validate (SEXP)
SEXP tRMatrix_validate (SEXP)
SEXP sTMatrix_validate (SEXP)
SEXP tTMatrix_validate (SEXP)
SEXP xgCMatrix_validate (SEXP)
SEXP xsCMatrix_validate (SEXP)
SEXP xtCMatrix_validate (SEXP)
SEXP xgRMatrix_validate (SEXP)
SEXP xsRMatrix_validate (SEXP)
SEXP xtRMatrix_validate (SEXP)
SEXP xgTMatrix_validate (SEXP)
SEXP xsTMatrix_validate (SEXP)
SEXP xtTMatrix_validate (SEXP)
SEXP xpoMatrix_validate (SEXP)
SEXP xppMatrix_validate (SEXP)
SEXP xpCMatrix_validate (SEXP)
SEXP xpRMatrix_validate (SEXP)
SEXP xpTMatrix_validate (SEXP)
SEXP corMatrix_validate (SEXP)
SEXP copMatrix_validate (SEXP)
SEXP sparseVector_validate (SEXP)
SEXP lsparseVector_validate (SEXP)
SEXP isparseVector_validate (SEXP)
SEXP dsparseVector_validate (SEXP)
SEXP zsparseVector_validate (SEXP)
SEXP MatrixFactorization_validate (SEXP)
SEXP denseSchur_validate (SEXP)
SEXP denseQR_validate (SEXP)
SEXP denseLU_validate (SEXP)
SEXP denseBunchKaufman_validate (SEXP)
SEXP denseCholesky_validate (SEXP)
SEXP sparseQR_validate (SEXP)
SEXP sparseLU_validate (SEXP)
SEXP sparseCholesky_validate (SEXP)
SEXP simplicialCholesky_validate (SEXP)
SEXP supernodalCholesky_validate (SEXP)
SEXP R_Matrix_version (void)
void attribute_visible R_init_Matrix (DllInfo *info)
void R_unload_Matrix (DllInfo *info)
Variables
static R_CallMethodDef CallMethodTable []
static const R_ExternalMethodDef ExternalMethodTable []
SEXP Matrix_DimNamesSym
SEXP Matrix_DimSym
SEXP Matrix_LSym
SEXP Matrix_RSym
SEXP Matrix_USym
SEXP Matrix_VSym
SEXP Matrix_betaSym
SEXP Matrix_colcountSym
SEXP Matrix_diagSym
SEXP Matrix_factorsSym
SEXP Matrix_iSym
SEXP Matrix_isllSym
SEXP Matrix_ismtSym
SEXP Matrix_jSym
SEXP Matrix_kindSym
SEXP Matrix_lengthSym
SEXP Matrix_logarithmSym
SEXP Matrix_marginSym
SEXP Matrix_maxcsizeSym
SEXP Matrix_maxesizeSym
SEXP Matrix_minorSym
SEXP Matrix_nextSym
SEXP Matrix_nzSym
SEXP Matrix_offSym
SEXP Matrix_orderingSym
SEXP Matrix_pSym
SEXP Matrix_permSym
SEXP Matrix_piSym
SEXP Matrix_prevSym
SEXP Matrix_pxSym
SEXP Matrix_qSym
SEXP Matrix_sSym
SEXP Matrix_sdSym
SEXP Matrix_superSym
SEXP Matrix_transSym
SEXP Matrix_uploSym
SEXP Matrix_valuesSym
SEXP Matrix_vectorsSym
SEXP Matrix_xSym
SEXP Matrix_LChar
SEXP Matrix_TChar
SEXP Matrix_UChar
Rcomplex Matrix_zzero
Rcomplex Matrix_zunit
Rcomplex Matrix_zna
Macro Definition Documentation
CALL_METHOD
#define CALL_METHOD (name, n)
Value:
{#name, (DL_FUNC) &name, n}
Definition at line 294 of file init.c.
EXTERNAL_METHOD
#define EXTERNAL_METHOD (name, n)
Value:
{#name, (DL_FUNC) &name, n}
Definition at line 295 of file init.c.
REGISTER
#define REGISTER (name)
Value:
R_RegisterCCallable("Matrix", #name, (DL_FUNC) name)
Definition at line 296 of file init.c.
Referenced by R_init_Matrix().
Function Documentation
compressed_non_0_ij()
SEXP compressed_non_0_ij (SEXP x, SEXP colP)
Return a 2 column matrix '' cbind(i, j) '' of 0-origin index vectors (i,j) which entirely correspond to the (i,j) slots of as(x, "TsparseMatrix") :
Definition at line 447 of file utils-R.c.
References expand_cmprPt(), GET_SLOT, Matrix_DimSym, Matrix_iSym, Matrix_jSym, and Matrix_pSym.
copMatrix_validate()
SEXP copMatrix_validate (SEXP obj)
Definition at line 1059 of file validity.c.
References _, DIM, GET_SLOT, Matrix_sdSym, Matrix_xSym, RMK, RMKMS, TYPEOF, and UPLO.
corMatrix_validate()
SEXP corMatrix_validate (SEXP obj)
Definition at line 1035 of file validity.c.
References _, DIM, GET_SLOT, Matrix_sdSym, Matrix_xSym, RMK, RMKMS, and TYPEOF.
Csparse_dmperm()
SEXP Csparse_dmperm (SEXP x, SEXP nans, SEXP seed)
Definition at line 344 of file Csparse.c.
References Matrix_cs_dmperm_results::cc, CXSPARSE_XTYPE_SET, Matrix_cs_sparse::m, M2CXS(), Matrix_cs_dfree(), Matrix_cs_dmperm(), Matrix_cs_sparse::n, Matrix_cs_dmperm_results::nb, Matrix_cs_dmperm_results::p, Matrix_cs_dmperm_results::q, Matrix_cs_dmperm_results::r, Matrix_cs_dmperm_results::rr, Matrix_cs_dmperm_results::s, and Matrix_cs_sparse::xtype.
Csparse_writeMM()
SEXP Csparse_writeMM (SEXP obj, SEXP file)
Definition at line 408 of file Csparse.c.
References _, c, M2CHS(), Matrix_class(), sparse_as_general(), sparse_as_kind(), and valid_sparse_compressed.
CsparseMatrix_validate()
SEXP CsparseMatrix_validate (SEXP obj)
Definition at line 299 of file validity.c.
References _, DIM, GET_SLOT, Matrix_iSym, Matrix_pSym, RMKMS, and TYPEOF.
CsparseMatrix_validate_maybe_sorting()
SEXP CsparseMatrix_validate_maybe_sorting (SEXP x)
Definition at line 64 of file Csparse.c.
References _, c, checkpi(), GET_SLOT, M2CHS(), Matrix_DimSym, Matrix_iSym, Matrix_pSym, and TYPEOF.
dCsparse_subassign()
SEXP dCsparse_subassign (SEXP , SEXP , SEXP , SEXP)
denseBunchKaufman_determinant()
SEXP denseBunchKaufman_determinant (SEXP s_trf, SEXP s_logarithm)
Definition at line 76 of file determinant.c.
References c, det(), DETERMINANT_START, GET_SLOT, Matrix_permSym, Matrix_xSym, TRANS, TYPEOF, and UPLO.
denseBunchKaufman_expand()
SEXP denseBunchKaufman_expand (SEXP s_trf)
Definition at line 6 of file expand.c.
References cl, DIM, GET_SLOT, Matrix_iSym, Matrix_permSym, Matrix_pSym, Matrix_xSym, newObject(), SET_DIAG, SET_DIM, SET_SLOT, SET_TRANS, SET_UPLO, TEMPLATE, TRANS, TYPEOF, and UPLO.
denseBunchKaufman_solve()
SEXP denseBunchKaufman_solve (SEXP s_a, SEXP s_b)
Definition at line 130 of file solve.c.
References duplicateVector(), ERROR_LAPACK_1, ERROR_LAPACK_2, FCONE, GET_SLOT, Matrix_permSym, Matrix_xSym, newObject(), SET_DIM, SET_SLOT, SET_TRANS, SET_UPLO, SOLVE_FINISH, SOLVE_START, TRANS, TYPEOF, and UPLO.
denseBunchKaufman_validate()
SEXP denseBunchKaufman_validate (SEXP obj)
Definition at line 1288 of file validity.c.
References _, DIM, GET_SLOT, HAS_SLOT, Matrix_permSym, Matrix_transSym, Matrix_uploSym, Matrix_xSym, RMKMS, and TYPEOF.
denseCholesky_determinant()
SEXP denseCholesky_determinant (SEXP s_trf, SEXP s_logarithm)
Definition at line 196 of file determinant.c.
References det(), DETERMINANT_START, GET_SLOT, Matrix_xSym, TYPEOF, and UPLO.
denseCholesky_diag_get()
SEXP denseCholesky_diag_get (SEXP s_trf, SEXP s_root)
Definition at line 666 of file diag.c.
References DIM, GET_SLOT, Matrix_xSym, TYPEOF, and UPLO.
denseCholesky_solve()
SEXP denseCholesky_solve (SEXP s_a, SEXP s_b)
Definition at line 257 of file solve.c.
References drowperm2(), dsymperm1(), dsymperm2(), ERROR_LAPACK_1, ERROR_LAPACK_2, FCONE, GET_SLOT, Matrix_permSym, Matrix_xSym, newObject(), SET_DIM, SET_SLOT, SET_UPLO, SOLVE_FINISH, SOLVE_START, TYPEOF, UPLO, zrowperm2(), zsymperm1(), and zsymperm2().
denseCholesky_validate()
SEXP denseCholesky_validate (SEXP obj)
Definition at line 1348 of file validity.c.
References _, DIM, FRMKMS, GET_SLOT, Matrix_Calloc, Matrix_Free, Matrix_permSym, Matrix_uploSym, Matrix_xSym, RMK, RMKMS, and TYPEOF.
denseLU_determinant()
SEXP denseLU_determinant (SEXP s_trf, SEXP s_logarithm)
Definition at line 28 of file determinant.c.
References det(), DETERMINANT_START, GET_SLOT, Matrix_permSym, Matrix_xSym, and TYPEOF.
denseLU_solve()
SEXP denseLU_solve (SEXP s_a, SEXP s_b)
Definition at line 33 of file solve.c.
References duplicateVector(), ERROR_LAPACK_1, ERROR_LAPACK_2, FCONE, GET_SLOT, Matrix_permSym, Matrix_xSym, newObject(), SET_DIM, SET_SLOT, SOLVE_FINISH, SOLVE_START, and TYPEOF.
denseLU_validate()
SEXP denseLU_validate (SEXP obj)
Definition at line 1259 of file validity.c.
References _, DIM, GET_SLOT, Matrix_permSym, Matrix_xSym, RMKMS, and TYPEOF.
denseQR_validate()
SEXP denseQR_validate (SEXP obj)
Definition at line 1217 of file validity.c.
References _, DIM, FRMKMS, GET_SLOT, Matrix_betaSym, Matrix_Calloc, Matrix_Free, Matrix_permSym, Matrix_xSym, RMKMS, and TYPEOF.
denseSchur_validate()
SEXP denseSchur_validate (SEXP obj)
Definition at line 1178 of file validity.c.
References _, DIM, GET_SLOT, Matrix_valuesSym, Matrix_vectorsSym, Matrix_xSym, RMKMS, and TYPEOF.
dgCMatrix_cholsol()
SEXP dgCMatrix_cholsol (SEXP at, SEXP b)
Definition at line 130 of file Csparse.c.
References _, c, CHF2M(), and M2CHS().
dgCMatrix_lusol()
SEXP dgCMatrix_lusol (SEXP a, SEXP b)
Definition at line 82 of file Csparse.c.
References _, CXSPARSE_REAL, CXSPARSE_XTYPE_SET, Matrix_cs_sparse::m, M2CXS(), Matrix_cs_lusol(), Matrix_cs_sparse::n, and TYPEOF.
dgCMatrix_qrsol()
SEXP dgCMatrix_qrsol (SEXP a, SEXP b, SEXP order)
Definition at line 101 of file Csparse.c.
References _, CXSPARSE_REAL, CXSPARSE_XTYPE_SET, Matrix_cs_sparse::m, M2CXS(), Matrix_cs_qrsol(), Matrix_cs_sparse::n, and TYPEOF.
diagonalMatrix_validate()
SEXP diagonalMatrix_validate (SEXP obj)
Definition at line 437 of file validity.c.
References _, DIM, GET_SLOT, Matrix_diagSym, Matrix_xSym, RMKMS, and TYPEOF.
dMatrix_validate()
SEXP dMatrix_validate (SEXP)
dsparseVector_validate()
SEXP dsparseVector_validate (SEXP)
dtCMatrix_diag()
SEXP dtCMatrix_diag (SEXP obj, SEXP op)
Definition at line 211 of file Csparse.c.
References _, GET_SLOT, Matrix_permSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, strmatch(), and TYPEOF.
geMatrix_norm()
SEXP geMatrix_norm (SEXP s_obj, SEXP s_type)
Definition at line 50 of file norm.c.
References DIM, FCONE, GET_SLOT, La_norm_type(), Matrix_xSym, and TYPEOF.
geMatrix_rcond()
SEXP geMatrix_rcond (SEXP s_obj, SEXP trf, SEXP s_type)
Definition at line 40 of file rcond.c.
References _, DIM, FCONE, GET_SLOT, La_rcond_type(), Matrix_xSym, and TYPEOF.
generalMatrix_validate()
SEXP generalMatrix_validate (SEXP obj)
Definition at line 165 of file validity.c.
References _, GET_SLOT, Matrix_factorsSym, RMKMS, and TYPEOF.
Referenced by symmetricMatrix_validate().
iCsparse_subassign()
SEXP iCsparse_subassign (SEXP , SEXP , SEXP , SEXP)
iMatrix_validate()
SEXP iMatrix_validate (SEXP)
indMatrix_validate()
SEXP indMatrix_validate (SEXP obj)
Definition at line 461 of file validity.c.
References _, DIM, GET_SLOT, Matrix_marginSym, Matrix_permSym, RMKMS, and TYPEOF.
isparseVector_validate()
SEXP isparseVector_validate (SEXP)
lCsparse_subassign()
SEXP lCsparse_subassign (SEXP , SEXP , SEXP , SEXP)
lMatrix_validate()
SEXP lMatrix_validate (SEXP)
lsparseVector_validate()
SEXP lsparseVector_validate (SEXP)
m_encodeInd()
SEXP m_encodeInd (SEXP ij, SEXP di, SEXP orig_1, SEXP chk_bnds)
Encode Matrix index (i,j) |--> i + j * nrow {i,j : 0-origin}.
Parameters
ij 2-column integer matrix
di dim(.), i.e. length 2 integer vector
chk_bnds logical indicating 0 <= ij[,k] < di[k] need to be checked.
Returns
encoded index; integer if prod(dim) is small; double otherwise
Definition at line 493 of file utils-R.c.
References _, do_ii_FILL, and TYPEOF.
m_encodeInd2()
SEXP m_encodeInd2 (SEXP i, SEXP j, SEXP di, SEXP orig_1, SEXP chk_bnds)
Encode Matrix index (i,j) |--> i + j * nrow {i,j : 0-origin}.
Parameters
i integer vector
j integer vector of same length as 'i'
orig_1 logical: if TRUE, "1-origin" otherwise "0-origin"
di dim(.), i.e. length 2 integer vector
chk_bnds logical indicating 0 <= ij[,k] < di[k] need to be checked.
Returns
encoded index; integer if prod(dim) is small; double otherwise
Definition at line 571 of file utils-R.c.
References _, do_ii_FILL, and TYPEOF.
Matrix_expand_pointers()
SEXP Matrix_expand_pointers (SEXP pP)
Definition at line 473 of file utils-R.c.
References expand_cmprPt().
Matrix_rle_d()
SEXP Matrix_rle_d (SEXP , SEXP)
Matrix_rle_i()
SEXP Matrix_rle_i (SEXP , SEXP)
Matrix_validate()
SEXP Matrix_validate (SEXP obj)
Definition at line 136 of file validity.c.
References Dim_validate(), DimNames_validate(), GET_SLOT, Matrix_DimNamesSym, and Matrix_DimSym.
Referenced by MatrixFactorization_validate().
MatrixFactorization_validate()
SEXP MatrixFactorization_validate (SEXP obj)
Definition at line 1173 of file validity.c.
References Matrix_validate().
Mmatrix()
SEXP Mmatrix (SEXP args)
Definition at line 290 of file utils-R.c.
References _, and TYPEOF.
nCsparse_subassign()
SEXP nCsparse_subassign (SEXP , SEXP , SEXP , SEXP)
nMatrix_validate()
SEXP nMatrix_validate (SEXP)
packedMatrix_validate()
SEXP packedMatrix_validate (SEXP obj)
Definition at line 290 of file validity.c.
References _, DIM, GET_SLOT, Matrix_xSym, and RMKMS.
pMatrix_validate()
SEXP pMatrix_validate (SEXP obj)
Definition at line 496 of file validity.c.
References _, DIM, FRMKMS, GET_SLOT, Matrix_Calloc, Matrix_Free, Matrix_permSym, and RMKMS.
poMatrix_rcond()
SEXP poMatrix_rcond (SEXP s_obj, SEXP trf, SEXP s_type)
Definition at line 154 of file rcond.c.
References DIM, FCONE, GET_SLOT, La_rcond_type(), Matrix_xSym, TYPEOF, and UPLO.
ppMatrix_rcond()
SEXP ppMatrix_rcond (SEXP s_obj, SEXP trf, SEXP s_type)
Definition at line 187 of file rcond.c.
References DIM, FCONE, GET_SLOT, La_rcond_type(), Matrix_xSym, TYPEOF, and UPLO.
R_all0()
SEXP R_all0 (SEXP x)
Definition at line 196 of file utils-R.c.
References _, FALSE_, TRUE_, and TYPEOF.
R_any0()
SEXP R_any0 (SEXP x)
Definition at line 242 of file utils-R.c.
References _, FALSE_, TRUE_, and TYPEOF.
R_asPerm()
SEXP R_asPerm (SEXP s_p, SEXP s_off, SEXP s_ioff, SEXP s_n)
Definition at line 133 of file perm.c.
References _, asPerm(), and TYPEOF.
R_bind()
SEXP R_bind (SEXP args)
Definition at line 946 of file bind.c.
References bind().
R_dense_as_general()
SEXP R_dense_as_general (SEXP s_from)
Definition at line 2292 of file coerce.c.
References dense_as_general(), Matrix_class(), and valid_dense.
R_dense_as_kind()
SEXP R_dense_as_kind (SEXP s_from, SEXP s_kind)
Definition at line 2066 of file coerce.c.
References dense_as_kind(), Matrix_class(), valid_dense, and VALID_KIND.
R_dense_as_packed()
SEXP R_dense_as_packed (SEXP s_from, SEXP s_uplo, SEXP s_trans, SEXP s_diag)
Definition at line 2717 of file coerce.c.
References dense_as_packed(), Matrix_class(), valid_dense, VALID_DIAG, VALID_TRANS, and VALID_UPLO.
R_dense_as_sparse()
SEXP R_dense_as_sparse (SEXP s_from, SEXP s_repr)
Definition at line 1735 of file coerce.c.
References dense_as_sparse(), Matrix_class(), valid_dense, and VALID_REPR.
R_dense_as_unpacked()
SEXP R_dense_as_unpacked (SEXP s_from)
Definition at line 2648 of file coerce.c.
References dense_as_unpacked(), Matrix_class(), and valid_dense.
R_dense_band()
SEXP R_dense_band (SEXP s_from, SEXP s_a, SEXP s_b)
Definition at line 350 of file band.c.
References _, dense_band(), DIM, matrix_as_dense(), Matrix_class(), TYPEOF, and valid_dense.
R_dense_bunchkaufman()
SEXP R_dense_bunchkaufman (SEXP s_obj, SEXP s_warn, SEXP s_uplo, SEXP s_trans)
Definition at line 95 of file BunchKaufman.c.
References dense_bunchkaufman(), get_factor(), Matrix_class(), set_factor(), valid_dense, VALID_TRANS, and VALID_UPLO.
R_dense_cholesky()
SEXP R_dense_cholesky (SEXP s_obj, SEXP s_warn, SEXP s_pivot, SEXP s_tol, SEXP s_uplo)
Definition at line 197 of file Cholesky.c.
References _, dense_cholesky(), get_factor(), Matrix_class(), set_factor(), TRANS, valid_dense, and VALID_UPLO.
R_dense_diag_get()
SEXP R_dense_diag_get (SEXP s_obj, SEXP s_names)
Definition at line 205 of file diag.c.
References dense_diag_get(), Matrix_class(), valid_dense, and VALID_LOGIC2.
R_dense_diag_set()
SEXP R_dense_diag_set (SEXP s_from, SEXP s_value)
Definition at line 508 of file diag.c.
References _, dense_as_general(), dense_as_kind(), dense_diag_set(), DIM, kindToType(), Matrix_class(), TRANS, TYPEOF, typeToKind(), and valid_dense.
R_dense_expm()
SEXP R_dense_expm (SEXP s_obj)
Definition at line 466 of file expm.c.
References dense_expm(), Matrix_class(), and valid_dense.
R_dense_force_canonical()
SEXP R_dense_force_canonical (SEXP s_from, SEXP s_check)
Definition at line 188 of file forceCanonical.c.
References dense_force_canonical(), Matrix_class(), valid_dense, and VALID_LOGIC2.
R_dense_force_symmetric()
SEXP R_dense_force_symmetric (SEXP s_from, SEXP s_uplo, SEXP s_trans)
Definition at line 401 of file forceSymmetric.c.
References dense_force_symmetric(), Matrix_class(), valid_dense, VALID_TRANS, and VALID_UPLO.
R_dense_is_canonical()
SEXP R_dense_is_canonical (SEXP s_obj)
Definition at line 86 of file isCanonical.c.
References dense_is_canonical(), Matrix_class(), and valid_dense.
R_dense_is_diagonal()
SEXP R_dense_is_diagonal (SEXP s_obj)
Definition at line 86 of file isDiagonal.c.
References dense_is_diagonal(), matrix_as_dense(), Matrix_class(), TYPEOF, and valid_dense.
R_dense_is_symmetric()
SEXP R_dense_is_symmetric (SEXP s_obj, SEXP s_trans, SEXP s_exact, SEXP s_checkDN)
Definition at line 305 of file isSymmetric.c.
References dense_is_symmetric(), matrix_as_dense(), Matrix_class(), TYPEOF, valid_dense, VALID_LOGIC2, and VALID_TRANS.
R_dense_is_triangular()
SEXP R_dense_is_triangular (SEXP s_obj, SEXP s_upper)
Definition at line 166 of file isTriangular.c.
References dense_is_triangular(), matrix_as_dense(), Matrix_class(), Matrix_kindSym, TYPEOF, valid_dense, and VALID_LOGIC3.
R_dense_lu()
SEXP R_dense_lu (SEXP s_obj, SEXP s_warn)
Definition at line 154 of file lu.c.
References dense_lu(), get_factor(), Matrix_class(), set_factor(), and valid_dense.
R_dense_marginsum()
SEXP R_dense_marginsum (SEXP s_obj, SEXP s_margin, SEXP s_narm, SEXP s_mean)
Definition at line 729 of file colSums.c.
References dense_marginsum(), Matrix_class(), valid_dense, VALID_LOGIC2, and VALID_MARGIN.
R_dense_matmult()
SEXP R_dense_matmult (SEXP s_x, SEXP s_y, SEXP s_xtrans, SEXP s_ytrans)
Definition at line 711 of file matmult.c.
References dense_as_general(), DO_AS, DO_S3, DO_TR, geMatrix_matmult(), matmultDim(), Matrix_class(), spMatrix_matmult(), syMatrix_matmult(), tpMatrix_matmult(), trMatrix_matmult(), and valid_matmult.
R_dense_prod()
SEXP R_dense_prod (SEXP s_obj, SEXP s_narm)
Definition at line 898 of file Summary.c.
References dense_prod(), Matrix_class(), valid_dense, and VALID_LOGIC2.
R_dense_schur()
SEXP R_dense_schur (SEXP s_obj, SEXP s_warn, SEXP s_vectors)
Definition at line 141 of file Schur.c.
References dense_schur(), get_factor(), Matrix_class(), set_factor(), and valid_dense.
R_dense_skewpart()
SEXP R_dense_skewpart (SEXP s_from, SEXP s_trans)
Definition at line 482 of file skewpart.c.
References dense_skewpart(), Matrix_class(), valid_dense, and VALID_TRANS.
R_dense_sum()
SEXP R_dense_sum (SEXP s_obj, SEXP s_narm)
Definition at line 445 of file Summary.c.
References dense_sum(), Matrix_class(), valid_dense, and VALID_LOGIC2.
R_dense_symmpart()
SEXP R_dense_symmpart (SEXP s_from, SEXP s_uplo, SEXP s_trans)
Definition at line 661 of file symmpart.c.
References dense_symmpart(), Matrix_class(), valid_dense, VALID_TRANS, and VALID_UPLO.
R_dense_transpose()
SEXP R_dense_transpose (SEXP s_from, SEXP s_trans)
Definition at line 170 of file t.c.
References dense_transpose(), Matrix_class(), valid_dense, and VALID_TRANS.
R_diagonal_as_dense()
SEXP R_diagonal_as_dense (SEXP s_from, SEXP s_kind, SEXP s_shape, SEXP s_packed, SEXP s_uplo, SEXP s_trans)
Definition at line 666 of file coerce.c.
References diagonal_as_dense(), Matrix_class(), valid_diagonal, VALID_KIND, VALID_LOGIC2, VALID_SHAPE, VALID_TRANS, and VALID_UPLO.
R_diagonal_as_kind()
SEXP R_diagonal_as_kind (SEXP s_from, SEXP s_kind)
Definition at line 2211 of file coerce.c.
References diagonal_as_kind(), Matrix_class(), valid_diagonal, and VALID_KIND.
R_diagonal_as_sparse()
SEXP R_diagonal_as_sparse (SEXP s_from, SEXP s_kind, SEXP s_shape, SEXP s_repr, SEXP s_uplo, SEXP s_trans)
Definition at line 1898 of file coerce.c.
References diagonal_as_sparse(), Matrix_class(), valid_diagonal, VALID_KIND, VALID_REPR, VALID_SHAPE, VALID_TRANS, and VALID_UPLO.
R_diagonal_as_Vector()
SEXP R_diagonal_as_Vector (SEXP s_from)
Definition at line 3368 of file coerce.c.
References diagonal_as_Vector(), Matrix_class(), and valid_diagonal.
R_diagonal_matmult()
SEXP R_diagonal_matmult (SEXP s_x, SEXP s_y, SEXP s_xtrans, SEXP s_ytrans, SEXP s_boolean)
Definition at line 1310 of file matmult.c.
References _, Csparse_colscale(), Csparse_rowscale(), dense_colscale(), dense_rowscale(), DIAG, DIMNAMES, DO_AS, DO_S3, GET_SLOT, matmultDim(), matmultDN(), Matrix_class(), Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_xSym, newObject(), SET_DIAG, SET_DIM, SET_SLOT, SET_UPLO, sparse_as_kind(), sparse_dropzero(), Tsparse_rowscale(), TYPEOF, UPLO, and valid_matmult.
R_Dim_prod()
SEXP R_Dim_prod (SEXP dim)
Definition at line 5 of file attrib.c.
References _, and Matrix_offSym.
R_Dim_validate()
SEXP R_Dim_validate (SEXP dim)
Definition at line 50 of file validity.c.
References Dim_validate().
R_DimNames_fixup()
SEXP R_DimNames_fixup (SEXP dimnames)
Definition at line 95 of file validity.c.
References TYPEOF.
R_DimNames_is_symmetric()
SEXP R_DimNames_is_symmetric (SEXP dn)
Definition at line 64 of file attrib.c.
References DimNames_is_symmetric().
R_DimNames_validate()
SEXP R_DimNames_validate (SEXP dimnames, SEXP dim)
Definition at line 89 of file validity.c.
References DimNames_validate().
R_index_as_dense()
SEXP R_index_as_dense (SEXP s_from, SEXP s_kind)
Definition at line 740 of file coerce.c.
References index_as_dense(), Matrix_class(), valid_index, and VALID_KIND.
R_index_as_kind()
SEXP R_index_as_kind (SEXP s_from, SEXP s_kind)
Definition at line 2227 of file coerce.c.
References index_as_kind(), Matrix_class(), valid_index, and VALID_KIND.
R_index_as_sparse()
SEXP R_index_as_sparse (SEXP s_from, SEXP s_kind, SEXP s_repr)
Definition at line 1989 of file coerce.c.
References index_as_sparse(), Matrix_class(), valid_index, VALID_KIND, and VALID_REPR.
R_index_as_Vector()
SEXP R_index_as_Vector (SEXP s_from)
Definition at line 3440 of file coerce.c.
References index_as_Vector(), Matrix_class(), and valid_index.
R_index_diagonal()
SEXP R_index_diagonal (SEXP s_n, SEXP s_packed, SEXP s_upper)
Definition at line 91 of file utils-R.c.
References _, and DO_INDEX.
R_index_triangle()
SEXP R_index_triangle (SEXP s_n, SEXP s_packed, SEXP s_upper, SEXP s_diag)
Definition at line 4 of file utils-R.c.
References _, and DO_INDEX.
R_init_Matrix()
void attribute_visible R_init_Matrix (DllInfo * info)
Definition at line 645 of file init.c.
References c, CallMethodTable, cholmod_dense_as_sexp(), cholmod_factor_as_sexp(), cholmod_factor_ldetA(), cholmod_factor_update(), cholmod_sparse_as_sexp(), cholmod_triplet_as_sexp(), ExternalMethodTable, Matrix_betaSym, Matrix_cholmod_start(), Matrix_colcountSym, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_isllSym, Matrix_ismtSym, Matrix_iSym, Matrix_jSym, Matrix_kindSym, Matrix_LChar, Matrix_lengthSym, Matrix_logarithmSym, Matrix_LSym, Matrix_marginSym, Matrix_maxcsizeSym, Matrix_maxesizeSym, Matrix_minorSym, Matrix_nextSym, Matrix_nzSym, Matrix_offSym, Matrix_orderingSym, Matrix_permSym, Matrix_piSym, Matrix_prevSym, Matrix_pSym, Matrix_pxSym, Matrix_qSym, Matrix_RSym, Matrix_sdSym, Matrix_sSym, Matrix_superSym, Matrix_TChar, Matrix_transSym, Matrix_UChar, Matrix_uploSym, Matrix_USym, Matrix_valuesSym, Matrix_vectorsSym, Matrix_VSym, Matrix_xSym, Matrix_zna, Matrix_zunit, Matrix_zzero, numeric_as_cholmod_dense(), REGISTER, sexp_as_cholmod_dense(), sexp_as_cholmod_factor(), sexp_as_cholmod_sparse(), and sexp_as_cholmod_triplet().
R_invertPerm()
SEXP R_invertPerm (SEXP s_p, SEXP s_off, SEXP s_ioff)
Definition at line 109 of file perm.c.
References _, invertPerm(), and TYPEOF.
R_isPerm()
SEXP R_isPerm (SEXP s_p, SEXP s_off)
Definition at line 75 of file perm.c.
References _, isPerm(), and TYPEOF.
R_Matrix_as_Csparse()
SEXP R_Matrix_as_Csparse (SEXP s_from)
Definition at line 3638 of file coerce.c.
References dense_as_sparse(), diagonal_as_sparse(), index_as_sparse(), Matrix_class(), sparse_as_Csparse(), and valid_matrix.
R_matrix_as_dense()
SEXP R_matrix_as_dense (SEXP s_from, SEXP s_zzz, SEXP s_uplo, SEXP s_trans, SEXP s_diag, SEXP s_margin)
Definition at line 377 of file coerce.c.
References _, ERROR_INVALID_TYPE, matrix_as_dense(), TYPEOF, VALID_DIAG, VALID_MARGIN, VALID_TRANS, and VALID_UPLO.
R_Matrix_as_general()
SEXP R_Matrix_as_general (SEXP s_from, SEXP s_kind)
Definition at line 3798 of file coerce.c.
References dense_as_general(), dense_as_kind(), diagonal_as_sparse(), index_as_sparse(), kindToType(), Matrix_class(), sparse_as_general(), sparse_as_kind(), VALID_KIND, and valid_matrix.
R_Matrix_as_kind()
SEXP R_Matrix_as_kind (SEXP s_from, SEXP s_kind, SEXP s_sparse)
Definition at line 3741 of file coerce.c.
References dense_as_kind(), dense_as_sparse(), diagonal_as_dense(), diagonal_as_kind(), diagonal_as_sparse(), index_as_dense(), index_as_sparse(), Matrix_class(), sparse_as_dense(), sparse_as_kind(), VALID_KIND, VALID_LOGIC3, and valid_matrix.
R_Matrix_as_matrix()
SEXP R_Matrix_as_matrix (SEXP s_from)
Definition at line 3516 of file coerce.c.
References dense_as_general(), diagonal_as_dense(), DIMNAMES, DimNames_is_trivial(), duplicateVector(), GET_SLOT, index_as_dense(), Matrix_class(), Matrix_DimSym, Matrix_xSym, naToUnit(), sparse_as_dense(), and valid_matrix.
R_Matrix_as_packed()
SEXP R_Matrix_as_packed (SEXP s_from)
Definition at line 3609 of file coerce.c.
References _, dense_as_packed(), diagonal_as_dense(), Matrix_class(), sparse_as_dense(), and valid_matrix.
R_Matrix_as_Rsparse()
SEXP R_Matrix_as_Rsparse (SEXP s_from)
Definition at line 3663 of file coerce.c.
References dense_as_sparse(), diagonal_as_sparse(), index_as_sparse(), Matrix_class(), sparse_as_Rsparse(), and valid_matrix.
R_matrix_as_sparse()
SEXP R_matrix_as_sparse (SEXP s_from, SEXP s_zzz, SEXP s_uplo, SEXP s_trans, SEXP s_diag, SEXP s_margin)
Definition at line 1317 of file coerce.c.
References _, ERROR_INVALID_TYPE, matrix_as_sparse(), TYPEOF, VALID_DIAG, VALID_MARGIN, VALID_TRANS, and VALID_UPLO.
R_Matrix_as_Tsparse()
SEXP R_Matrix_as_Tsparse (SEXP s_from)
Definition at line 3688 of file coerce.c.
References dense_as_sparse(), diagonal_as_sparse(), index_as_sparse(), Matrix_class(), sparse_as_Tsparse(), and valid_matrix.
R_Matrix_as_unpacked()
SEXP R_Matrix_as_unpacked (SEXP s_from)
Definition at line 3583 of file coerce.c.
References dense_as_unpacked(), diagonal_as_dense(), index_as_dense(), Matrix_class(), sparse_as_dense(), and valid_matrix.
R_Matrix_as_Vector()
SEXP R_Matrix_as_Vector (SEXP s_from)
Definition at line 3713 of file coerce.c.
References dense_as_sparse(), diagonal_as_Vector(), index_as_Vector(), Matrix_class(), sparse_as_Vector(), and valid_matrix.
R_Matrix_as_vector()
SEXP R_Matrix_as_vector (SEXP s_from)
Definition at line 3447 of file coerce.c.
References dense_as_general(), diagonal_as_dense(), duplicateVector(), GET_SLOT, index_as_dense(), Matrix_class(), Matrix_xSym, naToUnit(), sparse_as_dense(), and valid_matrix.
R_Matrix_class()
SEXP R_Matrix_class (SEXP s_obj, SEXP s_mode)
Definition at line 185 of file objects.c.
References Matrix_class(), and valid_matrix_or_vector.
R_Matrix_kind()
SEXP R_Matrix_kind (SEXP s_obj)
Definition at line 191 of file objects.c.
References Matrix_kind().
R_Matrix_repr()
SEXP R_Matrix_repr (SEXP s_obj)
Definition at line 203 of file objects.c.
References Matrix_repr().
R_Matrix_shape()
SEXP R_Matrix_shape (SEXP s_obj, SEXP s_mode)
Definition at line 197 of file objects.c.
References Matrix_shape().
R_Matrix_version()
SEXP R_Matrix_version (void)
Definition at line 4 of file version.c.
References MATRIX_ABI_VERSION, MATRIX_PACKAGE_VERSION, and MATRIX_SUITESPARSE_VERSION.
R_nnz()
SEXP R_nnz (SEXP s_x, SEXP s_countNA, SEXP s_nnzmax)
Definition at line 143 of file utils-R.c.
References SWITCH4, TEMPLATE, TYPEOF, and typeToKind().
R_set_factor()
SEXP R_set_factor (SEXP s_obj, SEXP s_nm, SEXP s_val, SEXP s_warn)
Definition at line 220 of file attrib.c.
References _, Matrix_factorsSym, set_factor(), and TYPEOF.
R_signPerm()
SEXP R_signPerm (SEXP s_p, SEXP s_off)
Definition at line 92 of file perm.c.
References _, signPerm(), and TYPEOF.
R_sparse_aggregate()
SEXP R_sparse_aggregate (SEXP s_from)
Definition at line 86 of file aggregate.c.
References Matrix_class(), sparse_aggregate(), and valid_sparse.
R_sparse_as_Csparse()
SEXP R_sparse_as_Csparse (SEXP s_from)
Definition at line 2841 of file coerce.c.
References Matrix_class(), sparse_as_Csparse(), and valid_sparse.
R_sparse_as_dense()
SEXP R_sparse_as_dense (SEXP s_from, SEXP s_packed)
Definition at line 589 of file coerce.c.
References Matrix_class(), sparse_as_dense(), VALID_LOGIC2, and valid_sparse.
R_sparse_as_general()
SEXP R_sparse_as_general (SEXP s_from)
Definition at line 2592 of file coerce.c.
References Matrix_class(), sparse_as_general(), and valid_sparse.
R_sparse_as_kind()
SEXP R_sparse_as_kind (SEXP s_from, SEXP s_kind)
Definition at line 2150 of file coerce.c.
References Matrix_class(), sparse_as_kind(), VALID_KIND, and valid_sparse.
R_sparse_as_Rsparse()
SEXP R_sparse_as_Rsparse (SEXP s_from)
Definition at line 2957 of file coerce.c.
References Matrix_class(), sparse_as_Rsparse(), and valid_sparse.
R_sparse_as_Tsparse()
SEXP R_sparse_as_Tsparse (SEXP s_from)
Definition at line 3038 of file coerce.c.
References Matrix_class(), sparse_as_Tsparse(), and valid_sparse.
R_sparse_as_Vector()
SEXP R_sparse_as_Vector (SEXP s_from)
Definition at line 3275 of file coerce.c.
References Matrix_class(), sparse_as_Vector(), and valid_sparse.
R_sparse_band()
SEXP R_sparse_band (SEXP s_from, SEXP s_a, SEXP s_b)
Definition at line 380 of file band.c.
References _, DIM, Matrix_class(), sparse_band(), and valid_sparse.
R_sparse_cholesky()
SEXP R_sparse_cholesky (SEXP s_obj, SEXP s_warn, SEXP s_order, SEXP s_ll, SEXP s_super, SEXP s_beta, SEXP s_force, SEXP s_uplo)
Definition at line 230 of file Cholesky.c.
References _, c, CHF2M(), DIMNAMES, get_factor(), M2CHF(), Matrix_class(), SET_DIMNAMES, set_factor(), sparse_cholesky(), TRANS, TYPEOF, valid_sparse, and VALID_UPLO.
R_sparse_diag_get()
SEXP R_sparse_diag_get (SEXP s_obj, SEXP s_names)
Definition at line 215 of file diag.c.
References Matrix_class(), sparse_diag_get(), VALID_LOGIC2, and valid_sparse.
R_sparse_diag_N2U()
SEXP R_sparse_diag_N2U (SEXP s_from)
Definition at line 660 of file diag.c.
References Matrix_class(), sparse_diag_N2U(), and valid_sparse.
R_sparse_diag_set()
SEXP R_sparse_diag_set (SEXP s_from, SEXP s_value)
Definition at line 566 of file diag.c.
References _, DIM, kindToType(), Matrix_class(), sparse_as_general(), sparse_as_kind(), sparse_diag_set(), TRANS, TYPEOF, typeToKind(), and valid_sparse.
Referenced by sparse_diag_U2N().
R_sparse_diag_U2N()
SEXP R_sparse_diag_U2N (SEXP s_from)
Definition at line 654 of file diag.c.
References Matrix_class(), sparse_diag_U2N(), and valid_sparse.
R_sparse_dropzero()
SEXP R_sparse_dropzero (SEXP s_from, SEXP s_tol)
Definition at line 211 of file dropzero.c.
References _, Matrix_class(), sparse_dropzero(), TYPEOF, and valid_sparse.
R_sparse_force_canonical()
SEXP R_sparse_force_canonical (SEXP s_from, SEXP s_check)
Definition at line 198 of file forceCanonical.c.
References Matrix_class(), sparse_force_canonical(), VALID_LOGIC2, and valid_sparse.
R_sparse_force_symmetric()
SEXP R_sparse_force_symmetric (SEXP s_from, SEXP s_uplo, SEXP s_trans)
Definition at line 413 of file forceSymmetric.c.
References Matrix_class(), sparse_force_symmetric(), valid_sparse, VALID_TRANS, and VALID_UPLO.
R_sparse_is_canonical()
SEXP R_sparse_is_canonical (SEXP s_obj)
Definition at line 92 of file isCanonical.c.
References Matrix_class(), sparse_is_canonical(), and valid_sparse.
R_sparse_is_diagonal()
SEXP R_sparse_is_diagonal (SEXP s_obj)
Definition at line 103 of file isDiagonal.c.
References Matrix_class(), sparse_is_diagonal(), and valid_sparse.
R_sparse_is_symmetric()
SEXP R_sparse_is_symmetric (SEXP s_obj, SEXP s_trans, SEXP s_exact, SEXP s_checkDN)
Definition at line 331 of file isSymmetric.c.
References Matrix_class(), sparse_is_symmetric(), VALID_LOGIC2, valid_sparse, and VALID_TRANS.
R_sparse_is_triangular()
SEXP R_sparse_is_triangular (SEXP s_obj, SEXP s_upper)
Definition at line 195 of file isTriangular.c.
References Matrix_class(), Matrix_kindSym, sparse_is_triangular(), VALID_LOGIC3, and valid_sparse.
R_sparse_lu()
SEXP R_sparse_lu (SEXP s_obj, SEXP s_warn, SEXP s_order, SEXP s_tol)
Definition at line 174 of file lu.c.
References _, get_factor(), Matrix_class(), set_factor(), sparse_lu(), and valid_sparse.
R_sparse_marginsum()
SEXP R_sparse_marginsum (SEXP s_obj, SEXP s_margin, SEXP s_narm, SEXP s_mean, SEXP s_sparse)
Definition at line 713 of file colSums.c.
References Matrix_class(), sparse_marginsum(), VALID_LOGIC2, VALID_MARGIN, and valid_sparse.
R_sparse_matmult()
SEXP R_sparse_matmult (SEXP s_x, SEXP s_y, SEXP s_xtrans, SEXP s_ytrans, SEXP s_ztrans, SEXP s_boolean)
Definition at line 1021 of file matmult.c.
References _, dense_as_general(), dense_as_kind(), DO_AS, DO_S3, DO_TR, gCgCMatrix_matmult(), gCgeMatrix_matmult(), matmultDim(), Matrix_class(), sparse_as_general(), sparse_diag_U2N(), TRANS, TYPEOF, UPLO, and valid_matmult.
R_sparse_prod()
SEXP R_sparse_prod (SEXP s_obj, SEXP s_narm)
Definition at line 908 of file Summary.c.
References Matrix_class(), sparse_prod(), VALID_LOGIC2, and valid_sparse.
R_sparse_qr()
SEXP R_sparse_qr (SEXP s_obj, SEXP s_warn, SEXP s_order)
Definition at line 115 of file qr.c.
References get_factor(), Matrix_class(), set_factor(), sparse_qr(), and valid_sparse.
R_sparse_skewpart()
SEXP R_sparse_skewpart (SEXP s_from, SEXP s_trans)
Definition at line 492 of file skewpart.c.
References Matrix_class(), sparse_skewpart(), valid_sparse, and VALID_TRANS.
R_sparse_sum()
SEXP R_sparse_sum (SEXP s_obj, SEXP s_narm)
Definition at line 455 of file Summary.c.
References Matrix_class(), sparse_sum(), VALID_LOGIC2, and valid_sparse.
R_sparse_symmpart()
SEXP R_sparse_symmpart (SEXP s_from, SEXP s_uplo, SEXP s_trans)
Definition at line 672 of file symmpart.c.
References Matrix_class(), sparse_symmpart(), valid_sparse, VALID_TRANS, and VALID_UPLO.
R_sparse_transpose()
SEXP R_sparse_transpose (SEXP s_from, SEXP s_trans, SEXP s_lazy)
Definition at line 180 of file t.c.
References Matrix_class(), sparse_transpose(), VALID_LOGIC2, valid_sparse, and VALID_TRANS.
R_subscript_1ary()
SEXP R_subscript_1ary (SEXP s_obj, SEXP s_s, SEXP s_o)
Definition at line 348 of file subscript.c.
References dense_subscript_1ary(), diagonal_subscript_1ary(), index_subscript_1ary(), Matrix_class(), sparse_subscript_1ary(), valid_matrix, and validObject().
R_subscript_1ary_2col()
SEXP R_subscript_1ary_2col (SEXP s_obj, SEXP s_s, SEXP s_o)
Definition at line 664 of file subscript.c.
References dense_subscript_1ary_2col(), diagonal_subscript_1ary_2col(), index_subscript_1ary_2col(), Matrix_class(), sparse_subscript_1ary_2col(), valid_matrix, and validObject().
R_subscript_2ary()
SEXP R_subscript_2ary (SEXP s_obj, SEXP s_si, SEXP s_sj)
Definition at line 1580 of file subscript.c.
References dense_subscript_2ary(), diagonal_subscript_2ary(), index_subscript_2ary(), Matrix_class(), sparse_subscript_2ary(), valid_matrix, and validObject().
R_symDN()
SEXP R_symDN (SEXP dn)
Definition at line 100 of file attrib.c.
References DimNames_is_trivial(), and symDN().
R_unload_Matrix()
void R_unload_Matrix (DllInfo * info)
Definition at line 764 of file init.c.
References c, and Matrix_cholmod_finish().
R_vector_as_dense()
SEXP R_vector_as_dense (SEXP s_from, SEXP s_zzz, SEXP s_uplo, SEXP s_trans, SEXP s_diag, SEXP s_m, SEXP s_n, SEXP s_byrow, SEXP s_dimnames)
Definition at line 137 of file coerce.c.
References _, ERROR_INVALID_TYPE, TYPEOF, VALID_DIAG, VALID_LOGIC2, VALID_TRANS, VALID_UPLO, and vector_as_dense().
R_Vector_as_sparse()
SEXP R_Vector_as_sparse (SEXP s_from, SEXP s_zzz, SEXP s_uplo, SEXP s_trans, SEXP s_diag, SEXP s_m, SEXP s_n, SEXP s_byrow, SEXP s_dimnames)
Definition at line 1180 of file coerce.c.
References _, GET_SLOT, Matrix_class(), Matrix_lengthSym, TYPEOF, VALID_DIAG, VALID_LOGIC2, VALID_TRANS, VALID_UPLO, valid_vector, and Vector_as_sparse().
R_vector_as_Vector()
SEXP R_vector_as_Vector (SEXP s_from, SEXP s_kind)
Definition at line 3124 of file coerce.c.
References ERROR_INVALID_TYPE, TYPEOF, VALID_KIND, and vector_as_Vector().
RsparseMatrix_validate()
SEXP RsparseMatrix_validate (SEXP obj)
Definition at line 349 of file validity.c.
References _, DIM, GET_SLOT, Matrix_jSym, Matrix_pSym, RMKMS, and TYPEOF.
sCMatrix_validate()
SEXP sCMatrix_validate (SEXP obj)
Definition at line 519 of file validity.c.
References _, GET_SLOT, Matrix_iSym, Matrix_pSym, RMKMS, and UPLO.
Referenced by tCMatrix_validate(), and xsCMatrix_validate().
simplicialCholesky_validate()
SEXP simplicialCholesky_validate (SEXP obj)
Definition at line 1690 of file validity.c.
References _, DIM, GET_SLOT, HAS_SLOT, Matrix_isllSym, Matrix_ismtSym, Matrix_iSym, Matrix_minorSym, Matrix_nextSym, Matrix_nzSym, Matrix_prevSym, Matrix_pSym, Matrix_xSym, RMK, RMKMS, and TYPEOF.
sparseCholesky_determinant()
SEXP sparseCholesky_determinant (SEXP s_trf, SEXP s_logarithm, SEXP s_root)
Definition at line 359 of file determinant.c.
References det(), DETERMINANT_START, and M2CHF().
sparseCholesky_diag_get()
SEXP sparseCholesky_diag_get (SEXP s_trf, SEXP s_root)
Definition at line 702 of file diag.c.
References M2CHF().
sparseCholesky_solve()
SEXP sparseCholesky_solve (SEXP s_a, SEXP s_b, SEXP s_sparse, SEXP s_system)
Definition at line 697 of file solve.c.
References _, c, CHD2M(), CHS2M(), ERROR_OOM, M2CHD(), M2CHF(), M2CHS(), SET_UPLO, SOLVE_FINISH, SOLVE_START, strmatch(), and TYPEOF.
sparseCholesky_update()
SEXP sparseCholesky_update (SEXP s_trf, SEXP s_obj, SEXP s_beta)
Definition at line 30 of file updown.c.
References _, c, M2CHF(), M2CHS(), Matrix_shape(), UPDOWN_FINISH, and UPLO.
sparseCholesky_updown()
SEXP sparseCholesky_updown (SEXP s_trf, SEXP s_obj, SEXP s_update)
Definition at line 7 of file updown.c.
References c, M2CHF(), M2CHS(), and UPDOWN_FINISH.
sparseCholesky_validate()
SEXP sparseCholesky_validate (SEXP obj)
Definition at line 1633 of file validity.c.
References _, DIM, FRMKMS, GET_SLOT, Matrix_Calloc, Matrix_colcountSym, Matrix_Free, Matrix_orderingSym, Matrix_permSym, RMKMS, and TYPEOF.
sparseLU_determinant()
SEXP sparseLU_determinant (SEXP s_trf, SEXP s_logarithm)
Definition at line 298 of file determinant.c.
References det(), DETERMINANT_START, GET_SLOT, Matrix_iSym, Matrix_pSym, Matrix_qSym, Matrix_USym, Matrix_xSym, signPerm(), and TYPEOF.
sparseLU_solve()
SEXP sparseLU_solve (SEXP s_a, SEXP s_b, SEXP s_sparse)
Definition at line 467 of file solve.c.
References _, CXS2M(), CXSPARSE_COMPLEX, CXSPARSE_XTYPE_SET, ERROR_OOM, GET_SLOT, Matrix_cs_sparse::i, M2CXS(), Matrix_cs_dropzeros(), Matrix_cs_free(), Matrix_cs_permute(), Matrix_cs_pinv(), Matrix_cs_speye(), Matrix_cs_spfree(), Matrix_cs_transpose(), Matrix_LSym, Matrix_pSym, Matrix_qSym, Matrix_USym, Matrix_xSym, newObject(), PROMOTE, SET_DIM, SET_SLOT, SOLVE_DENSE, SOLVE_FINISH, SOLVE_SPARSE, SOLVE_START, TYPEOF, and Matrix_cs_sparse::xtype.
sparseLU_validate()
SEXP sparseLU_validate (SEXP obj)
Definition at line 1535 of file validity.c.
References _, DIAG, DIM, FRMKMS, GET_SLOT, Matrix_Calloc, Matrix_Free, Matrix_iSym, Matrix_LSym, Matrix_pSym, Matrix_qSym, Matrix_USym, Matrix_xSym, RMKMS, TYPEOF, and UPLO.
sparseQR_determinant()
SEXP sparseQR_determinant (SEXP orf, SEXP s_logarithm)
Definition at line 228 of file determinant.c.
References _, det(), DETERMINANT_START, DIM, GET_SLOT, Matrix_iSym, Matrix_pSym, Matrix_qSym, Matrix_RSym, Matrix_xSym, signPerm(), and TYPEOF.
sparseQR_matmult()
SEXP sparseQR_matmult (SEXP s_qr, SEXP s_y, SEXP s_op, SEXP s_complete, SEXP s_yxjj)
Definition at line 902 of file solve.c.
References _, CXSPARSE_COMPLEX, CXSPARSE_XTYPE_SET, DIM, GET_SLOT, Matrix_cs_sparse::m, M2CXS(), Matrix_betaSym, Matrix_pSym, Matrix_VSym, Matrix_xSym, Matrix_cs_sparse::n, newObject(), PROMOTE, SET_SLOT, TEMPLATE, TYPEOF, and Matrix_cs_sparse::xtype.
sparseQR_validate()
SEXP sparseQR_validate (SEXP obj)
Definition at line 1434 of file validity.c.
References _, DIM, FRMKMS, GET_SLOT, Matrix_betaSym, Matrix_Calloc, Matrix_Free, Matrix_iSym, Matrix_pSym, Matrix_qSym, Matrix_RSym, Matrix_VSym, RMK, RMKMS, and TYPEOF.
sparseVector_validate()
SEXP sparseVector_validate (SEXP obj)
Definition at line 1089 of file validity.c.
References _, GET_SLOT, Matrix_iSym, Matrix_lengthSym, RMKMS, and TYPEOF.
spMatrix_norm()
SEXP spMatrix_norm (SEXP s_obj, SEXP s_type)
Definition at line 102 of file norm.c.
References DIM, FCONE, GET_SLOT, La_norm_type(), Matrix_xSym, TRANS, TYPEOF, and UPLO.
spMatrix_rcond()
SEXP spMatrix_rcond (SEXP s_obj, SEXP trf, SEXP s_type)
Definition at line 114 of file rcond.c.
References DIM, FCONE, GET_SLOT, La_rcond_type(), Matrix_permSym, Matrix_xSym, TRANS, TYPEOF, and UPLO.
sRMatrix_validate()
SEXP sRMatrix_validate (SEXP obj)
Definition at line 606 of file validity.c.
References _, GET_SLOT, Matrix_jSym, Matrix_pSym, RMKMS, and UPLO.
Referenced by tRMatrix_validate(), and xsRMatrix_validate().
sTMatrix_validate()
SEXP sTMatrix_validate (SEXP obj)
Definition at line 693 of file validity.c.
References _, GET_SLOT, Matrix_iSym, Matrix_jSym, RMKMS, and UPLO.
Referenced by tTMatrix_validate(), and xsTMatrix_validate().
supernodalCholesky_validate()
SEXP supernodalCholesky_validate (SEXP obj)
Definition at line 1847 of file validity.c.
References _, DIM, GET_SLOT, HAS_SLOT, Matrix_maxcsizeSym, Matrix_maxesizeSym, Matrix_minorSym, Matrix_piSym, Matrix_pxSym, Matrix_sSym, Matrix_superSym, Matrix_xSym, RMK, RMKMS, and TYPEOF.
syMatrix_norm()
SEXP syMatrix_norm (SEXP s_obj, SEXP s_type)
Definition at line 73 of file norm.c.
References DIM, FCONE, GET_SLOT, La_norm_type(), Matrix_xSym, TRANS, TYPEOF, and UPLO.
syMatrix_rcond()
SEXP syMatrix_rcond (SEXP s_obj, SEXP trf, SEXP s_type)
Definition at line 74 of file rcond.c.
References DIM, FCONE, GET_SLOT, La_rcond_type(), Matrix_permSym, Matrix_xSym, TRANS, TYPEOF, and UPLO.
symmetricMatrix_validate()
SEXP symmetricMatrix_validate (SEXP obj)
Definition at line 181 of file validity.c.
References _, DIM, equalString(), generalMatrix_validate(), GET_SLOT, HAS_SLOT, Matrix_DimNamesSym, Matrix_transSym, Matrix_uploSym, RMKMS, and TYPEOF.
tCMatrix_solve()
SEXP tCMatrix_solve (SEXP s_a, SEXP s_b, SEXP s_sparse)
Definition at line 771 of file solve.c.
References _, CXS2M(), CXSPARSE_COMPLEX, CXSPARSE_XTYPE_SET, ERROR_OOM, GET_SLOT, M2CXS(), Matrix_cs_dropzeros(), Matrix_cs_speye(), Matrix_cs_spfree(), Matrix_cs_transpose(), Matrix_xSym, newObject(), PROMOTE, SET_DIM, SET_SLOT, SET_UPLO, SOLVE_DENSE, SOLVE_FINISH, SOLVE_SPARSE, SOLVE_START, TYPEOF, UPLO, and Matrix_cs_sparse::xtype.
tCMatrix_validate()
SEXP tCMatrix_validate (SEXP obj)
Definition at line 558 of file validity.c.
References _, DIAG, GET_SLOT, Matrix_iSym, Matrix_pSym, RMKMS, sCMatrix_validate(), and UPLO.
Referenced by xtCMatrix_validate().
tpMatrix_norm()
SEXP tpMatrix_norm (SEXP s_obj, SEXP s_type)
Definition at line 155 of file norm.c.
References DIAG, DIM, FCONE, GET_SLOT, La_norm_type(), Matrix_xSym, TYPEOF, and UPLO.
tpMatrix_rcond()
SEXP tpMatrix_rcond (SEXP s_obj, SEXP s_type)
Definition at line 248 of file rcond.c.
References DIAG, DIM, FCONE, GET_SLOT, La_rcond_type(), Matrix_xSym, TYPEOF, and UPLO.
triangularMatrix_validate()
SEXP triangularMatrix_validate (SEXP obj)
Definition at line 254 of file validity.c.
References _, DIM, GET_SLOT, Matrix_diagSym, Matrix_uploSym, RMKMS, and TYPEOF.
trMatrix_norm()
SEXP trMatrix_norm (SEXP s_obj, SEXP s_type)
Definition at line 131 of file norm.c.
References DIAG, DIM, FCONE, GET_SLOT, La_norm_type(), Matrix_xSym, TYPEOF, and UPLO.
trMatrix_rcond()
SEXP trMatrix_rcond (SEXP s_obj, SEXP s_type)
Definition at line 220 of file rcond.c.
References DIAG, DIM, FCONE, GET_SLOT, La_rcond_type(), Matrix_xSym, TYPEOF, and UPLO.
trMatrix_solve()
SEXP trMatrix_solve (SEXP s_a, SEXP s_b)
Definition at line 367 of file solve.c.
References DIAG, duplicateVector(), ERROR_LAPACK_1, ERROR_LAPACK_2, FCONE, GET_SLOT, Matrix_xSym, newObject(), SET_DIAG, SET_DIM, SET_SLOT, SET_UPLO, SOLVE_FINISH, SOLVE_START, TYPEOF, and UPLO.
tRMatrix_validate()
SEXP tRMatrix_validate (SEXP obj)
Definition at line 645 of file validity.c.
References _, DIAG, GET_SLOT, Matrix_jSym, Matrix_pSym, RMKMS, sRMatrix_validate(), and UPLO.
Referenced by xtRMatrix_validate().
TsparseMatrix_validate()
SEXP TsparseMatrix_validate (SEXP obj)
Definition at line 399 of file validity.c.
References _, DIM, GET_SLOT, Matrix_iSym, Matrix_jSym, RMKMS, and TYPEOF.
tTMatrix_validate()
SEXP tTMatrix_validate (SEXP obj)
Definition at line 722 of file validity.c.
References _, DIAG, GET_SLOT, Matrix_iSym, Matrix_jSym, RMKMS, sTMatrix_validate(), and UPLO.
Referenced by xtTMatrix_validate().
unpackedMatrix_validate()
SEXP unpackedMatrix_validate (SEXP obj)
Definition at line 281 of file validity.c.
References _, DIM, GET_SLOT, Matrix_xSym, and RMKMS.
xgCMatrix_validate()
SEXP xgCMatrix_validate (SEXP obj)
Definition at line 766 of file validity.c.
References _, GET_SLOT, Matrix_iSym, Matrix_xSym, and RMKMS.
Referenced by xsCMatrix_validate(), and xtCMatrix_validate().
xgRMatrix_validate()
SEXP xgRMatrix_validate (SEXP obj)
Definition at line 792 of file validity.c.
References _, GET_SLOT, Matrix_jSym, Matrix_xSym, and RMKMS.
Referenced by xsRMatrix_validate(), and xtRMatrix_validate().
xgTMatrix_validate()
SEXP xgTMatrix_validate (SEXP obj)
Definition at line 818 of file validity.c.
References _, GET_SLOT, Matrix_iSym, Matrix_xSym, and RMKMS.
Referenced by xsTMatrix_validate(), and xtTMatrix_validate().
xpCMatrix_validate()
SEXP xpCMatrix_validate (SEXP obj)
Definition at line 907 of file validity.c.
References _, DIM, GET_SLOT, Matrix_iSym, Matrix_pSym, Matrix_xSym, RMK, RMKMS, TRANS, TYPEOF, and UPLO.
xpoMatrix_validate()
SEXP xpoMatrix_validate (SEXP obj)
Definition at line 849 of file validity.c.
References _, DIM, GET_SLOT, Matrix_xSym, RMK, RMKMS, TRANS, and TYPEOF.
xppMatrix_validate()
SEXP xppMatrix_validate (SEXP obj)
Definition at line 872 of file validity.c.
References _, DIM, GET_SLOT, Matrix_xSym, RMK, RMKMS, TRANS, TYPEOF, and UPLO.
xpRMatrix_validate()
SEXP xpRMatrix_validate (SEXP obj)
Definition at line 950 of file validity.c.
References _, DIM, GET_SLOT, Matrix_jSym, Matrix_pSym, Matrix_xSym, RMK, RMKMS, TRANS, TYPEOF, and UPLO.
xpTMatrix_validate()
SEXP xpTMatrix_validate (SEXP obj)
Definition at line 993 of file validity.c.
References _, DIM, FRMK, GET_SLOT, Matrix_Calloc, Matrix_Free, Matrix_iSym, Matrix_jSym, Matrix_xSym, RMKMS, TRANS, and TYPEOF.
xsCMatrix_validate()
SEXP xsCMatrix_validate (SEXP obj)
Definition at line 776 of file validity.c.
References sCMatrix_validate(), TYPEOF, and xgCMatrix_validate().
xsRMatrix_validate()
SEXP xsRMatrix_validate (SEXP obj)
Definition at line 802 of file validity.c.
References sRMatrix_validate(), TYPEOF, and xgRMatrix_validate().
xsTMatrix_validate()
SEXP xsTMatrix_validate (SEXP obj)
Definition at line 828 of file validity.c.
References sTMatrix_validate(), TYPEOF, and xgTMatrix_validate().
xtCMatrix_validate()
SEXP xtCMatrix_validate (SEXP obj)
Definition at line 784 of file validity.c.
References tCMatrix_validate(), TYPEOF, and xgCMatrix_validate().
xtRMatrix_validate()
SEXP xtRMatrix_validate (SEXP obj)
Definition at line 810 of file validity.c.
References tRMatrix_validate(), TYPEOF, and xgRMatrix_validate().
xtTMatrix_validate()
SEXP xtTMatrix_validate (SEXP obj)
Definition at line 836 of file validity.c.
References tTMatrix_validate(), TYPEOF, and xgTMatrix_validate().
zCsparse_subassign()
SEXP zCsparse_subassign (SEXP , SEXP , SEXP , SEXP)
zMatrix_validate()
SEXP zMatrix_validate (SEXP)
zsparseVector_validate()
SEXP zsparseVector_validate (SEXP)
Variable Documentation
CallMethodTable
R_CallMethodDef CallMethodTable[] static
Definition at line 298 of file init.c.
Referenced by R_init_Matrix().
ExternalMethodTable
const R_ExternalMethodDef ExternalMethodTable[] static
Initial value:
= {
    EXTERNAL_METHOD(R_bind, -1),
    EXTERNAL_METHOD(Mmatrix, 7),
    {NULL, NULL, 0}
}
Definition at line 586 of file init.c.
Referenced by R_init_Matrix().
Matrix_betaSym
SEXP Matrix_betaSym
Definition at line 603 of file init.c.
Referenced by denseQR_validate(), R_init_Matrix(), sparse_qr(), sparseQR_matmult(), and sparseQR_validate().
Matrix_colcountSym
SEXP Matrix_colcountSym
Definition at line 604 of file init.c.
Referenced by CHF2M(), cholmod_factor_as_sexp(), M2CHF(), R_init_Matrix(), sexp_as_cholmod_factor(), and sparseCholesky_validate().
Matrix_diagSym
SEXP Matrix_diagSym
Definition at line 605 of file init.c.
Referenced by cholmod_sparse_as_sexp(), cholmod_triplet_as_sexp(), Csparse_subassign(), diagonalMatrix_validate(), R_init_Matrix(), sexp_as_cholmod_sparse(), sexp_as_cholmod_triplet(), and triangularMatrix_validate().
Matrix_DimNamesSym
SEXP Matrix_DimNamesSym
Definition at line 597 of file init.c.
Referenced by bind(), cholmod_sparse_as_sexp(), cholmod_triplet_as_sexp(), Csparse_subassign(), DIMNAMES(), Matrix_validate(), R_init_Matrix(), scanArgs(), SET_DIMNAMES(), and symmetricMatrix_validate().
Matrix_DimSym
SEXP Matrix_DimSym
Definition at line 598 of file init.c.
Referenced by bind(), CHD2M(), CHF2M(), cholmod_dense_as_sexp(), cholmod_factor_as_sexp(), cholmod_sparse_as_sexp(), cholmod_triplet_as_sexp(), CHS2M(), compressed_non_0_ij(), Csparse_subassign(), CsparseMatrix_validate_maybe_sorting(), CXS2M(), dense_prod(), M2CHD(), M2CHF(), M2CHS(), M2CXS(), matmultDim(), Matrix_validate(), R_init_Matrix(), R_Matrix_as_matrix(), scanArgs(), sexp_as_cholmod_dense(), sexp_as_cholmod_factor(), sexp_as_cholmod_sparse(), and sexp_as_cholmod_triplet().
Matrix_factorsSym
SEXP Matrix_factorsSym
Definition at line 606 of file init.c.
Referenced by dense_as_general(), dense_as_packed(), dense_as_unpacked(), dense_force_canonical(), generalMatrix_validate(), get_factor(), R_init_Matrix(), R_set_factor(), set_factor(), sparse_aggregate(), sparse_as_Csparse(), sparse_as_general(), sparse_as_Rsparse(), and sparse_as_Tsparse().
Matrix_isllSym
SEXP Matrix_isllSym
Definition at line 608 of file init.c.
Referenced by CHF2M(), cholmod_factor_as_sexp(), M2CHF(), R_init_Matrix(), sexp_as_cholmod_factor(), and simplicialCholesky_validate().
Matrix_ismtSym
SEXP Matrix_ismtSym
Definition at line 609 of file init.c.
Referenced by CHF2M(), cholmod_factor_as_sexp(), M2CHF(), R_init_Matrix(), sexp_as_cholmod_factor(), and simplicialCholesky_validate().
Matrix_iSym
SEXP Matrix_iSym
Definition at line 607 of file init.c.
Referenced by bindArgs(), CHF2M(), cholmod_factor_as_sexp(), cholmod_sparse_as_sexp(), cholmod_triplet_as_sexp(), CHS2M(), compressed_non_0_ij(), Csparse_colsum(), Csparse_rowsum(), Csparse_subassign(), CsparseMatrix_validate(), CsparseMatrix_validate_maybe_sorting(), CXS2M(), dense_as_sparse(), denseBunchKaufman_expand(), diagonal_as_sparse(), diagonal_as_Vector(), diagonal_subscript_2ary(), index_as_sparse(), index_as_Vector(), index_subscript_2ary(), M2CHF(), M2CHS(), M2CXS(), R_diagonal_matmult(), R_init_Matrix(), scanArgs(), sCMatrix_validate(), sexp_as_cholmod_factor(), sexp_as_cholmod_sparse(), sexp_as_cholmod_triplet(), simplicialCholesky_validate(), sparse_aggregate(), sparse_as_Csparse(), sparse_as_dense(), sparse_as_general(), sparse_as_kind(), sparse_as_Rsparse(), sparse_as_Tsparse(), sparse_as_Vector(), sparse_band(), sparse_diag_get(), sparse_diag_set(), sparse_dropzero(), sparse_force_canonical(), sparse_force_symmetric(), sparse_is_canonical(), sparse_is_diagonal(), sparse_is_symmetric(), sparse_is_triangular(), sparse_marginsum(), sparse_prod(), sparse_skewpart(), sparse_subscript_1ary(), sparse_subscript_1ary_2col(), sparse_subscript_2ary(), sparse_sum(), sparse_symmpart(), sparse_transpose(), sparseLU_determinant(), sparseLU_validate(), sparseQR_determinant(), sparseQR_validate(), sparseVector_validate(), sTMatrix_validate(), tCMatrix_validate(), Tsparse_colsum(), TsparseMatrix_validate(), tTMatrix_validate(), Vector_as_sparse(), vector_as_Vector(), xgCMatrix_validate(), xgTMatrix_validate(), xpCMatrix_validate(), and xpTMatrix_validate().
Matrix_jSym
SEXP Matrix_jSym
Definition at line 610 of file init.c.
Referenced by bindArgs(), cholmod_triplet_as_sexp(), compressed_non_0_ij(), dense_as_sparse(), diagonal_as_sparse(), index_as_sparse(), index_subscript_2ary(), M2CHS(), M2CXS(), R_diagonal_matmult(), R_init_Matrix(), RsparseMatrix_validate(), scanArgs(), sexp_as_cholmod_sparse(), sparse_aggregate(), sparse_as_Csparse(), sparse_as_dense(), sparse_as_general(), sparse_as_kind(), sparse_as_Rsparse(), sparse_as_Tsparse(), sparse_as_Vector(), sparse_band(), sparse_diag_get(), sparse_diag_set(), sparse_dropzero(), sparse_force_canonical(), sparse_force_symmetric(), sparse_is_canonical(), sparse_is_diagonal(), sparse_is_symmetric(), sparse_is_triangular(), sparse_marginsum(), sparse_prod(), sparse_skewpart(), sparse_subscript_1ary(), sparse_subscript_1ary_2col(), sparse_subscript_2ary(), sparse_sum(), sparse_symmpart(), sparse_transpose(), sRMatrix_validate(), sTMatrix_validate(), tRMatrix_validate(), TsparseMatrix_validate(), tTMatrix_validate(), Vector_as_sparse(), xgRMatrix_validate(), xpRMatrix_validate(), and xpTMatrix_validate().
Matrix_kindSym
SEXP Matrix_kindSym
Definition at line 611 of file init.c.
Referenced by R_dense_is_triangular(), R_init_Matrix(), and R_sparse_is_triangular().
Matrix_LChar
SEXP Matrix_LChar
Definition at line 636 of file init.c.
Referenced by R_init_Matrix().
Matrix_lengthSym
SEXP Matrix_lengthSym
Definition at line 612 of file init.c.
Referenced by Csparse_subassign(), diagonal_as_Vector(), index_as_Vector(), R_init_Matrix(), R_Vector_as_sparse(), sparse_as_Vector(), sparse_marginsum(), sparseVector_validate(), Vector_as_sparse(), and vector_as_Vector().
Matrix_logarithmSym
SEXP Matrix_logarithmSym
Definition at line 613 of file init.c.
Referenced by det(), and R_init_Matrix().
Matrix_LSym
SEXP Matrix_LSym
Definition at line 599 of file init.c.
Referenced by R_init_Matrix(), sparse_lu(), sparseLU_solve(), and sparseLU_validate().
Matrix_marginSym
SEXP Matrix_marginSym
Definition at line 614 of file init.c.
Referenced by indMatrix_validate(), and R_init_Matrix().
Matrix_maxcsizeSym
SEXP Matrix_maxcsizeSym
Definition at line 615 of file init.c.
Referenced by CHF2M(), cholmod_factor_as_sexp(), M2CHF(), R_init_Matrix(), sexp_as_cholmod_factor(), and supernodalCholesky_validate().
Matrix_maxesizeSym
SEXP Matrix_maxesizeSym
Definition at line 616 of file init.c.
Referenced by CHF2M(), cholmod_factor_as_sexp(), M2CHF(), R_init_Matrix(), sexp_as_cholmod_factor(), and supernodalCholesky_validate().
Matrix_minorSym
SEXP Matrix_minorSym
Definition at line 617 of file init.c.
Referenced by CHF2M(), cholmod_factor_as_sexp(), M2CHF(), R_init_Matrix(), sexp_as_cholmod_factor(), simplicialCholesky_validate(), and supernodalCholesky_validate().
Matrix_nextSym
SEXP Matrix_nextSym
Definition at line 618 of file init.c.
Referenced by CHF2M(), cholmod_factor_as_sexp(), M2CHF(), R_init_Matrix(), sexp_as_cholmod_factor(), and simplicialCholesky_validate().
Matrix_nzSym
SEXP Matrix_nzSym
Definition at line 619 of file init.c.
Referenced by CHF2M(), cholmod_factor_as_sexp(), M2CHF(), R_init_Matrix(), sexp_as_cholmod_factor(), and simplicialCholesky_validate().
Matrix_offSym
SEXP Matrix_offSym
Definition at line 620 of file init.c.
Referenced by R_Dim_prod(), and R_init_Matrix().
Matrix_orderingSym
SEXP Matrix_orderingSym
Definition at line 621 of file init.c.
Referenced by CHF2M(), cholmod_factor_as_sexp(), M2CHF(), R_init_Matrix(), sexp_as_cholmod_factor(), and sparseCholesky_validate().
Matrix_permSym
SEXP Matrix_permSym
Definition at line 623 of file init.c.
Referenced by bindArgs(), CHF2M(), cholmod_factor_as_sexp(), dense_bunchkaufman(), dense_cholesky(), dense_lu(), denseBunchKaufman_determinant(), denseBunchKaufman_expand(), denseBunchKaufman_solve(), denseBunchKaufman_validate(), denseCholesky_solve(), denseCholesky_validate(), denseLU_determinant(), denseLU_solve(), denseLU_validate(), denseQR_validate(), dtCMatrix_diag(), index_as_dense(), index_as_sparse(), index_as_Vector(), index_subscript_1ary(), index_subscript_1ary_2col(), index_subscript_2ary(), indMatrix_validate(), M2CHF(), pMatrix_validate(), R_init_Matrix(), scanArgs(), sexp_as_cholmod_factor(), sparseCholesky_validate(), spMatrix_rcond(), and syMatrix_rcond().
Matrix_piSym
SEXP Matrix_piSym
Definition at line 624 of file init.c.
Referenced by CHF2M(), cholmod_factor_as_sexp(), M2CHF(), R_init_Matrix(), sexp_as_cholmod_factor(), and supernodalCholesky_validate().
Matrix_prevSym
SEXP Matrix_prevSym
Definition at line 625 of file init.c.
Referenced by CHF2M(), cholmod_factor_as_sexp(), M2CHF(), R_init_Matrix(), sexp_as_cholmod_factor(), and simplicialCholesky_validate().
Matrix_pSym
SEXP Matrix_pSym
Definition at line 622 of file init.c.
Referenced by bindArgs(), CHF2M(), cholmod_factor_as_sexp(), cholmod_sparse_as_sexp(), CHS2M(), compressed_non_0_ij(), Csparse_colscale(), Csparse_colsum(), Csparse_rowscale(), Csparse_rowsum(), Csparse_subassign(), CsparseMatrix_validate(), CsparseMatrix_validate_maybe_sorting(), CXS2M(), dense_as_sparse(), denseBunchKaufman_expand(), diagonal_as_sparse(), diagonal_subscript_2ary(), dtCMatrix_diag(), index_as_sparse(), index_subscript_2ary(), M2CHF(), M2CHS(), M2CXS(), R_diagonal_matmult(), R_init_Matrix(), RsparseMatrix_validate(), scanArgs(), sCMatrix_validate(), sexp_as_cholmod_factor(), sexp_as_cholmod_sparse(), sexp_as_cholmod_triplet(), simplicialCholesky_validate(), sparse_as_Csparse(), sparse_as_dense(), sparse_as_general(), sparse_as_kind(), sparse_as_Rsparse(), sparse_as_Tsparse(), sparse_as_Vector(), sparse_band(), sparse_diag_get(), sparse_diag_set(), sparse_dropzero(), sparse_force_canonical(), sparse_force_symmetric(), sparse_is_canonical(), sparse_is_diagonal(), sparse_is_symmetric(), sparse_is_triangular(), sparse_lu(), sparse_prod(), sparse_qr(), sparse_skewpart(), sparse_subscript_1ary(), sparse_subscript_1ary_2col(), sparse_subscript_2ary(), sparse_sum(), sparse_symmpart(), sparse_transpose(), sparseLU_determinant(), sparseLU_solve(), sparseLU_validate(), sparseQR_determinant(), sparseQR_matmult(), sparseQR_validate(), sRMatrix_validate(), tCMatrix_validate(), tRMatrix_validate(), Vector_as_sparse(), xpCMatrix_validate(), and xpRMatrix_validate().
Matrix_pxSym
SEXP Matrix_pxSym
Definition at line 626 of file init.c.
Referenced by CHF2M(), cholmod_factor_as_sexp(), M2CHF(), R_init_Matrix(), sexp_as_cholmod_factor(), and supernodalCholesky_validate().
Matrix_qSym
SEXP Matrix_qSym
Definition at line 627 of file init.c.
Referenced by R_init_Matrix(), sparse_lu(), sparse_qr(), sparseLU_determinant(), sparseLU_solve(), sparseLU_validate(), sparseQR_determinant(), and sparseQR_validate().
Matrix_RSym
SEXP Matrix_RSym
Definition at line 600 of file init.c.
Referenced by R_init_Matrix(), sparse_qr(), sparseQR_determinant(), and sparseQR_validate().
Matrix_sdSym
SEXP Matrix_sdSym
Definition at line 629 of file init.c.
Referenced by copMatrix_validate(), corMatrix_validate(), dense_as_packed(), dense_as_unpacked(), dense_force_canonical(), dense_transpose(), and R_init_Matrix().
Matrix_sSym
SEXP Matrix_sSym
Definition at line 628 of file init.c.
Referenced by CHF2M(), cholmod_factor_as_sexp(), M2CHF(), R_init_Matrix(), sexp_as_cholmod_factor(), and supernodalCholesky_validate().
Matrix_superSym
SEXP Matrix_superSym
Definition at line 630 of file init.c.
Referenced by CHF2M(), cholmod_factor_as_sexp(), M2CHF(), R_init_Matrix(), sexp_as_cholmod_factor(), and supernodalCholesky_validate().
Matrix_TChar
SEXP Matrix_TChar
Definition at line 637 of file init.c.
Referenced by R_init_Matrix().
Matrix_transSym
SEXP Matrix_transSym
Definition at line 631 of file init.c.
Referenced by denseBunchKaufman_validate(), R_init_Matrix(), and symmetricMatrix_validate().
Matrix_UChar
SEXP Matrix_UChar
Definition at line 638 of file init.c.
Referenced by R_init_Matrix().
Matrix_uploSym
SEXP Matrix_uploSym
Definition at line 632 of file init.c.
Referenced by cholmod_sparse_as_sexp(), cholmod_triplet_as_sexp(), Csparse_subassign(), denseBunchKaufman_validate(), denseCholesky_validate(), dtCMatrix_diag(), M2CHS(), R_init_Matrix(), sexp_as_cholmod_sparse(), sexp_as_cholmod_triplet(), symmetricMatrix_validate(), and triangularMatrix_validate().
Matrix_USym
SEXP Matrix_USym
Definition at line 601 of file init.c.
Referenced by R_init_Matrix(), sparse_lu(), sparseLU_determinant(), sparseLU_solve(), and sparseLU_validate().
Matrix_valuesSym
SEXP Matrix_valuesSym
Definition at line 633 of file init.c.
Referenced by dense_expm(), dense_schur(), denseSchur_validate(), and R_init_Matrix().
Matrix_vectorsSym
SEXP Matrix_vectorsSym
Definition at line 634 of file init.c.
Referenced by dense_expm(), dense_schur(), denseSchur_validate(), and R_init_Matrix().
Matrix_VSym
SEXP Matrix_VSym
Definition at line 602 of file init.c.
Referenced by R_init_Matrix(), sparse_qr(), sparseQR_matmult(), and sparseQR_validate().
Matrix_xSym
SEXP Matrix_xSym
Definition at line 635 of file init.c.
Referenced by CHD2M(), CHF2M(), cholmod_dense_as_sexp(), cholmod_factor_as_sexp(), cholmod_sparse_as_sexp(), cholmod_triplet_as_sexp(), CHS2M(), copMatrix_validate(), corMatrix_validate(), Csparse_colscale(), Csparse_colsum(), Csparse_rowscale(), Csparse_rowsum(), Csparse_subassign(), CXS2M(), dense_as_general(), dense_as_kind(), dense_as_packed(), dense_as_sparse(), dense_as_unpacked(), dense_band(), dense_bunchkaufman(), dense_cholesky(), dense_colscale(), dense_diag_get(), dense_diag_set(), dense_expm(), dense_force_canonical(), dense_force_symmetric(), dense_is_canonical(), dense_is_diagonal(), dense_is_symmetric(), dense_is_triangular(), dense_lu(), dense_marginsum(), dense_prod(), dense_rowscale(), dense_schur(), dense_skewpart(), dense_subscript_1ary(), dense_subscript_1ary_2col(), dense_subscript_2ary(), dense_sum(), dense_symmpart(), dense_transpose(), denseBunchKaufman_determinant(), denseBunchKaufman_expand(), denseBunchKaufman_solve(), denseBunchKaufman_validate(), denseCholesky_determinant(), denseCholesky_diag_get(), denseCholesky_solve(), denseCholesky_validate(), denseLU_determinant(), denseLU_solve(), denseLU_validate(), denseQR_validate(), denseSchur_validate(), diagonal_as_dense(), diagonal_as_kind(), diagonal_as_sparse(), diagonal_as_Vector(), diagonal_subscript_1ary(), diagonal_subscript_1ary_2col(), diagonal_subscript_2ary(), diagonalMatrix_validate(), dtCMatrix_diag(), gCgeMatrix_matmult(), geMatrix_matmult(), geMatrix_norm(), geMatrix_rcond(), index_as_dense(), index_as_sparse(), M2CHD(), M2CHF(), M2CHS(), M2CXS(), matrix_as_dense(), packedMatrix_validate(), poMatrix_rcond(), ppMatrix_rcond(), R_diagonal_matmult(), R_init_Matrix(), R_Matrix_as_matrix(), R_Matrix_as_vector(), sexp_as_cholmod_dense(), sexp_as_cholmod_factor(), sexp_as_cholmod_sparse(), sexp_as_cholmod_triplet(), simplicialCholesky_validate(), sparse_as_general(), sparse_as_kind(), sparse_as_Tsparse(), sparse_band(), sparse_dropzero(), sparse_force_canonical(), sparse_force_symmetric(), sparse_is_canonical(), sparse_is_symmetric(), sparse_prod(), sparse_skewpart(), sparse_sum(), sparse_symmpart(), sparse_transpose(), sparseLU_determinant(), sparseLU_solve(), sparseLU_validate(), sparseQR_determinant(), sparseQR_matmult(), spMatrix_matmult(), spMatrix_norm(), spMatrix_rcond(), supernodalCholesky_validate(), syMatrix_matmult(), syMatrix_norm(), syMatrix_rcond(), tCMatrix_solve(), tpMatrix_matmult(), tpMatrix_norm(), tpMatrix_rcond(), trMatrix_matmult(), trMatrix_norm(), trMatrix_rcond(), trMatrix_solve(), Tsparse_colsum(), Tsparse_rowscale(), unpackedMatrix_validate(), vector_as_dense(), Vector_as_sparse(), xgCMatrix_validate(), xgRMatrix_validate(), xgTMatrix_validate(), xpCMatrix_validate(), xpoMatrix_validate(), xppMatrix_validate(), xpRMatrix_validate(), and xpTMatrix_validate().
Matrix_zna
Rcomplex Matrix_zna
Definition at line 643 of file init.c.
Referenced by R_init_Matrix().
Matrix_zunit
Rcomplex Matrix_zunit
Definition at line 642 of file init.c.
Referenced by dense_expm(), geMatrix_matmult(), R_init_Matrix(), sexp_as_cholmod_triplet(), spMatrix_matmult(), syMatrix_matmult(), and trMatrix_matmult().
Matrix_zzero
Rcomplex Matrix_zzero
Definition at line 641 of file init.c.
Referenced by dense_expm(), geMatrix_matmult(), R_init_Matrix(), spMatrix_matmult(), and syMatrix_matmult().