Matrix: isDiagonal.c File Reference
isDiagonal.c File Reference
#include "Mdefines.h"
#include "M5.h"
#include "idz.h"
Macros
#define TEMPLATE(c)
Functions
int dense_is_diagonal (SEXP obj, const char *class)
int sparse_is_diagonal (SEXP obj, const char *class)
SEXP R_dense_is_diagonal (SEXP s_obj)
SEXP R_sparse_is_diagonal (SEXP s_obj)
Macro Definition Documentation
TEMPLATE
#define TEMPLATE (c)
Value:
    do { \
        c##TYPE *px = c##PTR(x); \
        if (class[1] == 'g') { \
            if (c##NAME(test2)(px, (size_t) n, '\0', '\0', -'N')) \
                return 0; \
        } else if (!packed) { \
            ul = (ul == 'U') ? 'L' : 'U'; \
            if (c##NAME(test2)(px, (size_t) n,   ul, '\0',  'N')) \
                return 0; \
        } else { \
            if (c##NAME(test1)(px, (size_t) n,   ul, '\0', -'N')) \
                return 0; \
        } \
    } while (0)
Referenced by dense_is_diagonal().
Function Documentation
dense_is_diagonal()
int dense_is_diagonal (SEXP obj, const char * class)
Definition at line 7 of file isDiagonal.c.
References DIM, GET_SLOT, Matrix_xSym, SWITCH4, TEMPLATE, and UPLO.
Referenced by dense_is_symmetric(), dense_is_triangular(), and R_dense_is_diagonal().
R_dense_is_diagonal()
SEXP R_dense_is_diagonal (SEXP s_obj)
Definition at line 86 of file isDiagonal.c.
References dense_is_diagonal(), matrix_as_dense(), Matrix_class(), TYPEOF, and valid_dense.
R_sparse_is_diagonal()
SEXP R_sparse_is_diagonal (SEXP s_obj)
Definition at line 103 of file isDiagonal.c.
References Matrix_class(), sparse_is_diagonal(), and valid_sparse.
sparse_is_diagonal()
int sparse_is_diagonal (SEXP obj, const char * class)
Definition at line 45 of file isDiagonal.c.
References DIM, GET_SLOT, Matrix_iSym, Matrix_jSym, and Matrix_pSym.
Referenced by R_sparse_is_diagonal(), sparse_is_symmetric(), and sparse_is_triangular().