Matrix: isSymmetric.c File Reference
isSymmetric.c File Reference
#include "Mdefines.h"
#include "M5.h"
#include "idz.h"
Macros
#define TEMPLATE(c)
#define TEMPLATE(c)
Functions
int dense_is_diagonal (SEXP, const char *)
int sparse_is_diagonal (SEXP, const char *)
int dense_is_symmetric (SEXP obj, const char *class, char op_ct, int exact, int checkDN)
int sparse_is_symmetric (SEXP obj, const char *class, char op_ct, int exact, int checkDN)
SEXP R_dense_is_symmetric (SEXP s_obj, SEXP s_trans, SEXP s_exact, SEXP s_checkDN)
SEXP R_sparse_is_symmetric (SEXP s_obj, SEXP s_trans, SEXP s_exact, SEXP s_checkDN)
Macro Definition Documentation
TEMPLATE [1/2]
#define TEMPLATE (c)
Value:
    do { \
        c##TYPE *px = c##PTR(x); \
        if (c##NAME(test2)(px, (size_t) n, '\0', op_ct, '\0')) \
            return 0; \
    } while (0)
Referenced by dense_is_symmetric(), and sparse_is_symmetric().
TEMPLATE [2/2]
#define TEMPLATE (c)
Value:
    do { \
        c##IF_NPATTERN( \
        SEXP x = GET_SLOT(obj, Matrix_xSym); \
        c##TYPE *px = c##PTR(x); \
        ); \
        for (j = 0, k = 0; j < n; ++j) { \
            kend = pp[j]; \
            while (k < kend) { \
                i = pi[k]; \
                if (i < j) { \
                    if (iwork[i] == pp[i] || pi[iwork[i]] != j) \
                        goto done; \
                    c##IF_NPATTERN( \
                    if (c##NOT_IDEN(px[k], px[iwork[i]])) \
                        goto done; \
                    ); \
                    ++iwork[i]; \
                    ++iwork[j]; \
                    ++k; \
                } else { \
                    if (pi[k] == j) \
                        ++iwork[j]; \
                    k = kend; \
                } \
            } \
        } \
    } while (0)
Function Documentation
dense_is_diagonal()
int dense_is_diagonal (SEXP obj, const char * class)
Definition at line 7 of file isDiagonal.c.
Referenced by dense_is_symmetric().
dense_is_symmetric()
int dense_is_symmetric (SEXP obj, const char * class, char op_ct, int exact, int checkDN)
Definition at line 11 of file isSymmetric.c.
References dense_is_diagonal(), DIAG, DIM, DIMNAMES, DimNames_is_symmetric(), GET_SLOT, Matrix_xSym, SWITCH5, TEMPLATE, TRANS, UPLO, zNOT_ZERO, and zNOT_ZERO_IMAG.
Referenced by R_dense_is_symmetric().
R_dense_is_symmetric()
SEXP R_dense_is_symmetric (SEXP s_obj, SEXP s_trans, SEXP s_exact, SEXP s_checkDN)
Definition at line 305 of file isSymmetric.c.
References dense_is_symmetric(), matrix_as_dense(), Matrix_class(), TYPEOF, valid_dense, VALID_LOGIC2, and VALID_TRANS.
R_sparse_is_symmetric()
SEXP R_sparse_is_symmetric (SEXP s_obj, SEXP s_trans, SEXP s_exact, SEXP s_checkDN)
Definition at line 331 of file isSymmetric.c.
References Matrix_class(), sparse_is_symmetric(), VALID_LOGIC2, valid_sparse, and VALID_TRANS.
sparse_is_diagonal()
int sparse_is_diagonal (SEXP obj, const char * class)
Definition at line 45 of file isDiagonal.c.
Referenced by sparse_is_symmetric().
sparse_is_symmetric()
int sparse_is_symmetric (SEXP obj, const char * class, char op_ct, int exact, int checkDN)
Definition at line 138 of file isSymmetric.c.
References cl, DIAG, DIM, DIMNAMES, DimNames_is_symmetric(), GET_SLOT, Matrix_Calloc, Matrix_Free, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_xSym, sparse_as_Csparse(), sparse_is_diagonal(), SWITCH5, TEMPLATE, TRANS, zNOT_CONJ, and zNOT_ZERO_IMAG.
Referenced by R_sparse_is_symmetric().