Matrix: kappa.c File Reference
kappa.c File Reference
#include "Lapack-etc.h"
#include "Mdefines.h"
#include "kappa.h"
Macros
#define ARGNAME "type"
#define ARGNAME "norm"
Functions
static char La_norm_type (SEXP s)
static char La_rcond_type (SEXP s)
SEXP dgeMatrix_norm (SEXP obj, SEXP type)
SEXP dsyMatrix_norm (SEXP obj, SEXP type)
SEXP dspMatrix_norm (SEXP obj, SEXP type)
SEXP dtrMatrix_norm (SEXP obj, SEXP type)
SEXP dtpMatrix_norm (SEXP obj, SEXP type)
SEXP dgeMatrix_rcond (SEXP obj, SEXP trf, SEXP type)
SEXP dsyMatrix_rcond (SEXP obj, SEXP trf, SEXP type)
SEXP dspMatrix_rcond (SEXP obj, SEXP trf, SEXP type)
SEXP dpoMatrix_rcond (SEXP obj, SEXP trf, SEXP type)
SEXP dppMatrix_rcond (SEXP obj, SEXP trf, SEXP type)
SEXP dtrMatrix_rcond (SEXP obj, SEXP type)
SEXP dtpMatrix_rcond (SEXP obj, SEXP type)
Macro Definition Documentation
ARGNAME [1/2]
#define ARGNAME "type"
ARGNAME [2/2]
#define ARGNAME "norm"
Function Documentation
dgeMatrix_norm()
SEXP dgeMatrix_norm (SEXP obj, SEXP type)
Definition at line 83 of file kappa.c.
References FCONE, GET_SLOT, La_norm_type(), Matrix_DimSym, and Matrix_xSym.
dgeMatrix_rcond()
SEXP dgeMatrix_rcond (SEXP obj, SEXP trf, SEXP type)
Definition at line 231 of file kappa.c.
References _, FCONE, GET_SLOT, La_rcond_type(), Matrix_DimSym, and Matrix_xSym.
dpoMatrix_rcond()
SEXP dpoMatrix_rcond (SEXP obj, SEXP trf, SEXP type)
Definition at line 349 of file kappa.c.
References FCONE, GET_SLOT, La_rcond_type(), Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
dppMatrix_rcond()
SEXP dppMatrix_rcond (SEXP obj, SEXP trf, SEXP type)
Definition at line 389 of file kappa.c.
References FCONE, GET_SLOT, La_rcond_type(), Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
dspMatrix_norm()
SEXP dspMatrix_norm (SEXP obj, SEXP type)
Definition at line 138 of file kappa.c.
References FCONE, GET_SLOT, La_norm_type(), Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
dspMatrix_rcond()
SEXP dspMatrix_rcond (SEXP obj, SEXP trf, SEXP type)
Definition at line 309 of file kappa.c.
References FCONE, GET_SLOT, La_rcond_type(), Matrix_DimSym, Matrix_permSym, Matrix_uploSym, and Matrix_xSym.
dsyMatrix_norm()
SEXP dsyMatrix_norm (SEXP obj, SEXP type)
Definition at line 109 of file kappa.c.
References FCONE, GET_SLOT, La_norm_type(), Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
dsyMatrix_rcond()
SEXP dsyMatrix_rcond (SEXP obj, SEXP trf, SEXP type)
Definition at line 269 of file kappa.c.
References FCONE, GET_SLOT, La_rcond_type(), Matrix_DimSym, Matrix_permSym, Matrix_uploSym, and Matrix_xSym.
dtpMatrix_norm()
SEXP dtpMatrix_norm (SEXP obj, SEXP type)
Definition at line 199 of file kappa.c.
References FCONE, GET_SLOT, La_norm_type(), Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
dtpMatrix_rcond()
SEXP dtpMatrix_rcond (SEXP obj, SEXP type)
Definition at line 467 of file kappa.c.
References FCONE, GET_SLOT, La_rcond_type(), Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
dtrMatrix_norm()
SEXP dtrMatrix_norm (SEXP obj, SEXP type)
Definition at line 167 of file kappa.c.
References FCONE, GET_SLOT, La_norm_type(), Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
dtrMatrix_rcond()
SEXP dtrMatrix_rcond (SEXP obj, SEXP type)
Definition at line 429 of file kappa.c.
References FCONE, GET_SLOT, La_rcond_type(), Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
La_norm_type()
static char La_norm_type (SEXP s) static
Definition at line 6 of file kappa.c.
References _, and ARGNAME.
Referenced by dgeMatrix_norm(), dspMatrix_norm(), dsyMatrix_norm(), dtpMatrix_norm(), and dtrMatrix_norm().
La_rcond_type()
static char La_rcond_type (SEXP s) static
Definition at line 50 of file kappa.c.
References _, and ARGNAME.
Referenced by dgeMatrix_rcond(), dpoMatrix_rcond(), dppMatrix_rcond(), dspMatrix_rcond(), dsyMatrix_rcond(), dtpMatrix_rcond(), and dtrMatrix_rcond().