Matrix: kappa.h File Reference
kappa.h File Reference
#include <Rinternals.h>
Functions
SEXP dgeMatrix_norm (SEXP, SEXP)
SEXP dsyMatrix_norm (SEXP, SEXP)
SEXP dspMatrix_norm (SEXP, SEXP)
SEXP dtrMatrix_norm (SEXP, SEXP)
SEXP dtpMatrix_norm (SEXP, SEXP)
SEXP dgeMatrix_rcond (SEXP, SEXP, SEXP)
SEXP dsyMatrix_rcond (SEXP, SEXP, SEXP)
SEXP dspMatrix_rcond (SEXP, SEXP, SEXP)
SEXP dpoMatrix_rcond (SEXP, SEXP, SEXP)
SEXP dppMatrix_rcond (SEXP, SEXP, SEXP)
SEXP dtrMatrix_rcond (SEXP, SEXP)
SEXP dtpMatrix_rcond (SEXP, SEXP)
Function Documentation
dgeMatrix_norm()
SEXP dgeMatrix_norm (SEXP obj, SEXP type)
Definition at line 83 of file kappa.c.
References FCONE, GET_SLOT, La_norm_type(), Matrix_DimSym, and Matrix_xSym.
dgeMatrix_rcond()
SEXP dgeMatrix_rcond (SEXP obj, SEXP trf, SEXP type)
Definition at line 231 of file kappa.c.
References _, FCONE, GET_SLOT, La_rcond_type(), Matrix_DimSym, and Matrix_xSym.
dpoMatrix_rcond()
SEXP dpoMatrix_rcond (SEXP obj, SEXP trf, SEXP type)
Definition at line 349 of file kappa.c.
References FCONE, GET_SLOT, La_rcond_type(), Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
dppMatrix_rcond()
SEXP dppMatrix_rcond (SEXP obj, SEXP trf, SEXP type)
Definition at line 389 of file kappa.c.
References FCONE, GET_SLOT, La_rcond_type(), Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
dspMatrix_norm()
SEXP dspMatrix_norm (SEXP obj, SEXP type)
Definition at line 138 of file kappa.c.
References FCONE, GET_SLOT, La_norm_type(), Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
dspMatrix_rcond()
SEXP dspMatrix_rcond (SEXP obj, SEXP trf, SEXP type)
Definition at line 309 of file kappa.c.
References FCONE, GET_SLOT, La_rcond_type(), Matrix_DimSym, Matrix_permSym, Matrix_uploSym, and Matrix_xSym.
dsyMatrix_norm()
SEXP dsyMatrix_norm (SEXP obj, SEXP type)
Definition at line 109 of file kappa.c.
References FCONE, GET_SLOT, La_norm_type(), Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
dsyMatrix_rcond()
SEXP dsyMatrix_rcond (SEXP obj, SEXP trf, SEXP type)
Definition at line 269 of file kappa.c.
References FCONE, GET_SLOT, La_rcond_type(), Matrix_DimSym, Matrix_permSym, Matrix_uploSym, and Matrix_xSym.
dtpMatrix_norm()
SEXP dtpMatrix_norm (SEXP obj, SEXP type)
Definition at line 199 of file kappa.c.
References FCONE, GET_SLOT, La_norm_type(), Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
dtpMatrix_rcond()
SEXP dtpMatrix_rcond (SEXP obj, SEXP type)
Definition at line 467 of file kappa.c.
References FCONE, GET_SLOT, La_rcond_type(), Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
dtrMatrix_norm()
SEXP dtrMatrix_norm (SEXP obj, SEXP type)
Definition at line 167 of file kappa.c.
References FCONE, GET_SLOT, La_norm_type(), Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.
dtrMatrix_rcond()
SEXP dtrMatrix_rcond (SEXP obj, SEXP type)
Definition at line 429 of file kappa.c.
References FCONE, GET_SLOT, La_rcond_type(), Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, and Matrix_xSym.