Matrix: ldense.c File Reference
ldense.c File Reference
#include "ldense.h"
Functions
SEXP lspMatrix_as_lsyMatrix (SEXP from, SEXP kind)
SEXP lsyMatrix_as_lgeMatrix (SEXP from, SEXP kind)
SEXP lsyMatrix_as_lspMatrix (SEXP from, SEXP kind)
SEXP ltpMatrix_as_ltrMatrix (SEXP from, SEXP kind)
SEXP ltrMatrix_as_lgeMatrix (SEXP from, SEXP kind)
SEXP ltrMatrix_as_ltpMatrix (SEXP from, SEXP kind)
Function Documentation
SEXP lspMatrix_as_lsyMatrix (SEXP from, SEXP kind)
Definition at line 8 of file ldense.c.
References ALLOC_SLOT(), LOW, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, and UPP.
SEXP lsyMatrix_as_lgeMatrix (SEXP from, SEXP kind)
Definition at line 120 of file ldense.c.
References make_i_matrix_symmetric(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorSym, Matrix_xSym, and slot_dup.
SEXP lsyMatrix_as_lspMatrix (SEXP from, SEXP kind)
Definition at line 29 of file ldense.c.
References ALLOC_SLOT(), LOW, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorSym, Matrix_uploSym, Matrix_xSym, NUN, and UPP.
SEXP ltpMatrix_as_ltrMatrix (SEXP from, SEXP kind)
Definition at line 53 of file ldense.c.
References ALLOC_SLOT(), LOW, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, and UPP.
SEXP ltrMatrix_as_lgeMatrix (SEXP from, SEXP kind)
Definition at line 103 of file ldense.c.
References make_i_matrix_triangular(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorSym, Matrix_xSym, and slot_dup.
SEXP ltrMatrix_as_ltpMatrix (SEXP from, SEXP kind)
Definition at line 78 of file ldense.c.
References ALLOC_SLOT(), LOW, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, NUN, UNT, and UPP.