Matrix: ldense.h File Reference
ldense.h File Reference
#include "Mutils.h"
Functions
SEXP lspMatrix_as_lsyMatrix (SEXP from, SEXP kind)
SEXP lsyMatrix_as_lgeMatrix (SEXP from, SEXP kind)
SEXP lsyMatrix_as_lspMatrix (SEXP from, SEXP kind)
SEXP ltpMatrix_as_ltrMatrix (SEXP from, SEXP kind)
SEXP ltrMatrix_as_lgeMatrix (SEXP from, SEXP kind)
SEXP ltrMatrix_as_ltpMatrix (SEXP from, SEXP kind)
Function Documentation
lspMatrix_as_lsyMatrix()
SEXP lspMatrix_as_lsyMatrix (SEXP from, SEXP kind)
Definition at line 8 of file ldense.c.
References ALLOC_SLOT(), LOW, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), and UPP.
lsyMatrix_as_lgeMatrix()
SEXP lsyMatrix_as_lgeMatrix (SEXP from, SEXP kind)
Definition at line 114 of file ldense.c.
References make_i_matrix_symmetric(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), and slot_dup.
lsyMatrix_as_lspMatrix()
SEXP lsyMatrix_as_lspMatrix (SEXP from, SEXP kind)
Definition at line 28 of file ldense.c.
References ALLOC_SLOT(), LOW, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), NUN, and UPP.
ltpMatrix_as_ltrMatrix()
SEXP ltpMatrix_as_ltrMatrix (SEXP from, SEXP kind)
Definition at line 51 of file ldense.c.
References ALLOC_SLOT(), LOW, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), and UPP.
ltrMatrix_as_lgeMatrix()
SEXP ltrMatrix_as_lgeMatrix (SEXP from, SEXP kind)
Definition at line 99 of file ldense.c.
References make_i_matrix_triangular(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), and slot_dup.
ltrMatrix_as_ltpMatrix()
SEXP ltrMatrix_as_ltpMatrix (SEXP from, SEXP kind)
Definition at line 75 of file ldense.c.
References ALLOC_SLOT(), LOW, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, NEW_OBJECT_OF_CLASS(), NUN, UNT, and UPP.