Matrix: lu.c File Reference
lu.c File Reference
#include "Lapack-etc.h"
#include "cs-etc.h"
#include "Mdefines.h"
Macros
#define DO_FREE(_T_, _S_, _N_, _P_)
#define DO_SORT(_A_, _T_)
Functions
SEXP dense_as_kind (SEXP, const char *, char, int)
SEXP dense_as_general (SEXP, const char *, int)
SEXP sparse_as_kind (SEXP, const char *, char)
SEXP sparse_as_general (SEXP, const char *)
SEXP sparse_as_Csparse (SEXP, const char *)
SEXP dense_lu (SEXP obj, const char *class, int warn)
SEXP sparse_lu (SEXP obj, const char *class, int warn, int order, double tol)
SEXP R_dense_lu (SEXP s_obj, SEXP s_warn)
SEXP R_sparse_lu (SEXP s_obj, SEXP s_warn, SEXP s_order, SEXP s_tol)
Macro Definition Documentation
DO_FREE
#define DO_FREE (_T_, _S_, _N_, _P_)
Value:
do { \
    if (!(_T_)) \
        _T_ = Matrix_cs_spfree(_T_); \
    if (!(_S_)) \
        _S_ = Matrix_cs_sfree (_S_); \
    if (!(_N_)) \
        _N_ = Matrix_cs_nfree (_N_); \
    if (!(_P_)) \
        _P_ = Matrix_cs_free  (_P_); \
} while (0)
Definition at line 53 of file lu.c.
Referenced by sparse_lu().
DO_SORT
#define DO_SORT (_A_, _T_)
Value:
do { \
    Matrix_cs_dropzeros(_A_); \
    _T_ = Matrix_cs_transpose(_A_, 1); \
    if (!_T_) \
        goto oom; \
    _A_ = Matrix_cs_spfree(_A_); \
    _A_ = Matrix_cs_transpose(_T_, 1); \
    if (!_A_) \
        goto oom; \
    _T_ = Matrix_cs_spfree(_T_); \
} while (0)
Definition at line 66 of file lu.c.
Referenced by sparse_lu().
Function Documentation
dense_as_general()
SEXP dense_as_general (SEXP from, const char * class, int new)
Definition at line 2237 of file coerce.c.
Referenced by dense_lu().
dense_as_kind()
SEXP dense_as_kind (SEXP from, const char * class, char kind, int new)
Definition at line 2000 of file coerce.c.
Referenced by dense_lu().
dense_lu()
SEXP dense_lu (SEXP obj, const char * class, int warn)
Definition at line 12 of file lu.c.
References cl, dense_as_general(), dense_as_kind(), DIM, DIMNAMES, ERROR_LAPACK_2, GET_SLOT, Matrix_class(), Matrix_permSym, Matrix_xSym, newObject(), SET_DIM, SET_DIMNAMES, SET_SLOT, TYPEOF, and valid_dense.
Referenced by R_dense_lu().
R_dense_lu()
SEXP R_dense_lu (SEXP s_obj, SEXP s_warn)
Definition at line 154 of file lu.c.
References dense_lu(), get_factor(), Matrix_class(), set_factor(), and valid_dense.
R_sparse_lu()
SEXP R_sparse_lu (SEXP s_obj, SEXP s_warn, SEXP s_order, SEXP s_tol)
Definition at line 174 of file lu.c.
References _, get_factor(), Matrix_class(), set_factor(), sparse_lu(), and valid_sparse.
sparse_as_Csparse()
SEXP sparse_as_Csparse (SEXP from, const char * class)
Definition at line 2731 of file coerce.c.
Referenced by sparse_lu().
sparse_as_general()
SEXP sparse_as_general (SEXP from, const char * class)
Definition at line 2298 of file coerce.c.
Referenced by sparse_lu().
sparse_as_kind()
SEXP sparse_as_kind (SEXP from, const char * class, char kind)
Definition at line 2076 of file coerce.c.
Referenced by sparse_lu().
sparse_lu()
SEXP sparse_lu (SEXP obj, const char * class, int warn, int order, double tol)
Definition at line 79 of file lu.c.
References _, cl, CXS2M(), CXSPARSE_COMPLEX, CXSPARSE_XTYPE_SET, DIMNAMES, DO_FREE, DO_SORT, Matrix_cs_numeric::L, Matrix_cs_sparse::m, M2CXS(), Matrix_class(), Matrix_cs_lu(), Matrix_cs_pinv(), Matrix_cs_sqr(), Matrix_LSym, Matrix_pSym, Matrix_qSym, Matrix_USym, Matrix_cs_sparse::n, newObject(), Matrix_cs_numeric::pinv, Matrix_cs_symbolic::q, SET_DIM, SET_DIMNAMES, SET_SLOT, SET_UPLO, sparse_as_Csparse(), sparse_as_general(), sparse_as_kind(), Matrix_cs_numeric::U, valid_sparse, and Matrix_cs_sparse::xtype.
Referenced by R_sparse_lu().