Matrix: Mutils.h File Reference
Mutils.h File Reference
#include <stdint.h>
#include <ctype.h>
#include <R.h>
#include <Rversion.h>
#include <Rdefines.h>
#include <R_ext/RS.h>
#include "Syms.h"
#include "t_sparseVector.c"
Macros
#define _(String) (String)
#define _dspV_
Accessing *sparseVectors : fast (and recycling) v[i] for v = ?sparseVector: -> .
#define _ispV_
#define _lspV_
#define _nspV_
#define _zspV_
#define Alloca(n, t) (t *) alloca(((size_t) n) * sizeof(t))
#define AZERO(x, n) {int _I_, _SZ_ = (n); for(_I_ = 0; _I_ < _SZ_; _I_++) (x)[_I_] = 0;}
#define C_or_Alloca_TO(_VAR_, _N_, _TYPE_)
#define class_P(_x_) CHAR(asChar(getAttrib(_x_, R_ClassSymbol)))
#define CMJ CblasColMajor
#define CTR CblasConjTrans
#define DECLARE_AND_GET_X_SLOT(__C_TYPE, __SEXP) __C_TYPE *xx = __SEXP(GET_SLOT(x, Matrix_xSym))
#define diag_P(_x_) CHAR(STRING_ELT(GET_SLOT(_x_, Matrix_diagSym), 0))
#define Diag_P(_x_)
#define dngettext(pkg, String, StringP, N) (N > 1 ? StringP : String)
#define FULL_TO_PACKED(TYPE)
#define imax2(x, y) ((x < y) ? y : x)
#define imin2(x, y) ((x < y) ? x : y)
#define LFT CblasLeft
#define LOW CblasLower
#define MATRIX_VALID_CHMfactor "dCHMsuper", "dCHMsimpl", "nCHMsuper", "nCHMsimpl"
#define MATRIX_VALID_Csparse
#define MATRIX_VALID_dCsparse "dgCMatrix", "dsCMatrix", "dtCMatrix"
#define MATRIX_VALID_ddense
#define MATRIX_VALID_ge_dense
#define MATRIX_VALID_ldense
#define MATRIX_VALID_nCsparse "ngCMatrix", "nsCMatrix", "ntCMatrix"
#define MATRIX_VALID_ndense
#define MATRIX_VALID_Rsparse
#define MATRIX_VALID_tri_Csparse "dtCMatrix", "ltCMatrix", "ntCMatrix", "ztCMatrix"
#define MATRIX_VALID_Tsparse
#define NTR CblasNoTrans
#define NUN CblasNonUnit
#define PACKED_LENGTH(n) ((n) * ((n) + 1))/2
#define PACKED_TO_FULL(TYPE)
#define Real_KIND(_x_)
#define Real_kind(_x_)
#define Real_KIND2(_x_)
#define RGT CblasRight
#define RMJ CblasRowMajor
#define slot_dup(dest, src, sym) SET_SLOT(dest, sym, duplicate(GET_SLOT(src, sym)))
#define slot_dup_if_has(dest, src, sym)
#define slot_nonNull_dup(dest, src, sym)
#define SMALL_4_Alloca 10000
#define TRN CblasTrans
#define UNT CblasUnit
#define uplo_P(_x_) CHAR(STRING_ELT(GET_SLOT(_x_, Matrix_uploSym), 0))
#define UPP CblasUpper
#define XLENGTH(x) LENGTH(x)
Enumerations
enum CBLAS_DIAG { CblasNonUnit =131 , CblasUnit =132 }
enum CBLAS_ORDER { CblasRowMajor =101 , CblasColMajor =102 }
enum CBLAS_SIDE { CblasLeft =141 , CblasRight =142 }
enum CBLAS_TRANSPOSE { CblasNoTrans =111 , CblasTrans =112 , CblasConjTrans =113 }
enum CBLAS_UPLO { CblasUpper =121 , CblasLower =122 }
enum dense_enum { ddense , ldense , ndense }
enum x_slot_kind { x_unknown =-2 , x_pattern =-1 , x_double =0 , x_logical =1 , x_integer =2 , x_complex =3 }
Functions
static R_INLINE SEXP ALLOC_SLOT (SEXP obj, SEXP nm, SEXPTYPE type, R_xlen_t length)
Allocate an SEXP of given type and length, assign it as slot nm in the object, and return the SEXP.
static R_INLINE Rboolean any_NA_in_x (SEXP obj)
Check if slot(obj, "x") contains any NA (or NaN).
SEXP as_det_obj (double val, int log, int sign)
SEXP check_scalar_string (SEXP sP, char *vals, char *nm)
Check validity of 1-letter string from a set of possible values (typically used in S4 validity method)
SEXP d_packed_addDiag (double *diag, int l_d, SEXP x, int n)
void d_packed_getDiag (double *dest, SEXP x, int n)
Copy the diagonal elements of the packed denseMatrix x to dest.
SEXP d_packed_setDiag (double *diag, int l_d, SEXP x, int n)
diag(x) <- D for x a <dspMatrix> or dppMatrix, ..etc
SEXP dense_nonpacked_validate (SEXP obj)
SEXP dim_validate (SEXP Dim, const char *name)
SEXP Dim_validate (SEXP obj, SEXP name)
SEXP dimNames_validate (SEXP obj)
Check R (Matrix-like) object: must have @Dim and @Dimnames.
SEXP dimNames_validate__ (SEXP dmNms, int dims[], const char *obj_name)
Validate dimnames (the @Dim slot typically), assuming that 'dims' is already checked.
SEXP dup_mMatrix_as_dgeMatrix (SEXP A)
SEXP dup_mMatrix_as_dgeMatrix2 (SEXP A, Rboolean tr_if_vec)
SEXP dup_mMatrix_as_geMatrix (SEXP A)
Duplicate a [dln]denseMatrix or a numeric matrix or even a vector as a [dln]geMatrix.
Rboolean equal_string_vectors (SEXP s1, SEXP s2)
static R_INLINE int * expand_cmprPt (int ncol, const int mp[], int mj[])
Expand compressed pointers in the array mp into a full set of indices in the array mj.
FULL_TO_PACKED (double)
FULL_TO_PACKED (int)
double get_double_by_name (SEXP obj, char *nm)
SEXP get_factors (SEXP obj, char *nm)
static R_INLINE SEXP inv_permutation (SEXP p_, SEXP zero_p, SEXP zero_res)
Inverse Permutation C version of .inv.perm.R <- function(p) { p[p] <- seq_along(p) ; p }.
void l_packed_getDiag (int *dest, SEXP x, int n)
SEXP l_packed_setDiag (int *diag, int l_d, SEXP x, int n)
char La_norm_type (const char *typstr)
char La_rcond_type (const char *typstr)
SEXP m_encodeInd (SEXP ij, SEXP di, SEXP orig_1, SEXP chk_bnds)
Encode Matrix index (i,j) |--> i + j * nrow {i,j : 0-origin}.
SEXP m_encodeInd2 (SEXP i, SEXP j, SEXP di, SEXP orig_1, SEXP chk_bnds)
Encode Matrix index (i,j) |--> i + j * nrow {i,j : 0-origin}.
void make_d_matrix_symmetric (double *to, SEXP from)
void make_d_matrix_triangular (double *x, SEXP from)
void make_i_matrix_symmetric (int *to, SEXP from)
void make_i_matrix_triangular (int *x, SEXP from)
static R_INLINE int Matrix_check_class (char *class, const char **valid)
Return the 0-based index of a string match in a vector of strings terminated by an empty string.
SEXP Matrix_expand_pointers (SEXP pP)
SEXP Matrix_getElement (SEXP list, char *nm)
Return the element of a given name from a named list.
SEXP Mmatrix (SEXP args)
static R_INLINE SEXP mMatrix_as_dgeMatrix (SEXP A)
static R_INLINE SEXP mMatrix_as_dgeMatrix2 (SEXP A, Rboolean tr_if_vec)
static R_INLINE SEXP mMatrix_as_geMatrix (SEXP A)
SEXP new_dgeMatrix (int nrow, int ncol)
SEXP NEW_OBJECT_OF_CLASS (const char *cls)
These are the ones "everyone" should use – is() versions, also looking at super classes:
static R_INLINE int packed_ncol (int len)
Check for valid length of a packed triangular array and return the corresponding number of columns.
PACKED_TO_FULL (double)
PACKED_TO_FULL (int)
SEXP R_all0 (SEXP x)
SEXP R_any0 (SEXP x)
SEXP R_empty_factors (SEXP obj, SEXP warn)
SEXP R_rbind2_vector (SEXP a, SEXP b)
From the two 'x' slots of two dense matrices a and b, compute the 'x' slot of rbind(a, b)
SEXP R_set_factors (SEXP obj, SEXP val, SEXP name, SEXP warn)
SEXP R_symmetric_Dimnames (SEXP x)
Even if the Dimnames slot is list(NULL, <names>) etc, return symmetric dimnames: Get .
static R_INLINE void SET_DimNames (SEXP dest, SEXP src)
void SET_DimNames_symm (SEXP dest, SEXP src)
Set 'Dimnames' slot of 'dest' from the one of 'src' when 'src' is a "symmetricMatrix" with possibly asymmetric dimnames, and 'dest' must contain corresponding symmetric dimnames.
SEXP set_double_by_name (SEXP obj, double val, char *nm)
SEXP set_factors (SEXP obj, SEXP val, char *nm)
Caches 'val' in the 'factors' slot of obj, i.e.
SEXP symmetric_DimNames (SEXP dn)
Produce symmetric 'Dimnames' from possibly asymmetric ones.
SEXP symmetricMatrix_validate (SEXP obj)
SEXP tr_d_packed_addDiag (double *diag, int l_d, SEXP x, int n)
void tr_d_packed_getDiag (double *dest, SEXP x, int n)
SEXP tr_d_packed_setDiag (double *diag, int l_d, SEXP x, int n)
void tr_l_packed_getDiag (int *dest, SEXP x, int n)
SEXP tr_l_packed_setDiag (int *diag, int l_d, SEXP x, int n)
SEXP triangularMatrix_validate (SEXP obj)
Macro Definition Documentation
_
#define _ (String) (String)
Definition at line 39 of file Mutils.h.
_dspV_
#define _dspV_
Accessing *sparseVectors : fast (and recycling) v[i] for v = ?sparseVector: -> .
/sparseVector.c -> ./t_sparseVector.c :
Definition at line 484 of file Mutils.h.
_ispV_
#define _ispV_
Definition at line 487 of file Mutils.h.
_lspV_
#define _lspV_
Definition at line 490 of file Mutils.h.
_nspV_
#define _nspV_
Definition at line 493 of file Mutils.h.
_zspV_
#define _zspV_
Definition at line 496 of file Mutils.h.
Alloca
#define Alloca (n, t) (t *) alloca(((size_t) n) * sizeof(t))
Definition at line 53 of file Mutils.h.
AZERO
#define AZERO (x, n) {int _I_, _SZ_ = (n); for(_I_ = 0; _I_ < _SZ_; _I_++) (x)[_I_] = 0;}
Definition at line 151 of file Mutils.h.
C_or_Alloca_TO
#define C_or_Alloca_TO (_VAR_, _N_, _TYPE_)
Value:
        if(_N_ < SMALL_4_Alloca) {                              \
            _VAR_ = Alloca(_N_, _TYPE_);  R_CheckStack();       \
        } else {                                                \
            _VAR_ = Calloc(_N_, _TYPE_);                        \
        }
Definition at line 58 of file Mutils.h.
class_P
#define class_P (_x_) CHAR(asChar(getAttrib(_x_, R_ClassSymbol)))
Definition at line 187 of file Mutils.h.
CMJ
#define CMJ CblasColMajor
Definition at line 87 of file Mutils.h.
CTR
#define CTR CblasConjTrans
Definition at line 90 of file Mutils.h.
DECLARE_AND_GET_X_SLOT
#define DECLARE_AND_GET_X_SLOT (__C_TYPE, __SEXP) __C_TYPE *xx = __SEXP(GET_SLOT(x, Matrix_xSym))
Definition at line 210 of file Mutils.h.
diag_P
#define diag_P (_x_) CHAR(STRING_ELT(GET_SLOT(_x_, Matrix_diagSym), 0))
Definition at line 184 of file Mutils.h.
Diag_P
#define Diag_P (_x_)
Value:
                     (R_has_slot(x, Matrix_diagSym) ?                   \
                     CHAR(STRING_ELT(GET_SLOT(_x_, Matrix_diagSym), 0)) : " ")
Definition at line 185 of file Mutils.h.
dngettext
#define dngettext (pkg, String, StringP, N) (N > 1 ? StringP : String)
Definition at line 41 of file Mutils.h.
FULL_TO_PACKED
#define FULL_TO_PACKED (TYPE)
Value:
TYPE *full_to_packed_ ## TYPE(TYPE *dest, const TYPE *src, int n,       \
                              enum CBLAS_UPLO uplo, enum CBLAS_DIAG diag)
Definition at line 139 of file Mutils.h.
imax2
#define imax2 (x, y) ((x < y) ? y : x)
Definition at line 20 of file Mutils.h.
imin2
#define imin2 (x, y) ((x < y) ? x : y)
Definition at line 21 of file Mutils.h.
LFT
#define LFT CblasLeft
Definition at line 95 of file Mutils.h.
LOW
#define LOW CblasLower
Definition at line 92 of file Mutils.h.
MATRIX_VALID_CHMfactor
#define MATRIX_VALID_CHMfactor "dCHMsuper", "dCHMsimpl", "nCHMsuper", "nCHMsimpl"
Definition at line 431 of file Mutils.h.
MATRIX_VALID_Csparse
#define MATRIX_VALID_Csparse
Value:
    MATRIX_VALID_dCsparse,                      \
 "lgCMatrix", "lsCMatrix", "ltCMatrix",         \
    MATRIX_VALID_nCsparse,                      \
 "zgCMatrix", "zsCMatrix", "ztCMatrix"
Definition at line 396 of file Mutils.h.
MATRIX_VALID_dCsparse
#define MATRIX_VALID_dCsparse "dgCMatrix", "dsCMatrix", "dtCMatrix"
Definition at line 391 of file Mutils.h.
MATRIX_VALID_ddense
#define MATRIX_VALID_ddense
Value:
                    "dgeMatrix", "dtrMatrix",                   \
                    "dsyMatrix", "dpoMatrix", "ddiMatrix",      \
                    "dtpMatrix", "dspMatrix", "dppMatrix",      \
                    /* sub classes of those above:*/            \
                    /* dtr */ "Cholesky", "LDL", "BunchKaufman",\
                    /* dtp */ "pCholesky", "pBunchKaufman",     \
                    /* dpo */ "corMatrix"
Definition at line 372 of file Mutils.h.
MATRIX_VALID_ge_dense
#define MATRIX_VALID_ge_dense
Value:
        "dmatrix", "dgeMatrix",                 \
        "lmatrix", "lgeMatrix",                 \
        "nmatrix", "ngeMatrix",                 \
        "zmatrix", "zgeMatrix"
Definition at line 361 of file Mutils.h.
MATRIX_VALID_ldense
#define MATRIX_VALID_ldense
Value:
                    "lgeMatrix", "ltrMatrix",   \
                    "lsyMatrix", "ldiMatrix",   \
                    "ltpMatrix", "lspMatrix"
Definition at line 381 of file Mutils.h.
MATRIX_VALID_nCsparse
#define MATRIX_VALID_nCsparse "ngCMatrix", "nsCMatrix", "ntCMatrix"
Definition at line 393 of file Mutils.h.
MATRIX_VALID_ndense
#define MATRIX_VALID_ndense
Value:
                    "ngeMatrix", "ntrMatrix",   \
                    "nsyMatrix",                \
                    "ntpMatrix", "nspMatrix"
Definition at line 386 of file Mutils.h.
MATRIX_VALID_Rsparse
#define MATRIX_VALID_Rsparse
Value:
 "dgRMatrix", "dsRMatrix", "dtRMatrix",         \
 "lgRMatrix", "lsRMatrix", "ltRMatrix",         \
 "ngRMatrix", "nsRMatrix", "ntRMatrix",         \
 "zgRMatrix", "zsRMatrix", "ztRMatrix"
Definition at line 408 of file Mutils.h.
MATRIX_VALID_tri_Csparse
#define MATRIX_VALID_tri_Csparse "dtCMatrix", "ltCMatrix", "ntCMatrix", "ztCMatrix"
Definition at line 414 of file Mutils.h.
MATRIX_VALID_Tsparse
#define MATRIX_VALID_Tsparse
Value:
 "dgTMatrix", "dsTMatrix", "dtTMatrix",         \
 "lgTMatrix", "lsTMatrix", "ltTMatrix",         \
 "ngTMatrix", "nsTMatrix", "ntTMatrix",         \
 "zgTMatrix", "zsTMatrix", "ztTMatrix"
Definition at line 402 of file Mutils.h.
NTR
#define NTR CblasNoTrans
Definition at line 88 of file Mutils.h.
NUN
#define NUN CblasNonUnit
Definition at line 93 of file Mutils.h.
PACKED_LENGTH
#define PACKED_LENGTH (n) ((n) * ((n) + 1))/2
Definition at line 154 of file Mutils.h.
PACKED_TO_FULL
#define PACKED_TO_FULL (TYPE)
Value:
TYPE *packed_to_full_ ## TYPE(TYPE *dest, const TYPE *src,              \
                             int n, enum CBLAS_UPLO uplo)
Definition at line 132 of file Mutils.h.
Real_KIND
#define Real_KIND (_x_)
Value:
                         (IS_S4_OBJECT(_x_) ? Real_kind(_x_) : \
                         (isReal(_x_) ? x_double : (isLogical(_x_) ? x_logical : x_pattern)))
Definition at line 200 of file Mutils.h.
Real_kind
#define Real_kind (_x_)
Value:
                         (isReal(GET_SLOT(_x_, Matrix_xSym)) ? x_double : \
                         (isLogical(GET_SLOT(_x_, Matrix_xSym)) ? x_logical : x_pattern))
Definition at line 207 of file Mutils.h.
Real_KIND2
#define Real_KIND2 (_x_)
Value:
                         (IS_S4_OBJECT(_x_) ? Real_kind(_x_) : \
                         (isLogical(_x_) ? x_logical : x_double))
Definition at line 203 of file Mutils.h.
RGT
#define RGT CblasRight
Definition at line 96 of file Mutils.h.
RMJ
#define RMJ CblasRowMajor
Definition at line 86 of file Mutils.h.
slot_dup
#define slot_dup (dest, src, sym) SET_SLOT(dest, sym, duplicate(GET_SLOT(src, sym)))
Definition at line 158 of file Mutils.h.
slot_dup_if_has
#define slot_dup_if_has (dest, src, sym)
Value:
    if(R_has_slot(src, sym))                                    \
        SET_SLOT(dest, sym, duplicate(GET_SLOT(src, sym)))
Definition at line 165 of file Mutils.h.
slot_nonNull_dup
#define slot_nonNull_dup (dest, src, sym)
Value:
    if(GET_SLOT(src, sym) != R_NilValue)                        \
        SET_SLOT(dest, sym, duplicate(GET_SLOT(src, sym)))
Definition at line 161 of file Mutils.h.
SMALL_4_Alloca
#define SMALL_4_Alloca 10000
Definition at line 55 of file Mutils.h.
TRN
#define TRN CblasTrans
Definition at line 89 of file Mutils.h.
UNT
#define UNT CblasUnit
Definition at line 94 of file Mutils.h.
uplo_P
#define uplo_P (_x_) CHAR(STRING_ELT(GET_SLOT(_x_, Matrix_uploSym), 0))
Definition at line 183 of file Mutils.h.
UPP
#define UPP CblasUpper
Definition at line 91 of file Mutils.h.
XLENGTH
#define XLENGTH (x) LENGTH(x)
Definition at line 46 of file Mutils.h.
Enumeration Type Documentation
CBLAS_DIAG
enum CBLAS_DIAG
Enumerator
CblasNonUnit
CblasUnit
Definition at line 84 of file Mutils.h.
CBLAS_ORDER
enum CBLAS_ORDER
Enumerator
CblasRowMajor
CblasColMajor
Definition at line 81 of file Mutils.h.
CBLAS_SIDE
enum CBLAS_SIDE
Enumerator
CblasLeft
CblasRight
Definition at line 85 of file Mutils.h.
CBLAS_TRANSPOSE
enum CBLAS_TRANSPOSE
Enumerator
CblasNoTrans
CblasTrans
CblasConjTrans
Definition at line 82 of file Mutils.h.
CBLAS_UPLO
enum CBLAS_UPLO
Enumerator
CblasUpper
CblasLower
Definition at line 83 of file Mutils.h.
dense_enum
enum dense_enum
Enumerator
ddense
ldense
ndense
Definition at line 190 of file Mutils.h.
x_slot_kind
enum x_slot_kind
Enumerator
x_unknown
x_pattern
x_double
x_logical
x_integer
x_complex
Definition at line 193 of file Mutils.h.
Function Documentation
ALLOC_SLOT()
static R_INLINE SEXP ALLOC_SLOT (SEXP obj, SEXP nm, SEXPTYPE type, R_xlen_t length) static
Allocate an SEXP of given type and length, assign it as slot nm in the object, and return the SEXP.
The validity of this function depends on SET_SLOT not duplicating val when NAMED(val) == 0. If this behavior changes then ALLOC_SLOT must use SET_SLOT followed by GET_SLOT to ensure that the value returned is indeed the SEXP in the slot. NOTE: GET_SLOT(x, what) :== R_do_slot (x, what) -— SET_SLOT(x, what, value) :== R_do_slot_assign(x, what, value) and the R_do_slot* are in src/main/attrib.c
Parameters
obj object in which to assign the slot
nm name of the slot, as an R name object
type type of SEXP to allocate
length length of SEXP to allocate
Returns
SEXP of given type and length assigned as slot nm in obj
Definition at line 252 of file Mutils.h.
Referenced by chm_dense_to_SEXP(), chm_factor_to_SEXP(), chm_sparse_to_SEXP(), chm_triplet_to_SEXP(), compressed_to_TMatrix(), Csparse_subassign(), dgCMatrix_QR(), dgeMatrix_LU_(), dpoMatrix_chol(), dspMatrix_as_dsyMatrix(), dspMatrix_trf(), dsyMatrix_as_dspMatrix(), dsyMatrix_trf(), dtCMatrix_matrix_solve(), dtCMatrix_sparse_solve(), dtpMatrix_as_dtrMatrix(), dtrMatrix_as_dtpMatrix(), dtrMatrix_dtrMatrix_mm(), dup_mMatrix_as_geMatrix(), gCMatrix_colSums(), install_lu(), lspMatrix_as_lsyMatrix(), lsyMatrix_as_lspMatrix(), ltpMatrix_as_ltrMatrix(), ltrMatrix_as_ltpMatrix(), LU_expand(), Matrix_cs_to_SEXP(), matrix_trf(), new_dgeMatrix(), nz2Csparse(), R_to_CMatrix(), and Tsparse_diagU2N().
any_NA_in_x()
static R_INLINE Rboolean any_NA_in_x (SEXP obj) static
Check if slot(obj, "x") contains any NA (or NaN).
Parameters
obj a 'Matrix' object with a (double precision) 'x' slot.
Returns
Rboolean :== any(is.na(slot(obj, "x"))
Definition at line 289 of file Mutils.h.
References Matrix_xSym.
Referenced by get_norm().
as_det_obj()
SEXP as_det_obj (double val, int log, int sign)
Definition at line 94 of file Mutils.c.
Referenced by dgeMatrix_determinant().
check_scalar_string()
SEXP check_scalar_string (SEXP sP, char * vals, char * nm)
Check validity of 1-letter string from a set of possible values (typically used in S4 validity method)
Parameters
sP
vals a string containing the possible valid letters
nm the name of the slot being checked
Returns
a SEXP, either NULL (= success) or an error message
Definition at line 280 of file Mutils.c.
References _, and SPRINTF.
Referenced by symmetricMatrix_validate(), and triangularMatrix_validate().
d_packed_addDiag()
SEXP d_packed_addDiag (double * diag, int l_d, SEXP x, int n)
Definition at line 584 of file Mutils.c.
References Matrix_xSym, and uplo_P.
Referenced by tr_d_packed_addDiag().
d_packed_getDiag()
void d_packed_getDiag (double * dest, SEXP x, int n)
Copy the diagonal elements of the packed denseMatrix x to dest.
Parameters
dest vector of length ncol(x)
x (pointer to) a "d?pMatrix" object
n number of columns in the matrix represented by x
Returns
dest
Definition at line 490 of file Mutils.c.
References END_packed_getDiag, and Matrix_xSym.
Referenced by dspMatrix_getDiag(), and tr_d_packed_getDiag().
d_packed_setDiag()
SEXP d_packed_setDiag (double * diag, int l_d, SEXP x, int n)
diag(x) <- D for x a <dspMatrix> or dppMatrix, ..etc
Definition at line 520 of file Mutils.c.
References END_packed_setDiag, and SET_packed_setDiag.
Referenced by dspMatrix_setDiag().
dense_nonpacked_validate()
SEXP dense_nonpacked_validate (SEXP obj)
Definition at line 336 of file Mutils.c.
References _, Matrix_DimSym, Matrix_xSym, and XLENGTH.
Referenced by dgeMatrix_validate(), and dpoMatrix_validate().
dim_validate()
SEXP dim_validate (SEXP Dim, const char * name)
Definition at line 344 of file Mutils.c.
References _, and dngettext.
Referenced by dgeMatrix_validate(), Dim_validate(), dMatrix_validate(), and MatrixFactorization_validate().
Dim_validate()
SEXP Dim_validate (SEXP obj, SEXP name)
Definition at line 363 of file Mutils.c.
References dim_validate(), and Matrix_DimSym.
dimNames_validate()
SEXP dimNames_validate (SEXP obj)
Check R (Matrix-like) object: must have @Dim and @Dimnames.
Assume 'Dim' is already checked. (typically used in S4 validity method)
Parameters
obj an R object (typically inheriting from Matrix)
Returns
a SEXP, either TRUE (= success) or an error message string ("character")
Definition at line 417 of file Mutils.c.
References dimNames_validate__(), Matrix_DimNamesSym, and Matrix_DimSym.
Referenced by LU_validate().
dimNames_validate__()
SEXP dimNames_validate__ (SEXP dmNms, int dims[], const char * obj_name)
Validate dimnames (the @Dim slot typically), assuming that 'dims' is already checked.
Utility, called from dimNames_validate(), but available to other routines.
Parameters
dmNms an R object should be valid dimnames
dims an integer vector of length 2 (must have been checked by caller!).
Returns
a SEXP, either TRUE (= success) or an error message string ("character")
Definition at line 379 of file Mutils.c.
References _.
Referenced by dimNames_validate().
dup_mMatrix_as_dgeMatrix()
SEXP dup_mMatrix_as_dgeMatrix (SEXP A)
Definition at line 918 of file Mutils.c.
References dup_mMatrix_as_dgeMatrix2().
Referenced by CHMfactor_solve(), ddense_symmpart(), dgCMatrix_matrix_solve(), dgeMatrix_matrix_solve(), dppMatrix_matrix_solve(), dspMatrix_matrix_mm(), dspMatrix_matrix_solve(), dsyMatrix_matrix_mm(), dsyMatrix_matrix_solve(), dtpMatrix_matrix_mm(), dtpMatrix_matrix_solve(), dtrMatrix_dtrMatrix_mm(), dtrMatrix_matrix_mm(), dtrMatrix_matrix_solve(), and mMatrix_as_dgeMatrix().
dup_mMatrix_as_dgeMatrix2()
SEXP dup_mMatrix_as_dgeMatrix2 (SEXP A, Rboolean tr_if_vec)
Definition at line 888 of file Mutils.c.
References _, class_P, DUP_MMATRIX_ddense_CASES, DUP_MMATRIX_NON_CLASS, DUP_MMATRIX_SET_1, Matrix_DimNamesSym, Matrix_DimSym, MATRIX_VALID_ddense, and NEW_OBJECT_OF_CLASS().
Referenced by dup_mMatrix_as_dgeMatrix(), and mMatrix_as_dgeMatrix2().
dup_mMatrix_as_geMatrix()
SEXP dup_mMatrix_as_geMatrix (SEXP A)
Duplicate a [dln]denseMatrix or a numeric matrix or even a vector as a [dln]geMatrix.
This is for the many "*_matrix_{prod,crossprod,tcrossprod, etc.}" functions that work with both classed and unclassed matrices.
Used generally for Generalized – "geMatrix" – dispatch where needed.
Parameters
A either a denseMatrix, a diagonalMatrix or a traditional matrix object
TODO: Return 'A' unduplicated if ctype indicates "?geMatrix"' – and new argument 'check' is TRUE
Definition at line 714 of file Mutils.c.
References _, ALLOC_SLOT(), class_P, ddense, DUP_MMATRIX_ddense_CASES, DUP_MMATRIX_NON_CLASS, DUP_MMATRIX_SET_1, install_diagonal_int(), ldense, LOW, make_i_matrix_symmetric(), make_i_matrix_triangular(), Matrix_DimNamesSym, Matrix_DimSym, MATRIX_VALID_ddense, MATRIX_VALID_ldense, MATRIX_VALID_ndense, Matrix_xSym, ndense, NEW_OBJECT_OF_CLASS(), uplo_P, and UPP.
Referenced by dense_band(), dense_to_symmetric(), geMatrix_crossprod(), geMatrix_geMatrix_crossprod(), geMatrix_matrix_crossprod(), geMatrix_matrix_mm(), and mMatrix_as_geMatrix().
equal_string_vectors()
Rboolean equal_string_vectors (SEXP s1, SEXP s2)
Definition at line 312 of file Mutils.c.
References _.
Referenced by Csparse_general_to_symmetric(), and dense_to_symmetric().
expand_cmprPt()
static R_INLINE int* expand_cmprPt (int ncol, const int mp[], int mj[]) static
Expand compressed pointers in the array mp into a full set of indices in the array mj.
Parameters
ncol number of columns (or rows)
mp column pointer vector of length ncol + 1
mj vector of length mp[ncol] to hold the result
Returns
mj
Definition at line 271 of file Mutils.h.
Referenced by compressed_non_0_ij(), compressed_to_TMatrix(), Matrix_expand_pointers(), tCMatrix_validate(), and tRMatrix_validate().
FULL_TO_PACKED() [1/2]
FULL_TO_PACKED (double)
FULL_TO_PACKED() [2/2]
FULL_TO_PACKED (int)
get_double_by_name()
double get_double_by_name (SEXP obj, char * nm)
Definition at line 44 of file Mutils.c.
References _.
get_factors()
SEXP get_factors (SEXP obj, char * nm)
Definition at line 111 of file Mutils.c.
References _, and Matrix_factorSym.
Referenced by dgCMatrix_LU(), dgCMatrix_matrix_solve(), dgeMatrix_LU_(), dpoMatrix_chol(), dppMatrix_chol(), dspMatrix_trf(), and dsyMatrix_trf().
inv_permutation()
static R_INLINE SEXP inv_permutation (SEXP p_, SEXP zero_p, SEXP zero_res) static
Inverse Permutation C version of .inv.perm.R <- function(p) { p[p] <- seq_along(p) ; p }.
Definition at line 305 of file Mutils.h.
l_packed_getDiag()
void l_packed_getDiag (int * dest, SEXP x, int n)
Definition at line 507 of file Mutils.c.
References END_packed_getDiag, and Matrix_xSym.
Referenced by lspMatrix_getDiag(), and tr_l_packed_getDiag().
l_packed_setDiag()
SEXP l_packed_setDiag (int * diag, int l_d, SEXP x, int n)
Definition at line 550 of file Mutils.c.
References END_packed_setDiag, and SET_packed_setDiag.
Referenced by lspMatrix_setDiag().
La_norm_type()
char La_norm_type (const char * typstr)
Definition at line 8 of file Mutils.c.
References _.
Referenced by get_norm(), get_norm_sp(), and get_norm_sy().
La_rcond_type()
char La_rcond_type (const char * typstr)
Definition at line 27 of file Mutils.c.
References _.
Referenced by dgeMatrix_rcond(), dtpMatrix_rcond(), and dtrMatrix_rcond().
m_encodeInd()
SEXP m_encodeInd (SEXP ij, SEXP di, SEXP orig_1, SEXP chk_bnds)
Encode Matrix index (i,j) |--> i + j * nrow {i,j : 0-origin}.
Parameters
ij 2-column integer matrix
di dim(.), i.e. length 2 integer vector
chk_bnds logical indicating 0 <= ij[,k] < di[k] need to be checked.
Returns
encoded index; integer if prod(dim) is small; double otherwise
Definition at line 946 of file Mutils.c.
References _, do_ii_FILL, and ii.
m_encodeInd2()
SEXP m_encodeInd2 (SEXP i, SEXP j, SEXP di, SEXP orig_1, SEXP chk_bnds)
Encode Matrix index (i,j) |--> i + j * nrow {i,j : 0-origin}.
Parameters
i integer vector
j integer vector of same length as 'i'
orig_1 logical: if TRUE, "1-origin" otherwise "0-origin"
di dim(.), i.e. length 2 integer vector
chk_bnds logical indicating 0 <= ij[,k] < di[k] need to be checked.
Returns
encoded index; integer if prod(dim) is small; double otherwise
Definition at line 1011 of file Mutils.c.
References _, do_ii_FILL, and ii.
make_d_matrix_symmetric()
void make_d_matrix_symmetric (double * to, SEXP from)
Referenced by dsyMatrix_as_matrix().
make_d_matrix_triangular()
void make_d_matrix_triangular (double * x, SEXP from)
Referenced by dtrMatrix_as_matrix(), dtrMatrix_dtrMatrix_mm(), and LU_expand().
make_i_matrix_symmetric()
void make_i_matrix_symmetric (int * to, SEXP from)
Referenced by dup_mMatrix_as_geMatrix(), and lsyMatrix_as_lgeMatrix().
make_i_matrix_triangular()
void make_i_matrix_triangular (int * x, SEXP from)
Referenced by dup_mMatrix_as_geMatrix(), and ltrMatrix_as_lgeMatrix().
Matrix_check_class()
static R_INLINE int Matrix_check_class (char * class, const char ** valid) static
Return the 0-based index of a string match in a vector of strings terminated by an empty string.
Returns -1 for no match. Is cheap : not looking at superclasses --> better use R_check_class_etc(obj, *)
Parameters
class string to match
valid vector of possible matches terminated by an empty string
Returns
index of match or -1 for no match
Definition at line 444 of file Mutils.h.
Referenced by Matrix_cs_to_SEXP().
Matrix_expand_pointers()
SEXP Matrix_expand_pointers (SEXP pP)
Definition at line 635 of file Mutils.c.
References expand_cmprPt().
Matrix_getElement()
SEXP Matrix_getElement (SEXP list, char * nm)
Return the element of a given name from a named list.
Parameters
list
nm name of desired element
Returns
element of list with name nm
Definition at line 656 of file Mutils.c.
Mmatrix()
SEXP Mmatrix (SEXP args)
Definition at line 1046 of file Mutils.c.
References _, and XLENGTH.
mMatrix_as_dgeMatrix()
static R_INLINE SEXP mMatrix_as_dgeMatrix (SEXP A) static
Definition at line 346 of file Mutils.h.
References class_P, and dup_mMatrix_as_dgeMatrix().
Referenced by dgeMatrix_matrix_mm(), and dsCMatrix_matrix_solve().
mMatrix_as_dgeMatrix2()
static R_INLINE SEXP mMatrix_as_dgeMatrix2 (SEXP A, Rboolean tr_if_vec) static
Definition at line 350 of file Mutils.h.
References class_P, and dup_mMatrix_as_dgeMatrix2().
mMatrix_as_geMatrix()
static R_INLINE SEXP mMatrix_as_geMatrix (SEXP A) static
Definition at line 355 of file Mutils.h.
References class_P, and dup_mMatrix_as_geMatrix().
Referenced by dense_to_Csparse().
new_dgeMatrix()
SEXP new_dgeMatrix (int nrow, int ncol)
Definition at line 922 of file Mutils.c.
References ALLOC_SLOT(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_xSym, and NEW_OBJECT_OF_CLASS().
NEW_OBJECT_OF_CLASS()
SEXP NEW_OBJECT_OF_CLASS (const char * cls)
These are the ones "everyone" should use – is() versions, also looking at super classes:
They now use R(semi_API) from Rinternals.h : int R_check_class_and_super(SEXP x, const char **valid, SEXP rho); int R_check_class_etc (SEXP x, const char **valid);
R_check_class_etc (x, v) basically does rho <- .classEnv(x) and then calls R_check_class_and_super(x, v, rho)
These are the ones "everyone" should use – is() versions, also looking at super classes:
Parameters
an R character string specifying the name of a known S4 class
Definition at line 1407 of file Mutils.c.
Referenced by chm_dense_to_SEXP(), chm_sparse_to_SEXP(), chm_triplet_to_SEXP(), compressed_to_TMatrix(), Csparse_subassign(), Csparse_to_dense(), ddense_symmpart(), dense_band(), dense_to_symmetric(), dgCMatrix_QR(), dgeMatrix_LU_(), dgeMatrix_solve(), dpoMatrix_chol(), dpoMatrix_dgeMatrix_solve(), dpoMatrix_solve(), dppMatrix_chol(), dppMatrix_solve(), dspMatrix_as_dsyMatrix(), dspMatrix_solve(), dspMatrix_trf(), dsTMatrix_as_dgTMatrix(), dsTMatrix_as_dsyMatrix(), dsyMatrix_as_dspMatrix(), dsyMatrix_solve(), dsyMatrix_trf(), dtCMatrix_matrix_solve(), dtCMatrix_sparse_solve(), dtpMatrix_as_dtrMatrix(), dtrMatrix_as_dtpMatrix(), dtrMatrix_chol2inv(), dtrMatrix_dtrMatrix_mm(), dtTMatrix_as_dtrMatrix(), dup_mMatrix_as_dgeMatrix2(), dup_mMatrix_as_geMatrix(), gCMatrix_colSums(), install_lu(), lspMatrix_as_lsyMatrix(), lsTMatrix_as_lgTMatrix(), lsTMatrix_as_lsyMatrix(), lsyMatrix_as_lgeMatrix(), lsyMatrix_as_lspMatrix(), ltpMatrix_as_ltrMatrix(), ltrMatrix_as_lgeMatrix(), ltrMatrix_as_ltpMatrix(), ltTMatrix_as_ltrMatrix(), LU_expand(), Matrix_cs_to_SEXP(), matrix_trf(), new_dgeMatrix(), nsTMatrix_as_ngTMatrix(), nsTMatrix_as_nsyMatrix(), ntTMatrix_as_ntrMatrix(), nz2Csparse(), R_to_CMatrix(), and Tsparse_diagU2N().
packed_ncol()
static R_INLINE int packed_ncol (int len) static
Check for valid length of a packed triangular array and return the corresponding number of columns.
Parameters
len length of a packed triangular array
Returns
number of columns
Definition at line 223 of file Mutils.h.
References _.
PACKED_TO_FULL() [1/2]
PACKED_TO_FULL (double)
PACKED_TO_FULL() [2/2]
PACKED_TO_FULL (int)
R_all0()
SEXP R_all0 (SEXP x)
Definition at line 1244 of file Mutils.c.
References _, FALSE_, TRUE_, and XLENGTH.
R_any0()
SEXP R_any0 (SEXP x)
Definition at line 1286 of file Mutils.c.
References _, FALSE_, TRUE_, and XLENGTH.
R_empty_factors()
SEXP R_empty_factors (SEXP obj, SEXP warn)
Definition at line 183 of file Mutils.c.
References _, and Matrix_factorSym.
R_rbind2_vector()
SEXP R_rbind2_vector (SEXP a, SEXP b)
From the two 'x' slots of two dense matrices a and b, compute the 'x' slot of rbind(a, b)
Currently, an auxiliary only for setMethod rbind2(<denseMatrix>, <denseMatrix>) in ../R/bind2.R
Parameters
a
b
Returns
Definition at line 1186 of file Mutils.c.
R_set_factors()
SEXP R_set_factors (SEXP obj, SEXP val, SEXP name, SEXP warn)
Definition at line 171 of file Mutils.c.
References _, Matrix_factorSym, and set_factors().
R_symmetric_Dimnames()
SEXP R_symmetric_Dimnames (SEXP x)
Even if the Dimnames slot is list(NULL, <names>) etc, return symmetric dimnames: Get .
@Dimnames and modify when needed.
Called e.g., from symmetricDimnames() in ../R/symmetricMatrix.R
Parameters
from a symmetricMatrix
Returns
symmetric dimnames: length-2 list twice the same, NULL or character vector (of correct length)
Definition at line 1377 of file Mutils.c.
Referenced by dsyMatrix_as_matrix().
SET_DimNames()
static R_INLINE void SET_DimNames (SEXP dest, SEXP src) static
Definition at line 170 of file Mutils.h.
References Matrix_DimNamesSym.
Referenced by compressed_to_TMatrix(), dtrMatrix_dtrMatrix_mm(), R_to_CMatrix(), and Tsparse_diagU2N().
SET_DimNames_symm()
void SET_DimNames_symm (SEXP dest, SEXP src)
Set 'Dimnames' slot of 'dest' from the one of 'src' when 'src' is a "symmetricMatrix" with possibly asymmetric dimnames, and 'dest' must contain corresponding symmetric dimnames.
Parameters
dest Matrix, typically not symmetric
src symmetricMatrix
Definition at line 1390 of file Mutils.c.
set_double_by_name()
SEXP set_double_by_name (SEXP obj, double val, char * nm)
Definition at line 62 of file Mutils.c.
References _.
set_factors()
SEXP set_factors (SEXP obj, SEXP val, char * nm)
Caches 'val' in the 'factors' slot of obj, i.e.
modifies obj, and returns val. In the past this function installed a duplicate of factors slot for obj then returned the (typically unprotected) val. This is now changed to return the duplicate, which will be protected if obj is protected.
Definition at line 135 of file Mutils.c.
References _, and Matrix_factorSym.
Referenced by dgeMatrix_LU_(), dpoMatrix_chol(), dppMatrix_chol(), dspMatrix_trf(), dsyMatrix_trf(), install_lu(), internal_chm_factor(), and R_set_factors().
symmetric_DimNames()
SEXP symmetric_DimNames (SEXP dn)
Produce symmetric 'Dimnames' from possibly asymmetric ones.
Parameters
dn list of length 2; typically 'Dimnames' slot of "symmetricMatrix"
Definition at line 1333 of file Mutils.c.
References NON_TRIVIAL_DN, and SYMM_DIMNAMES.
Referenced by Csparse_general_to_symmetric(), Csparse_symmetric_to_general(), and Csparse_to_matrix().
symmetricMatrix_validate()
SEXP symmetricMatrix_validate (SEXP obj)
Definition at line 3 of file dsyMatrix.c.
References _, check_scalar_string(), Matrix_DimSym, and Matrix_uploSym.
Referenced by dspMatrix_validate().
tr_d_packed_addDiag()
SEXP tr_d_packed_addDiag (double * diag, int l_d, SEXP x, int n)
Definition at line 600 of file Mutils.c.
References d_packed_addDiag(), diag_P, and Matrix_diagSym.
Referenced by dtpMatrix_addDiag().
tr_d_packed_getDiag()
void tr_d_packed_getDiag (double * dest, SEXP x, int n)
Definition at line 615 of file Mutils.c.
References d_packed_getDiag(), and diag_P.
Referenced by dtpMatrix_getDiag().
tr_d_packed_setDiag()
SEXP tr_d_packed_setDiag (double * diag, int l_d, SEXP x, int n)
Definition at line 566 of file Mutils.c.
References SET_packed_setDiag, and tr_END_packed_setDiag.
Referenced by dtpMatrix_setDiag().
tr_l_packed_getDiag()
void tr_l_packed_getDiag (int * dest, SEXP x, int n)
Definition at line 625 of file Mutils.c.
References diag_P, and l_packed_getDiag().
Referenced by ltpMatrix_getDiag().
tr_l_packed_setDiag()
SEXP tr_l_packed_setDiag (int * diag, int l_d, SEXP x, int n)
Definition at line 572 of file Mutils.c.
References SET_packed_setDiag, and tr_END_packed_setDiag.
Referenced by ltpMatrix_setDiag().
triangularMatrix_validate()
SEXP triangularMatrix_validate (SEXP obj)
Definition at line 5 of file dtrMatrix.c.
References _, check_scalar_string(), Matrix_diagSym, Matrix_DimSym, and Matrix_uploSym.
Referenced by dtpMatrix_validate().