Matrix: norm.c File Reference
norm.c File Reference
#include "Lapack-etc.h"
#include "Mdefines.h"
Macros
#define ARGNAME "type"
Functions
static char La_norm_type (SEXP s)
SEXP geMatrix_norm (SEXP s_obj, SEXP s_type)
SEXP syMatrix_norm (SEXP s_obj, SEXP s_type)
SEXP spMatrix_norm (SEXP s_obj, SEXP s_type)
SEXP trMatrix_norm (SEXP s_obj, SEXP s_type)
SEXP tpMatrix_norm (SEXP s_obj, SEXP s_type)
Macro Definition Documentation
ARGNAME
#define ARGNAME "type"
Referenced by La_norm_type().
Function Documentation
geMatrix_norm()
SEXP geMatrix_norm (SEXP s_obj, SEXP s_type)
Definition at line 50 of file norm.c.
References DIM, FCONE, GET_SLOT, La_norm_type(), Matrix_xSym, and TYPEOF.
La_norm_type()
static char La_norm_type (SEXP s) static
Definition at line 7 of file norm.c.
References _, ARGNAME, and TYPEOF.
Referenced by geMatrix_norm(), spMatrix_norm(), syMatrix_norm(), tpMatrix_norm(), and trMatrix_norm().
spMatrix_norm()
SEXP spMatrix_norm (SEXP s_obj, SEXP s_type)
Definition at line 102 of file norm.c.
References DIM, FCONE, GET_SLOT, La_norm_type(), Matrix_xSym, TRANS, TYPEOF, and UPLO.
syMatrix_norm()
SEXP syMatrix_norm (SEXP s_obj, SEXP s_type)
Definition at line 73 of file norm.c.
References DIM, FCONE, GET_SLOT, La_norm_type(), Matrix_xSym, TRANS, TYPEOF, and UPLO.
tpMatrix_norm()
SEXP tpMatrix_norm (SEXP s_obj, SEXP s_type)
Definition at line 155 of file norm.c.
References DIAG, DIM, FCONE, GET_SLOT, La_norm_type(), Matrix_xSym, TYPEOF, and UPLO.
trMatrix_norm()
SEXP trMatrix_norm (SEXP s_obj, SEXP s_type)
Definition at line 131 of file norm.c.
References DIAG, DIM, FCONE, GET_SLOT, La_norm_type(), Matrix_xSym, TYPEOF, and UPLO.