Matrix: objects.c File Reference
objects.c File Reference
#include "Mdefines.h"
Functions
SEXP newObject (const char *what)
char typeToKind (SEXPTYPE type)
SEXPTYPE kindToType (char kind)
size_t kindToSize (char kind)
const char * Matrix_superclass (const char *class, int mode)
const char * Matrix_class (SEXP x, const char **valid, int mode, const char *caller)
char Matrix_kind (SEXP obj)
char Matrix_shape (SEXP obj, int mode)
char Matrix_repr (SEXP obj)
SEXP R_Matrix_class (SEXP s_obj, SEXP s_mode)
SEXP R_Matrix_kind (SEXP s_obj)
SEXP R_Matrix_shape (SEXP s_obj, SEXP s_mode)
SEXP R_Matrix_repr (SEXP s_obj)
Variables
const char * valid_dense [] = { VALID_DENSE , "" }
const char * valid_sparse [] = { VALID_SPARSE , "" }
const char * valid_sparse_compressed [] = { VALID_SPARSE_COMPRESSED, "" }
const char * valid_sparse_triplet [] = { VALID_SPARSE_TRIPLET , "" }
const char * valid_diagonal [] = { VALID_DIAGONAL , "" }
const char * valid_index [] = { VALID_INDEX , "" }
const char * valid_matrix [] = { VALID_MATRIX , "" }
const char * valid_vector [] = { VALID_VECTOR , "" }
const char * valid_matrix_or_vector [] = { VALID_MATRIX_OR_VECTOR , "" }
Function Documentation
kindToSize()
size_t kindToSize (char kind)
Definition at line 56 of file objects.c.
References _.
Referenced by diagonal_as_dense(), index_as_dense(), and sparse_as_dense().
kindToType()
SEXPTYPE kindToType (char kind)
Definition at line 38 of file objects.c.
References _.
Referenced by coerceArgs(), dense_as_kind(), dense_diag_get(), dense_subscript_1ary(), dense_subscript_1ary_2col(), diagonal_as_dense(), diagonal_as_kind(), diagonal_as_sparse(), diagonal_subscript_1ary(), diagonal_subscript_1ary_2col(), index_as_dense(), index_as_sparse(), matrix_as_dense(), R_dense_diag_set(), R_Matrix_as_general(), R_sparse_diag_set(), sparse_as_kind(), sparse_diag_get(), sparse_subscript_1ary(), sparse_subscript_1ary_2col(), vector_as_dense(), Vector_as_sparse(), and vector_as_Vector().
Matrix_class()
const char * Matrix_class (SEXP x, const char ** valid, int mode, const char * caller)
Definition at line 112 of file objects.c.
References ERROR_INVALID_CLASS, and Matrix_superclass().
Referenced by bind(), coerceArgs(), Csparse_writeMM(), dense_bunchkaufman(), dense_cholesky(), dense_expm(), dense_lu(), dense_schur(), M2CHD(), M2CHF(), M2CHS(), M2CXS(), Matrix_kind(), Matrix_repr(), Matrix_shape(), R_dense_as_general(), R_dense_as_kind(), R_dense_as_packed(), R_dense_as_sparse(), R_dense_as_unpacked(), R_dense_band(), R_dense_bunchkaufman(), R_dense_cholesky(), R_dense_diag_get(), R_dense_diag_set(), R_dense_expm(), R_dense_force_canonical(), R_dense_force_symmetric(), R_dense_is_canonical(), R_dense_is_diagonal(), R_dense_is_symmetric(), R_dense_is_triangular(), R_dense_lu(), R_dense_marginsum(), R_dense_matmult(), R_dense_prod(), R_dense_schur(), R_dense_skewpart(), R_dense_sum(), R_dense_symmpart(), R_dense_transpose(), R_diagonal_as_dense(), R_diagonal_as_kind(), R_diagonal_as_sparse(), R_diagonal_as_Vector(), R_diagonal_matmult(), R_index_as_dense(), R_index_as_kind(), R_index_as_sparse(), R_index_as_Vector(), R_Matrix_as_Csparse(), R_Matrix_as_general(), R_Matrix_as_kind(), R_Matrix_as_matrix(), R_Matrix_as_packed(), R_Matrix_as_Rsparse(), R_Matrix_as_Tsparse(), R_Matrix_as_unpacked(), R_Matrix_as_Vector(), R_Matrix_as_vector(), R_Matrix_class(), R_sparse_aggregate(), R_sparse_as_Csparse(), R_sparse_as_dense(), R_sparse_as_general(), R_sparse_as_kind(), R_sparse_as_Rsparse(), R_sparse_as_Tsparse(), R_sparse_as_Vector(), R_sparse_band(), R_sparse_cholesky(), R_sparse_diag_get(), R_sparse_diag_N2U(), R_sparse_diag_set(), R_sparse_diag_U2N(), R_sparse_dropzero(), R_sparse_force_canonical(), R_sparse_force_symmetric(), R_sparse_is_canonical(), R_sparse_is_diagonal(), R_sparse_is_symmetric(), R_sparse_is_triangular(), R_sparse_lu(), R_sparse_marginsum(), R_sparse_matmult(), R_sparse_prod(), R_sparse_qr(), R_sparse_skewpart(), R_sparse_sum(), R_sparse_symmpart(), R_sparse_transpose(), R_subscript_1ary(), R_subscript_1ary_2col(), R_subscript_2ary(), R_Vector_as_sparse(), scanArgs(), sexp_as_cholmod_dense(), sexp_as_cholmod_factor(), sexp_as_cholmod_sparse(), sexp_as_cholmod_triplet(), sparse_as_Vector(), sparse_cholesky(), sparse_lu(), and sparse_qr().
Matrix_kind()
char Matrix_kind (SEXP obj)
Definition at line 125 of file objects.c.
References Matrix_class(), TYPEOF, and valid_matrix_or_vector.
Referenced by R_Matrix_kind().
Matrix_repr()
char Matrix_repr (SEXP obj)
Definition at line 156 of file objects.c.
References Matrix_class(), TYPEOF, and valid_matrix_or_vector.
Referenced by R_Matrix_repr().
Matrix_shape()
char Matrix_shape (SEXP obj, int mode)
Definition at line 146 of file objects.c.
References Matrix_class(), TYPEOF, and valid_matrix_or_vector.
Referenced by R_Matrix_shape(), and sparseCholesky_update().
Matrix_superclass()
const char * Matrix_superclass (const char * class, int mode)
Definition at line 73 of file objects.c.
Referenced by Matrix_class().
newObject()
SEXP newObject (const char * what)
Definition at line 13 of file objects.c.
Referenced by bind(), CHD2M(), CHF2M(), cholmod_dense_as_sexp(), cholmod_factor_as_sexp(), cholmod_sparse_as_sexp(), cholmod_triplet_as_sexp(), CHS2M(), Csparse_subassign(), CXS2M(), dense_as_general(), dense_as_kind(), dense_as_packed(), dense_as_sparse(), dense_as_unpacked(), dense_band(), dense_bunchkaufman(), dense_cholesky(), dense_diag_set(), dense_expm(), dense_force_canonical(), dense_force_symmetric(), dense_lu(), dense_schur(), dense_skewpart(), dense_subscript_2ary(), dense_symmpart(), dense_transpose(), denseBunchKaufman_expand(), denseBunchKaufman_solve(), denseCholesky_solve(), denseLU_solve(), diagonal_as_dense(), diagonal_as_kind(), diagonal_as_sparse(), diagonal_as_Vector(), diagonal_subscript_2ary(), gCgeMatrix_matmult(), geMatrix_matmult(), index_as_dense(), index_as_sparse(), index_as_Vector(), index_subscript_2ary(), matrix_as_dense(), R_diagonal_matmult(), sparse_as_Csparse(), sparse_as_dense(), sparse_as_general(), sparse_as_kind(), sparse_as_Rsparse(), sparse_as_Tsparse(), sparse_as_Vector(), sparse_band(), sparse_diag_N2U(), sparse_diag_set(), sparse_dropzero(), sparse_force_canonical(), sparse_force_symmetric(), sparse_lu(), sparse_marginsum(), sparse_qr(), sparse_skewpart(), sparse_subscript_2ary(), sparse_symmpart(), sparse_transpose(), sparseLU_solve(), sparseQR_matmult(), spMatrix_matmult(), syMatrix_matmult(), tCMatrix_solve(), tpMatrix_matmult(), trMatrix_matmult(), trMatrix_solve(), vector_as_dense(), Vector_as_sparse(), and vector_as_Vector().
R_Matrix_class()
SEXP R_Matrix_class (SEXP s_obj, SEXP s_mode)
Definition at line 185 of file objects.c.
References Matrix_class(), and valid_matrix_or_vector.
R_Matrix_kind()
SEXP R_Matrix_kind (SEXP s_obj)
Definition at line 191 of file objects.c.
References Matrix_kind().
R_Matrix_repr()
SEXP R_Matrix_repr (SEXP s_obj)
Definition at line 203 of file objects.c.
References Matrix_repr().
R_Matrix_shape()
SEXP R_Matrix_shape (SEXP s_obj, SEXP s_mode)
Definition at line 197 of file objects.c.
References Matrix_shape().
typeToKind()
char typeToKind (SEXPTYPE type)
Definition at line 20 of file objects.c.
References _.
Referenced by matrix_as_dense(), matrix_as_sparse(), R_dense_diag_set(), R_nnz(), R_sparse_diag_set(), sparse_marginsum(), vector_as_dense(), Vector_as_sparse(), and vector_as_Vector().
Variable Documentation
valid_dense
const char* valid_dense[] = { VALID_DENSE , "" }
Definition at line 3 of file objects.c.
Referenced by dense_bunchkaufman(), dense_cholesky(), dense_expm(), dense_lu(), dense_schur(), R_dense_as_general(), R_dense_as_kind(), R_dense_as_packed(), R_dense_as_sparse(), R_dense_as_unpacked(), R_dense_band(), R_dense_bunchkaufman(), R_dense_cholesky(), R_dense_diag_get(), R_dense_diag_set(), R_dense_expm(), R_dense_force_canonical(), R_dense_force_symmetric(), R_dense_is_canonical(), R_dense_is_diagonal(), R_dense_is_symmetric(), R_dense_is_triangular(), R_dense_lu(), R_dense_marginsum(), R_dense_prod(), R_dense_schur(), R_dense_skewpart(), R_dense_sum(), R_dense_symmpart(), and R_dense_transpose().
valid_diagonal
const char* valid_diagonal[] = { VALID_DIAGONAL , "" }
Definition at line 7 of file objects.c.
valid_index
const char* valid_index[] = { VALID_INDEX , "" }
Definition at line 8 of file objects.c.
valid_matrix
const char* valid_matrix[] = { VALID_MATRIX , "" }
Definition at line 9 of file objects.c.
valid_matrix_or_vector
const char* valid_matrix_or_vector[] = { VALID_MATRIX_OR_VECTOR , "" }
Definition at line 11 of file objects.c.
Referenced by Matrix_kind(), Matrix_repr(), Matrix_shape(), and R_Matrix_class().
valid_sparse
const char* valid_sparse[] = { VALID_SPARSE , "" }
Definition at line 4 of file objects.c.
valid_sparse_compressed
const char* valid_sparse_compressed[] = { VALID_SPARSE_COMPRESSED, "" }
Definition at line 5 of file objects.c.
valid_sparse_triplet
const char* valid_sparse_triplet[] = { VALID_SPARSE_TRIPLET , "" }
Definition at line 6 of file objects.c.
valid_vector
const char* valid_vector[] = { VALID_VECTOR , "" }
Definition at line 10 of file objects.c.