Matrix: perm.h File Reference
perm.h File Reference
#include <Rinternals.h>
Functions
SEXP R_isPerm (SEXP, SEXP)
SEXP R_signPerm (SEXP, SEXP)
SEXP R_invertPerm (SEXP, SEXP, SEXP)
SEXP R_asPerm (SEXP, SEXP, SEXP, SEXP)
Function Documentation
R_asPerm()
SEXP R_asPerm (SEXP p, SEXP off, SEXP ioff, SEXP n)
Definition at line 130 of file perm.c.
References _, and asPerm().
R_invertPerm()
SEXP R_invertPerm (SEXP p, SEXP off, SEXP ioff)
Definition at line 110 of file perm.c.
References _, and invertPerm().
R_isPerm()
SEXP R_isPerm (SEXP p, SEXP off)
Definition at line 76 of file perm.c.
References _, and isPerm().
R_signPerm()
SEXP R_signPerm (SEXP p, SEXP off)
Definition at line 93 of file perm.c.
References _, and signPerm().