Matrix: perm.c File Reference
perm.c File Reference
#include "Mdefines.h"
Functions
int isPerm (const int *p, int n, int off)
int signPerm (const int *p, int n, int off)
void invertPerm (const int *p, int *ip, int n, int off, int ioff)
void asPerm (const int *p, int *ip, int m, int n, int off, int ioff)
SEXP R_isPerm (SEXP s_p, SEXP s_off)
SEXP R_signPerm (SEXP s_p, SEXP s_off)
SEXP R_invertPerm (SEXP s_p, SEXP s_off, SEXP s_ioff)
SEXP R_asPerm (SEXP s_p, SEXP s_off, SEXP s_ioff, SEXP s_n)
Function Documentation
asPerm()
void asPerm (const int * p, int * ip, int m, int n, int off, int ioff)
Definition at line 57 of file perm.c.
References _.
Referenced by R_asPerm().
invertPerm()
void invertPerm (const int * p, int * ip, int n, int off, int ioff)
Definition at line 47 of file perm.c.
References _, and isPerm().
Referenced by index_subscript_2ary(), and R_invertPerm().
isPerm()
int isPerm (const int * p, int n, int off)
Definition at line 3 of file perm.c.
References Matrix_Calloc, and Matrix_Free.
Referenced by index_subscript_2ary(), invertPerm(), R_isPerm(), and signPerm().
R_asPerm()
SEXP R_asPerm (SEXP s_p, SEXP s_off, SEXP s_ioff, SEXP s_n)
Definition at line 133 of file perm.c.
References _, asPerm(), and TYPEOF.
R_invertPerm()
SEXP R_invertPerm (SEXP s_p, SEXP s_off, SEXP s_ioff)
Definition at line 109 of file perm.c.
References _, invertPerm(), and TYPEOF.
R_isPerm()
SEXP R_isPerm (SEXP s_p, SEXP s_off)
Definition at line 75 of file perm.c.
References _, isPerm(), and TYPEOF.
R_signPerm()
SEXP R_signPerm (SEXP s_p, SEXP s_off)
Definition at line 92 of file perm.c.
References _, signPerm(), and TYPEOF.
signPerm()
int signPerm (const int * p, int n, int off)
Definition at line 22 of file perm.c.
References _, isPerm(), Matrix_Calloc, and Matrix_Free.
Referenced by R_signPerm(), sparseLU_determinant(), and sparseQR_determinant().