Matrix: products.h File Reference
products.h File Reference
#include <Rinternals.h>
Functions
SEXP R_dense_matmult (SEXP, SEXP, SEXP, SEXP)
SEXP R_sparse_matmult (SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP R_diagonal_matmult (SEXP, SEXP, SEXP, SEXP, SEXP)
Function Documentation
R_dense_matmult()
SEXP R_dense_matmult (SEXP x, SEXP y, SEXP xtrans, SEXP ytrans)
Definition at line 634 of file products.c.
References dense_as_general(), dense_as_kind(), dgeMatrix_matmult(), dspMatrix_matmult(), dsyMatrix_matmult(), dtpMatrix_matmult(), dtrMatrix_matmult(), ERROR_INVALID_CLASS, GET_SLOT, matmultDim(), matrix_as_dense(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_uploSym, valid, and VALID_DENSE.
R_diagonal_matmult()
SEXP R_diagonal_matmult (SEXP x, SEXP y, SEXP xtrans, SEXP ytrans, SEXP boolean)
Definition at line 1285 of file products.c.
References _, Csparse_colscale(), Csparse_rowscale(), dense_as_general(), dense_as_kind(), dense_colscale(), dense_rowscale(), dense_transpose(), diagonal_as_kind(), ERROR_INVALID_CLASS, GET_SLOT, matmultDim(), matmultDN(), matrix_as_dense(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_memcpy(), Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, sparse_as_general(), sparse_as_kind(), sparse_diag_U2N(), sparse_drop0(), sparse_transpose(), Tsparse_rowscale(), valid, VALID_CSPARSE, VALID_DENSE, VALID_DIAGONAL, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_matmult()
SEXP R_sparse_matmult (SEXP x, SEXP y, SEXP xtrans, SEXP ytrans, SEXP ztrans, SEXP boolean)
Definition at line 935 of file products.c.
References _, dense_as_general(), dense_as_kind(), dense_as_sparse(), dgCMatrix_dgCMatrix_matmult(), dgCMatrix_dgeMatrix_matmult(), ERROR_INVALID_CLASS, GET_SLOT, matmultDim(), matrix_as_dense(), matrix_as_sparse(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_uploSym, sparse_as_Csparse(), sparse_as_general(), sparse_as_kind(), sparse_diag_U2N(), sparse_drop0(), sparse_transpose(), valid, VALID_CSPARSE, VALID_DENSE, VALID_RSPARSE, and VALID_TSPARSE.