Matrix: products.c File Reference
products.c File Reference
#include "Lapack-etc.h"
#include "cholmod-etc.h"
#include "Mdefines.h"
#include "idz.h"
#include "coerce.h"
#include "dense.h"
#include "sparse.h"
#include "products.h"
Macros
#define MULTIPLY_COMPLEX(_X_, _D_)
#define MULTIPLY_REAL(_X_, _D_) (_X_) = (_X_) * (_D_)
#define MULTIPLY_LOGICAL(_X_, _D_) (_X_) = (_X_) && (_D_)
#define SCALE_CASES(_J_)
#define SCALE(_CTYPE_, _PTR_, _OP_, _J_)
#define SCALE(_CTYPE_, _PTR_, _OP_, _J_)
#define SCALE(_CTYPE_, _PTR_, _OP_, _J_)
Functions
static void matmultDim (SEXP x, SEXP y, int *xtrans, int *ytrans, int *ztrans, int *m, int *n, int *v)
static void matmultDN (SEXP dest, SEXP asrc, int ai, SEXP bsrc, int bi)
static SEXP dgeMatrix_matmult (SEXP a, SEXP b, int atrans, int btrans)
static SEXP dsyMatrix_matmult (SEXP a, SEXP b, int aleft, int btrans)
static SEXP dspMatrix_matmult (SEXP a, SEXP b, int aleft, int btrans)
static SEXP dtrMatrix_matmult (SEXP a, SEXP b, int aleft, int atrans, int btrans, int triangular)
static SEXP dtpMatrix_matmult (SEXP a, SEXP b, int aleft, int atrans, int btrans, int triangular)
SEXP R_dense_matmult (SEXP x, SEXP y, SEXP xtrans, SEXP ytrans)
static SEXP dgCMatrix_dgCMatrix_matmult (SEXP x, SEXP y, int xtrans, int ytrans, int ztrans, int triangular, int boolean)
static SEXP dgCMatrix_dgeMatrix_matmult (SEXP x, SEXP y, int xtrans, int ytrans, int ztrans, int triangular, int symmetric)
SEXP R_sparse_matmult (SEXP x, SEXP y, SEXP xtrans, SEXP ytrans, SEXP ztrans, SEXP boolean)
static void dense_colscale (SEXP obj, SEXP d, int m, int n, char uplo, char diag)
static void dense_rowscale (SEXP obj, SEXP d, int m, int n, char uplo, char diag)
static void Csparse_colscale (SEXP obj, SEXP d)
static void Csparse_rowscale (SEXP obj, SEXP d, SEXP iSym)
static void Tsparse_rowscale (SEXP obj, SEXP d, SEXP iSym)
SEXP R_diagonal_matmult (SEXP x, SEXP y, SEXP xtrans, SEXP ytrans, SEXP boolean)
Macro Definition Documentation
MULTIPLY_COMPLEX
#define MULTIPLY_COMPLEX (_X_, _D_)
Value:
    do { \
        tmp = (_X_); \
        (_X_).r = tmp.r * (_D_).r - tmp.i * (_D_).i; \
        (_X_).i = tmp.r * (_D_).i + tmp.i * (_D_).r; \
    } while (0)
Definition at line 1113 of file products.c.
MULTIPLY_LOGICAL
#define MULTIPLY_LOGICAL (_X_, _D_) (_X_) = (_X_) && (_D_)
Definition at line 1121 of file products.c.
MULTIPLY_REAL
#define MULTIPLY_REAL (_X_, _D_) (_X_) = (_X_) * (_D_)
Definition at line 1119 of file products.c.
SCALE [1/3]
#define SCALE (_CTYPE_, _PTR_, _OP_, _J_)
SCALE [2/3]
#define SCALE (_CTYPE_, _PTR_, _OP_, _J_)
Value:
    do { \
        _CTYPE_ *px = _PTR_(x), *pd = _PTR_(d); \
        for (j = 0; j < n; ++j) { \
            kend = pp[j]; \
            while (k < kend) { \
                _OP_(*px, *pd); \
                ++px; \
                ++k; \
            } \
            ++pd; \
        } \
    } while (0)
SCALE [3/3]
#define SCALE (_CTYPE_, _PTR_, _OP_, _J_)
Value:
    do { \
        _CTYPE_ *px = _PTR_(x), *pd = _PTR_(d); \
        for (k = 0; k < nnz; ++k) { \
            _OP_(*px, pd[*pi]); \
            ++px; \
            ++pi; \
        } \
    } while (0)
SCALE_CASES
#define SCALE_CASES (_J_)
Value:
    do { \
        switch (TYPEOF(d)) { \
        case CPLXSXP: \
        { \
            Rcomplex tmp; \
            SCALE(Rcomplex, COMPLEX, MULTIPLY_COMPLEX, _J_); \
            break; \
        } \
        case REALSXP: \
            SCALE(double, REAL, MULTIPLY_REAL, _J_); \
            break; \
        default: \
            SCALE(int, LOGICAL, MULTIPLY_LOGICAL, _J_); \
            break; \
        } \
    } while (0)
Definition at line 1124 of file products.c.
Function Documentation
Csparse_colscale()
static void Csparse_colscale (SEXP obj, SEXP d) static
Definition at line 1212 of file products.c.
References GET_SLOT, Matrix_pSym, Matrix_xSym, and SCALE_CASES.
Referenced by R_diagonal_matmult().
Csparse_rowscale()
static void Csparse_rowscale (SEXP obj, SEXP d, SEXP iSym) static
Definition at line 1243 of file products.c.
References GET_SLOT, Matrix_pSym, Matrix_xSym, and SCALE_CASES.
Referenced by R_diagonal_matmult().
dense_colscale()
static void dense_colscale (SEXP obj, SEXP d, int m, int n, char uplo, char diag) static
Definition at line 1143 of file products.c.
References GET_SLOT, Matrix_xSym, and SCALE_CASES.
Referenced by R_diagonal_matmult().
dense_rowscale()
static void dense_rowscale (SEXP obj, SEXP d, int m, int n, char uplo, char diag) static
Definition at line 1198 of file products.c.
References GET_SLOT, Matrix_xSym, and SCALE_CASES.
Referenced by R_diagonal_matmult().
dgCMatrix_dgCMatrix_matmult()
static SEXP dgCMatrix_dgCMatrix_matmult (SEXP x, SEXP y, int xtrans, int ytrans, int ztrans, int triangular, int boolean) static
Definition at line 771 of file products.c.
References _, c, CHS2M(), GET_SLOT, M2CHS(), matmultDN(), Matrix_DimNamesSym, Matrix_uploSym, SET_SLOT, sparse_diag_N2U(), sparse_transpose(), and symDN().
Referenced by R_sparse_matmult().
dgCMatrix_dgeMatrix_matmult()
static SEXP dgCMatrix_dgeMatrix_matmult (SEXP x, SEXP y, int xtrans, int ytrans, int ztrans, int triangular, int symmetric) static
Definition at line 844 of file products.c.
References _, c, CHD2M(), GET_SLOT, get_symmetrized_DimNames(), M2CHD(), M2CHS(), matmultDN(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, newObject(), and SET_SLOT.
Referenced by R_sparse_matmult().
dgeMatrix_matmult()
static SEXP dgeMatrix_matmult (SEXP a, SEXP b, int atrans, int btrans) static
Definition at line 142 of file products.c.
References _, FCONE, GET_SLOT, matmultDN(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_memset(), Matrix_xSym, Matrix_zone, Matrix_zzero, newObject(), SET_SLOT, and symDN().
Referenced by R_dense_matmult().
dspMatrix_matmult()
static SEXP dspMatrix_matmult (SEXP a, SEXP b, int aleft, int btrans) static
Definition at line 367 of file products.c.
References _, FCONE, GET_SLOT, get_symmetrized_DimNames(), matmultDN(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, Matrix_zone, Matrix_zzero, newObject(), and SET_SLOT.
Referenced by R_dense_matmult().
dsyMatrix_matmult()
static SEXP dsyMatrix_matmult (SEXP a, SEXP b, int aleft, int btrans) static
Definition at line 279 of file products.c.
References _, FCONE, GET_SLOT, get_symmetrized_DimNames(), matmultDN(), Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, Matrix_zone, newObject(), and SET_SLOT.
Referenced by R_dense_matmult().
dtpMatrix_matmult()
static SEXP dtpMatrix_matmult (SEXP a, SEXP b, int aleft, int atrans, int btrans, int triangular) static
Definition at line 537 of file products.c.
References _, FCONE, GET_SLOT, matmultDN(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_memcpy(), Matrix_uploSym, Matrix_xSym, newObject(), and SET_SLOT.
Referenced by R_dense_matmult().
dtrMatrix_matmult()
static SEXP dtrMatrix_matmult (SEXP a, SEXP b, int aleft, int atrans, int btrans, int triangular) static
Definition at line 443 of file products.c.
References _, FCONE, GET_SLOT, matmultDN(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_memcpy(), Matrix_uploSym, Matrix_xSym, Matrix_zone, newObject(), and SET_SLOT.
Referenced by R_dense_matmult().
matmultDim()
static void matmultDim (SEXP x, SEXP y, int * xtrans, int * ytrans, int * ztrans, int * m, int * n, int * v) static
Definition at line 11 of file products.c.
References _, GET_SLOT, and Matrix_DimSym.
Referenced by R_dense_matmult(), R_diagonal_matmult(), and R_sparse_matmult().
matmultDN()
static void matmultDN (SEXP dest, SEXP asrc, int ai, SEXP bsrc, int bi) static
Definition at line 119 of file products.c.
Referenced by dgCMatrix_dgCMatrix_matmult(), dgCMatrix_dgeMatrix_matmult(), dgeMatrix_matmult(), dspMatrix_matmult(), dsyMatrix_matmult(), dtpMatrix_matmult(), dtrMatrix_matmult(), and R_diagonal_matmult().
R_dense_matmult()
SEXP R_dense_matmult (SEXP x, SEXP y, SEXP xtrans, SEXP ytrans)
Definition at line 634 of file products.c.
References dense_as_general(), dense_as_kind(), dgeMatrix_matmult(), dspMatrix_matmult(), dsyMatrix_matmult(), dtpMatrix_matmult(), dtrMatrix_matmult(), ERROR_INVALID_CLASS, GET_SLOT, matmultDim(), matrix_as_dense(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_uploSym, valid, and VALID_DENSE.
R_diagonal_matmult()
SEXP R_diagonal_matmult (SEXP x, SEXP y, SEXP xtrans, SEXP ytrans, SEXP boolean)
Definition at line 1282 of file products.c.
References _, Csparse_colscale(), Csparse_rowscale(), dense_as_general(), dense_as_kind(), dense_colscale(), dense_rowscale(), dense_transpose(), diagonal_as_kind(), ERROR_INVALID_CLASS, GET_SLOT, matmultDim(), matmultDN(), matrix_as_dense(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_memcpy(), Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, sparse_as_general(), sparse_as_kind(), sparse_diag_U2N(), sparse_drop0(), sparse_transpose(), Tsparse_rowscale(), valid, VALID_CSPARSE, VALID_DENSE, VALID_DIAGONAL, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_matmult()
SEXP R_sparse_matmult (SEXP x, SEXP y, SEXP xtrans, SEXP ytrans, SEXP ztrans, SEXP boolean)
Definition at line 932 of file products.c.
References _, dense_as_general(), dense_as_kind(), dense_as_sparse(), dgCMatrix_dgCMatrix_matmult(), dgCMatrix_dgeMatrix_matmult(), ERROR_INVALID_CLASS, GET_SLOT, matmultDim(), matrix_as_dense(), matrix_as_sparse(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_uploSym, sparse_as_Csparse(), sparse_as_general(), sparse_as_kind(), sparse_diag_U2N(), sparse_drop0(), sparse_transpose(), valid, VALID_CSPARSE, VALID_DENSE, VALID_RSPARSE, and VALID_TSPARSE.
Tsparse_rowscale()
static void Tsparse_rowscale (SEXP obj, SEXP d, SEXP iSym) static
Definition at line 1268 of file products.c.
References GET_SLOT, Matrix_xSym, and SCALE_CASES.
Referenced by R_diagonal_matmult().