Matrix: qr.c File Reference
qr.c File Reference
#include "cs-etc.h"
#include "Mdefines.h"
Macros
#define DO_FREE(_T_, _S_, _N_, _P_)
#define DO_SORT(_A_, _T_)
Functions
SEXP sparse_as_kind (SEXP, const char *, char)
SEXP sparse_as_general (SEXP, const char *)
SEXP sparse_as_Csparse (SEXP, const char *)
SEXP sparse_qr (SEXP obj, const char *class, int warn, int order)
SEXP R_sparse_qr (SEXP s_obj, SEXP s_warn, SEXP s_order)
Macro Definition Documentation
DO_FREE
#define DO_FREE (_T_, _S_, _N_, _P_)
Value:
do { \
    if (!(_T_)) \
        _T_ = Matrix_cs_spfree(_T_); \
    if (!(_S_)) \
        _S_ = Matrix_cs_sfree (_S_); \
    if (!(_N_)) \
        _N_ = Matrix_cs_nfree (_N_); \
    if (!(_P_)) \
        _P_ = Matrix_cs_free  (_P_); \
} while (0)
Definition at line 10 of file qr.c.
Referenced by sparse_qr().
DO_SORT
#define DO_SORT (_A_, _T_)
Value:
do { \
    Matrix_cs_dropzeros(_A_); \
    _T_ = Matrix_cs_transpose(_A_, 1); \
    if (!_T_) \
        goto oom; \
    _A_ = Matrix_cs_spfree(_A_); \
    _A_ = Matrix_cs_transpose(_T_, 1); \
    if (!_A_) \
        goto oom; \
    _T_ = Matrix_cs_spfree(_T_); \
} while (0)
Definition at line 23 of file qr.c.
Referenced by sparse_qr().
Function Documentation
R_sparse_qr()
SEXP R_sparse_qr (SEXP s_obj, SEXP s_warn, SEXP s_order)
Definition at line 115 of file qr.c.
References get_factor(), Matrix_class(), set_factor(), sparse_qr(), and valid_sparse.
sparse_as_Csparse()
SEXP sparse_as_Csparse (SEXP from, const char * class)
Definition at line 2731 of file coerce.c.
Referenced by R_Matrix_as_Csparse(), R_sparse_as_Csparse(), sparse_as_Vector(), sparse_qr(), and Vector_as_sparse().
sparse_as_general()
SEXP sparse_as_general (SEXP from, const char * class)
Definition at line 2298 of file coerce.c.
Referenced by R_Matrix_as_general(), R_sparse_as_general(), sparse_as_Vector(), and sparse_qr().
sparse_as_kind()
SEXP sparse_as_kind (SEXP from, const char * class, char kind)
Definition at line 2076 of file coerce.c.
Referenced by sparse_qr().
sparse_qr()
SEXP sparse_qr (SEXP obj, const char * class, int warn, int order)
Definition at line 36 of file qr.c.
References _, Matrix_cs_numeric::B, cl, CXS2M(), CXSPARSE_COMPLEX, CXSPARSE_XTYPE_SET, DIMNAMES, DO_FREE, DO_SORT, Matrix_cs_numeric::L, Matrix_cs_sparse::m, Matrix_cs_symbolic::m2, M2CXS(), Matrix_betaSym, Matrix_class(), Matrix_cs_pinv(), Matrix_cs_qr(), Matrix_cs_sqr(), Matrix_pSym, Matrix_qSym, Matrix_RSym, Matrix_VSym, Matrix_cs_sparse::n, newObject(), Matrix_cs_symbolic::pinv, Matrix_cs_symbolic::q, SET_DIM, SET_DIMNAMES, SET_SLOT, sparse_as_Csparse(), sparse_as_general(), sparse_as_kind(), Matrix_cs_numeric::U, valid_sparse, and Matrix_cs_sparse::xtype.
Referenced by R_sparse_qr().