Matrix: rcond.c File Reference
rcond.c File Reference
#include "Lapack-etc.h"
#include "Mdefines.h"
Macros
#define ARGNAME "norm"
Functions
static char La_rcond_type (SEXP s)
SEXP geMatrix_rcond (SEXP s_obj, SEXP trf, SEXP s_type)
SEXP syMatrix_rcond (SEXP s_obj, SEXP trf, SEXP s_type)
SEXP spMatrix_rcond (SEXP s_obj, SEXP trf, SEXP s_type)
SEXP poMatrix_rcond (SEXP s_obj, SEXP trf, SEXP s_type)
SEXP ppMatrix_rcond (SEXP s_obj, SEXP trf, SEXP s_type)
SEXP trMatrix_rcond (SEXP s_obj, SEXP s_type)
SEXP tpMatrix_rcond (SEXP s_obj, SEXP s_type)
Macro Definition Documentation
ARGNAME
#define ARGNAME "norm"
Referenced by La_rcond_type().
Function Documentation
geMatrix_rcond()
SEXP geMatrix_rcond (SEXP s_obj, SEXP trf, SEXP s_type)
Definition at line 40 of file rcond.c.
References _, DIM, FCONE, GET_SLOT, La_rcond_type(), Matrix_xSym, and TYPEOF.
La_rcond_type()
static char La_rcond_type (SEXP s) static
Definition at line 7 of file rcond.c.
References _, ARGNAME, and TYPEOF.
Referenced by geMatrix_rcond(), poMatrix_rcond(), ppMatrix_rcond(), spMatrix_rcond(), syMatrix_rcond(), tpMatrix_rcond(), and trMatrix_rcond().
poMatrix_rcond()
SEXP poMatrix_rcond (SEXP s_obj, SEXP trf, SEXP s_type)
Definition at line 154 of file rcond.c.
References DIM, FCONE, GET_SLOT, La_rcond_type(), Matrix_xSym, TYPEOF, and UPLO.
ppMatrix_rcond()
SEXP ppMatrix_rcond (SEXP s_obj, SEXP trf, SEXP s_type)
Definition at line 187 of file rcond.c.
References DIM, FCONE, GET_SLOT, La_rcond_type(), Matrix_xSym, TYPEOF, and UPLO.
spMatrix_rcond()
SEXP spMatrix_rcond (SEXP s_obj, SEXP trf, SEXP s_type)
Definition at line 114 of file rcond.c.
References DIM, FCONE, GET_SLOT, La_rcond_type(), Matrix_permSym, Matrix_xSym, TRANS, TYPEOF, and UPLO.
syMatrix_rcond()
SEXP syMatrix_rcond (SEXP s_obj, SEXP trf, SEXP s_type)
Definition at line 74 of file rcond.c.
References DIM, FCONE, GET_SLOT, La_rcond_type(), Matrix_permSym, Matrix_xSym, TRANS, TYPEOF, and UPLO.
tpMatrix_rcond()
SEXP tpMatrix_rcond (SEXP s_obj, SEXP s_type)
Definition at line 248 of file rcond.c.
References DIAG, DIM, FCONE, GET_SLOT, La_rcond_type(), Matrix_xSym, TYPEOF, and UPLO.
trMatrix_rcond()
SEXP trMatrix_rcond (SEXP s_obj, SEXP s_type)
Definition at line 220 of file rcond.c.
References DIAG, DIM, FCONE, GET_SLOT, La_rcond_type(), Matrix_xSym, TYPEOF, and UPLO.