Matrix: Schur.c File Reference
Schur.c File Reference
#include "Lapack-etc.h"
#include "Mdefines.h"
Functions
SEXP dense_as_kind (SEXP, const char *, char, int)
SEXP dense_as_general (SEXP, const char *, int)
SEXP dense_schur (SEXP obj, const char *class, int warn, int vectors)
SEXP R_dense_schur (SEXP s_obj, SEXP s_warn, SEXP s_vectors)
Function Documentation
dense_as_general()
SEXP dense_as_general (SEXP from, const char * class, int new)
Definition at line 2237 of file coerce.c.
References _, cl, COPY_SLOT, DIAG, DIM, DIMNAMES, GET_SLOT, Matrix_factorsSym, Matrix_xSym, newObject(), SET_DIM, SET_DIMNAMES, SET_SLOT, SWITCH4, TEMPLATE, TRANS, TYPEOF, and UPLO.
Referenced by coerceArgs(), dense_schur(), R_dense_as_general(), R_dense_diag_set(), R_dense_matmult(), R_Matrix_as_general(), R_Matrix_as_matrix(), R_Matrix_as_vector(), and R_sparse_matmult().
dense_as_kind()
SEXP dense_as_kind (SEXP from, const char * class, char kind, int new)
Definition at line 2000 of file coerce.c.
Referenced by dense_schur().
dense_schur()
SEXP dense_schur (SEXP obj, const char * class, int warn, int vectors)
Definition at line 8 of file Schur.c.
References _, cl, dense_as_general(), dense_as_kind(), DIM, DIMNAMES, ERROR_LAPACK_5, FCONE, GET_SLOT, Matrix_class(), Matrix_valuesSym, Matrix_vectorsSym, Matrix_xSym, newObject(), SET_DIM, SET_DIMNAMES, SET_SLOT, TRANS, TYPEOF, UPLO, and valid_dense.
Referenced by dense_expm(), and R_dense_schur().
R_dense_schur()
SEXP R_dense_schur (SEXP s_obj, SEXP s_warn, SEXP s_vectors)
Definition at line 141 of file Schur.c.
References dense_schur(), get_factor(), Matrix_class(), set_factor(), and valid_dense.