Matrix: solve.h File Reference
solve.h File Reference
#include <Rinternals.h>
Functions
SEXP denseLU_solve (SEXP, SEXP)
SEXP BunchKaufman_solve (SEXP, SEXP)
SEXP Cholesky_solve (SEXP, SEXP)
SEXP dtrMatrix_solve (SEXP, SEXP)
SEXP sparseLU_solve (SEXP, SEXP, SEXP)
SEXP CHMfactor_solve (SEXP, SEXP, SEXP, SEXP)
SEXP dtCMatrix_solve (SEXP, SEXP, SEXP)
SEXP sparseQR_matmult (SEXP, SEXP, SEXP, SEXP, SEXP)
Function Documentation
BunchKaufman_solve()
SEXP BunchKaufman_solve (SEXP a, SEXP b)
Definition at line 134 of file solve.c.
References ERROR_LAPACK_1, ERROR_LAPACK_2, FCONE, GET_SLOT, Matrix_DimSym, Matrix_permSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, SOLVE_FINISH, and SOLVE_START.
CHMfactor_solve()
SEXP CHMfactor_solve (SEXP a, SEXP b, SEXP sparse, SEXP system)
Definition at line 711 of file solve.c.
References _, c, CHD2M(), CHS2M(), ERROR_SOLVE_OOM, EYE, M2CHD(), M2CHF(), M2CHS(), Matrix_uploSym, Matrix_zone, SET_SLOT, SOLVE_FINISH, SOLVE_START, strmatch(), and valid.
Cholesky_solve()
SEXP Cholesky_solve (SEXP a, SEXP b)
Definition at line 240 of file solve.c.
References ERROR_LAPACK_1, ERROR_LAPACK_2, FCONE, GET_SLOT, Matrix_Calloc, Matrix_DimSym, Matrix_Free, Matrix_permSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, SOLVE_FINISH, and SOLVE_START.
denseLU_solve()
SEXP denseLU_solve (SEXP a, SEXP b)
Definition at line 31 of file solve.c.
References ERROR_LAPACK_1, ERROR_LAPACK_2, FCONE, GET_SLOT, Matrix_DimSym, Matrix_permSym, Matrix_xSym, newObject(), SET_SLOT, SOLVE_FINISH, and SOLVE_START.
dtCMatrix_solve()
SEXP dtCMatrix_solve (SEXP a, SEXP b, SEXP sparse)
Definition at line 804 of file solve.c.
References CXS2M(), ERROR_SOLVE_OOM, GET_SLOT, IF_COMPLEX, M2CXS(), Matrix_cs_dropzeros(), Matrix_cs_speye(), Matrix_cs_spfree(), Matrix_cs_transpose(), Matrix_DimSym, Matrix_uploSym, Matrix_xSym, Matrix_zone, MCS_COMPLEX, MCS_XTYPE_GET, MCS_XTYPE_SET, newObject(), SET_SLOT, SOLVE_DENSE_1, SOLVE_DENSE_2, SOLVE_FINISH, SOLVE_SPARSE, SOLVE_START, and Matrix_cs_sparse::xtype.
dtrMatrix_solve()
SEXP dtrMatrix_solve (SEXP a, SEXP b)
Definition at line 372 of file solve.c.
References ERROR_LAPACK_1, ERROR_LAPACK_2, FCONE, GET_SLOT, Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, SOLVE_FINISH, and SOLVE_START.
sparseLU_solve()
SEXP sparseLU_solve (SEXP a, SEXP b, SEXP sparse)
Definition at line 493 of file solve.c.
References CXS2M(), ERROR_SOLVE_OOM, GET_SLOT, Matrix_cs_sparse::i, IF_COMPLEX, M2CXS(), Matrix_cs_dropzeros(), Matrix_cs_free(), Matrix_cs_permute(), Matrix_cs_pinv(), Matrix_cs_speye(), Matrix_cs_spfree(), Matrix_cs_transpose(), Matrix_DimSym, Matrix_LSym, Matrix_pSym, Matrix_qSym, Matrix_USym, Matrix_xSym, Matrix_zone, MCS_COMPLEX, MCS_XTYPE_GET, MCS_XTYPE_SET, newObject(), SET_SLOT, SOLVE_DENSE_1, SOLVE_DENSE_2, SOLVE_FINISH, SOLVE_SPARSE, SOLVE_START, and Matrix_cs_sparse::xtype.
sparseQR_matmult()
SEXP sparseQR_matmult (SEXP qr, SEXP y, SEXP op, SEXP complete, SEXP yxjj)
Definition at line 930 of file solve.c.
References _, EYE, GET_SLOT, IF_COMPLEX, Matrix_cs_sparse::m, M2CXS(), MATMULT, Matrix_betaSym, Matrix_DimSym, Matrix_pSym, Matrix_VSym, Matrix_xSym, Matrix_zone, MCS_COMPLEX, MCS_XTYPE_GET, MCS_XTYPE_SET, Matrix_cs_sparse::n, newObject(), SET_SLOT, and Matrix_cs_sparse::xtype.