Matrix: sparse.h File Reference
sparse.h File Reference
#include <Rinternals.h>
Functions
SEXP sparse_drop0 (SEXP, const char *, double)
SEXP R_sparse_drop0 (SEXP, SEXP)
SEXP sparse_diag_U2N (SEXP, const char *)
SEXP R_sparse_diag_U2N (SEXP)
SEXP sparse_diag_N2U (SEXP, const char *)
SEXP R_sparse_diag_N2U (SEXP)
SEXP sparse_band (SEXP, const char *, int, int)
SEXP R_sparse_band (SEXP, SEXP, SEXP)
SEXP sparse_diag_get (SEXP, const char *, int)
SEXP R_sparse_diag_get (SEXP, SEXP)
SEXP sparse_diag_set (SEXP, const char *, SEXP)
SEXP R_sparse_diag_set (SEXP, SEXP)
SEXP sparse_transpose (SEXP, const char *, int)
SEXP R_sparse_transpose (SEXP, SEXP)
SEXP sparse_force_symmetric (SEXP, const char *, char)
SEXP R_sparse_force_symmetric (SEXP, SEXP)
SEXP sparse_symmpart (SEXP, const char *)
SEXP R_sparse_symmpart (SEXP)
SEXP sparse_skewpart (SEXP, const char *)
SEXP R_sparse_skewpart (SEXP)
int sparse_is_symmetric (SEXP, const char *, int)
SEXP R_sparse_is_symmetric (SEXP, SEXP)
int sparse_is_triangular (SEXP, const char *, int)
SEXP R_sparse_is_triangular (SEXP, SEXP)
int sparse_is_diagonal (SEXP, const char *)
SEXP R_sparse_is_diagonal (SEXP)
SEXP sparse_marginsum (SEXP, const char *, int, int, int, int)
SEXP R_sparse_marginsum (SEXP, SEXP, SEXP, SEXP, SEXP)
SEXP sparse_sum (SEXP, const char *, int)
SEXP R_sparse_sum (SEXP, SEXP)
SEXP sparse_prod (SEXP, const char *, int)
SEXP R_sparse_prod (SEXP, SEXP)
SEXP Tsparse_aggregate (SEXP)
Function Documentation
R_sparse_band()
SEXP R_sparse_band (SEXP from, SEXP k1, SEXP k2)
Definition at line 574 of file sparse.c.
References _, ERROR_INVALID_CLASS, GET_SLOT, Matrix_DimSym, sparse_band(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_diag_get()
SEXP R_sparse_diag_get (SEXP obj, SEXP names)
Definition at line 772 of file sparse.c.
References _, ERROR_INVALID_CLASS, sparse_diag_get(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_diag_N2U()
SEXP R_sparse_diag_N2U (SEXP from)
Definition at line 270 of file sparse.c.
References ERROR_INVALID_CLASS, sparse_diag_N2U(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_diag_set()
SEXP R_sparse_diag_set (SEXP from, SEXP value)
Definition at line 1051 of file sparse.c.
References _, ERROR_INVALID_CLASS, GET_SLOT, kindToType(), Matrix_DimSym, sparse_as_kind(), sparse_diag_set(), typeToKind(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
Referenced by sparse_diag_U2N().
R_sparse_diag_U2N()
SEXP R_sparse_diag_U2N (SEXP from)
Definition at line 222 of file sparse.c.
References ERROR_INVALID_CLASS, sparse_diag_U2N(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_drop0()
SEXP R_sparse_drop0 (SEXP from, SEXP tol)
Definition at line 185 of file sparse.c.
References _, ERROR_INVALID_CLASS, sparse_drop0(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_force_symmetric()
SEXP R_sparse_force_symmetric (SEXP from, SEXP uplo)
Definition at line 1612 of file sparse.c.
References _, ERROR_INVALID_CLASS, sparse_force_symmetric(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_is_diagonal()
SEXP R_sparse_is_diagonal (SEXP obj)
Definition at line 2641 of file sparse.c.
References ERROR_INVALID_CLASS, sparse_is_diagonal(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_is_symmetric()
SEXP R_sparse_is_symmetric (SEXP obj, SEXP checkDN)
Definition at line 2437 of file sparse.c.
References _, ERROR_INVALID_CLASS, sparse_is_symmetric(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_is_triangular()
SEXP R_sparse_is_triangular (SEXP obj, SEXP upper)
Definition at line 2570 of file sparse.c.
References _, ERROR_INVALID_CLASS, sparse_is_triangular(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_marginsum()
SEXP R_sparse_marginsum (SEXP obj, SEXP margin, SEXP narm, SEXP mean, SEXP sparse)
Definition at line 3123 of file sparse.c.
References _, ERROR_INVALID_CLASS, sparse_marginsum(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_prod()
SEXP R_sparse_prod (SEXP obj, SEXP narm)
Definition at line 3652 of file sparse.c.
References _, ERROR_INVALID_CLASS, sparse_prod(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_skewpart()
SEXP R_sparse_skewpart (SEXP from)
Definition at line 2311 of file sparse.c.
References ERROR_INVALID_CLASS, sparse_skewpart(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_sum()
SEXP R_sparse_sum (SEXP obj, SEXP narm)
Definition at line 3415 of file sparse.c.
References _, ERROR_INVALID_CLASS, sparse_sum(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_symmpart()
SEXP R_sparse_symmpart (SEXP from)
Definition at line 2051 of file sparse.c.
References ERROR_INVALID_CLASS, sparse_symmpart(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
R_sparse_transpose()
SEXP R_sparse_transpose (SEXP from, SEXP lazy)
Definition at line 1222 of file sparse.c.
References _, ERROR_INVALID_CLASS, sparse_transpose(), valid, VALID_CSPARSE, VALID_RSPARSE, and VALID_TSPARSE.
sparse_band()
SEXP sparse_band (SEXP from, const char * class, int a, int b)
Definition at line 281 of file sparse.c.
References BAND_CASES, BAND_SUBCASES, cl, GET_SLOT, HIDE, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_memset(), Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, set_symmetrized_DimNames(), and sparse_transpose().
Referenced by R_sparse_band(), and sparse_diag_N2U().
sparse_diag_get()
SEXP sparse_diag_get (SEXP obj, const char * class, int names)
Definition at line 603 of file sparse.c.
References DG_CASES, DG_LOOP, equal_character_vectors(), GET_SLOT, HIDE, INCREMENT_PATTERN, kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, and SECONDOF.
Referenced by R_sparse_diag_get().
sparse_diag_N2U()
SEXP sparse_diag_N2U (SEXP from, const char * class)
Definition at line 233 of file sparse.c.
References GET_SLOT, Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, SET_SLOT, and sparse_band().
Referenced by dgCMatrix_dgCMatrix_matmult(), and R_sparse_diag_N2U().
sparse_diag_set()
SEXP sparse_diag_set (SEXP from, const char * class, SEXP value)
Definition at line 788 of file sparse.c.
References _, DS_CASES, DS_LOOP, GET_SLOT, HIDE, ISNZ_LOGICAL, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), and SET_SLOT.
Referenced by R_sparse_diag_set().
sparse_diag_U2N()
SEXP sparse_diag_U2N (SEXP from, const char * class)
Definition at line 201 of file sparse.c.
References GET_SLOT, Matrix_diagSym, and R_sparse_diag_set().
Referenced by R_diagonal_matmult(), R_sparse_diag_U2N(), and R_sparse_matmult().
sparse_drop0()
SEXP sparse_drop0 (SEXP from, const char * class, double tol)
Definition at line 5 of file sparse.c.
References DROP0_CASES, DROP0_LOOP1, DROP0_LOOP2, GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), and SET_SLOT.
Referenced by R_diagonal_matmult(), R_sparse_drop0(), and R_sparse_matmult().
sparse_force_symmetric()
SEXP sparse_force_symmetric (SEXP from, const char * class, char ul)
Definition at line 1238 of file sparse.c.
References _, cl, conjugate(), FS_CASES, FS_SUBCASES, GET_SLOT, HIDE, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, set_symmetrized_DimNames(), and sparse_transpose().
Referenced by CsparseMatrix_subscript_2ary(), R_sparse_force_symmetric(), and RsparseMatrix_subscript_2ary().
sparse_is_diagonal()
int sparse_is_diagonal (SEXP obj, const char * class)
Definition at line 2597 of file sparse.c.
References GET_SLOT, Matrix_DimSym, Matrix_iSym, Matrix_jSym, and Matrix_pSym.
Referenced by R_sparse_is_diagonal(), sparse_is_symmetric(), and sparse_is_triangular().
sparse_is_symmetric()
int sparse_is_symmetric (SEXP obj, const char * class, int checkDN)
Definition at line 2322 of file sparse.c.
References DimNames_is_symmetric(), GET_SLOT, HIDE, IS_LOOP, Matrix_Calloc, Matrix_DimNamesSym, Matrix_DimSym, Matrix_Free, Matrix_iSym, Matrix_jSym, Matrix_memcpy(), Matrix_pSym, Matrix_xSym, NOTCONJ_COMPLEX, NOTCONJ_INTEGER, NOTCONJ_LOGICAL, NOTCONJ_PATTERN, NOTCONJ_REAL, NOTREAL_COMPLEX, NOTREAL_INTEGER, NOTREAL_LOGICAL, NOTREAL_PATTERN, NOTREAL_REAL, SHOW, sparse_as_Csparse(), and sparse_is_diagonal().
Referenced by R_sparse_is_symmetric().
sparse_is_triangular()
int sparse_is_triangular (SEXP obj, const char * class, int upper)
Definition at line 2453 of file sparse.c.
References GET_SLOT, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, and sparse_is_diagonal().
Referenced by R_sparse_is_triangular().
sparse_marginsum()
SEXP sparse_marginsum (SEXP obj, const char * class, int margin, int narm, int mean, int sparse)
Definition at line 3051 of file sparse.c.
References cl, Csparse_colsum(), Csparse_rowsum(), GET_SLOT, get_symmetrized_DimNames(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_lengthSym, newObject(), SET_SLOT, SUM_TYPEOF, and Tsparse_colsum().
Referenced by R_sparse_marginsum().
sparse_prod()
SEXP sparse_prod (SEXP obj, const char * class, int narm)
Definition at line 3431 of file sparse.c.
References GET_SLOT, LONGDOUBLE_AS_DOUBLE, Matrix_diagSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, and Tsparse_aggregate().
Referenced by R_sparse_prod().
sparse_skewpart()
SEXP sparse_skewpart (SEXP from, const char * class)
Definition at line 2062 of file sparse.c.
References _, ASSIGN_COMPLEX, ASSIGN_REAL, cl, GET_SLOT, INCREMENT_COMPLEX, INCREMENT_REAL, kindToType(), Matrix_Calloc, Matrix_DimNamesSym, Matrix_DimSym, Matrix_Free, Matrix_iSym, Matrix_jSym, Matrix_memset(), Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, set_symmetrized_DimNames(), SP_LOOP, sparse_as_kind(), sparse_transpose(), and zeroRe().
Referenced by R_sparse_skewpart().
sparse_sum()
SEXP sparse_sum (SEXP obj, const char * class, int narm)
Definition at line 3176 of file sparse.c.
References GET_SLOT, LONGDOUBLE_AS_DOUBLE, Matrix_diagSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, TRY_INCREMENT, and Tsparse_aggregate().
Referenced by R_sparse_sum().
sparse_symmpart()
SEXP sparse_symmpart (SEXP from, const char * class)
Definition at line 1631 of file sparse.c.
References _, ASSIGN_COMPLEX, ASSIGN_REAL, cl, GET_SLOT, INCREMENT_COMPLEX, INCREMENT_REAL, kindToType(), Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, Matrix_zone, newObject(), SET_SLOT, set_symmetrized_DimNames(), SP_LOOP, sparse_as_kind(), sparse_transpose(), and zeroIm().
Referenced by R_sparse_symmpart().
sparse_transpose()
SEXP sparse_transpose (SEXP from, const char * class, int lazy)
Definition at line 1105 of file sparse.c.
References cl, GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, Matrix_xSym, newObject(), set_reversed_DimNames(), SET_SLOT, and trans().
Referenced by dgCMatrix_dgCMatrix_matmult(), R_diagonal_matmult(), R_sparse_matmult(), R_sparse_transpose(), sparse_band(), sparse_force_symmetric(), sparse_skewpart(), and sparse_symmpart().
Tsparse_aggregate()
SEXP Tsparse_aggregate (SEXP from)
Definition at line 3671 of file sparse.c.
References cl, ERROR_INVALID_CLASS, GET_SLOT, Matrix_diagSym, Matrix_DimNamesSym, Matrix_DimSym, Matrix_factorsSym, Matrix_iSym, Matrix_jSym, Matrix_uploSym, Matrix_xSym, newObject(), SET_SLOT, taggr(), valid, and VALID_TSPARSE.
Referenced by scanArgs(), sparse_as_kind(), sparse_prod(), sparse_sum(), and Tsparse_colsum().