Matrix: sparseQR.h File Reference
sparseQR.h File Reference
#include "Mutils.h"
#include "cs_utils.h"
#include "chm_common.h"
Functions
SEXP sparseQR_coef (SEXP qr, SEXP y)
SEXP sparseQR_qty (SEXP qr, SEXP y, SEXP trans, SEXP keep_dimnames)
Given a sparse QR decomposition and y, compute Q y or Q'y.
SEXP sparseQR_resid_fitted (SEXP qr, SEXP y, SEXP resid)
Compute qr.resid(qr, y) or qr.fitted(qr, y)
SEXP sparseQR_validate (SEXP x)
Function Documentation
sparseQR_coef()
SEXP sparseQR_coef (SEXP qr, SEXP y)
Definition at line 147 of file sparseQR.c.
References _, AS_CSP__, C_or_Alloca_TO, cs_ipvec(), cs_usolve(), EXIT_sparseQR_, INIT_sparseQR_, Matrix_betaSym, Matrix_DimNamesSym, Matrix_pSym, Matrix_RSym, Matrix_xSym, cs_sparse::n, SMALL_4_Alloca, and sparseQR_Qmult().
sparseQR_qty()
SEXP sparseQR_qty (SEXP qr, SEXP y, SEXP trans, SEXP keep_dimnames)
Given a sparse QR decomposition and y, compute Q y or Q'y.
Parameters
qr a "sparseQR" object
y a (dense) Matrix
trans logical, if TRUE compute Q'y else Q y
Returns
Q'y ("qty") or Qy ("qy")
Definition at line 87 of file sparseQR.c.
References _, EXIT_sparseQR_, INIT_sparseQR_, Matrix_betaSym, Matrix_pSym, and sparseQR_Qmult().
sparseQR_resid_fitted()
SEXP sparseQR_resid_fitted (SEXP qr, SEXP y, SEXP resid)
Compute qr.resid(qr, y) or qr.fitted(qr, y)
Definition at line 198 of file sparseQR.c.
References _, EXIT_sparseQR_, INIT_sparseQR_, Matrix_betaSym, Matrix_pSym, Matrix_xSym, and sparseQR_Qmult().
sparseQR_validate()
SEXP sparseQR_validate (SEXP x)
Definition at line 3 of file sparseQR.c.
References _, AS_CSP__, cs_sparse::m, Matrix_betaSym, Matrix_pSym, Matrix_RSym, Matrix_VSym, and cs_sparse::n.