Matrix: sparseQR.c File Reference
sparseQR.c File Reference
#include "sparseQR.h"
Macros
#define EXIT_sparseQR_
#define INIT_sparseQR_(_DM_NMS_)
Functions
SEXP sparseQR_coef (SEXP qr, SEXP y)
static void sparseQR_Qmult (cs *V, SEXP dmns, double *beta, int *p, int trans, SEXP ans)
Apply Householder transformations and the row permutation P to y.
SEXP sparseQR_qty (SEXP qr, SEXP y, SEXP trans, SEXP keep_dimnames)
Given a sparse QR decomposition and y, compute Q y or Q'y.
SEXP sparseQR_resid_fitted (SEXP qr, SEXP y, SEXP want_resid)
Compute qr.resid(qr, y) or qr.fitted(qr, y)
SEXP sparseQR_validate (SEXP x)
Macro Definition Documentation
EXIT_sparseQR_
#define EXIT_sparseQR_
Value:
    /* remove the extra rows from ans */                                \
        d_a[0] = m;/* -> @Dim is ok;  @Dimnames (i.e. colnames) still are */ \
        double *yy = REAL( GET_SLOT(ans, Matrix_xSym)); /* is  M  x n */ \
        double *xx = REAL(ALLOC_SLOT(aa, Matrix_xSym, REALSXP, m * (R_xlen_t) n)); \
        for(int j = 0; j < n; j++) { /*  j-th column */                 \
            Memcpy(xx + j*m, yy + j*M, m); /* copy    x[ 1:m, j ] := yy[,j] */ \
        }                                                               \
        ans = duplicate(aa); /*  m x n  finally */                      \
        UNPROTECT(1)
INIT_sparseQR_
#define INIT_sparseQR_ (_DM_NMS_)
Value:
    SEXP V_ = GET_SLOT(qr, Matrix_VSym);                                \
    CSP V = AS_CSP__(V_);                                               \
    R_CheckStack();                                                     \
    SEXP ans, aa, dmns = R_NilValue;                                    \
    if(_DM_NMS_) dmns = GET_SLOT(V_, Matrix_DimNamesSym);               \
    PROTECT_INDEX ipx;                                                  \
    PROTECT_WITH_INDEX(ans = dup_mMatrix_as_dgeMatrix(y), &ipx);        \
    int *ydims = INTEGER(GET_SLOT(ans, Matrix_DimSym)),                 \
        m = ydims[0], n = ydims[1], M = V->m, *d_a;                     \
    Rboolean rank_def = (m < M);                                        \
    if(rank_def) { /* must add 0-rows to y, i.e. ans, and remove them *before* return */ \
        aa = PROTECT(NEW_OBJECT_OF_CLASS("dgeMatrix"));                 \
        d_a = INTEGER(GET_SLOT(aa, Matrix_DimSym)); d_a[0] = M; d_a[1] = n; \
        SEXP dn = GET_SLOT(aa, Matrix_DimNamesSym);                     \
        SET_VECTOR_ELT(dn, 1,                                           \
                       duplicate(VECTOR_ELT(GET_SLOT(ans, Matrix_DimNamesSym), 1)));    \
        SET_SLOT(aa, Matrix_DimNamesSym, dn);                           \
        double *yy = REAL( GET_SLOT(ans, Matrix_xSym));     /* m * n */ \
        double *xx = REAL(ALLOC_SLOT(aa, Matrix_xSym, REALSXP, M * (R_xlen_t) n));      \
        for(int j = 0; j < n; j++) { /* j-th column */                  \
            Memcpy(xx + j*M, yy + j*m, m); /* copy          x[   1:m , j ] := yy[,j] */ \
            for(int i = m; i < M; i++) xx[i + j*M] = 0.;/*  x[(m+1):M, j ] := 0 */      \
        }                                                               \
        REPROTECT(ans = duplicate(aa), ipx); /* is  M x n  now */       \
    }
Function Documentation
sparseQR_coef()
SEXP sparseQR_coef (SEXP qr, SEXP y)
Definition at line 147 of file sparseQR.c.
References _, AS_CSP__, C_or_Alloca_TO, cs_ipvec(), cs_usolve(), EXIT_sparseQR_, INIT_sparseQR_, Matrix_betaSym, Matrix_DimNamesSym, Matrix_pSym, Matrix_RSym, Matrix_xSym, cs_sparse::n, SMALL_4_Alloca, and sparseQR_Qmult().
sparseQR_Qmult()
static void sparseQR_Qmult (cs * V, SEXP dmns, double * beta, int * p, int trans, SEXP ans) static
Apply Householder transformations and the row permutation P to y.
Parameters
V sparse matrix containing the vectors defining the Householder transformations
dmns == dimnames(V) or "NULL" (R_NilValue)
beta scaling factors for the Householder transformations
p 0-based permutation vector of length V->m
trans logical value - if TRUE create Q'y[p] otherwise Qy[p]
ans : both function argument and result ("input and output")
Definition at line 37 of file sparseQR.c.
References _, C_or_Alloca_TO, cs_happly(), cs_ipvec(), cs_pvec(), cs_sparse::m, Matrix_DimNamesSym, Matrix_DimSym, Matrix_xSym, cs_sparse::n, and SMALL_4_Alloca.
Referenced by sparseQR_coef(), sparseQR_qty(), and sparseQR_resid_fitted().
sparseQR_qty()
SEXP sparseQR_qty (SEXP qr, SEXP y, SEXP trans, SEXP keep_dimnames)
Given a sparse QR decomposition and y, compute Q y or Q'y.
Parameters
qr a "sparseQR" object
y a (dense) Matrix
trans logical, if TRUE compute Q'y else Q y
Returns
Q'y ("qty") or Qy ("qy")
Definition at line 87 of file sparseQR.c.
References _, EXIT_sparseQR_, INIT_sparseQR_, Matrix_betaSym, Matrix_pSym, and sparseQR_Qmult().
sparseQR_resid_fitted()
SEXP sparseQR_resid_fitted (SEXP qr, SEXP y, SEXP want_resid)
Compute qr.resid(qr, y) or qr.fitted(qr, y)
Definition at line 198 of file sparseQR.c.
References _, EXIT_sparseQR_, INIT_sparseQR_, Matrix_betaSym, Matrix_pSym, Matrix_xSym, and sparseQR_Qmult().
sparseQR_validate()
SEXP sparseQR_validate (SEXP x)
Definition at line 3 of file sparseQR.c.
References _, AS_CSP__, cs_sparse::m, Matrix_betaSym, Matrix_pSym, Matrix_RSym, Matrix_VSym, and cs_sparse::n.