Matrix: subscript.h File Reference
subscript.h File Reference
#include <Rinternals.h>
Functions
SEXP R_subscript_1ary (SEXP, SEXP)
SEXP R_subscript_1ary_mat (SEXP, SEXP)
SEXP R_subscript_2ary (SEXP, SEXP, SEXP)
Function Documentation
R_subscript_1ary()
SEXP R_subscript_1ary (SEXP x, SEXP i)
Definition at line 411 of file subscript.c.
References cl, CsparseMatrix_subscript_1ary(), diagonalMatrix_subscript_1ary(), ERROR_INVALID_CLASS, indMatrix_subscript_1ary(), packedMatrix_subscript_1ary(), RsparseMatrix_subscript_1ary(), sparse_as_Csparse(), unpackedMatrix_subscript_1ary(), valid, VALID_NONVIRTUAL_MATRIX, VALID_NONVIRTUAL_SHIFT, and validObject().
R_subscript_1ary_mat()
SEXP R_subscript_1ary_mat (SEXP x, SEXP i)
Definition at line 792 of file subscript.c.
References cl, CsparseMatrix_subscript_1ary_mat(), diagonalMatrix_subscript_1ary_mat(), ERROR_INVALID_CLASS, indMatrix_subscript_1ary_mat(), packedMatrix_subscript_1ary_mat(), RsparseMatrix_subscript_1ary_mat(), sparse_as_Csparse(), unpackedMatrix_subscript_1ary_mat(), valid, VALID_NONVIRTUAL_MATRIX, VALID_NONVIRTUAL_SHIFT, and validObject().
R_subscript_2ary()
SEXP R_subscript_2ary (SEXP x, SEXP i, SEXP j)
Definition at line 2174 of file subscript.c.
References cl, CsparseMatrix_subscript_2ary(), diagonalMatrix_subscript_2ary(), ERROR_IF_ANYNA, ERROR_INVALID_CLASS, indMatrix_subscript_2ary(), packedMatrix_subscript_2ary(), RsparseMatrix_subscript_2ary(), sparse_as_Csparse(), sparse_as_Tsparse(), unpackedMatrix_subscript_2ary(), valid, VALID_NONVIRTUAL_MATRIX, VALID_NONVIRTUAL_SHIFT, and validObject().