Matrix: t.c File Reference
t.c File Reference
#include "Mdefines.h"
#include "M5.h"
#include "idz.h"
Macros
#define TEMPLATE(c)
#define TEMPLATE(c)
Functions
SEXP dense_transpose (SEXP from, const char *class, char op_ct)
SEXP sparse_transpose (SEXP from, const char *class, char op_ct, int lazy)
SEXP R_dense_transpose (SEXP s_from, SEXP s_trans)
SEXP R_sparse_transpose (SEXP s_from, SEXP s_trans, SEXP s_lazy)
Macro Definition Documentation
TEMPLATE [1/2]
#define TEMPLATE (c)
Value:
    do { \
        c##TYPE *px0 = c##PTR(x0), *px1 = c##PTR(x1); \
        if (!packed) \
            c##NAME(trans2)(px1, px0, m_, n_, op_ct); \
        else \
            c##NAME(trans1)(px1, px0, n_, ul, op_ct); \
    } while (0)
Referenced by dense_transpose(), and sparse_transpose().
TEMPLATE [2/2]
#define TEMPLATE (c)
Value:
        do { \
            c##TYPE *px0 = NULL, *px1 = NULL; \
            c##IF_NPATTERN( \
            SEXP x0 = PROTECT(GET_SLOT(from, Matrix_xSym)), \
                x1 = PROTECT(Rf_allocVector(c##TYPESXP, nnz)); \
            px0 = c##PTR(x0); \
            px1 = c##PTR(x1); \
            SET_SLOT(to, Matrix_xSym, x1); \
            UNPROTECT(2); /* x1, x0 */ \
            ); \
            c##csptrans(pp1, pi1, px1, pp0, pi0, px0, m, n, op_ct, iwork); \
        } while (0)
Function Documentation
dense_transpose()
SEXP dense_transpose (SEXP from, const char * class, char op_ct)
Definition at line 7 of file t.c.
References COPY_SLOT, DIAG, DIM, DIMNAMES, GET_SLOT, Matrix_sdSym, Matrix_xSym, newObject(), SET_DIAG, SET_DIM, SET_DIMNAMES, SET_SLOT, SET_TRANS, SET_UPLO, SWITCH4, TEMPLATE, TRANS, TYPEOF, and UPLO.
Referenced by R_dense_transpose().
R_dense_transpose()
SEXP R_dense_transpose (SEXP s_from, SEXP s_trans)
Definition at line 170 of file t.c.
References dense_transpose(), Matrix_class(), valid_dense, and VALID_TRANS.
R_sparse_transpose()
SEXP R_sparse_transpose (SEXP s_from, SEXP s_trans, SEXP s_lazy)
Definition at line 180 of file t.c.
References Matrix_class(), sparse_transpose(), VALID_LOGIC2, valid_sparse, and VALID_TRANS.
sparse_transpose()
SEXP sparse_transpose (SEXP from, const char * class, char op_ct, int lazy)
Definition at line 52 of file t.c.
References cl, DIAG, DIM, DIMNAMES, GET_SLOT, Matrix_Calloc, Matrix_Free, Matrix_iSym, Matrix_jSym, Matrix_pSym, Matrix_xSym, newObject(), SET_DIAG, SET_DIM, SET_DIMNAMES, SET_SLOT, SET_TRANS, SET_UPLO, SWAP, SWITCH5, TEMPLATE, TRANS, UPLO, and zvconj().
Referenced by gCgCMatrix_matmult(), R_sparse_transpose(), and sparse_cholesky().