Matrix: TMatrix_as.c File Reference
TMatrix_as.c File Reference
#include "TMatrix_as.h"
Macros
#define ALLOC_val_x_SLOT(__SEXP__, __S_TYPE__) vx = __SEXP__(ALLOC_SLOT(val, Matrix_xSym,__S_TYPE__, nv))
#define Matrix_sT_as_GENERAL(_C_TYPE_, _SEXP_, _SEXPTYPE_)
#define Matrix_T_as_DENSE(_C_TYPE_, _SEXP_, _SEXPTYPE_, _SYMM_)
#define Matrix_T_as_DENSE_FINISH(_X_k_)
#define MAYBE_ALLOC_val_x_SLOT(_S1_, _S2_) ALLOC_val_x_SLOT(_S1_, _S2_)
#define MAYBE_ALLOC_val_x_SLOT(_S1_, _S2_)
#define MAYBE_DECLARE_AND_GET_X_SLOT(__T__, __S__) DECLARE_AND_GET_X_SLOT(__T__, __S__)
#define MAYBE_DECLARE_AND_GET_X_SLOT(__T__, __S__) DECLARE_AND_GET_X_SLOT(__T__, __S__), *vx
#define MAYBE_DECLARE_AND_GET_X_SLOT(__T__, __S__)
#define MAYBE_MEMCPY_x_SLOT MEMCPY_x_SLOT
#define MAYBE_MEMCPY_x_SLOT
#define MAYBE_SET_x_SLOT SET_x_SLOT
#define MAYBE_SET_x_SLOT
#define MEMCPY_x_SLOT Memcpy(&vx[nv], xx, nnz)
#define SET_x_SLOT vx[nv] = xx[i]
Functions
SEXP dsTMatrix_as_dgTMatrix (SEXP x)
SEXP dsTMatrix_as_dsyMatrix (SEXP x)
SEXP dtTMatrix_as_dtrMatrix (SEXP x)
SEXP lsTMatrix_as_lgTMatrix (SEXP x)
SEXP lsTMatrix_as_lsyMatrix (SEXP x)
SEXP ltTMatrix_as_ltrMatrix (SEXP x)
SEXP nsTMatrix_as_ngTMatrix (SEXP x)
SEXP nsTMatrix_as_nsyMatrix (SEXP x)
SEXP ntTMatrix_as_ntrMatrix (SEXP x)
Macro Definition Documentation
ALLOC_val_x_SLOT
#define ALLOC_val_x_SLOT (__SEXP__, __S_TYPE__) vx = __SEXP__(ALLOC_SLOT(val, Matrix_xSym,__S_TYPE__, nv))
Definition at line 73 of file TMatrix_as.c.
Matrix_sT_as_GENERAL
#define Matrix_sT_as_GENERAL (_C_TYPE_, _SEXP_, _SEXPTYPE_)
Definition at line 85 of file TMatrix_as.c.
Matrix_T_as_DENSE
#define Matrix_T_as_DENSE (_C_TYPE_, _SEXP_, _SEXPTYPE_, _SYMM_)
Value:
    SEXP dimP = GET_SLOT(x, Matrix_DimSym),                             \
          xiP = GET_SLOT(x, Matrix_iSym);                               \
    int k, n = INTEGER(dimP)[0]; R_xlen_t nnz = xlength(xiP);           \
    int *xi = INTEGER(xiP), *xj = INTEGER(GET_SLOT(x, Matrix_jSym));    \
    R_xlen_t n_ = n, sz = n * n_;                                       \
    _C_TYPE_ *tx = _SEXP_(ALLOC_SLOT(val, Matrix_xSym, _SEXPTYPE_, sz)); \
    MAYBE_DECLARE_AND_GET_X_SLOT(_C_TYPE_, _SEXP_);                     \
                                                                        \
    SET_SLOT(val, Matrix_DimSym, duplicate(dimP));                      \
    if(_SYMM_)                                                          \
        SET_DimNames_symm(val, x);                                      \
    else                                \
    SET_DimNames(val, x);                                          \
    slot_dup(val, x, Matrix_uploSym)
Definition at line 7 of file TMatrix_as.c.
Matrix_T_as_DENSE_FINISH
#define Matrix_T_as_DENSE_FINISH (_X_k_)
Value:
    AZERO(tx, sz);                              \
    for (k = 0; k < nnz; k++)                   \
        tx[xi[k] + xj[k] * n_] = _X_k_;         \
    UNPROTECT(1);                               \
    return val
Definition at line 23 of file TMatrix_as.c.
MAYBE_ALLOC_val_x_SLOT [1/2]
#define MAYBE_ALLOC_val_x_SLOT (_S1_, _S2_) ALLOC_val_x_SLOT(_S1_, _S2_)
Definition at line 146 of file TMatrix_as.c.
MAYBE_ALLOC_val_x_SLOT [2/2]
#define MAYBE_ALLOC_val_x_SLOT (_S1_, _S2_)
Definition at line 146 of file TMatrix_as.c.
MAYBE_DECLARE_AND_GET_X_SLOT [1/3]
#define MAYBE_DECLARE_AND_GET_X_SLOT (__T__, __S__) DECLARE_AND_GET_X_SLOT(__T__, __S__)
Definition at line 144 of file TMatrix_as.c.
MAYBE_DECLARE_AND_GET_X_SLOT [2/3]
#define MAYBE_DECLARE_AND_GET_X_SLOT (__T__, __S__) DECLARE_AND_GET_X_SLOT(__T__, __S__), *vx
Definition at line 144 of file TMatrix_as.c.
MAYBE_DECLARE_AND_GET_X_SLOT [3/3]
#define MAYBE_DECLARE_AND_GET_X_SLOT (__T__, __S__)
Definition at line 144 of file TMatrix_as.c.
MAYBE_MEMCPY_x_SLOT [1/2]
#define MAYBE_MEMCPY_x_SLOT MEMCPY_x_SLOT
Definition at line 148 of file TMatrix_as.c.
MAYBE_MEMCPY_x_SLOT [2/2]
#define MAYBE_MEMCPY_x_SLOT
Definition at line 148 of file TMatrix_as.c.
MAYBE_SET_x_SLOT [1/2]
#define MAYBE_SET_x_SLOT SET_x_SLOT
Definition at line 150 of file TMatrix_as.c.
MAYBE_SET_x_SLOT [2/2]
#define MAYBE_SET_x_SLOT
Definition at line 150 of file TMatrix_as.c.
MEMCPY_x_SLOT
#define MEMCPY_x_SLOT Memcpy(&vx[nv], xx, nnz)
Definition at line 79 of file TMatrix_as.c.
SET_x_SLOT
#define SET_x_SLOT vx[nv] = xx[i]
Definition at line 82 of file TMatrix_as.c.
Function Documentation
dsTMatrix_as_dgTMatrix()
SEXP dsTMatrix_as_dgTMatrix (SEXP x)
Definition at line 128 of file TMatrix_as.c.
References Matrix_sT_as_GENERAL, and NEW_OBJECT_OF_CLASS().
dsTMatrix_as_dsyMatrix()
SEXP dsTMatrix_as_dsyMatrix (SEXP x)
Definition at line 31 of file TMatrix_as.c.
References Matrix_T_as_DENSE, Matrix_T_as_DENSE_FINISH, and NEW_OBJECT_OF_CLASS().
dtTMatrix_as_dtrMatrix()
SEXP dtTMatrix_as_dtrMatrix (SEXP x)
Definition at line 49 of file TMatrix_as.c.
References Matrix_diagSym, Matrix_T_as_DENSE, Matrix_T_as_DENSE_FINISH, NEW_OBJECT_OF_CLASS(), and slot_dup.
lsTMatrix_as_lgTMatrix()
SEXP lsTMatrix_as_lgTMatrix (SEXP x)
Definition at line 135 of file TMatrix_as.c.
References Matrix_sT_as_GENERAL, and NEW_OBJECT_OF_CLASS().
lsTMatrix_as_lsyMatrix()
SEXP lsTMatrix_as_lsyMatrix (SEXP x)
Definition at line 39 of file TMatrix_as.c.
References Matrix_T_as_DENSE, Matrix_T_as_DENSE_FINISH, and NEW_OBJECT_OF_CLASS().
ltTMatrix_as_ltrMatrix()
SEXP ltTMatrix_as_ltrMatrix (SEXP x)
Definition at line 58 of file TMatrix_as.c.
References Matrix_diagSym, Matrix_T_as_DENSE, Matrix_T_as_DENSE_FINISH, NEW_OBJECT_OF_CLASS(), and slot_dup.
nsTMatrix_as_ngTMatrix()
SEXP nsTMatrix_as_ngTMatrix (SEXP x)
Definition at line 169 of file TMatrix_as.c.
References Matrix_sT_as_GENERAL, and NEW_OBJECT_OF_CLASS().
nsTMatrix_as_nsyMatrix()
SEXP nsTMatrix_as_nsyMatrix (SEXP x)
Definition at line 152 of file TMatrix_as.c.
References Matrix_T_as_DENSE, Matrix_T_as_DENSE_FINISH, and NEW_OBJECT_OF_CLASS().
ntTMatrix_as_ntrMatrix()
SEXP ntTMatrix_as_ntrMatrix (SEXP x)
Definition at line 160 of file TMatrix_as.c.
References Matrix_diagSym, Matrix_T_as_DENSE, Matrix_T_as_DENSE_FINISH, NEW_OBJECT_OF_CLASS(), and slot_dup.