Matrix: TMatrix_as.h File Reference
TMatrix_as.h File Reference
#include "Mutils.h"
Functions
SEXP dsTMatrix_as_dgTMatrix (SEXP x)
SEXP dsTMatrix_as_dsyMatrix (SEXP x)
SEXP dtTMatrix_as_dtrMatrix (SEXP x)
SEXP lsTMatrix_as_lgTMatrix (SEXP x)
SEXP lsTMatrix_as_lsyMatrix (SEXP x)
SEXP ltTMatrix_as_ltrMatrix (SEXP x)
SEXP nsTMatrix_as_ngTMatrix (SEXP x)
SEXP nsTMatrix_as_nsyMatrix (SEXP x)
SEXP ntTMatrix_as_ntrMatrix (SEXP x)
Function Documentation
dsTMatrix_as_dgTMatrix()
SEXP dsTMatrix_as_dgTMatrix (SEXP x)
Definition at line 128 of file TMatrix_as.c.
References Matrix_sT_as_GENERAL, and NEW_OBJECT_OF_CLASS().
dsTMatrix_as_dsyMatrix()
SEXP dsTMatrix_as_dsyMatrix (SEXP x)
Definition at line 31 of file TMatrix_as.c.
References Matrix_T_as_DENSE, Matrix_T_as_DENSE_FINISH, and NEW_OBJECT_OF_CLASS().
dtTMatrix_as_dtrMatrix()
SEXP dtTMatrix_as_dtrMatrix (SEXP x)
Definition at line 49 of file TMatrix_as.c.
lsTMatrix_as_lgTMatrix()
SEXP lsTMatrix_as_lgTMatrix (SEXP x)
Definition at line 135 of file TMatrix_as.c.
References Matrix_sT_as_GENERAL, and NEW_OBJECT_OF_CLASS().
lsTMatrix_as_lsyMatrix()
SEXP lsTMatrix_as_lsyMatrix (SEXP x)
Definition at line 39 of file TMatrix_as.c.
References Matrix_T_as_DENSE, Matrix_T_as_DENSE_FINISH, and NEW_OBJECT_OF_CLASS().
ltTMatrix_as_ltrMatrix()
SEXP ltTMatrix_as_ltrMatrix (SEXP x)
Definition at line 58 of file TMatrix_as.c.
References Matrix_diagSym, Matrix_T_as_DENSE, Matrix_T_as_DENSE_FINISH, NEW_OBJECT_OF_CLASS(), and slot_dup.
nsTMatrix_as_ngTMatrix()
SEXP nsTMatrix_as_ngTMatrix (SEXP x)
Definition at line 169 of file TMatrix_as.c.
References Matrix_sT_as_GENERAL, and NEW_OBJECT_OF_CLASS().
nsTMatrix_as_nsyMatrix()
SEXP nsTMatrix_as_nsyMatrix (SEXP x)
Definition at line 152 of file TMatrix_as.c.
References Matrix_T_as_DENSE, Matrix_T_as_DENSE_FINISH, and NEW_OBJECT_OF_CLASS().
ntTMatrix_as_ntrMatrix()
SEXP ntTMatrix_as_ntrMatrix (SEXP x)
Definition at line 160 of file TMatrix_as.c.
References Matrix_diagSym, Matrix_T_as_DENSE, Matrix_T_as_DENSE_FINISH, NEW_OBJECT_OF_CLASS(), and slot_dup.