Matrix: Tsparse.c File Reference
Tsparse.c File Reference
#include "Tsparse.h"
#include "chm_common.h"
Functions
SEXP Tsparse_diagU2N (SEXP x)
SEXP Tsparse_to_Csparse (SEXP x, SEXP tri)
SEXP Tsparse_to_tCsparse (SEXP x, SEXP uplo, SEXP diag)
SEXP Tsparse_validate (SEXP x)
Function Documentation
SEXP Tsparse_diagU2N (SEXP x)
Definition at line 63 of file Tsparse.c.
References ALLOC_SLOT(), class_P, diag_P, Matrix_check_class_etc, Matrix_diagSym, Matrix_DimSym, Matrix_iSym, Matrix_jSym, Matrix_uploSym, Matrix_xSym, SET_DimNames, and slot_dup.
Referenced by Csparse_crossprod().
SEXP Tsparse_to_Csparse (SEXP x, SEXP tri)
Definition at line 34 of file Tsparse.c.
References AS_CHM_TR__, c, chm_sparse_to_SEXP(), diag_P, Matrix_DimNamesSym, Real_kind, and uplo_P.
SEXP Tsparse_to_tCsparse (SEXP x, SEXP uplo, SEXP diag)
Definition at line 49 of file Tsparse.c.
References AS_CHM_TR__, c, chm_sparse_to_SEXP(), Matrix_DimNamesSym, and Real_kind.
SEXP Tsparse_validate (SEXP x)
Definition at line 5 of file Tsparse.c.
References _, Matrix_DimSym, Matrix_iSym, and Matrix_jSym.