Matrix: updown.c File Reference
updown.c File Reference
#include "cholmod-etc.h"
#include "Mdefines.h"
#include "M5.h"
Macros
#define UPDOWN_FINISH
Functions
SEXP sparseCholesky_updown (SEXP s_trf, SEXP s_obj, SEXP s_update)
SEXP sparseCholesky_update (SEXP s_trf, SEXP s_obj, SEXP s_beta)
Macro Definition Documentation
UPDOWN_FINISH
#define UPDOWN_FINISH
Value:
    do { \
        SEXP dimnames = PROTECT(DIMNAMES(s_trf, 0)); \
        PROTECT(s_trf = CHF2M(L, 1)); \
        cholmod_free_factor(&L, &c); \
        if (TYPEOF(s_trf) == CHARSXP) \
            Rf_error("%s", CHAR(s_trf)); \
        SET_DIMNAMES(s_trf, 0, dimnames); \
        UNPROTECT(2); \
    } while (0)
Referenced by sparseCholesky_update(), and sparseCholesky_updown().
Function Documentation
sparseCholesky_update()
SEXP sparseCholesky_update (SEXP s_trf, SEXP s_obj, SEXP s_beta)
Definition at line 30 of file updown.c.
References _, c, M2CHF(), M2CHS(), Matrix_shape(), UPDOWN_FINISH, and UPLO.
sparseCholesky_updown()
SEXP sparseCholesky_updown (SEXP s_trf, SEXP s_obj, SEXP s_update)
Definition at line 7 of file updown.c.
References c, M2CHF(), M2CHS(), and UPDOWN_FINISH.