Matrix: utils.c File Reference
utils.c File Reference
#include <stdio.h>
#include "Mdefines.h"
#include "utils.h"
Functions
void * Matrix_memset (void *dest, int ch, R_xlen_t length, size_t size)
void * Matrix_memcpy (void *dest, const void *src, R_xlen_t length, size_t size)
char * Matrix_sprintf (const char *format,...)
int equal_character_vectors (SEXP s1, SEXP s2, int n)
void conjugate (SEXP x)
void zeroRe (SEXP x)
void zeroIm (SEXP x)
void naToOne (SEXP x)
Function Documentation
conjugate()
void conjugate (SEXP x)
Definition at line 152 of file utils.c.
Referenced by dense_force_symmetric(), and sparse_force_symmetric().
equal_character_vectors()
int equal_character_vectors (SEXP s1, SEXP s2, int n)
Definition at line 143 of file utils.c.
Referenced by dense_diag_get(), DimNames_is_symmetric(), sparse_diag_get(), and symmetricMatrix_validate().
Matrix_memcpy()
void * Matrix_memcpy (void * dest, const void * src, R_xlen_t length, size_t size)
Definition at line 70 of file utils.c.
Referenced by bindArgs(), CHD2M(), CHF2M(), CHS2M(), CXS2M(), dgCMatrix_cholsol(), dgCMatrix_orf(), dgCMatrix_qrsol(), dgCMatrix_trf(), dgeMatrix_trf_(), dppMatrix_trf_(), dspMatrix_trf_(), dtpMatrix_matmult(), dtrMatrix_matmult(), index_as_sparse(), matrix_as_dense(), R_diagonal_matmult(), sparse_as_Tsparse(), sparse_is_symmetric(), and trans().
Matrix_memset()
void * Matrix_memset (void * dest, int ch, R_xlen_t length, size_t size)
Definition at line 8 of file utils.c.
Referenced by bindArgs(), dense_skewpart(), dgeMatrix_exp(), dgeMatrix_matmult(), diagonal_as_sparse(), dpoMatrix_trf_(), dsyMatrix_trf_(), index_as_sparse(), sparse_as_general(), sparse_band(), sparse_skewpart(), trans(), and vector_as_sparse().
Matrix_sprintf()
char * Matrix_sprintf (const char * format, ...)
Definition at line 133 of file utils.c.
References Matrix_ErrorBufferSize.
naToOne()
void naToOne (SEXP x)
Definition at line 185 of file utils.c.
References ERROR_INVALID_TYPE, and Matrix_zone.
Referenced by dense_as_kind(), diagonal_as_dense(), diagonal_as_kind(), diagonal_as_sparse(), R_Matrix_as_matrix(), and R_Matrix_as_vector().
zeroIm()
void zeroIm (SEXP x)
Definition at line 174 of file utils.c.
Referenced by dense_symmpart(), and sparse_symmpart().
zeroRe()
void zeroRe (SEXP x)
Definition at line 163 of file utils.c.
Referenced by dense_skewpart(), and sparse_skewpart().