Matrix: validity.h File Reference
validity.h File Reference
#include <Rinternals.h>
Functions
char * Dim_validate (SEXP)
Test that dim is a length-2, non-negative integer vector.
SEXP R_Dim_validate (SEXP)
char * DimNames_validate (SEXP, int[])
SEXP R_DimNames_validate (SEXP, SEXP)
SEXP R_DimNames_fixup (SEXP)
Sanitize user-supplied [dD]imnames.
SEXP Matrix_validate (SEXP)
SEXP MatrixFactorization_validate (SEXP)
SEXP nMatrix_validate (SEXP)
SEXP lMatrix_validate (SEXP)
SEXP iMatrix_validate (SEXP)
SEXP dMatrix_validate (SEXP)
SEXP zMatrix_validate (SEXP)
SEXP compMatrix_validate (SEXP)
SEXP symmetricMatrix_validate (SEXP)
SEXP triangularMatrix_validate (SEXP)
SEXP diagonalMatrix_validate (SEXP)
SEXP indMatrix_validate (SEXP)
SEXP pMatrix_validate (SEXP)
SEXP CsparseMatrix_validate (SEXP)
SEXP RsparseMatrix_validate (SEXP)
SEXP TsparseMatrix_validate (SEXP)
SEXP sCMatrix_validate (SEXP)
SEXP tCMatrix_validate (SEXP)
SEXP sRMatrix_validate (SEXP)
SEXP tRMatrix_validate (SEXP)
SEXP sTMatrix_validate (SEXP)
SEXP tTMatrix_validate (SEXP)
SEXP xgCMatrix_validate (SEXP)
SEXP xsCMatrix_validate (SEXP)
SEXP xtCMatrix_validate (SEXP)
SEXP xgRMatrix_validate (SEXP)
SEXP xsRMatrix_validate (SEXP)
SEXP xtRMatrix_validate (SEXP)
SEXP xgTMatrix_validate (SEXP)
SEXP xsTMatrix_validate (SEXP)
SEXP xtTMatrix_validate (SEXP)
SEXP unpackedMatrix_validate (SEXP)
SEXP packedMatrix_validate (SEXP)
SEXP dpoMatrix_validate (SEXP)
SEXP dppMatrix_validate (SEXP)
SEXP corMatrix_validate (SEXP)
SEXP pcorMatrix_validate (SEXP)
SEXP sparseVector_validate (SEXP)
SEXP lsparseVector_validate (SEXP)
SEXP isparseVector_validate (SEXP)
SEXP dsparseVector_validate (SEXP)
SEXP zsparseVector_validate (SEXP)
SEXP denseLU_validate (SEXP)
SEXP sparseLU_validate (SEXP)
SEXP sparseQR_validate (SEXP)
SEXP BunchKaufman_validate (SEXP)
SEXP pBunchKaufman_validate (SEXP)
SEXP Cholesky_validate (SEXP)
SEXP pCholesky_validate (SEXP)
SEXP CHMfactor_validate (SEXP)
SEXP CHMsimpl_validate (SEXP)
SEXP CHMsuper_validate (SEXP)
SEXP dCHMsimpl_validate (SEXP)
SEXP dCHMsuper_validate (SEXP)
SEXP Schur_validate (SEXP)
void validObject (SEXP, const char *)
Function Documentation
BunchKaufman_validate()
SEXP BunchKaufman_validate (SEXP obj)
Definition at line 1312 of file validity.c.
References _, GET_SLOT, Matrix_DimSym, Matrix_permSym, and RMKMS.
Referenced by pBunchKaufman_validate().
CHMfactor_validate()
SEXP CHMfactor_validate (SEXP obj)
Definition at line 1441 of file validity.c.
References _, FRMKMS, GET_SLOT, Matrix_Calloc, Matrix_DimSym, Matrix_Free, Matrix_permSym, and RMKMS.
CHMsimpl_validate()
SEXP CHMsimpl_validate (SEXP obj)
Definition at line 1500 of file validity.c.
References _, GET_SLOT, Matrix_DimSym, Matrix_iSym, Matrix_pSym, and RMKMS.
CHMsuper_validate()
SEXP CHMsuper_validate (SEXP obj)
Definition at line 1621 of file validity.c.
References _, GET_SLOT, Matrix_DimSym, and RMKMS.
Cholesky_validate()
SEXP Cholesky_validate (SEXP obj)
Definition at line 1351 of file validity.c.
References _, FRMKMS, GET_SLOT, Matrix_Calloc, Matrix_DimSym, Matrix_Free, Matrix_permSym, Matrix_xSym, RMK, and RMKMS.
compMatrix_validate()
SEXP compMatrix_validate (SEXP obj)
Definition at line 193 of file validity.c.
References _, GET_SLOT, Matrix_factorsSym, and RMKMS.
corMatrix_validate()
SEXP corMatrix_validate (SEXP obj)
Definition at line 945 of file validity.c.
References _, GET_SLOT, Matrix_DimSym, Matrix_sdSym, Matrix_xSym, RMK, and RMKMS.
CsparseMatrix_validate()
SEXP CsparseMatrix_validate (SEXP obj)
Definition at line 395 of file validity.c.
References _, GET_SLOT, Matrix_DimSym, Matrix_iSym, Matrix_pSym, and RMKMS.
dCHMsimpl_validate()
SEXP dCHMsimpl_validate (SEXP obj)
Definition at line 1739 of file validity.c.
References _, GET_SLOT, Matrix_pSym, Matrix_xSym, RMK, and RMKMS.
dCHMsuper_validate()
SEXP dCHMsuper_validate (SEXP obj)
Definition at line 1766 of file validity.c.
References _, GET_SLOT, Matrix_xSym, RMK, and RMKMS.
denseLU_validate()
SEXP denseLU_validate (SEXP obj)
Definition at line 1085 of file validity.c.
References _, GET_SLOT, Matrix_DimSym, Matrix_permSym, and RMKMS.
diagonalMatrix_validate()
SEXP diagonalMatrix_validate (SEXP obj)
Definition at line 300 of file validity.c.
References _, GET_SLOT, Matrix_diagSym, Matrix_DimSym, Matrix_xSym, and RMKMS.
Dim_validate()
char * Dim_validate (SEXP dim)
Test that dim is a length-2, non-negative integer vector.
Parameters
dim A SEXP, typically the Dim slot of a (to be validated) Matrix.
Returns
A string containing an error message, empty if dim is valid.
Definition at line 35 of file validity.c.
References _, and RMS.
Referenced by Matrix_validate(), and R_Dim_validate().
DimNames_validate()
char * DimNames_validate (SEXP , int [])
dMatrix_validate()
SEXP dMatrix_validate (SEXP)
dpoMatrix_validate()
SEXP dpoMatrix_validate (SEXP obj)
Definition at line 895 of file validity.c.
References _, GET_SLOT, Matrix_DimSym, Matrix_xSym, and RMK.
dppMatrix_validate()
SEXP dppMatrix_validate (SEXP obj)
Definition at line 916 of file validity.c.
References _, GET_SLOT, Matrix_DimSym, Matrix_uploSym, Matrix_xSym, and RMK.
dsparseVector_validate()
SEXP dsparseVector_validate (SEXP)
iMatrix_validate()
SEXP iMatrix_validate (SEXP)
indMatrix_validate()
SEXP indMatrix_validate (SEXP obj)
Definition at line 331 of file validity.c.
References _, GET_SLOT, Matrix_DimSym, Matrix_marginSym, Matrix_permSym, and RMKMS.
isparseVector_validate()
SEXP isparseVector_validate (SEXP)
lMatrix_validate()
SEXP lMatrix_validate (SEXP)
lsparseVector_validate()
SEXP lsparseVector_validate (SEXP)
Matrix_validate()
SEXP Matrix_validate (SEXP obj)
Definition at line 160 of file validity.c.
References Dim_validate(), DimNames_validate(), GET_SLOT, Matrix_DimNamesSym, and Matrix_DimSym.
Referenced by MatrixFactorization_validate().
MatrixFactorization_validate()
SEXP MatrixFactorization_validate (SEXP obj)
Definition at line 173 of file validity.c.
References Matrix_validate().
nMatrix_validate()
SEXP nMatrix_validate (SEXP)
packedMatrix_validate()
SEXP packedMatrix_validate (SEXP obj)
Definition at line 884 of file validity.c.
References _, GET_SLOT, Matrix_DimSym, Matrix_xSym, and RMKMS.
pBunchKaufman_validate()
SEXP pBunchKaufman_validate (SEXP obj)
Definition at line 1344 of file validity.c.
References BunchKaufman_validate().
pCholesky_validate()
SEXP pCholesky_validate (SEXP obj)
Definition at line 1392 of file validity.c.
References _, FRMKMS, GET_SLOT, Matrix_Calloc, Matrix_DimSym, Matrix_Free, Matrix_permSym, Matrix_uploSym, Matrix_xSym, RMK, and RMKMS.
pcorMatrix_validate()
SEXP pcorMatrix_validate (SEXP obj)
Definition at line 970 of file validity.c.
References _, GET_SLOT, Matrix_DimSym, Matrix_sdSym, Matrix_uploSym, Matrix_xSym, RMK, and RMKMS.
pMatrix_validate()
SEXP pMatrix_validate (SEXP obj)
Definition at line 371 of file validity.c.
References _, FRMKMS, GET_SLOT, Matrix_Calloc, Matrix_DimSym, Matrix_Free, Matrix_permSym, and RMKMS.
R_Dim_validate()
SEXP R_Dim_validate (SEXP dim)
Definition at line 50 of file validity.c.
References Dim_validate().
R_DimNames_fixup()
SEXP R_DimNames_fixup (SEXP dn)
Sanitize user-supplied [dD]imnames.
Replaces length-0 vectors with NULL and non-character vectors with the result of coercing to character. Intended to emulate the behaviour of do_matrix() from src/main/array.c.
Parameters
dn A list of length 2 passing DimNames_validate().
Returns
A modified copy of dn, or dn if no modification is necessary.
Definition at line 118 of file validity.c.
R_DimNames_validate()
SEXP R_DimNames_validate (SEXP dimnames, SEXP dim)
Definition at line 100 of file validity.c.
References DimNames_validate().
RsparseMatrix_validate()
SEXP RsparseMatrix_validate (SEXP obj)
Definition at line 446 of file validity.c.
References _, GET_SLOT, Matrix_DimSym, Matrix_jSym, Matrix_pSym, and RMKMS.
Schur_validate()
SEXP Schur_validate (SEXP obj)
Definition at line 1800 of file validity.c.
References _, GET_SLOT, Matrix_DimSym, Matrix_QSym, Matrix_TSym, and RMKMS.
sCMatrix_validate()
SEXP sCMatrix_validate (SEXP obj)
Definition at line 536 of file validity.c.
References _, GET_SLOT, Matrix_iSym, Matrix_pSym, Matrix_uploSym, and RMKMS.
Referenced by tCMatrix_validate(), and xsCMatrix_validate().
sparseLU_validate()
SEXP sparseLU_validate (SEXP obj)
Definition at line 1110 of file validity.c.
References _, FRMKMS, GET_SLOT, Matrix_Calloc, Matrix_diagSym, Matrix_DimSym, Matrix_Free, Matrix_iSym, Matrix_LSym, Matrix_pSym, Matrix_qSym, Matrix_uploSym, Matrix_USym, Matrix_xSym, and RMKMS.
sparseQR_validate()
SEXP sparseQR_validate (SEXP obj)
Definition at line 1199 of file validity.c.
References _, FRMKMS, GET_SLOT, Matrix_betaSym, Matrix_Calloc, Matrix_DimSym, Matrix_Free, Matrix_iSym, Matrix_pSym, Matrix_qSym, Matrix_RSym, Matrix_VSym, RMK, and RMKMS.
sparseVector_validate()
SEXP sparseVector_validate (SEXP obj)
Definition at line 1003 of file validity.c.
References _, GET_SLOT, Matrix_iSym, Matrix_lengthSym, and RMKMS.
sRMatrix_validate()
SEXP sRMatrix_validate (SEXP obj)
Definition at line 627 of file validity.c.
References _, GET_SLOT, Matrix_jSym, Matrix_pSym, Matrix_uploSym, and RMKMS.
Referenced by tRMatrix_validate(), and xsRMatrix_validate().
sTMatrix_validate()
SEXP sTMatrix_validate (SEXP obj)
Definition at line 718 of file validity.c.
References _, GET_SLOT, Matrix_iSym, Matrix_jSym, Matrix_uploSym, and RMKMS.
Referenced by tTMatrix_validate(), and xsTMatrix_validate().
symmetricMatrix_validate()
SEXP symmetricMatrix_validate (SEXP obj)
Definition at line 209 of file validity.c.
References _, equal_character_vectors(), GET_SLOT, Matrix_DimNamesSym, Matrix_DimSym, Matrix_uploSym, and RMKMS.
tCMatrix_validate()
SEXP tCMatrix_validate (SEXP obj)
Definition at line 576 of file validity.c.
References _, GET_SLOT, Matrix_diagSym, Matrix_iSym, Matrix_pSym, Matrix_uploSym, RMKMS, and sCMatrix_validate().
Referenced by xtCMatrix_validate().
triangularMatrix_validate()
SEXP triangularMatrix_validate (SEXP obj)
Definition at line 272 of file validity.c.
References _, GET_SLOT, Matrix_diagSym, Matrix_DimSym, Matrix_uploSym, and RMKMS.
tRMatrix_validate()
SEXP tRMatrix_validate (SEXP obj)
Definition at line 667 of file validity.c.
References _, GET_SLOT, Matrix_diagSym, Matrix_jSym, Matrix_pSym, Matrix_uploSym, RMKMS, and sRMatrix_validate().
Referenced by xtRMatrix_validate().
TsparseMatrix_validate()
SEXP TsparseMatrix_validate (SEXP obj)
Definition at line 497 of file validity.c.
References _, GET_SLOT, Matrix_DimSym, Matrix_iSym, Matrix_jSym, and RMKMS.
tTMatrix_validate()
SEXP tTMatrix_validate (SEXP obj)
Definition at line 748 of file validity.c.
References _, GET_SLOT, Matrix_diagSym, Matrix_iSym, Matrix_jSym, Matrix_uploSym, RMKMS, and sTMatrix_validate().
Referenced by xtTMatrix_validate().
unpackedMatrix_validate()
SEXP unpackedMatrix_validate (SEXP obj)
Definition at line 873 of file validity.c.
References _, GET_SLOT, Matrix_DimSym, Matrix_xSym, and RMKMS.
validObject()
void validObject (SEXP obj, const char * cl)
Definition at line 1835 of file validity.c.
xgCMatrix_validate()
SEXP xgCMatrix_validate (SEXP obj)
Definition at line 795 of file validity.c.
References _, GET_SLOT, Matrix_iSym, Matrix_xSym, and RMKMS.
Referenced by xsCMatrix_validate(), and xtCMatrix_validate().
xgRMatrix_validate()
SEXP xgRMatrix_validate (SEXP obj)
Definition at line 821 of file validity.c.
References _, GET_SLOT, Matrix_jSym, Matrix_xSym, and RMKMS.
Referenced by xsRMatrix_validate(), and xtRMatrix_validate().
xgTMatrix_validate()
SEXP xgTMatrix_validate (SEXP obj)
Definition at line 847 of file validity.c.
References _, GET_SLOT, Matrix_iSym, Matrix_xSym, and RMKMS.
Referenced by xsTMatrix_validate(), and xtTMatrix_validate().
xsCMatrix_validate()
SEXP xsCMatrix_validate (SEXP obj)
Definition at line 805 of file validity.c.
References sCMatrix_validate(), and xgCMatrix_validate().
xsRMatrix_validate()
SEXP xsRMatrix_validate (SEXP obj)
Definition at line 831 of file validity.c.
References sRMatrix_validate(), and xgRMatrix_validate().
xsTMatrix_validate()
SEXP xsTMatrix_validate (SEXP obj)
Definition at line 857 of file validity.c.
References sTMatrix_validate(), and xgTMatrix_validate().
xtCMatrix_validate()
SEXP xtCMatrix_validate (SEXP obj)
Definition at line 813 of file validity.c.
References tCMatrix_validate(), and xgCMatrix_validate().
xtRMatrix_validate()
SEXP xtRMatrix_validate (SEXP obj)
Definition at line 839 of file validity.c.
References tRMatrix_validate(), and xgRMatrix_validate().
xtTMatrix_validate()
SEXP xtTMatrix_validate (SEXP obj)
Definition at line 865 of file validity.c.
References tTMatrix_validate(), and xgTMatrix_validate().
zMatrix_validate()
SEXP zMatrix_validate (SEXP)
zsparseVector_validate()
SEXP zsparseVector_validate (SEXP)