# -*- Makefile -*- for Windows

include Win.mk
#       |-> gnuwin32/MkRules

CPPFLAGS=$(PKG_CPPFLAGS) -I$(RHOME)/include
SHLIB_EXT = .dll
SHLIB_CXXLD = g++ --shared
SHLIB_LINK = $(SHLIB_LD) $(SHLIB_LDFLAGS) $(LDFLAGS)

## Use this to
build_under_Windows = true
include Makefile
