## Generated by ./rules.sh :
BunchKaufman.o: BunchKaufman.c Lapack-etc.h \
  Mdefines.h \
  Msymbols.h
Cholesky.o: Cholesky.c Lapack-etc.h \
  cholmod-etc.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h Mdefines.h \
  Msymbols.h
Csparse.o: Csparse.c Mdefines.h \
  Msymbols.h cs-etc.h \
  SuiteSparse/CXSparse/Include/cs.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h cholmod-etc.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h
Schur.o: Schur.c Lapack-etc.h \
  Mdefines.h \
  Msymbols.h
Summary.o: Summary.c Mdefines.h \
  Msymbols.h M5.h
aggregate.o: aggregate.c Mdefines.h \
  Msymbols.h M5.h idz.h
attrib.o: attrib.c Mdefines.h \
  Msymbols.h
band.o: band.c Mdefines.h \
  Msymbols.h M5.h idz.h
bind.o: bind.c Mdefines.h \
  Msymbols.h M5.h coerce.h
cholmod-api.o: cholmod-api.c Mdefines.h \
  Msymbols.h cholmod-api.h \
  cholmod-etc.h SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h
cholmod-etc.o: cholmod-etc.c Mdefines.h \
  Msymbols.h idz.h cholmod-etc.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h
coerce.o: coerce.c Mdefines.h \
  Msymbols.h M5.h idz.h coerce.h
colSums.o: colSums.c Mdefines.h \
  Msymbols.h M5.h
cs-etc.o: cs-etc.c Mdefines.h \
  Msymbols.h cs-etc.h \
  SuiteSparse/CXSparse/Include/cs.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h
determinant.o: determinant.c Mdefines.h \
  Msymbols.h \
  cholmod-etc.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h
diag.o: diag.c cholmod-etc.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h Mdefines.h \
  Msymbols.h M5.h idz.h
dropzero.o: dropzero.c Mdefines.h \
  Msymbols.h M5.h
expand.o: expand.c Mdefines.h \
  Msymbols.h M5.h
expm.o: expm.c Lapack-etc.h \
  Mdefines.h \
  Msymbols.h
forceCanonical.o: forceCanonical.c Mdefines.h \
  Msymbols.h M5.h idz.h
forceSymmetric.o: forceSymmetric.c Mdefines.h \
  Msymbols.h M5.h idz.h
idz.o: idz.c Mdefines.h \
  Msymbols.h M5.h idz.h
init.o: init.c cholmod-api.h cholmod-etc.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h \
  Msymbols.h
isCanonical.o: isCanonical.c Mdefines.h \
  Msymbols.h M5.h idz.h
isDiagonal.o: isDiagonal.c Mdefines.h \
  Msymbols.h M5.h idz.h
isSymmetric.o: isSymmetric.c Mdefines.h \
  Msymbols.h M5.h idz.h
isTriangular.o: isTriangular.c Mdefines.h \
  Msymbols.h M5.h idz.h
lu.o: lu.c Lapack-etc.h \
  cs-etc.h \
  SuiteSparse/CXSparse/Include/cs.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h Mdefines.h \
  Msymbols.h
matmult.o: matmult.c Lapack-etc.h \
  cholmod-etc.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h Mdefines.h \
  Msymbols.h M5.h idz.h coerce.h
norm.o: norm.c Lapack-etc.h \
  Mdefines.h \
  Msymbols.h
objects.o: objects.c Mdefines.h \
  Msymbols.h
perm.o: perm.c Mdefines.h \
  Msymbols.h
qr.o: qr.c cs-etc.h \
  SuiteSparse/CXSparse/Include/cs.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h Mdefines.h \
  Msymbols.h
rcond.o: rcond.c Lapack-etc.h \
  Mdefines.h \
  Msymbols.h
skewpart.o: skewpart.c Mdefines.h \
  Msymbols.h M5.h idz.h
solve.o: solve.c Lapack-etc.h \
  cs-etc.h \
  SuiteSparse/CXSparse/Include/cs.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h cholmod-etc.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h Mdefines.h \
  Msymbols.h M5.h idz.h
subassign.o: subassign.c Mdefines.h \
  Msymbols.h t_subassign.c
subscript.o: subscript.c Mdefines.h \
  Msymbols.h M5.h idz.h
symmpart.o: symmpart.c Mdefines.h \
  Msymbols.h M5.h idz.h
t.o: t.c Mdefines.h \
  Msymbols.h M5.h idz.h
updown.o: updown.c cholmod-etc.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h Mdefines.h \
  Msymbols.h M5.h
utils-R.o: utils-R.c Mdefines.h \
  Msymbols.h M5.h t_rle.c
utils.o: utils.c Mdefines.h \
  Msymbols.h
validity.o: validity.c Mdefines.h \
  Msymbols.h
version.o: version.c \
  version.h
