## Generated by ./rules.sh :
Csparse.o: Csparse.c Mdefines.h version.h \
  Msymbols.h utils.h cs-etc.h \
  SuiteSparse/CXSparse/Include/cs.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h cholmod-etc.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h Csparse.h
abIndex.o: abIndex.c Mdefines.h version.h \
  Msymbols.h utils.h abIndex.h \
  t_Matrix_rle.c
attrib.o: attrib.c Mdefines.h version.h \
  Msymbols.h utils.h attrib.h
bind.o: bind.c Mdefines.h version.h \
  Msymbols.h utils.h coerce.h bind.h
chm_common.o: chm_common.c Mdefines.h version.h \
  Msymbols.h utils.h chm_common.h \
  cholmod-etc.h SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h
cholmod-etc.o: cholmod-etc.c Mdefines.h version.h \
  Msymbols.h utils.h idz.h \
  cholmod-etc.h SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h
coerce.o: coerce.c Mdefines.h version.h \
  Msymbols.h utils.h idz.h coerce.h
cs-etc.o: cs-etc.c Mdefines.h version.h \
  Msymbols.h utils.h cs-etc.h \
  SuiteSparse/CXSparse/Include/cs.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h
dense.o: dense.c Mdefines.h version.h \
  Msymbols.h utils.h idz.h dense.h
determinant.o: determinant.c \
  Mdefines.h version.h \
  Msymbols.h utils.h cholmod-etc.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h determinant.h
dgCMatrix.o: dgCMatrix.c Mdefines.h version.h \
  Msymbols.h utils.h cs-etc.h \
  SuiteSparse/CXSparse/Include/cs.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h cholmod-etc.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h dgCMatrix.h
expm.o: expm.c Lapack-etc.h \
  Mdefines.h version.h \
  Msymbols.h utils.h expm.h
factorizations.o: factorizations.c Lapack-etc.h \
  cs-etc.h \
  SuiteSparse/CXSparse/Include/cs.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h cholmod-etc.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h Mdefines.h version.h \
  Msymbols.h utils.h factorizations.h
idz.o: idz.c Mdefines.h version.h \
  Msymbols.h utils.h idz.h
init.o: init.c Mdefines.h version.h \
  Msymbols.h utils.h Csparse.h \
  abIndex.h attrib.h bind.h chm_common.h cholmod-etc.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h coerce.h dense.h determinant.h \
  dgCMatrix.h expm.h factorizations.h kappa.h objects.h perm.h \
  products.h solve.h sparse.h sparseVector.h subassign.h subscript.h \
  utils-R.h validity.h 
kappa.o: kappa.c Lapack-etc.h \
  Mdefines.h version.h \
  Msymbols.h utils.h kappa.h
objects.o: objects.c Mdefines.h version.h \
  Msymbols.h utils.h objects.h
perm.o: perm.c Mdefines.h version.h \
  Msymbols.h utils.h perm.h
products.o: products.c Lapack-etc.h \
  cholmod-etc.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h Mdefines.h version.h \
  Msymbols.h utils.h idz.h coerce.h \
  dense.h sparse.h products.h
solve.o: solve.c Lapack-etc.h \
  cs-etc.h \
  SuiteSparse/CXSparse/Include/cs.h \
  SuiteSparse/SuiteSparse_config/SuiteSparse_config.h cholmod-etc.h \
  SuiteSparse/CHOLMOD/Include/cholmod.h Mdefines.h version.h \
  Msymbols.h utils.h idz.h solve.h
sparse.o: sparse.c Mdefines.h version.h \
  Msymbols.h utils.h sparse.h
sparseVector.o: sparseVector.c Mdefines.h version.h \
  Msymbols.h utils.h sparseVector.h
subassign.o: subassign.c Mdefines.h version.h \
  Msymbols.h utils.h subassign.h \
  t_Csparse_subassign.c
subscript.o: subscript.c Mdefines.h version.h \
  Msymbols.h utils.h subscript.h
utils-R.o: utils-R.c Mdefines.h version.h \
  Msymbols.h utils.h utils-R.h
utils.o: utils.c Mdefines.h version.h \
  Msymbols.h utils.h
validity.o: validity.c Mdefines.h version.h \
  Msymbols.h utils.h validity.h
