library(Matrix)
tp6 <- as(chol(Hilbert(6)),"dtpMatrix")
validObject(tp6)
str(tp6)
show(tp6)
as(tp6, "matrix")
t(tp6)
determinant(tp6)
rcond(tp6)
norm(tp6, "I")
norm(tp6, "1")
norm(tp6, "F")
object.size(tp6)
object.size(as(tp6, "dtrMatrix"))
object.size(as(tp6, "matrix"))
set.seed(123)
rl <- new("dtpMatrix", uplo="L", diag="N", Dim = rep.int(1000:1000,2),
          x = rnorm(500*1001))
validObject(rl)
str(rl)
norm(rl, "I")
norm(rl, "1")
norm(rl, "F")
rcond(rl)
#all.equal(rl %*% diag(1000), as(rl, "matrix"))
object.size(rl)
object.size(as(rl, "dtrMatrix"))
object.size(as(rl, "matrix"))
determinant(rl)
q('no')
