#!/bin/sh

pkg=Matrix
if [ ! -f DESCRIPTION -o -z "$(grep "^Package: ${pkg}$" DESCRIPTION)" ]; then
	echo "script must be run in package [${pkg}] root directory"
	exit 1
fi
out=scripts/rules.mk
echo "Regenerating src/${out} for inclusion in src/Makevars ..."
echo "entering src"
cd src
R=R
ssdir=SuiteSparse
include1="$(${R} RHOME)/include"
include2="${ssdir}/SuiteSparse_config"
smk=scripts/sources.mk
echo "Getting source file names from ${smk} ..."
lst=$(cat ${smk}| sed -E "1d;s/^[\t ]*([^ ]*[.]c).*$/\1/")
for file in ${lst}; do
	echo "  ${file}"
done
echo "done"
if [ -f ${out} ]; then
	echo "Moving existing ${out} to ${out}.bak ..."
	mv ${out} ${out}.bak
	echo "done"
fi
echo "Writing gcc -MM output to ${out} ..."
echo "===="
echo "## Generated by ./rules.sh :" | tee ${out}
for file in ${lst}; do
	if [ -f ${file} ]; then
		gcc -I${include1} -I${include2} -MM ${file} |
			sed -E "s~${include1}/[^ ]*[.]h( |$)~~g;\~^[\t ]*\\\\$~d" |
			tee -a ${out}
	else
		echo "## missing ${file}" | tee -a ${out}
	fi
done
echo "===="
echo "done"
echo "leaving src"
cd ..
echo "done"
