## Take advantage of coercions automatically generated by 'methods'
## to get an object of a nonvirtual superclass, one that is guaranteed
## to be "ours" (exported by 'Matrix'):
.promote <-
function(x, mode = 7L)
    as(x, .M.class(x, 7L))

## "...Matrix" or ".sparseVector" or "", promoting:
##     "pMatrix" -> "indMatrix"  if  bit 0 is set
##   "co.Matrix" -> "dp.Matrix"  if  bit 1 is set
##   "dp.Matrix" -> "ds.Matrix"  if  bit 2 is set
##   "zp.Matrix" -> "zs.Matrix"  if  bit 2 is set
.M.class <-
function(x, mode = 7L)
    .Call(R_Matrix_class, x, mode)

## "[nlidz]" for Matrix, sparseVector,
## logical, integer, double, complex 'x'; otherwise ""
.M.kind <-
function(x)
    .Call(R_Matrix_kind , x)

## "[gsptdi]" for Matrix, sparseVector 'x'; otherwise ""
.M.shape <-
function(x, mode = 7L)
    .Call(R_Matrix_shape, x, mode)

## "[CRTdinp]" for Matrix 'x'; otherwise ""
.M.repr <-
function(x)
    .Call(R_Matrix_repr , x)

.isMatrix   <- function(x)
    nzchar(cl <- .M.class(x)) && substr(cl, 4L, 4L) == "M"
.isVector   <- function(x)
    nzchar(cl <- .M.class(x)) && substr(cl, 4L, 4L) != "M"
.isUnpacked <- function(x) .M.repr(x) == "n"
.isPacked   <- function(x) .M.repr(x) == "p"
.isC        <- function(x) .M.repr(x) == "C"
.isR        <- function(x) .M.repr(x) == "R"
.isT        <- function(x) .M.repr(x) == "T"
.isDiagonal <- function(x) .M.repr(x) == "d"
.isIndex    <- function(x) .M.repr(x) == "i"
.isDense    <- function(x) any(.M.repr(x) == c("n", "p"))
.isSparse   <- function(x) any(.M.repr(x) == c("C", "R", "T", "d", "i"))
.isCRT      <- function(x) any(.M.repr(x) == c("C", "R", "T"))

## for .type.kind[.M.kind(x)]:
.type.kind <- c("n" = "logical",
                "l" = "logical",
                "i" = "integer",
                "d" = "double",
                "z" = "complex")

## for .kind.type[ typeof(x)]:
.kind.type <- c("logical" = "l",
                "integer" = "i",
                "double"  = "d",
                "complex" = "z")

extends1of <- function(class, classes, ...) {
    if(is.character(class))
        class <- getClassDef(class[[1L]])
    for(cl in classes)
        if(extends(class, cl, ...))
            return(TRUE)
    FALSE
}

MatrixClass <- function(cl, cld = getClassDef(cl),
                        ...Matrix = TRUE, dropVirtual = TRUE, ...) {
    if(!is.character(cl) || length(cl) != 1L || is.na(cl))
        stop("'cl' is not a character string")
    if(is.null(pkg <- cld@package) && is.null(pkg <- attr(cl, "package")))
        return(character(0L))
    if(identical(pkg, "Matrix") && (!...Matrix ||
           grepl("^[nlidz](ge|sy|sp|tr|tp|di|[gst][CRT])Matrix$", cl)))
        return(cl)
    r <- .selectSuperClasses(cld@contains, dropVirtual = dropVirtual,
                             namesOnly = TRUE, ...)
    if(length(r) == 0L)
        return(character(0L))
    while({
        r1 <- Recall(r[1L], ...Matrix = ...Matrix, dropVirtual = dropVirtual, ...)
        length(r1) == 0L && length(r) > 1L
    })
        r <- r[-1L]
    r1
}

class2 <- function(cl, kind = "l")
    sub("^[nlidz]", kind, MatrixClass(cl))

copyClass <- function(from, to.class,
                      sNames = intersect(slotNames(to.class), slotNames(from)),
                      check = TRUE) {
    to <- new(to.class)
    if(check)
        for(nm in sNames)
            slot(to, nm) <- slot(from, nm)
    else
        for(nm in sNames)
            attr(to, nm) <- attr(from, nm)
    to
}
